== Chapter X.

The firm belief of Samuel Fothergill in the great doctrines of the Christian religion,
as held by the religious Society of which he was a member,
and his entire conviction of the truth and propriety of
the various testimonies of the Society,
and of their accordance with the doctrines and precepts of the New Testament,
were not in him the result of education or tradition.
He had diligently examined for himself the grounds upon which they rested;
for this examination, and the thorough conviction which it produced upon his mind,
he was well enabled, through the grace and aid of the Holy Spirit,
to recommend and to explain these principles, to advocate them as occasions arose,
and to defend them when questioned or attacked.

This full acquaintance with the principles of the Society,
and his well-known ability to explain and enforce them,
together with the eminent station which he occupied as a minister,
caused frequent applications to be made to him for advice and assistance;
it introduced him into much correspondence,
and an extended care over many parts of the Society.

For several years before his visit to America, and ever after his return,
he was a constant attender, (when health permitted) of the yearly meeting in London, and,
with his brother John, took a deep interest, and no inconsiderable share,
in the transactions of, and various important concerns which came before that assembly.
Several of the printed epistles during this period contain strong evidence,
in their language and style, that portions of them were of his composition.
From the records of the yearly meeting in 1753,
it appears that he then proposed the establishment of a
yearly meeting of ministers and elders,
and several minutes occur on the subject The proposal made by our friend Samuel
Fothergill respecting the establishment of a yearly meeting of ministers and elders,
being reconsidered,
was referred to the consideration of the committee for drawing up the epistle John Fry,
from the committee appointed to consider the proposal made by
Samuel Fothergill with respect to the holding a general
meeting for ministers and elders annually in this city,
brought in a report, in which they say, That having solidly considered the proposition,
it is their sense and judgment that it may contribute to the advantage of
the Society to have such a meeting of ministers and elders established.
The report was read and considered,
and on the following day it was agreed that it should remain solidly on Friends`' minds,
and in the year following it was deliberately considered and concluded.
The regulations proposed, and then agreed upon, for the said meeting,
are nearly the same as at the present time.

In the same year, 1753,
it is recorded that Samuel Fothergill brought in from the committee an epistle,
to be sent in MS. to the several quarterly meetings;
the epistle is fraught with excellent counsel.

Of the character adverted to in a preceding paragraph,
are several of the following letters.

In the beginning of 1760, he was engaged in some correspondence with R. Selby,
the clergyman of a neighbouring parish (Budworth.) The daughter of a
Friend near that place had been married before this individual,
and, previously to the ceremony of the marriage,
he had insisted upon her submitting to the rite of water baptism.
The marriage was one of peculiar aggravation and distress to her parents,
who were treated with much unkindness by the clergyman;
they applied for counsel and consolation to Samuel Fothergill,
and the following extracts are from some of his letters to R. Selby on the occasion.

[.embedded-content-document.letter]
--

"`I am convinced, by the testimony of the Holy Scriptures,
that the sprinkling of water upon the face of either
adults or infants hath no warrantry therein:
it is neither the baptism of John, nor of our blessed Redeemer;
but having no ground in Holy Writ, nor example nor precept therein,
corroborating thy practice,
and it appearing foreign to the nature of the religion of the Holy Jesus, I disclaim it,
as being one of the inventions of men apostatized from
the power and purity of the gospel.
Had thy mind been happily subjected to the purifying
effects of the baptism of the Holy Ghost,
the baptism that now saves, and of which the holy Jesus was and is the minister,
I persuade myself thou wouldest have acted a different part.`"

"`I suppose thy remark on S. C.^
footnote:[The father of the young woman.]
being an enemy to the religion of his country, is a reflection on our Society.
I trust we are not enemies to true religion, which avails before God the Father.
It is true, we think differently from some others respecting it,
believing its chief emolument is sanctity of heart and the favour of God,
and not lucrative advantages.
We have reason to believe there yet remain men who suppose gain is godliness,
and are more concerned to advocate their claims by temporal motives,
than by the love of Christ; and from such we turn away.`"

--

In reply to some harsh and unjust expressions of his correspondent respecting himself,
Samuel Fothergill writes thus:

[.embedded-content-document.letter]
--

"`I am very free to tell thee I make not merchandise of religion:
I amuse not the people with the false traffic of unfelt truths.
I confess some of the earlier scenes of my life were passed in folly, vanity,
and infidelity; but having found mercy with God, through Jesus Christ,
and knowing the terrors of the Lord for sin,
I endeavour to persuade others to be reconciled unto God, by forsaking every evil way,
and turning to him in faith and prayer, with their whole hearts.
This is the end of my labour, and its whole intention;
for this I am willing to spend and to be spent, without any fee or reward from men.
The Lord judge between me and thee in this matter.`"

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to R. Oliver.^
footnote:[Probably Robert Oliver, who was vicar of the parish of Warton, near Lancaster,
from 1734 to 1775.
I have not been able to collect any further particulars
of the case named in this letter.--G. C.]

[.signed-section-context-open]
Warrington, 1760. 1760.

My friend, Abraham Rawlinson, some time ago, gave me thine, dated 11th of April,
which brought thy Commissary`'s remarks on the suffering case of the Websters,
which Abraham Rawlinson had, at my request, put into thy hands some time since.
A tedious indisposition,
and a necessary inquiry into the truth of the Commissary`'s aspersions,
have prevented my earlier attempt to suggest a few sentiments to thy consideration,
on account of thy Commissary`'s letter: I hope for thy candour in doing it now.

Much might be said to his "`concurrence in opinion,
that every civil government ought highly to discourage every excuse and
pretence which are alleged to be founded on principles of conscience,
for a premeditated disobedience to the laws of their country;`"
as also to his charge of the most "`perverse obstinacy.`"
May I not query whether this is not a full justification of all the high
discouragements the primitive church suffered from Jewish and Gentile governments,
and those inflicted on the reformers from Popery,
the founders of the Church of England`'. '`The hierarchy
of those days called their invincible constancy,
"`the most perverse obstinacy.`"
Hath not this been the language of a persecuting spirit,
from the time of the accusation of our Saviour by the chief priests;
both Jews and Gentiles, and those worst of Gentiles,
persecutors professing the religion of the Prince of peace and love,
and counteracting it to the utmost of their power by acts of cruelty and injustice?
I apprehend the case in question is a proof of this unchristian disposition,
and that it is in the first instance illegal and unjust,
and that no law of our country subjects us to pay wages to a parish clerk;
and I am ready to put it to the issue of common law.
Perhaps this might be known to the prosecutor,
and thence he was induced to put them into the Ecclesiastical Court,
where they might be harassed and lurched into a contempt,
and subjected to every hardship a court hateful to God and man hath power to inflict.
Their being sued there was for an illegal and unjust demand,
and every act of that court was, and is, accumulated injustice.
We have no reason to hope for any compliment to our
religious scruples from chancellors and registrars.
We have read of such officers and their conduct, in Queen Mary`'s days,
and we apprehend succeeding times have only varied the object,
not the nature of the people`'s zeal.
I freely own we are entirely at ease with respect to any
spiritual disadvantage accruing to us from excommunication.
The Judge of the whole universe is not at the beck of any mercenary officer,
whether civil or ecclesiastical, to execute his sentence of injustice and oppression,
at the price of his own attributes of love and compassion.
Nay, indeed,
whilst such instruments of cruelty are found in the habitations of Simeon and Levi,
may not thinking men say with old Jacob, "`Oh my soul! come not thou into their secret;
unto their assembly, mine honour, be not thou united.`"

I was astonished at the account he gave me of
two Quakers being lessees of wool and Iambs,
and suing as appellants, because the appellees had not made a sufficient tender, etc.
I have heard of many instances, and known some,
where Quakers being possessed of estates by inheritance or purchase,
to which tithes belonged, have,
without any temporal consideration dismembered them from their estates,
and in the strongest manner conveyed them to the
land owners from whose estate they arose,
being as conscientiously concerned against receiving as paying them;
but never before heard of their suing for them.
I procured an inquiry to be made into this matter,
and were I disposed to give thy Commissary as hard
words as he uses for Webster`'s conscientious dissent,
I might keenly recriminate--but I spare him.
Two Papists commenced such a suit, but that two Quakers did, I call upon him to prove.
I have copies of two certificates, one from the plaintiff`'s solicitor,
and one from the defendant`'s proctor, as my vouchers; the originals are in my hands.
May I not call in question thy Commissary`'s claim to the epithets of "`good
and worthy,`" who can thus take up and make a false report,
and impose upon thee with it.

I am much mistaken in the judgment I have formed of my friend Oliver,
if these remarks are in his sight insignificant.
I cannot think thy nature unfeeling,
and am persuaded religion would improve every sentiment of sympathy with distress,
especially where unjustly procured and unmerited.
I, therefore appeal to the man, to the Christian, for redress,
which I hope is in thy power to procure.
For though we fear no spiritual damages from excommunication, as now prostituted,
we know there are temporal ones which do affect the already injured, oppressed parties.

[.signed-section-closing]
I am thy real friend and well wisher,

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to his Sister.

[.signed-section-context-open]
Warrington, 1760. Third month 23rd, 1760.

I am favoured with pretty good health, a blessing greatly to be prized,
and in other respects quiet and content; I do not abound, nor am I wholly destitute;
I have more than I have merited, and if I be stripped, I acquiesce with His will,
whom I think I can call my Father who is in heaven.

The revolving year brings nigh a season I look at with
the alternate sensations of pleasure and sorrow,
as these result from meeting with similar spirits,
and being renewedly baptized with them for ourselves, for the living and the dead.
It is pleasing beyond expression to renew a personal
converse with those who are dear to me from every tie;
and to see a brother and sister in the strongest union, conveys a pleasure which,
like the connexion, is deeper than nature.

Yesterday, I received an invitation from Jonathan Laycock, of Halifax,
to the burial of his wife.
To which an apprehension of duty obliges me to submit,
though I confess not without reluctance.
But I only ask to be right, and leave the what and the where.
I expect little more rest.
Our northern yearly meeting, that for Wales, and London, are coming fast on;
I am thankful for the present share of ability,
which I hope will continue proportioned to the labour of the day.

Our worthy ancient friends, Grace Chambers^
footnote:[Grace Chambers was born at Monkheselden, in the county of Durham;
and about the year 1713, on being married, she removed to near Kendal.
She was of strict, exemplary life and conversation,
remarkable for her great plainness and simplicity of apparel, manners, and deportment,
as well as for openness and generosity to her friends, and hospitality to all,
especially to the poor.
She had free access to many families of distinction,
to whom her affectionate visits were acceptable, and of service.
She possessed considerable skill in surgery,
and in administering relief in many disorders; and this she did without fee or reward,
and devoted much of her time to visiting the sick and those in affliction,
to whom she was very helpful.
As a minister, she was strong and lively in her testimonies,
even when bodily ability had much abated.
She finished a well spent life, at her own house at Sedgwick, near Kendal,
in ninth month, 1762, aged eighty-five years;
being favoured at last with a comfortable evidence of gracious acceptance.]
and Lydia Lancaster, are about to set out on a long journey;
I expect them here next week, and they intend for the Welsh yearly meeting, Bristol,
Bath, and London.

Full of days and full of virtue, their spirits are refined, by long experience,
into a meetness for the holy inheritance.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Mary Pemberton.

[.signed-section-context-open]
Warrington, 1760. Fourth month 7th, 1760.

I was favoured with thine, and must acknowledge it was acceptable,
though it brought me the tidings of thy daughter`'s^
footnote:[Mary Jordan.]
departure out of this troublesome world;
and I doubt not but thy mind will be so favoured with
that calm acquiescence with the present dispensation,
as to be enabled to say, It is the Lord`'s doing, and let him work as it pleaseth him.
It is a debt we must all pay, and we ought not to repine at the hour of our summons.
Indeed, when the race is shortened,
and a quicker transition to eternal peace is granted than through the long,
laborious scenes of sorrow allotted to many, it may be considered and prized as a mercy,
and doubtless will be so in the cool moments of sedate meditation,
when the mind is loosened from lower connexions,
and reaching onwards to the immutable union and
inseparable fellowship of the Lord`'s family.
I was much comforted to observe in thine the happy,
blessed end dear Mary was favoured with.
I trust the remembrance of it will often solace her parents,
and may it be memorably instructive to her surviving brothers and sisters,
who know not how soon they must close their eyes to all visible things.
Then, O then, a religious, watchful life, spent in the Divine fear,
will appear as it really is, an absolutely necessary preparation to what,
in a solemn hour, is eligible to all--even a happy conclusion.
I nearly and affectionately sympathize with thee,
in the various exercising steps thou hast assigned thee to tread.
I doubt not but the present afflictions will
work for thee a more exceeding weight of glory;
and such times of favour will be renewed, as to enable thee to rejoice in tribulation.
May the ancient Helper of his humble children graciously support thee,
and lead forward in the way to true peace; that, in the obedience of faith,
thou mayest be established,
and all things work together under divine direction for thy comfort in hope.

I am about preparing a few instances of the great advantage and necessity of early piety,
intending to print them, with some little introduction,
believing they may be of some use.
I think thy testimony concerning thy dear daughter will
greatly add to the value and usefulness of such a performance;
and I believe thou wilt not have any objection
to my gathering up her valuable fragments.^
footnote:[What progress was made by Samuel Fothergill
in this collection does not now appear.
He did not publish any such work, and no remains of it were found after his decease.]

I am, through mercy, in a pretty good state of health.
I have been much about home this winter, not wholely useless, nor idle;
as the summer advances, it seems likely I may be more abroad,
though I have no clear perception of any long journey.
The visitation of the Shepherd of Israel seems extending itself, and in some places,
with a blessed prevalence to the scattered sheep amongst us,
bringing some near who have been afar off,
as well as bringing here and there one to the saving knowledge of his own Truth.
May his work prosper, and the place of his feet become more and more glorious.

Our worthy ancient friends, Grace Chambers, in her eighty-fourth year,
and Lydia Lancaster, in her seventy-seventh, were lately with us, on a religious visit;
they bent their course towards Bristol and some adjacent places, and thence to London.
They are as well as can be expected, considering their great age,
and bravely strong in the root of living virtue.
O, desirable state indeed, to have run a bright and glorious race,
and be enriched with treasure, ancient and new; green in old age,
monuments of Almighty power and goodness, descending to the grave,
as much of them as the grave can hold, but the immortal part renewed in holy ardour,
and happy in the evident foretaste of everlasting felicity.
I have not seen Joseph White for several months;
his service in this land is truly acceptable and useful;
his Master is eminently with him,
and I trust will keep him in the simplicity and power of the gospel.
Assure thyself of my most cordial affection being ever warm to thee and thine,
in which I wish you all happiness, in this; in the salutation of near love,
my wife joins with thy sincere friend,

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to John Pemberton.

[.signed-section-context-open]
Warrington, 1760. Fourth month 10th, 1760.

As I tenderly love you, I rejoice in whatever attends you that is prosperous,
particularly that our gracious Lord and Lawgiver overshadows your meetings,
when the body is collectively assembled for his service.
He hath often limited the turbulent waves which contentious spirits have raised,
and for his own name`'s sake made evidently bare his holy arm.
I have often remarked it with admiration and worship of heart, and learned from ii,
that if we do the Lord`'s work in his spirit, no weapon formed against us shall prosper.
I am thankful for the proofs repeatedly afforded, that we are brethren,
and are in that spiritual fellowship which is not straitened by distance of place,
and therein are capable of adapting matter
suitable to your states in our annual assembly.
Those epistles have required a vigilant eye,
to prevent their being prejudicial instead of helpful; for there are too many amongst us,
as well as you, who consider the approbation of men,
more than the conformity to the pattern God clearly
showed to the living amongst us in his holy mount.

I have just now received from London, the enclosed printed epistle.
I thought for some time I had a concern to send Friends of Tortola a few hints, and I,
therefore, threw together a few sentiments.
I sent it up to my brother for his consideration; he laid it before the Morning meeting,
who, with some little immaterial alteration in the words, directed it to the press,
as it was considered that the transient reading of an epistle once in a meeting,
might be of less use than printing such a number
as might supply every family with several.
One hundred of them will be sent to Tortola.

My time hath been pretty much employed, in one little service or another,
during the past winter; and I have got peace of mind, and that is very great riches.
I am obliged to thee for the yearly epistle from Philadelphia.
It contains profitable truths, and will, I doubt not, be of service.
I think the artless simplicity of the gospel, unlaboured in point of diction,
is most likely to add weight to these epistles; and perhaps,
if you judge it necessary to continue the practice of printing yearly epistles,
you may study simplicity and plainness of address.
Though I suppose you will hardly judge it necessary to print every year,
lest the wheels be clogged, and the frequency of instruction destroy its use.

I most sincerely wish thee every degree of essential happiness,
and that peace and satisfaction which alone soothes the sorrows,
and alleviates the distress of our probationary pilgrimage.

[.signed-section-signature]
Samuel Fothergill.

--

The following is the epistle mentioned in the foregoing letter:

[.embedded-content-document.letter]
--

[.letter-heading]
To Friends of the Island of Tortola.

[.signed-section-context-open]
Warrington, 1760. Third month 17th, 1760.

[.salutation]
Dear friends,

Though I am personally a stranger, and unknown to most of you,
yet ye have been, of late time especially,
so frequently the subject of close thoughtfulness to me,
and with so much warmth as to engage my mind to visit
you in a collective capacity with this epistle,
from some apprehension of duty, and with a heart replenished with sincere good will,
in which, I wish you the possession of that happiness which is everlasting.

It was tidings of great joy to the living body of Friends in this land,
to hear that the Lord Almighty was at work in your island, to beget children to himself;
and that the same substanstial virtue which wrought upon many, in this and other nations,
to redeem and purify them a people to the praise of his great Name,
had also visited you with a day-spring from on high,
and produced the same blessed fruits in measure, even a death unto sin,
and a new birth unto righteousness; and by the baptism of the Holy Ghost,
brought them into the one spiritual body, whereof Christ is head.
Oh the tenderness, the fear, and watchfulness,
which attended some of your souls in that day!--a precious day of visitation,
which ought for ever to be remembered; a day wherein the Lord allured some of you,
and brought you into the wilderness, speaking comfortably to you,
and in his own time gave you vineyards from thence: some of you, I believe,
have in remembrance those times of divine betrothing,
and cannot but acknowledge it was the Lord`'s doing.
Then the mind was humbled as in the dust, and a living concern arose, to walk in white,
and to enter into covenant with the Lord your God;
a covenant you then hoped would never be broken.
In this simplicity of heart, the Lord`'s children are ever safest.
Almighty power watching over them for good, and regarding with a Father`'s care.
As individuals amongst you were thus engaged,
the sympathy and fellowship of the one body spread over sea and land,
and we became as epistles written in one another`'s hearts,
and were baptized by the one Spirit into the one body,
wherein is the bond of peace and unity of the saints.
In this stood our rejoicing on your account;
for it is not the accession of numbers to our name,
but the gathering of souls to the everlasting Shepherd,
which gives joy to the Lord`'s family in heaven and earth.

Now, dear Friends, is not the dew of your morning at times brought to recollection,
and its heavenly relish remembered?
Yet, hath not a loss sensibly attended you,
and the once promising plantation amongst you become less fruitful and beautiful?
If so, where shall we inquire for the cause?
We shall not find any deficiency in Divine compassion;
but the loss hath been occasioned by a neglect to
follow on to know the Lord in his own way and leading,
and a departure in heart from him hath ensued, whereby the work hath been marred,
and that goodness, wherein the holy, unchangeable One would have established you,
and rendered a permanent blessing and beauty to you,
hath been to too many as a morning cloud, and as the early dew, it hath soon passed away.
Such ever was the consequence of unfaithfulness to the discoveries of the pure light;
weakness, revolt,
and backsliding have ensued--and when people have forsaken the Fountain of living waters,
which is open for sanctification and refreshment,
all their labour and inventions have been as broken cisterns, that can hold no water;
and the latter end of such, unless they return and repent,
will be worse than their former unenlightened state.
Bear with me, dear friends, in this freedom; my soul longs for your help and restoration,
that by and through you the great Name may be exalted in those islands,
and that part of the Lord`'s footstool may become glorious.

Let, I beseech you,
the seeming foremost rank amongst you look closely to their own steps,
and consider carefully,
whether they have not by some means contributed
to the general decay of lively zeal and care,
through their own declension and lukewarmness; for it is most certain,
the faithfulness or unfaithfulness, of this rank,
hath a very great influence over young and tender minds,
as well as of those who may be more advanced in years and experience,
and yet not void of a secret relish for heavenly matters.
Return therefore, I beseech you, oh ye chiefs amongst the people, to your first love,
and do your first works, lest greater desolation ensue, and He,
who walketh in the midst of the seven golden candlesticks, come unto you quickly,
and remove yours out of its place; for why should the candlestick remain,
when the light and lustre of the candle is extinguished?
And dearly beloved friends of the rising generation, and ye in the prime of life,
suffer and receive the word of exhortation from one who tenderly loves you;
remember your Creator and your Judge; let not the foolish amusements,
or vain conversation,
of this world prevail to turn you aside from your great and everlasting interest;
remember there is not any thing of this world can lay the foundation of eternal peace;
it is an earnest, humble seeking after the sanctifying Hand,
and submission to its virtue, which can alone fashion you as vessels of honour,
and fit you for the heavenly kingdom.
Cherish the secret drawings of divine love; be not ashamed of its tendering,
restraining effects; why should you sell your souls for a thing of naught?
for such will be the smiles and frowns of this world in a day that is hastily approaching.
Let not, therefore, the evil example of others, nor the reproach of the scornful,
prevail to your hurt, but retain the fear of God, which will keep the heart clean,
and be an excellent enduring treasure, when every thing else shall vanish as a vapour.

And it most certainly behooves you, friends, who were natives of this land,
and have had your education amongst us as a people,
and been frequently directed to the heavenly Monitor, to walk with great circumspection;
ye are amongst a people who have been made partakers of the like precious faith with us,
principally through the immediate reach of a Divine Hand.
Will not their eyes be turned to look at your conduct,
and to observe the fruits of your faith,
by its prevalence in your lives and conversation?
And if, instead of the blessed fruits of righteousness, the contrary should appear,
and your conduct be the means of stumbling to any, and evil liberties pursued by you,
to your own and others`' hurt; to such I testify,
in the name and under an awful sense of the authority of the Most High,
it had been better for them never to have known the way of righteousness.
Heavy, very heavy,
will be the weight of the complicated guilt of their own transgressions,
and the transgressions of others made worse by their example.
Wo, from a righteous and dreadful God, to those by whom such offences come.
I make no doubt but there are amongst you an honest seed, an afflicted and poor people,
some of the Lord`'s poor, who retain in some good degree, their first love,
and bewail the hurt of Zion.
I beseech such, stand fast in their own lots; abide in the faith and patience; be sober,
and hope to the end: though the times are gloomy,
the out-goings of the morning are of God, and he can, and will in his own time,
cause the wilderness to become a fruitful field.
Look not too much at the declension of others, lest your faith should fail;
but steadfastly look to, and follow on to know the Lord Almighty, who remains for ever,
and the defection of multitudes can by no means
impair his unchangeable truth and righteousness.

In a sense of the fresh extending of ancient, all-sufficient Help,
I most tenderly and affectionately salute you.
May the scattered amongst you be brought home, and the negligent be roused to diligence,
whilst yet a little day continues;
let the tender breathings still remaining be cherished, that they may gather strength,
and enter with holy prevalence the ear of the Lord and Father of his people:
this is the sincere prayer of one concerned at heart for your
restoration and stability in righteousness and peace for ever.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Susanna Hatton.^
footnote:[This Friend was born at Grange, in the north of Ireland, in 1720.
Very early in life, her mind was brought under the tender visitations of Divine love,
and such was her zeal and her love for the Truth,
that she generally went many miles on foot to attend meetings,
and laboured hard in the service of her employer to make up for the time thus occupied.
In the seventeenth year of her age, she received a gift in the ministry,
and as one planted by the Master`'s hand, so rapid was her growth therein, that,
with the unity of her friends, she paid a general visit,
before she was eighteen years of age, to Friends on the continent of America,
in company with Ruth Courtney.
She was married in 1742,
and for many years had to pass through many outward difficulties,
as well as inward exercises and trials, for the cause and testimony she had espoused,
and she was favoured to hold fast her integrity to the Truth.
She travelled much as a minister in several parts of Great Britain and Ireland.
In 1760, being then a widow, she embarked on a second visit to America.
She afterwards married Thomas Lightfoot, and they settled in Pennsylvania,
where she continued to be a faithful labourer in the cause and service of Truth.
She was a living and powerful minister, awful and weighty in prayer,
careful to wait for the fresh anointing for right qualification.
She departed this life on the 8th of fifth month, 1781, aged sixty-one,
a minister forty-five years.]

[.signed-section-context-open]
Sixth month 27th, 1760.

In some sense of that sympathy and union which
renders the church of Christ a compact body,
I tenderly and affectionately salute thee.
I most sincerely wish thee a good journey; good to thyself and so to others.
I cannot doubt of the propriety of thy mission to that part of the Lord`'s vineyard;
I had an evidence in myself, in solemn silence,
that thou wast under the Master`'s appointment for that service,
and I earnestly desire the wisdom and power of Truth
may seal its own evidence on all thy labours;
and dear friend, though I apprehend myself a younger brother,
and now addressing myself to one who was in Christ before me,
yet permit me to offer to thy thoughts a few sentiments,
which have been sealed usefully on my heart.

First.--It is a most solemn and awful thing to assume the name of the Lord`'s ambassador;
I believe thou considers it so.
Thence ought we also to consider the high obligations we are under to receive from him,
not only his instructions, but our credentials.

Secondly.--These will not be withheld, if we wait our Master`'s time;
his sound will be certain, and his discoveries clear.
We shall not say, like Ahimaaz, When I ran, there was a tumult;
but distinctly receive and deliver our Master`'s message, in his own wisdom and spirit.

Thirdly.--In all our service, let us remember our Lord`'s dignity,
and endeavour to maintain it according to the proportion of strength vouchsafed,
both in purity of life, and singleness to him, in our ministerial capacity,
being empty without him, and only filled with his fulness.

Fourthly.--Let us learn to try the spirits, whether they are of God.
I have seen a danger, especially in your sex, of being taken by the passions;
the passionate preacher hath affected the passionate hearer; both have been in raptures,
and neither of them profited.
This is a place I would endeavour to guard thee in, my dear friend,
as I am apprehensive the emotions of thy mind are sometimes strong and animated.
Mistake not the warmth of passion for the gospel authority;
the first is like the rattling thunder, which frights, but never hurts;
the last is like the lightning from the east, which illuminates,
and at times breaks through all opposition, and melts down every obstruction.
I know the integrity of thy heart, and what is infinitely better,
our Father who is in heaven also knows it, and will not forget to be gracious; and,
therefore, with the most unreserved freedom, I remind thee of these things.
May thy Urim and Thummim be with thy Holy One, whom thou didst prove at Massah,
which implies the hour of temptation,
and with whom thou didst strive at the waters of Meribah, or strife.
Look carefully to him in all thy goings, so shalt thou dip thy foot in oil,
when thou treadest on high places,
and the arms of thy hands will be strengthened by the mighty God of Jacob.
If deep poverty be thy lot, be not disquieted,
neither pour forth thy complaints to any mortal; have no confidant, but eternal Help.
I never knew deeper poverty, nor more glorious riches, than in that land,
but I found it safe to wear my sackcloth on my loins,
and put on my best garments honestly and sparingly.
Receive no obligation from that quarter, which thou can avoid, lest they say,
"`I have requited her labour,`" or make vain the purport of thy testimony.

In the course of thy passage, be courteous to all,
unless restricted by secret direction with respect to any particular,
which I have found my peculiar duty in some parts.
Let not affability enervate thy mind,
nor lead from the steady stability attending the faithful minister;
and yet guard against a spirit which leads zealous people sometimes to say,
"`There is none righteous, no not one,`" and therein to overlook the hidden,
suffering seed.
Let thy eye be in thy head, so shall thy goings be ordered of the Lord,
and be attended with peace to thyself, comfort to the living,
and general usefulness to the church.
Be not hasty to embrace the offer of any companion in service; try their spirits,
and feel the liberty of Truth in it.
I should rather choose to take one occasionally, as way might open,
than engage for any considerable journey.
I think it is still more necessary to press thy
declining any companion from England or Europe,
who might have a concern for themselves to discharge their own duty,
without regard to thine, and so might another be oppressed by thee.
Farewell, and may the Lord of all consolation be with thee in every trial,
and support thee by his arm, enrich thee by his grace, replenish thee by his wisdom,
and comfort thee by his rod and staff.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Jane Crosfield.

[.signed-section-context-open]
Warrington, 1760. Sixth month 28th, 1760.

I am concerned that it so falls out I cannot be at home
personally to bid thee farewell and wish thee a good journey.
However, the travail of my soul is for the help, strength,
and safety of all our heavenly Father`'s children,
that they may be so wisely conducted in all things, as to know the returns of peace,
and feel the unity of the spirit and of the body.

If we are little enough in our own eyes, we shall know divine strength in our weakness;
but when any apprehension of our strength and wisdom possesses the mind,
weakness and loss in every respect ensue.
Thou hast my good wishes in thy present concern;^
footnote:[A visit to Friends in America.]
it is, indeed, a weighty undertaking,
and requires a double portion of the Spirit to go through.
Let thy dependence be upon the renewings of divine help,
and all thy movements in the gospel spirit.
Seek after the simplicity of Truth, and its littleness.
Thou art going amongst a people, many of whom have understanding hearts,
and can discern wisely between spirit and spirit, between sound and substance;
this I mention for thy encouragement, if thou art single hearted.

May best wisdom direct thee in all thy steps, preserve thee solid in thy spirit,
lively in thy ministry, wise and discerning in thy conduct towards all,
and upright and exemplary in thy conversation!

[.signed-section-signature]
Samuel Fothergill.

--

Jane Crosfield was the daughter of James Rowlandson, and wife of George Crosfield,
of Preston Patrick, in Westmoreland.
The following notice of her occurs in the journal of James Gough,
date 1740:--"`After meeting (at Height) I went with
James Rowlandson`'s family to his house at Frith.
His daughter Jane had, for a little while past, appeared at times in the public ministry,
in our meetings.
So much of tenderness and of inward fervency toward Christ, the beloved of her soul,
prevailed in her as to make deep and lively impressions on my mind.`"

She received a gift in the ministry when about twenty-six years of age;
and in the Christian exercise of it visited Scotland, North America, Ireland three times,
and many parts of England several times;
"`She was enabled to labour honestly in the line of the gospel ministry,
and made instrumental to the help and encouragement of many
She was often engaged in visiting the families of Friends,
and had considerable service therein,
being qualified to administer close and pertinent counsel and
advice to their various states and conditions.
In much tenderness and affection she was anxiously
concerned to labour with the rising generation,
that they might devote their early days to the Lord`'s service, and come up steadily,
and at all times and in all places,
in that plainness and simplicity of dress and address,
into which Truth ever leads its faithful followers;
and not yield a temporizing conformity to the
prevalent fashions and manners of the world,
which expose to many dangers, and tend to alienate the mind from its best interests.`"

"`Her conduct and conversation amongst mankind
well corresponded with the doctrines which,
as a minister of Christ, she was concerned to deliver;
being an exemplary pattern of self-denial, moderation, and Christian simplicity,
and much distinguished for her hospitality and openness of heart.`"

She departed this life on the 2nd of the second month, 1784, aged about seventy-one,
a minister forty-four years.

This honourable woman, the editor`'s grandmother, is also mentioned by John Woolman,
in his journal; he says, "`Being now at George Crosfield`'s in the county of Westmoreland,
I feel a concern to commit to writing that which to me hath been a case uncommon.`"
And again, "`I rested a few days, both in body and mind, with our friend Jane Crosfield,
who was once in America.`"
(Seventh month, 1772.)

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Gilbert Thompson.

[.signed-section-context-open]
Warrington, 1760. Sixth month 29th, 1760.

[.salutation]
Dear Cousin,

I believe I should be out of the way of my duty,
if I did not impart to thee and thy sisters a dream or
vision that was represented to me the last night,
and perhaps the interpretation of it may be brought home to your own hearts.

I thought the great day of account was come,
and all nations gathered to receive the irreversible sentence;
I beheld a variety of stales, and many clothed in different colours, many in white,
which, nevertheless, was of different degrees of lustre and beauty.
I saw many whom I knew, and amongst others thyself and sisters;
I thought your garments appeared more white than many;
and whilst I mused on the tremendous, yet glorious day,
the trumpet sounded with a distinguishing energy, and seemed to say.
Come, ye blessed.
I beheld multitudes arise, as from the eminence of a mountain, and ascend triumphantly.
My eye descended to the mountain whence many had risen,
and in whose company I had seen thee and thy sisters.
I thought I clearly saw you remain on the earth, clothed in garments measurably white.
I queried in my heart, alas! how happens it that these are left behind?
Immediately the white garments fell off,
and each of you appeared in the common dress in which you usually appear.
But I beheld chains which seemed fastened about your necks,
and bound every limb and part of the body but the head,
and these chains were fastened to great rings in the earth,
and held you so fast as to prevent any of you ascending
to those who had taken wing and risen on high.
Here I awaked in great concern of mind,
and found an engagement to impart it immediately to thyself and sisters;
none other knows the least tittle of it, nor shall, from your most affectionate,

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Israel and Mary Pemberton.

[.signed-section-context-open]
Warrington, 1760. Ninth month 8th, 1760.

Though the channel of personal and epistolary conversation
with you may be at times interrupted by other occasions,
which abundantly present themselves in the course of my labours in the heritage,
yet the best springs of that love are often opened in my heart towards you and yours,
in which I travail for your preservation in the way of righteousness,
and increase in the saving knowledge of God, and his dear Son,
the redemption of his family and people.

Dear friends, this generation, and we with it, are passing away fast;
let us be careful to leave good footsteps to the next, that our memory may be sweet,
and our peace flow as a river.
We have our several probations to pass through, and our warfare to accomplish;
various are the trials and besetments, some constitutional and some adventitious,
so as to occasion a query.
Who is sufficient for these things`'? I beheld a
state to which salvation is ever extended;
and that is true poverty: "`This poor man cried, and the Lord heard him,
and saved him out of all his troubles.`"
Oh, the excellence of this state of poverty,
and being stripped of every human dependence, when all flesh is silent before God,
and confusion covers its face; then, indeed, the Lord arises in his holy habitation,
made so by his refining Spirit.
The longer I live, the more clearly I see, in emptiness is fulness,
and that our capacity of service is in our deep submission;
then will the Lord`'s arm awake, and lay hold on strength, and fill the bow with Ephraim.

My soul is humblingly relieved in the fresh and
feeling sense of His precious love and life,
who is the strength and hope of his children; let yours be broken down before him,
to be searched and then bound up,
and the fresh renewing of covenant and holy zeal
for his Truth become the girdle of your loins.
So be it, O Father of all the living, amen.

And, dear children, beloved and longed for, my prayers are for you, and my wishes,
as for my own soul, that you may acquaint yourselves with the power of an endless life,
and be mindful of your privilege in being descended
from a line that Truth has made honourable,
and would bless you in like manner.
Let an early remembrance of your Creator possess your minds,
and the cloud of witnesses to the glorious manifestation of Truth in
the inward parts prevail with you to join their happy experience;
let the peaceful, happy conclusion of your beloved sister be often remembered,
and the blessed means of it, even her love to Truth, and obedience to its manifestations.
This led her to fear and love God, and honour her parents; they mourned for her loss,
but not without hope, as she entered into everlasting mansions of peace.
But very different is the sorrow of religious parents
which arises from undutiful conduct in children,
who pierce the parents with bitter sorrow,
and that exceedingly aggravated by a reflection
that such conduct is offensive to a righteous,
heavenly Judge,
who will plead the cause of afflicted religious parents with their rebellious offspring.
May other conduct from you furnish the well-grounded
hope of a portion with the just of all generations.

At present I enjoy my health more uninterruptedly than for some time past;
I have spent two weeks at Scarborough, to my advantage and satisfaction of mind.
I propose setting out tomorrow towards the Circular
yearly meeting for the seven western counties,
to be held in a small town in Gloucestershire,^
footnote:[Wootten-under-Edge,
at least one hundred and fifty miles from his own habitation.]
where are none of our Society.

[.signed-section-signature]
Samuel Fothergill.

--

In the foregoing letter, Samuel Fothergill mentions a visit of two weeks to Scarborough.
He was accustomed to visit that place,
both for the benefit to his health which he derived from it,
and from the stronger motive of religious duty.
It was then much frequented during the season,
by many of the nobility and higher classes;
amongst whom he was often largely engaged in the ministry,
they being much in the practice of coming to Friends`' meetings on such occasions.
In one of his letters from this place he says--"`I have been
mercifully sustained by best help to labour in the gospel service,
in several very large, crowded meetings, to which many people of distinction resort.
This seems my principal business here,
together with some more retired opportunities
amongst Friends`' families as occasions offer.`"

It was during his visit at this time that the following circumstance occurred,
as was afterwards related by Samuel Fothergill himself to some
Friends who accompanied him on his journey homewards from London.
He told them that during one of his visits to Scarborough,
he observed that Admiral Tyrrell attended several meetings of Friends at that place;
and he took particular notice of the solemnity and reverence
of the Admiral`'s behaviour during the meetings,
especially in the time of silence.
One morning the Admiral came up to Samuel in the public room,
before many of the nobility and gentry, and said--"`Mr. Fothergill,
I have a very high opinion of your people`'s principles and practices,
especially the inwardness and spirituality of your silent worship.`"
Samuel replied --"`Admiral, I think such a testimony from thee, as a man of war,
rather extraordinary, concerning us and our principles, which are for peace,
and against all fighting.`"
The other answered--"`Sir, I am of your opinion in that particular,
and fully believe that the time will come,
when nation shall not lift up sword against nation,
neither shall they learn war any more:
but as every dispensation of unerring wisdom must have a beginning,
so this has had one amongst you, but has not yet reached us;
and as to what you hold of a union and communion with the Divine Intelligence, I know,
by happy experience, it is attainable in this life.

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to John Gurney.

[.signed-section-context-open]
Warrington, 1760. Tenth month 11th, 1760.

A variety of engagements fill up my time;
several journeys the last summer have fallen to my lot,
yet the affection I bear to many individuals, thyself and dear wife amongst others,
remain strong, though concealed in silence: may the holy flame of love be maintained,
so shall we be made precious in the sight of our heavenly Father, and dear to his family.
Its most certain effect is to purify the soul; some have received its lustre,
and walked in the speculation formed from its light; these fail of its blessed fruits,
and lie down in sorrow.
But when the light of Israel becomes a fire, and his Holy One a flame,
and our hearts truly subjected to its operation,
our feet will be fixed steadily in the path, and our peace will flow as a river.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to his Brother John.

[.signed-section-context-open]
Warrington, 1760. Eleventh month 12th, 1760.

The secret emotions of tender affection to thee and dear
sister frequently and strongly bring you both to remembrance;
and when I can,
I pray for your preservation and establishment in the possession of every blessing;
in particular, of hearts clothed with a holy sensibility of Divine favour,
and an anxious thirst of soul after still more and more worthiness;
for gracious remembrance in every needful time, for such times will come;
the smoothest passage is often mercifully thorny;
and the kings and priests of God`'s own anointing,
when a superficial eye views ensigns of royalty,
have underneath sackcloth on their loins.

It is never better with me,
than when I descend to bring up some fresh memorials from the hidden depths.
Though the waves and billows may at times pass over my head, they are thy waves, oh.
Father, and I will humbly look through them all towards thy holy temple.

I have thrown together some sentiments and remarks,
by way of reply to the Sermon and Address I mentioned to thee in my last;
as soon as I can, after they are transcribed, I think to send them to thee,
and refer them to thy decision, whether to destroy them,
or lay them before the Morning meeting.
I think I shall be easy either way, though I sometimes think something of the kind,
if well done, might be useful in those parts, about Lichfield,
where the Address and Sermon is spread, and where there are very few Friends.
I am not fond of controversy, still less of seeing my name in print,
but I was not wholly void of an apprehension of duty.

The great event of the decease of the king hath
manifestly proved Jacobitism to be at a low ebb;
he is sincerely mourned for by many.
I was considering what Friends would do on the present occasion;
there seemed a duty to the Society which required instant attention, that is,
to caution against the inconsistency of going into mourning.
What is done in this respect I know not.
I also thought the Society would consider itself obliged to address the successor.
I knew not whether the Meeting for Sufferings would undertake it,
or defer it to the yearly meeting;
but a letter just received informs me that the Meeting
for Sufferings have concluded to address the new king;
in which, may best wisdom guide you.
Though I cannot help you, I could almost wish to be present at your deliberations.
As I was musing a little last night upon the subject,
it came into my mind to offer one paragraph to thee; if the sentiment be improper,
reject it,--if there be any thing in it worth a thought, thou knows how to improve it,
and give it a proper turn.
I know thou wilt make allowance for me if a warmth of heart surpass right judgment.

[.signed-section-signature]
Samuel Fothergill.

[.postscript]
The suggested paragraph.--"`May He who touched the mind of youthful Solomon,
at an age similar to thine, with the love of wisdom, which,
at his accession to the throne of his royal father, he asked of God, bless thee, O king,
with a wise and understanding heart, and add thereto riches, honour,
and length of days.`"

N+++.+++ B.--I believe Solomon`'s vision, in Gibeon, was in the twenty-third year of his age,
the age of our present king.
If the sentiment be too trifling, excuse me, and pass it by.

[.signed-section-signature]
Samuel Fothergill

--

In the preceding letter,
Samuel Fothergill mentions some remarks which he had written
upon a Sermon and Address delivered at Litchfield.
His remarks were afterwards published,
and led him into some controversy in defence of the doctrines
of the Society of Friends on the subject of Water Baptism.
His opponent was Edward Owen, at that time Rector of Warrington,
and in much reputation as a learned man, and as an accomplished classical scholar.

The occasion of this controversy is thus described by Samuel Fothergill,
in the introduction to his second pamphlet: --

"`M. Pilkington, Prebendary of Litchfield,
some time ago published a Sermon on the Nature and Necessity of Water Baptism,
as an indispensable token of the Christian Covenant, etc.
This he prefaced with an '`Address to the People called Quakers;
'` in which he called upon them to declare their sentiments,
and pointed them out as in a state of exclusion from the covenant in Jesus Christ.

"`This induced me to throw together a few reasons for our dissent:
though I enter into controversy with, reluctance,
I would not decline a sober discussion of the things
most surely believed amongst us as a people.

"`This I hope will be sufficient excuse for my remarks on the Prebendary`'s arguments:
I did not begin the dispute, but attempted to speak our sentiments in our own language,
and remove the censures he had passed upon us,
as it seemed consistent with the Apostle`'s advice,
'`Be ready always to give an answer to every man that
asketh you a reason of the hope that is in you,
with meekness and fear, having a good conscience; that,
whereas they speak evil of you as of evil doers,
they may be ashamed that falsely accuse your good conversation in Christ.`' 1 Peter 3:15-16.

"`Respecting the temper in which I wrote, I have this evidence in my own mind,
that I felt no sensation inconsistent with the angelic song,
'`Glory to God in the highest, and on earth peace, good-will towards men!

"`An anonymous auxiliary to M. Pilkington, anticipates the reply with what he styles,
a temporary local antidote against the errors in my
pamphlet,`' and soon after a second part is published;
the author no longer conceals his name, but signs, E. Owen.
This pamphlet engageth my present attention,
as he calls upon me to a review of the subject with this remark,
'`An honest man owes so much to his Creator, the world, and his own conscience,
that he ought to justify or retract his opinions.`'
As my opinions are not taken upon trust, nor merely the result of education,
but arise from the evidence of what appears to me to be truth,
I cannot recede from them without violence to my understanding and conscience.
I stand open to conviction, and follow truth with suitable dispositions;
in this pursuit I humbly confide in success and
acceptance with an omniscient gracious Judge.
I must, therefore, either be silent, or give a reason of the hope that is in me:
the former seems a suppression of truth;
the last I hope to perform with decency and candour,
it being my principal design to vindicate the spiritual religion of the Holy Jesus,
and a people who embrace it, though under the discouragement of popular prejudice.`"

The first publication was entitled, "`Remarks on an Address to the people called Quakers;
and a Sermon on the nature and necessity of being
admitted into Covenant with Christ by Baptism;
published by Matthew Pilkington, LL. B., and Prebendary of Litchfield;
in a Letter to the Author, by Samuel Fothergill.
To which are added, a few Observations, by J. Phipps.
London, 1761.`"

This was answered by a pamphlet, in two parts, signed E. Owen;
"`The necessity of Water Baptism;
a Discourse occasioned by a pamphlet lately published by Mr. Samuel Fothergill,
of Warrington, in defence of the Quaker notion of Baptism.`"
Liverpool, 1761.

Some time after this, Samuel Fothergill`'s second publication appeared,
"`A Reply to a pamphlet published, in two parts, by E. Owen, entitled.
The Necessity of Water Baptism; by Samuel Fothergill,`" London, 1763.

Here the controversy ended.
The subject was treated by Samuel Fothergill in a clear manner,
the arguments and proofs he adduced in support
of Friends`' principles were close and forcible,
and it was admitted, even by those who differed from him in sentiment,
that he had much the best of the argument.

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Ellen Evans.

[.signed-section-context-open]
Warrington, 1760. Second month 6th, 1761.

I am much indebted to thee for the tokens of thy remembrance of me,
which I have lately received;
there is room for renewed encouragement to seek
after that Hand which maketh fruitful in old age,
even covers with verdure and plenty all the trees of the Lord`'s house,
according to their degrees of growth.
I am thankful to cultivate my acquaintance with these signal instances of
the mercy and power of Him who is the preserver of his people;
these have known him throughout all their day, from their beginning to advanced years;
they can commemorate his kindness in youth, his strength in the meridian of life,
and his tender regard when the shadows of the evening approach.
I observe with pleasure thy happy experience of his regard;
may it be thy covering through the valley of the shadow of death;
and may the Everlasting Arms be open to receive thee when thy race here is accomplished!
I have strong hopes that the ties of nature, the example of honourable parents,
their solicitude, the weight of filial duty,
the evidence of the beauty and usefulness of religion,
and the importance of Divine favour, will combine to excite thy children,
for whose welfare I am anxious, to renew their diligence and care to walk in that path,
which all the generations of the righteous have trod, in their way to glory and peace.
Not all the wisdom of the world, nor the fallacious promises of its favours,
are able to direct to this path; the wayfaring man, who is on his pilgrimage,
in weakness, besetments, and poverty, shall not err in his seeking,
though he may be accounted simple; it is better to be a fool for Christ`'s sake,
than wise in all the wisdom of this world!

I am, through mercy, preserved thus far, this winter,
in a tolerably good state of health, mostly about home, and seldom idle;
peace is my reward, and that is better than all the world.
Dear Joseph White spent last week with us; he is well,
and his Master is eminently with him; his bow abides in strength,
and his hands are strong: the state of the church requires close labour,
and in that is the reward of the faithful, as when they pour water out of their buckets.
Farewell, dear friend; I love to hear from thee.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Israel Pemberton.

[.signed-section-context-open]
Warrington, 1760. Second month 21st, 1761.

I remember thee frequently, with unabated affection, and never more nearly,
and with greater sympathy, than of late,
when one of the bitterest cups thou ever partook of has fallen to thy lot.
I cannot enlarge upon it;
I trust thou hast a secret resource to apply to on this occasion,
and may the never-failing Helper support thee and thine,
in this and every other probation.
How greatly necessary is it for us all to wait diligently,
to know our minds and affections circumscribed within the holy limits,
and an early government over our own spirits;
thus the lamb and the lion can lie down together,
and an habitation of peace and quietude is found in the mountain of God`'s holiness.
Out of this subjection of spirit, is ruin and contention;
and though we may detest imbruing our hands in blood, yet we may destroy the hidden,
innocent life in ourselves or others.
May every dispensation instruct us, and may we be like the skilful, industrious bee,
who gathers honey from flowers of almost every kind.
I have in vain attempted to express my sympathy with thy dear wife,
in a few lines I enclose; I wish her every thing I could petition Heaven for,
on my own account, in the day of my distress.
I remember thy children very tenderly,
and scarcely forbear reminding them of the striking
instruction resulting to them from their dear sister,
who lived beloved of God and man.
Instructed by her conduct and example, the incautious youth grew up in piety and honour,
learned how to live,
and met the languishments of sickness and the terrors of death with holy,
humble fortitude; her last days were crowned with honour,
and her conclusion was glorious.
Such was her happy translation to a life exempt from sorrow and danger,
and for ever to drink the heavenly wine unmixed in her Father`'s kingdom.
An early acquaintance with the Lord of all power and goodness,
who drew her by the engaging virtue of his love, and taught her to love his judgments,
subjected her will, seasoned her spirit, and sanctified all to her.
An humble, submissive, meek spirit rendered her amiable;
due regard to her parents rendered her acceptable, and preserved her in righteousness.
She knew the sting of death to be removed,
and could commit her lamblike spirit into the hands of the Lord of perfection and purity.
But, alas! my heart is pained within me,
to consider the opposite conduct of one united
to her in the natural alliance of a brother.
I cannot pursue the subject; I need not; you, dear children,
are too sensible of it to need much explanation.

Think not, I beseech you, especially dear Israel the younger,
that it is possible to be safe any where but under the humbling hand of God.
Let all proud, exalted, unmortified flesh tremble,
for confusion in various forms attends it, in its loftiest, securest state.
I most sincerely salute you all, elder and younger;
may the blessings of the everlasting hills, whose foundations can never be shaken,
rest upon you, is the humble prayer of, dear friends.

[.signed-section-closing]
Yours, in tenderest affection,

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Mary Pemberton, on the Death of her Son.

[.signed-section-context-open]
Warrington, 1760. Second month 20th, 1761.

I never knew until lately, how near thou wast and art to my soul,
though I thought I ever placed thee amongst those with whom I am not merely united,
but bound up in the bundle of life, in such a covenant as will survive time, mortality,
and all its troubles.
The exquisite sympathy I feel with thee is not to be described; all language is baffled.
I can sit down with thee in deep and solemn silence,
and mingle my tears and sorrows with thine.
I cannot attempt to suggest motives of comfort to thee; I believe, nay, I am assured,
the Invisible Stay of all ages and nations is not far off to succour thee.
When the tide of maternal sorrow rises to the highest,
he can command its noise to be the voice of praise,
and stay the tossed soul upon himself.

I cannot add much; my feelings exceed my utterance;
I know dear Israel is now thy help-meet, and sharer in affliction.
May the Lord of Heaven regard you and yours, and support in the closest trial.

My wife joins with me in tender affection and sympathy.

[.signed-section-closing]
Dear Mary, thy afflicted friend,

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Elizabeth Baker.^
footnote:[This letter was addressed to Elizabeth Baker,
on her marriage with Joshua Sibson, of Lancaster.
She afterwards married Thomas Whitwell, and died at Manchester, in Third month, 1826,
aged 87.]

[.signed-section-context-open]
Warrington, 1760. Second month 22nd, 1761.

Among the many wishes of thy friends for thy happiness,
none desires it with more sincerity than myself,
though more silent about it than some others;
and as a testimony of my concern for thy welfare,
I sit down to throw before thee a few hints, which may be useful to thee if attended to,
even to render thy life easy and happy, and thy end honourable and peaceful.

First and principally, thy duty to the Almighty Lord and Maker of all things, by whom,
and through whom, all things visible and invisible consist; the Author of all blessings.
Let him be looked to and remembered by thee in this light,
and be humbly engaged to seek his favour.
Let nothing impair thy love to him.
He it is that can blast every pleasing prospect, can wither every hope,
and also sanctify every affliction.
Be not ashamed to show thy trust in him, by humbly walking before him.
It is in vain to expect a total freedom from sorrowful events,
but a great mercy to have the Staff of ages to lean upon.

Secondly; thy duty to thy husband, who,
if I judge right from his tenderness and affection to thee,
will be entitled to every degree of a mutual return; study his temper;
accommodate thy own to it.
I have seen great inconvenience arise through inattention,
where the wife hesitates at the request of the husband,
and yields at last a reluctant obedience.
This diminishes that tender affection which is the life and comfort of the married state,
gradually creates a distance, and then life may be uncomfortably dragged along,
but not happily enjoyed.
Cultivate in his mind, and in thy own, every religious sentiment;
strengthen that part as much as possible:
hereby a twofold cord of divine love and natural affection
will unite you in a covenant never to be broken.

Third; towards Friends of the meeting into which thou art removing,
let thy conduct be humble, affable, and exemplary, not assuming; preferring others,
that others may prefer thee.
Humility is the surest way to honour: let no emulation to be greater than some,
and equal to the greatest, ever be harboured in thy breast;
for this will raise displeasure, envy,
and other disagreeable affections in the minds of others.
Let thy dress be rather beneath, than on the level with thy circumstances;
it will be to thy reputation.

Fourth; let it become thy constant watch to avoid that ruinous practice of tattling,
talebearing, and secret reflection.
These sources of division and mischief are hateful to God and man.
This character sets itself as the object of general contempt;
its hand is against every one,
and every one`'s hand and heart will be against those who merit it.
The concerns of one`'s own mind and family are sufficient to employ a prudent mind,
without interfering unnecessarily in the business of others.
Notwithstanding this, sacred reproof, where just, and immediately addressed to the party,
is a beautiful, useful part of friendship.

Fifth; let thy husband`'s relations become dear to thee;
cultivate every sentiment of friendship and affection for them,
especially for his mother, with whose anxieties a son must sacredly sympathize.

Excuse, dear cousin, the freedom of these hints;
they proceed not from any painful apprehension of a contrary conduct,
but my affection for thee induces me to wish thou mayest be found in the way to blessing,
even the blessing of Heaven above and of the earth beneath,
the blessing of the ancient mountains and of the everlasting hills.

[.signed-section-signature]
Samuel Fothergill.

--

In 1761, Samuel Fothergill attended the Northerly yearly meeting held at Appleby;
the individual to whom he addressed the following letter had
occupied unseasonably a portion of the time of the meeting,
and caused uneasiness in the minds of Friends present.
It shows the care which he extended towards his fellow-labourers,
and the honest and faithful way in which he handed counsel.

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Jonathan Harrison.^
footnote:[Jonathan Harrison died in Twelfth month, 1792.]

[.signed-section-context-open]
Settle, Fourth month 18th, 1761.

I wanted a little converse with thee at Appleby,
but could not see how or where to get an opportunity;
which induces me to make use of this method to make a few remarks to thee,
in much good will to thee and the blessed cause of truth.

I have been some years conversant in the ministry,
and not unacquainted with the wiles of our common enemy,
who seeks to destroy the Lord`'s work by every stratagem,
and adapts his snares to our various states.
I know it from experience;
when the living minister feels the holy flame to be kindled in his mind,
then is the time to be very watchful,
and humbly to wait to distinguish whether it be not a portion for himself,
in order to burn up the hay, straw, and stubble effectually,
to purge and render him more and more a true son of life.
Now, if this holy flame be suffered to blaze out in the wandering
uncertainty of even a mind disposed to do some good,
it leaves the individual like a cake half baked;
the work of true religion unperfected in his own mind; and consequently weak,
and like a novice, ready to fall into the condemnation of the devil,
who kept not his first estate, but becoming exalted, was cast down.
I have clearly seen his working amongst the called, true ministers of God;
thus to lead out of the patient abode under the purifying Hand,
and into a form of religion, and promoting an inclination to labour any where,
but where we ought.
I confess I have for some time had a painful jealousy,
lest after this manner he should work with thee.
I wish thy escape, even if thou art desperately wounded and half dead.
I have feared thy branches are too large for thy root;
and I wish thou mayest centre down in thy mind, under the forming Hand,
which will be thy alone safety;
and if (as I believe will certainly be the case) thou shouldest be reduced to nothing,
and have to begin again in the littleness and simplicity of a child,
and die to the present show, mayest thou in humility submit to it,
and bear the turning of the Father`'s hand.

Thou art situated in a part where too few wise and judicious helpers are to be found;
the life of the people seems to be in words,
and the tempter works to confirm them in their barren state;
and nothing seems more likely to bring this about than a noisy, floating ministry;
and so the deceivableness of unrighteousness works, in the hearer and in the preacher,
and the blind lead the blind.
O that thy mind may be induced to ponder deeply, in the light, thy whole state,
and be stirred up to wait for the Lord in the way of his
judgment--then wilt thou take from the noise of the harp;
but judgment will run down as a river,
and more inward peace and right knowledge of
straight stepping onwards towards the holy city,
possess thy mind.

I was exceedingly distressed for thee at Appleby; the more sensibly so,
as I am assured it was my proper place to have appeared at that time in prayer;
the door of holy, humble access being sensibly and livingly set open before me;
and what added to my affliction was, the pain thou gave to sensible Friends,
by thy justifying that appearance, and seeming very stiff and high,
whereby thou hast greatly suffered in the esteem
of the sensible part of the body of Friends.
I must be thus plain and honest to acquit myself;
and earnestly request thee to study to be quiet, and mind thy own business,
that therein thou may be helped to get out of thy present state,
which appears to me to be much bewildered, and arise in the Lord`'s time,
as his workmanship, formed to his praise, and in the true line of his service.
I am not destitute of hope for thee;
and may it be confirmed by thy careful return to the day of small things,
that thence thou may be helped to be, and to act, for thy own peace,
the church`'s help and the Lord`'s honour.

[.signed-section-closing]
Thy true well-wisher,

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Ann Payton.^
footnote:[Ann Payton, of Dudley, died Eleventh month 1st, 1774, aged 91. Her daughter,
here mentioned, was Hannah, the wife of William Young, of Leominster;
she died Tenth month 30th, 1761.]

[.signed-section-context-open]
London, Eleventh month 13th, 1761.

My mind hath deeply partaken with thee and thy children,
upon the present affecting circumstance, the removal of thy daughter.
The breach of such a lender connexion cannot fail of producing deep sorrow,
in a mind less susceptible of tender impressions than thine;
and when we reflect upon the amiable, endearing qualities of deceased relations,
they are as additional motives to bemoan our loss;
but as they were prepared for a resting place beyond the limits of sorrow and calamity,
the inducement to grief may be wisely considered as its alleviation.
The debt of nature must be paid;
we are but sojourners in a world of probation and exercise,
and ought not to repine if it pleaseth the Author of all wisdom and mercy to
bring to a glorious rest by a shorter path than a long succession of painful,
weary steps through weakness and affliction, that often fill the cup of advanced years.

I know there are in the present case circumstances that aggravate the loss;
a family of young children stripped of an affectionate mother,
of a prudent Christian to instruct their tender minds in the ways of religion and virtue,
and of a good example to walk before them, and lead them in the road to happiness.
But there is an all-sufficient Hand of power,
able and willing to guard and protect them in every state.
And the offspring of the righteous share in its gracious offers, in a particular manner.
I remember, with great warmth,
some of the last expressions of my honourable mother to her afflicted husband,
respecting him, her children, and herself.
"`Thou wilt be blessed, they will be cared for, and there is a place provided for me.
They are not left under the tuition of a father, like too many now a days,
who will neglect their true interests, but of one who,
knowing from whence every good comes, will seek to the gracious, all-sufficient Father,
for himself and for his children.`"

Thou hast largely partaken of afflictions; many have been thy bitter cups; and,
this added, in the decline of life, must be exceedingly painful.
But I beseech thee, dear friend,
to remember who it was that delivered in the sixth trouble,
and rest in humble hope that he will not forsake in the seventh.
My brother and sister unite in near sympathy with thee and thy children.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Mary Pemberton.

[.signed-section-context-open]
Warrington, 1760. Second month 26th, 1762.

A warmth of sincere affection and friendship is
lively and fresh upon my spirit towards thee,
and every branch of the family; and I think I can safely and solemnly say,
I have accompanied thee in thy deep distress,
with sympathy and a participation of the wormwood and the gall; a secret,
silent partaking with thee and the family, hath accompanied me in my solitude;
I know not how to say, but I know how to feel.
I hope the billows are rolled over in a great degree
and the peaceful voice of Him who rules the ocean,
distinctly heard to bound its waves;
and may the calming presence of the Prince of peace be experienced to prevail.
O, the benefit of a hiding place from the storm,
and protection in the hour of severe conflict.

The warm,
animated sentiments of tender friendship and Christian
fellowship I often feel towards thee and thy husband,
tell me the ardour of friendship I felt at our parting, about five years ago,
is not abated;
a series of employments of various kinds have demanded my
attention and stopped the channel of correspondence sometimes,
but not destroyed or impaired the bonds of union.
I am, through mercy, favoured with tolerably good health,
employment in my Master`'s cause,
and a good degree of qualification is extended in the needful time;
herein I have cause to be most humbly thankful,
that my Master hath called me into some part of his service,
and furnished proportionable peace and strength.
My weakness is great, my buffetings many, but the Lord is my strength, my sun,
and my shield; of whom then shall I be afraid?

I am often solicitous in my mind about your children;
I remember them with a tender affection,
and run from one to another with a degree of solicitude,
as if I viewed a race of youth connected to me in the ties of nearest natural alliance.
How are they?
are they thy comfort,
as far as religion and virtue in offspring can be so to anxious parents?
Oh, how grateful to me, how comfortable to thee and their dear father,
how honourable to themselves might they become,
if suitably humbled to seek and abide under the fashioning Hand,
which alone makes vessels of sanctification and honour!
What becomes of dear Charley?
doth the softness and delicacy of tender years remain with him,
and give reason to hope advance in years and piety will be proportionate to each other?
Salute them all in my name;
for my heart and eyes overflow in strong petitions and
desires for every durable blessing to attend them,
their parents, and the whole family.

Perhaps it will be acceptable to thy husband to know a visitation of divine virtue hath,
by its own immediate operation,
wrought to the convincement of several in the neighbourhood of Bolton,
whence the family of the Pembertons, I suppose, derive their origin;
and that our Northern yearly meeting for the four counties of Chester, Lancaster,
Westmoreland and Cumberland, is to be held there in the fourth month next.

[.signed-section-closing]
Dear friend, thine in every Christian service,

[.signed-section-signature]
Samuel Fothergill.

--

The yearly meeting at Bolton, mentioned in the preceding letter, was large,
and attended by many valuable ministers, and a great number of sober inquiring people,
to whom much was communicated, in gospel authority, to their comfort and instruction.
From Bolton, Samuel Fothergill,
in company with Catharine Payton and several other Friends,
went to the yearly meeting for Wales, held this year at Bala.
This also was a large and favoured meeting.

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Catharine Payton.

[.signed-section-context-open]
Warrington, 1760. Sixth month, 1762.

Few successive hours have elapsed for several weeks past,
in which thou hast been out of my remembrance,
with the affection and tenderness which accompanies friendship of the genuine kind,
and earnest wishes for thy preservation and sure establishment upon
the rock against which the gates of hell can never prevail.
For myself I pray for it, even from the bottom of my soul, for I never had greater need.
It is a comfort,
when we are encouraged to remember the sufficiency and
unchangeableness of the universal Father,
who views us in every probation, and compassionately regards us,
when destitute of every other helper, and perhaps receiving the bitter cup,
when we might hope for some alleviation of sorrow;
but what shall we say of the Lord Almighty, but just and true are all his ways?
and what of ourselves, but unto us belong blushing and confusion of face.
I was by no means unmindful of thee in my return from London,
nor was ---- out of my thoughts: two reasons hastened me home: one,
my wife`'s indisposition, the other,
a want of that evidence of duty which was in measure
necessary to encourage me to appoint a meeting.
Indeed,
such has been the situation of my mind as sometimes to induce me to cry in secret,
with holy Job--"`My days are extinct, the graves are ready for me.`"
For some beneficial end hath a series of hidden distress attended me;
I only beg it may promote my sanctification.

I was pleased to meet thy brother in London; I hope his mind is rightly baptized,
at times, for his own and the Society`'s help; may he be blessed with sedate stability,
and produce in patience,
the peaceable fruits of righteousness Several persons
have come to our meetings since the meeting at Bolton,
and from some account several are fully convinced,
and would sit down with Friends if there was any meeting thereabouts.
The like account I had from Bala, by a tender spirited young man,
who called upon me a few days ago; thus, I verily believe,
the Lord`'s work is going forward.
O may it possess the gates of his enemies,
and effectually lay waste as well as smite all the corners of Moab.

[.signed-section-signature]
Samuel Fothergill.

--

The yearly meeting held in London, in 1760,
had appointed a committee to pay a visit to the
quarterly and other meetings throughout the nation.
Samuel Fothergill was one of that committee, and upon him, with Jonathan Raine,
Isaac Wilson, and William Rathbone, devolved, in 1762,
the important duty of performing this service in Ireland.
They embarked in the eighth month, and were closely engaged, for nearly three months,
in a general visit to the meetings for worship and discipline throughout that country.

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to his Sister.

[.signed-section-context-open]
At Robert Lecky`'s, Kilnock, Tenth month, 1762.

Being detained a week later than we expected in England,
hath rendered it necessary for us to be at meeting or on horseback,
and frequently both every day except two, for fifty days successively,
in order to finish our visit before the National meeting in Dublin.
However, we have occasion to confess, with thankful hearts,
that hitherto we have been remarkably and eminently
helped to prosecute the object of our journey,
and help every way hath been graciously extended to us, and health also,
in such a degree as to render the journey practicable (though at times painful) to me;
the other friends are well.

The state of the church is painful in many places.
I think there is not a great decrease of number since I was first here,
eighteen years ago, but most of the valuable ministers and elders are gone off the stage,
and few, very few, are raised to fill their places, or even attempt it.
But it hath been a renewed and eminent visitation of divine favour,
from which I hope some effectual service will accrue to individuals,
if not to the general.
Our labour hath been close, searching, and salutary,
and in the precious unction of divine love, at once to inform the judgment,
and reach the oppressed seed.
The living have unity with us,
and the more distant part of the Society seem to approve of our labour,
and see its intention and tendency.
May the Lord of the heritage arise, and have mercy upon it.

Dublin, tenth month 9th.--We arrived here this evening;
yesterday was the monthly meeting at Carlow, which was very large, and a time, I hope,
never to be forgotten by many besides myself.
We came to worthy Abraham Shackleton`'s last night; he met us at Carlow,
and I hope will accompany us on our whole visit.
The monthly meeting for this city is to be held tomorrow, and is likely to be very large.
I quietly hope in His aid who hath hitherto been our gracious helper.

A copy of Friends`' Address to the King, was put into my hand this evening;
it is pleasing to Friends here, and I think it a good one,
but hope Friends will be cautious of making our incense to the throne too cheap.

[.signed-section-signature]
Samuel Fothergill.

--

Except the foregoing, there does not appear to be any letter extant,
written during this visit to Ireland; but of the latter part of it,
and of the labours of Samuel Fothergill in particular,
an account was drawn up by Elizabeth, wife of Richard Shackleton, of Ballitore,
an abridgement of which is here inserted.

1762, tenth month 8th.--Our friend Samuel Fothergill, with others,
visited the monthly meeting held at Carlow.
In the meeting for worship he was largely engaged in testimony,
setting forth the doctrines of Christianity, and the foundation of it, at much length,
for the information of those differing in name from us (for
true religion is the same in all;) saying,
that as we were a people who almost everywhere had been spoken against,
sometimes through ignorance, and sometimes, he was afraid, through malevolence,
he was willing to inform them what principles we held,
and what our belief was concerning the fundamentals of Christianity;
and that it was not being men of literature,
nor of any natural or acquired ability as men and creatures,
that could procure to us that substantial
religion that would stand by us beyond the grave,
by assisting us to renounce the devil and all his works,
the pomps and vanities of this wicked world;
but our humbly depending upon that sufficiency which is of God:
He said he was sensible that many were prevented from coming to partake of
the inestimable blessing of peace and serenity of soul by that monster,
shame, so that they cannot bear ridicule from their acquaintance,
which must be their lot if they are bent to live a Christian life.
But the cross being as foolishness, and a stone of stumbling,
men remain in darkness and ignorance, and answer not the end of their creation,
and are prevented from coming to the knowledge
of Him who has called us to glory and to virtue.
This, he acknowledged, had been the case with himself in the early part of his life,
when he lived in as loose and forgetful a manner as perhaps any present,
though often convicted in the secret of his soul for his folly.
But shame would not allow him to submit to be accounted a fool,
for he had extended pretty far in notion and speculation,
and endeavoured to procure some knowledge in literature,
but was made sensible it would avail nothing in
that which pertains to life and godliness,
through the knowledge of Him who has called us to glory and virtue.
And as destruction from God was a terror to him, because of his highness and majesty,
he could not endure, he was enabled in measure to conquer this shame,
and submit to that power that could cleanse his heart, for which unmerited favour,
all within him worshipped and praised Him that lives for ever.
And having happily experienced the advantage of joining with wisdom`'s call,
he was earnest in inviting others to join with il.
For wisdom has extended and builded her house, and hewn her seven pillars,
which he compared to the virtues to which the apostle exhorts and calls the believers,
when he says.
Add to your faith virtue, etc.
And if we come thus to obey the call of wisdom, we shall dwell in a quiet habitation,
in a covert from the storm in times of trial, when afflictions roll upon us,
for these we must expect on this side the grave.
He addressed himself particularly to those of our own profession,
and much desired that we might be as lights in the world.

The meeting for worship being over,
he with courtesy acknowledged the favour done to us by
those of other societies giving us their company,
and their having behaved in so becoming a manner;
and informed them that as we had now some particulars
to inquire into relative to our own Society only,
he requested that those who were not of us, would, without taking offence,
be pleased to withdraw,
excepting that those who had at any time been members
amongst us might remain on this particular occasion,
so that they were not of scandalous lives, or notoriously bad.
Afterwards, he described the nature of their visit;
that they came not as severe censurers or rigid inquisitors,
neither to lord it over the heritage; but in love, and in order to help and assist;
and gave a close caution that such overseers as were to answer the queries,
should consider well what they were going about, and give such answers as were just;
adding, that those in such offices ought to be men of truth.

The first query being read, and an answer given by one from each meeting,
he spoke upon it in his usual powerful manner,
showing the necessity of the great duty of attending meetings
for the worship of that Being to whom we owe all,
in order to have our strength renewed in Him;
and if we were concerned thus to wait for it,
we should not let trivial things prevent our attendance;
and our conduct and behaviour when there would be becoming,
and if the spirit of heaviness came over us, we should labour diligently to overcome it.
But some men he thought there were, too big to enter in at the strait gate,
and too great to be religious; and others too lazy to walk in the narrow way;
but such are far from the little child`'s state, of whom is the kingdom.
He enlarged upon the love and unity which ought to subsist between brethren,
and how cautious they ought to be of saying
anything detracting one of another -- of saying,
"`Report,
and we will report it;`" and how great ought to be the care on the minds of Friends,
lest at any time they should be led to speak in any way to lessen any elder, minister,
or overseer, or any others, before their children,
and of what hurtful consequence such conduct might be to the youth,
in fixing prejudices in their minds that could not be easily removed.
So he would have Friends keep to that wisdom which is from above,
and then that implacable disposition would be removed,
which insists upon whatever it thinks right, saying, "`I will have rigid justice;
I will be paid to the uttermost farthing;`" and not giving up anything for peace`'s sake.
He much desired that all such feelings might not have any place,
and that none might give way to such a spirit of resentment, but be willing to suffer,
and be losers, rather than to contend; this was the true way to live in peace.
To enforce this,
he mentioned an instance of two persons between whom a strong friendship had existed,
but a misunderstanding arose, and was carried to a great length; it continued some years,
till at last, he who thought himself the injured person, and who was the accused,
to the hurt of his character, went to the other party, who was in much heat, and said,
"`My innocence supports me; take it to thyself;
I will leave the decision to the great day; let the just Judge decide between us,
only let there be peace between thee and me.`"
This so melted the heart of the party addressed,
that he said there should be no difference between them;
and from that time peace was restored, and a true friendship,
which continued to the end of their lives.

He expressed an earnest desire that parents,
and such as have the charge of children and their education, might endeavour,
by example and precept, to train them up in a godly conversation,
and prevent them conforming to the world and its customs,
but have them kept in a plainness of speech and deportment, out of superfluity in dress,
which would be a means of preserving them out of unsuitable company,
to which a conformity to the fashions and customs of the world would much subject them.

He earnestly exhorted the rising youth not to
give way to the foolish customs of the world,
nor to let their minds be entangled by such things.
He said he could well remember the tender care of one of the best of fathers,
when he would take one child on one knee, and another upon the other,
with others standing before him;
how he bestowed upon them his tender and suitable counsel;
and though he could not recollect the words,
he could well remember the tears that fell from
the cheeks of his venerable father upon theirs.
He was much concerned that the elder branches of families of children
should help their religious parents in taking care of the younger,
by example and by precept,
and mentioned an instance of care in one nearly related to him;
what concern he had for those who were younger, and how he laboured for their good;
and after finishing his labours, how that worthy youth was called to give up his charge,
and enter into that rest prepared for him,
and finished his course about the twelfth year of his age.^
footnote:[His brother William Fothergill.]
He would have all be encouraged to go on in a godly conversation,
and shun destructive pride in all its appearances, for it is grounded in ignorance,
and the want of a right knowledge and due consideration
of what we are--poor dust and ashes.
Some parents, he believed, were careful to provide for their families,
and to teach them frugality, etc.; but he would recommend them to be also frugal of time,
which is so precious that few know its value until it is too late.
This he illustrated, by relating the case of a young man whom he had been with,
at or near the time of his being called to give an account of how he had spent his days,
and who would then have given all he was worth in the world,
and he had large possessions, to have had a short time allowed him; so well did he know,
at that trying moment, the value of time,
which but a few days before he had been insensible of.
He wished the youth might prize it, for time is short, and death is awful,
and that parents might not only be diligent in making a good use of it,
but also teach their children to be frugal of that,
as well as of their outward substance, and so to endeavour to conduct themselves,
that when inquisition is made for blood, they may stand clear before the just Judge.

He spoke of Friends being just in their dealings,
and punctual in fulfilling their engagements.
He thought that justice extended further than many apprehended;
and cautioned the young men that they ought to be punctual in their engagements, and not,
as too many do, ungenerously endeavour to draw out,
or engage the affections of young women,
without having serious intentions towards them--this he accounted robbery.
Concerning the care that should be taken to prevent
young people joining in marriage contrary to our rules,
he spoke persuasively to the youth,
exhorting them in all such engagements to seek for the counsel of best Wisdom,
and to follow its instructions,
and to endeavour to have the best Guest present with them; to invite him,
so that he might cause the water, which might sometimes be as the bitter waters of Marah,
to be turned into wine,
and sweeten the bitter cups of affliction that might be their lots,
through the various changes of life; and thus to begin,
he considered was the way to lay a foundation for social comfort and domestic happiness.

He spoke of the concern which had been upon his mind
for several years past to pay a visit to this nation;
and now as they went along from place to place,
they had seen the situation of the various ranks amongst us,
and they had beheld with sorrow that too generally we had not come forward,
as it was intended we should--neither the elders, the middle aged, nor the youth.
But still there was a living seed left, who were in measure preserved clean;
and although the glory of the Lord had moved to the threshold of the door,
and to the mountain hard by, yet it was not wholly departed from us,
but the shout of a King was still amongst us, and we were not forsaken;
and for this his heart was made thankful.

12th.--At Edenbury, in the meeting of discipline,
he again enlarged on the education of youth, and how parents ought,
by example and precept, to train up their children in a godly conversation,
and what an indispensable duty it is, especially upon mothers,
who have frequent opportunities to form the minds of their children,
while the father might be engaged in the arduous duties of business abroad;
and mentioned the great pains taken by the benighted inhabitants of
this nation to instruct their children in superstition;
and that we,
who are called from darkness to light should not be destitute of the form and power,
but be diligent, by example and precept, to train them up in a godly conversation;
also in preventing destructive books from being read; and he laid before the youth,
the nature and evil tendency of reading such books;
as also of following the fantastic fashions that are in
the world--such things introduce into improper company,
and the friendship of the world; and too many parents he was sensible,
were negligent in the proper care of their children in education,
though very assiduous in providing things for the body.
He owned the nearness of the connexion, and the justice of such care,
but he would that such should remember,
that as they were instrumental in bringing them into life,
they should be so also in nursing that part in them that is immortal,
and keeping it from being hurt or killed.
But instead of this,
some conclude that they provide well for their
offspring when they settle them well in the world,
build their nests on high,
above the reach of those difficulties to which many are subject,
make their sons great men of the earth, form rich connexions for their daughters,
but as to a godly conversation, let them look to that themselves,
and are ready to bring the words of Scripture to justify their conduct--that
he is worse than an infidel that does not provide for his family;
not enough considering how far that extends.
But to such earthly minded parents as are adding house to house, and field to field,
he spoke closely, and said he had seen such disappointed in their designs;
and a blast from heaven had often attended them;
and that perhaps some there might live to see it,
and he was ready to say would feel it--live to see themselves disappointed,
surrounded with confusion, anxiety, and paleness efface, deserted of heaven and earth.
He mentioned his knowledge of an instance of Almighty
justice in one who had been visited when young,
was an officer in the church, and likely to be made an instrument of use,
had he been content with what was allotted him,
and kept faithful to that which had visited him;
but aspiring to be something in the world, he launched out beyond what he could compass,
and having neglected what was committed to his care, a blight came over him,
one sorrow and disappointment after another, so that he became darkened and wretched,
and when near his close, he went to see him,
to try if he could feel any thing near him that was good;
but he found darkness and horror,
and heard him cry out--That if he had been the Lord`'s freeman,
he should not have been man`'s prisoner, but he was then deserted of heaven and earth,
of God and man, and gave a shriek that pierced the hearts of those who heard it,
and so departed out of this life.
This he said deeply affected his mind, both at the time,
and as often as he thought of it since, and he ardently desired of God,
that he might be preserved and enabled to do his duty faithfully,
and be clear of the blood of all men.

He spoke on the subject of tithes,
that the priesthood which was to be maintained
by them was abrogated by the coming of Christ,
who was the minister of the sanctuary and true
tabernacle which God hath pitched and not man;
and said he believed that if he should actually
pay towards maintaining a hireling ministry,
he should forfeit his interest in him.

He spoke tenderly to the rising youth,
to persuade them against spending their precious time in diversions;
and expatiated upon the superior advantages of going to
the house of mourning rather than to the house of mirth;
and advised that they should accustom themselves to visit the sick and distressed,
to witness the trials of the sick room, and the anxieties of the death-bed,
which would be far more instructive than attending places of diversion;
as by the sadness of the countenance the heart is sometimes made better.
He was also earnest in his desires that the youth might
be prudent concerning entering into the married state,
that they should not hastily nor inconsiderately rush into it,
and so bring sorrow for the rest of their days.
This he thought, often led to a wretched dragging on of human life;
but to be tenderly connected together in the covenant of life,
was the true way to have domestic happiness and social comfort,
and to be enabled to bear the variety of trials which are met
with as we pass through this land of uncertainty,
checkered with good and evil.

13th.--In the select meeting he spoke of a state which
seemed much to prevail amongst Friends in this nation,
even as amongst the royal tribe of Judah;
a complaint that the strength of the bearers of burdens was ready '`to fail,
because there is so much rubbish;
but he recommended such not to give way to ineffectual bemoaning,
but rather to be willing to rise up and work, to repair the breaches,
and rebuild the walls, and they would find that the King would be with them,
and amongst them, to help, and they would be furnished with a weapon of war in one hand,
and an implement with which to work in another;
so he desired such might not be discouraged,
nor give way to lamentation over the state of the church,
without endeavouring to labour for its help.

In the Province meeting he was led to speak of many excellent things.
He reminded us of our deep obligations to a merciful, all-wise Providence,
who had so wonderfully sheltered us from the devouring
jaws of war and distress of various kinds,
which others had so deeply felt, and put the question formerly used,
"`Or those eighteen upon whom the tower in Siloam fell, and slew them;
think ye that they were sinners above all men that dwelt in Jerusalem?
I tell you.
Nay, but except ye repent, ye shall all likewise perish.`"
He wished us to be humbled, and endeavour to answer the end of so great mercy.
He endeavoured to disengage the minds of the people from having a dependence on mortals,
even upon those who might have laboured faithfully, as the Apostle did;
the minds of the people are too apt to be drawn after that which is visible,
so as to be ready to worship that which is not good: one says, I am of Paul; another,
I am of Apollos; so, satan, knowing their weakness,
disputed with the Archangel about the body of Moses, perhaps that he might deify it,
and so delude this weak people, who had before while Moses was in the mount,
made a calf to worship, and had such a veneration for Moses,
that it is possible they would have worshipped his body, had not the Almighty,
in his wisdom, buried him, where they knew not, and could not find him.

Afterwards, in the awfulness of power,
he addressed in prayer Him who dwells in the clefts of the rock,
and in the secret places of the stairs, that having witnessed the word of reconciliation,
he was emboldened, though but dust and ashes,
to intercede with him on account of his church and people at large,
the workmanship of his hands, that being enamoured with his beauty,
many might flock to him, as doves to the windows.
He was fervently engaged for the strayed and lost sheep of the house of Israel,
that they might be saved.

In the select meeting he spoke with clearness,
and under a lively sense of the state of the meeting, a living power attending,
to the humbling of the minds of many.
He expressed how very sensible he felt of the great want there
was of Friends being sufficiently deep and weighty in their
waiting upon the Fountain of wisdom and strength,
especially ministers,
that they might indeed witness the springing up of the well of life,
and being cleansed by it, be enabled to sing to it.
This deep, inward waiting for the springing up of life is more wanting than words;
and if Friends would diligently endeavour to be deep enough,
they would find weight would be added to them,
and their countenances would discover to others something of the concern of their hearts,
and perhaps, stir up the pure mind in others also.
He encouraged such to endeavour to be helpful to their friends and neighbours,
to visit them as occasions offer, to drop a word here and a word there;
it might be a means of sowing the good seed.
He mentioned also a disposition apparent in some,
which retards their journey forward in that strength they might otherwise possess;
namely, a vivacity of constitution which they have,
and which he found it to be necessary in himself to guard against.
He tenderly advised that such would be willing
to let the girdle be drawn a little tighter,
and to know the foal to be bound to the vine, and the ass`'s colt to the choice vine,
that they might be strong to labour in the work.
He spoke, as it had opened upon his mind, of the Feast of Tabernacles,
how it was formerly held, and a holy convocation,
that after they had gathered in their fruits,
they were not unconcernedly to sit down and enjoy them,
but to get boughs and make booths to dwell in for a season,
and hold a holy convocation for the Feast of Tabernacles.
So in this day we are not to take up a rest in the fruits we have gathered,
but endeavour to be at liberty to attend to the service of Truth,
in whatever way it may be pointed out to us;
and if such were often to go to the bottom of Jordan,
it should be for the washing and cleansing of them,
and they would have to come up and bring their memorials with them;
and some then present, he said, must bear twins; as it appeared to him,
they must be concerned to maintain the discipline and good order in the church,
they must also divide the word--they must bear twins.

In the select meeting at Lurgan, in order, as was supposed,
to awaken the negligent to diligence before it was too late,
he told them of a Friend related to himself, who, when young,
was religiously concerned for his soul`'s salvation, and also for the good of others,
and about that time had a dream, which he related to Samuel Fothergill when in America.
He was then in the decline of life,
and in appearance not far from the conclusion of his time on earth,
but was not in the state he formerly had been,
having much neglected the gift bestowed upon him,
and cared too much for the things of this life, how he should provide for his family,
etc., had lost the good state, and was plunged into distress, darkness, and sorrow,
the portion of the disobedient; and in this latter part of his life he had another dream.
The first was, his being placed in a fine green field or pasture, walled round,
and several lambs feeding in it, well favoured and in good order,
and in the midst a pure clear spring for them to drink at;
that a sharp axe was given him with which to guard the well,
that nothing should muddy it, and to keep up the wall,
and if any breaches were made in it that he must repair them.
The latter dream was, that he saw himself in the same field, but it had lost its verdure,
the lambs were distempered and disordered, the wall much broken down, the water muddy,
and serpents in it hissing at him, which he could not destroy or overcome,
having lost the weapon formerly given him, and that as he stood looking at the lambs,
he thought he heard a voice, saying--"`All these will I require at thy hands.`"

Eleventh month 3rd.--At the concluding meeting in Dublin,
he began with the salutation of the Apostle Paul to one of the churches;
"`The grace of the Lord Jesus Christ, and the love of God,
and the communion of the Holy Ghost be with you all, Amen!`"
He enlarged upon this, setting forth the efficacy of that grace, through the birth, life,
sufferings, and death of our Lord Jesus Christ and how wonderful was that grace,
that he who was with the Father before the foundation of the world, rejoicing before him,
who was heir of all things, should take upon him the form of a servant,
and be clothed with the infirmities of human nature, and be like unto us in all things,
sin only excepted, in that body which his Father had prepared for him to do his will in,
as in the volume of the book it is written, in order to be a propitiatory sacrifice,
not for our sins only, but for the sins of the whole world;
that his coming should be so humble, though he came from the bosom of the Father,
and being the brightness of his glory, as to be laid in a manger.
This appearance was so mean in the eyes of the Jews,
who expected it would have been in a splendid manner, that they could not receive it,
but queried,--Is not this the carpenter`'s son?--And a Luciferian spirit was, he feared,
too much given way to in this day,
by such as are above his small appearance in their hearts.
Yet how astonishing was this grace of our Lord
Jesus Christ! who submitted to suffer temptation,
reproach, distressing agony, when he trod the wine-press alone,
and of the people there was none with him,
as it was prophesied:--"`Who is this that Cometh from Edom?
with dyed garments from Bozrah?
this, that is glorious in his apparel, travelling in the greatness of his strength?
I that speak in righteousness, mighty to save.
Wherefore art thou red in thine apparel,
and thy garments like him that treadeth in the wine-fat?
I have trodden the wine-press alone, and of the people there was none with me.`"
And when the drops of sweat were like blood, he would, if it were possible,
that the cup might pass from him, but, in resignation to the will of his Father,
he gave up to drink it, and to feel that agonizing state,
when he was stripped of all comfort, so as to cry out--"`My God, my God,
why hast thou forsaken me?`"
And all this that he might be offered as a sacrifice for our sins,
and for the sins of the whole world:
so that no state of life is exempted from the benefit of his sufferings and death,
if it be not our own fault.
He would not have such as might count themselves in a low state of life,
to be discouraged;
for a state of sin and wickedness was what he esteemed low and despicable, and no other;
for the favour of Heaven is not confined to any station in life;
the good tidings of our Saviour`'s birth were proclaimed
to the shepherds as well as to the wise men of the East.
So that his earnest desire and concern was,
that all ranks might witness the advantage intended by such admirable grace,
extended by the compassion of the Father to his creature man,
the workmanship of his hands.
That as the shepherd taketh out of the mouth of the lion two legs and a piece of an ear,
so shall the children of Israel be taken out, that dwell in Samaria,
in the corner of a bed, and in Damascus in a couch.
And although the form seems almost destroyed by the devourer,
and it can scarcely be known what it was when complete,
yet the good Shepherd was willing to save his people, and rescue them from destruction,
though so entangled in snares that little remains of
that ancient beauty that adorned our ancestors;
and this for want of adhering to the grace of our Lord Jesus Christ,
and dwelling in the pure love of God,
which would lead us into communion one with another, and with the Holy Ghost,
which he desired might be with us all.

The account of the visit thus concludes: On the 4th of the eleventh month,
our friends "`set sail for Liverpool, and had a safe passage,
and were undoubtedly kindly received by such as love the cause which
they so nobly gave themselves up to maintain in our poor land;
and if their extraordinary labours do not produce some good fruits,
it seems as if it would add a heavy weight in the balance against us.`"

At the conclusion of their visit,
the four Friends addressed an epistle to the National half-year`'s meeting held in Dublin,
which was by that meeting directed to be printed
and distributed to Friends throughout the nation.
In their epistle,
the committee gave a comment upon each of the eight queries
which had been read and answered in the various meetings,
and thus communicated their view of the state of the Society,
adding much excellent counsel on the contents of the queries,
and also on some other subjects.

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Catharine Payton.

[.signed-section-context-open]
Warrington, 1760. Second month 26th, 1763.

Thou art always, dear Friend, regarded with pure and tender friendship by me,
though I have not always the power or opportunity to tell thee so,
and my wishes for thy preservation and essential help are as strong as ever--
I mean when I am favoured with such a sense of life and strength,
as to wish for any good thing for myself or others.

With regard to the state of my mind; I live by faith,
and am thankful I have that to live on; and if I enjoy little,
I hope a blessing rests upon that little.
I was indisposed last week,
but a messenger brought me an invitation to the funeral of Robert Abbatt, the elder,
of Preston; and I found, upon looking at it, that duty required me to go.
He was buried in that town, where never was a Friend interred before,
he having very lately contracted for a piece of ground for that purpose.^
footnote:[A burying-ground for the Society of Friends.]
The meeting was very large, and the latter part of it solid, weighty,
and eminently favoured.
I hope it was a meeting of memorable use.
There are two young men who come amongst the few Friends in that place,
and appear sober and hopeful, attend the meetings, first and week day,
but have a deal to bear from their relations; they were so closely watched,
the night I was at Preston, that they durst not come to converse with me.
Thus, the Lord`'s work is going forward, and it will prosper in his own way and time,
notwithstanding every discouragement, arising from within and without.
Several are convinced at Bolton, some of whom have joined in society with Friends;
and I hope the Truth gains ground in those parts,
though too many of the children of Abraham revolt deeply,
and may be thrown aside as useless, or unmeet for the great work of reformation.

I have received a letter from my brother; there are two circumstances mentioned in it,
which are interesting to my affections:--our sister`'s indisposition,
which had been severe, but was abated; the other take in his own words;--"`Our worthy,
steady friend, John Hayward, is now no more; he departed this life last night,
at Plaistow, after a slow, and somewhat painful illness of some weeks.
I am just come from thence this evening,
and thought it would be proper to tell thee that our father`'s friend, and ours,
retained his senses and integrity to the last.
Full of love, full of hope, and satisfied that his work was done,
and his house in order.`"
Thus, dear friend, are we gradually deprived of the company of faithful elders.
Oh may we silently and solemnly prostrate ourselves daily before the Preserver of men,
that if old age be allotted us, it may be dignified with that steady, uniform virtue,
which hath rendered to some the latest hours of life the best.
With this sentiment fresh on my spirit,
I conclude with the assurance of constant affection, in which my wife concurs.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Israel and Mary Pemberton.

[.signed-section-context-open]
Warrington, 1760. Third month 14th, 1763.

In a fresh sense of undiminished friendship, I affectionately salute you,
with strong and fervent wishes for your stability and increase in every substantial good;
that you may be replenished with that peace and fruition of heavenly good,
which in all ages have been the stay and strength of the faithful.
The means conducive to this end have been clearly exhibited to you in various experience,
in which, by the permission of our Father who is in heaven,
you have been repeatedly exercised.
I see a great deal of instruction in the words--"`If ye know these things,
happy are ye if ye do them.`"
To know the counsel of the Lord,
is rendered an essential blessing only in proportion to
our fidelity in correspondent practice;
the simplicity of obedience is our best covering,
and will stand us in stead when extensive knowledge and
quickness of apprehension in unpractised truths,
will only pierce the hand that grasps at them, as the principal dependence and treasure.

Dear friends, I am often present in spirit with you;
I rejoice in every genuine joy you possess,
and I sympathize with you in whatever afflictive scene opens to you;
and to nothing better can I recommend you than a patient, quiet,
steady attention to Him who forms day and night, directs the alternation of the seasons,
and holds in his hand every wind that can possibly blow on the dwellings of men.
I feel for your children that anxious concern which attends a solicitude for the
preservation of those who are ranked in the near relation of most tender friends;
they are now grown up to mature years,
they have had many opportunities of knowing wherein the durable riches consist.

And you, beloved young people,
descendants of such as have been zealous for the Lord`'s cause,
I beseech you be ye helpers of their joy, strengthen their hands to labour,
by evidencing to the world the influence of their example and instruction in yourselves,
who are allied to them by the tenderest connexion.
For it is a mournful circumstance when the Lord`'s servants are
enfeebled by the transgressions of their own house,
and that any children should call their parents fools,
by acting contrary to their tender, affectionate advice, and parental authority.

My friendship for you is not transient, not warm only while I am writing to you,
it often animates my mind when I have neither opportunity nor capacity to tell you so.

I am not idle, some employment or other often offers;
I only beg preservation as an individual, and help to fill up my duty.
I have been a laborious journey through Ireland, to my own peace.
Immediately on my return, I was seized with an indisposition, which continued some weeks.
I recovered my health;
my wife was taken very ill and for some time imminent danger attended, but she is,
through mercy, recovered.
I would not be further tedious; I love you with great sincerity,
and should be glad to find I am remembered by you in the same tender affection.
Our mutual friend, John Stevenson, is sitting by me; I tell him I am writing to you;
he desires to be affectionately remembered to you and your children.
Farewell, and be assured I am your constant, cordial friend,

[.signed-section-signature]
Samuel Fothergill.

--

In the third month, 1763,
he obtained the certificate of the monthly meeting to
pay a religious visit to Friends in Essex,
and some of the eastern counties; and in the eleventh month of the same year,
he was engaged in a similar service in the city of London, and some neighbouring places.

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to John Gurney.

[.signed-section-context-open]
Warrington, 1760. Eleventh month 10th, 1763.

I am sensible my silence hath borne the mark of
ingratitude to a friend to whom I am much obliged,
and for whom I retain the warmest sentiments of affection; but frequent avocations,
indisposition of body, and feebleness of mind must plead my excuse;
thou hast very frequently been the subject of my cordial remembrance,
and the sincerest wishes for every thing prosperous to
thee and thine accompany that remembrance.

I have been several journeys since my return from Norwich; twice into Yorkshire,
and some in adjacent counties.
I oftentimes feel the weight and burden of the concern for the church`'s welfare,
and rejoice at times in the revival of the same concern on divers minds: may all such,
to whom the interests of our Zion are precious,
ever keep under the influence of that Hand which can
alone preserve individuals alive and vigorous,
and render useful for general edification.
It is a singular favour to dwell near the Fountain of wisdom,
and under the sense of the support of all-powerful Goodness.
By this means, the good report which attended the faithful elders was obtained,
and the durable riches of holy peace crowned their life and death; their faith, patience,
and victory are inciting examples to the like-minded of the present generation,
and oh that our lots may be cast in their goodly quarters!
I see, methinks clearly, the extending of an unchangeable virtue towards many amongst us,
and it prevails so far as to excite strong desires for
the honour of the glorious name and cause:
too few, alas I so follow on in the most holy path,
as to grow up to that degree of perfection in labour and understanding,
that lies before us as the standard of religious growth.
May thou and I, dear John, follow on to know the Lord with full purpose of heart,
that we may fill up the duty of our day, and enjoy the reward of all the faithful.
I am made often to remember,
it is by the renewing of the Holy Ghost our salvation is perfected.
Neither tradition, former experience,
the most indubitable conviction of the nature of true religion, seated in the head,
can ever effectually complete the work in us or others;
but the renewed daily experience of redeeming, enlarging virtue,
to build us up to His praise, who hath gathered us in measure to the morning,
and to the advanced light of a blessed, heavenly day.

The same affectionate solicitude which warms and engages my mind on thy account,
strongly prevails with me for thy dear wife,
accompanied with hope for her preservation and sure establishment in Divine favour,
which hath not failed her in many besetments in time past;
and may every essential favour from Heaven be with you and your`'s for ever.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to George Harrison.^
footnote:[George Harrison was a native of Kendal, resided for many years in London,
and died at Wandsworth, in the third month, 1827, aged eighty years.]

[.signed-section-context-open]
Warrington, 1760. First month 20th, 1764.

The agreeable impressions thy sobriety, and I hope religious conduct, made upon my mind,
whilst thou wast at school at Penketh, remain with me,
and my desires are very strong that they may ever remain upon thee,
as the means of thy happiness, here and for ever.
And the motions of true well-wishing are now so fresh upon my mind,
as to induce me to give thee this proof of my affectionate friendship,
and earnest desires on thy account,
that so promising a morning may rise higher in lustre,
to the full completion of His glorious purpose,
who hath remembered thee with a precious visitation from on high.

We live, dear George,
in a time wherein too many forget the end of their being--to glorify God on earth,
and be glorified with him hereafter.
Vanity, folly, and dissipation captivate the minds of most; oh that thou,
who hast seen into a more exalted end of thy being,
may be preserved from such a deplorable state!
And in order to rejoice in this experience,
may thy mind dwell always under the influence of that circumscribing fear,
which keeps the heart clean,
whereby wisdom and knowledge will become the stability of thy times.
Let thy heart be often lifted up to God in secret prayer for preservation,
and keep within the bounds of his revealed will.
Beware of departing, in the least, from that plainness, watchfulness,
and simplicity of heart, which often drew my mind towards thee in tender love, and which,
I am assured, also recommended thee to heavenly regard.

I understand thou goest to a school where the master is not a member of our Society,
nor many, if any of the boys, thy school-fellows.
Very serviceable mayst thou be in thy place,
if thou art so subject to the power of that principle of grace and truth we profess,
as to show forth its excellency by a good conversation coupled with true fear.
This may be the happy means of affecting other youthful minds
with the remembrance of their Creator in their youth;
thou wilt then be rendered a happy instrument of
advancing the kingdom of righteousness on earth,
and enjoy the glorious reward;
for they that be wise shall shine as the brightness of the firmament,
and they that turn many to righteousness, as the stars for ever and ever.
I beseech thee be careful in all thy conduct;
have a care how thou departs away in things deemed little.
The boundaries of innocence once passed, it is difficult to say where people will stop.
Daily seek after the favour of the Most High;
let a morning and evening sacrifice arise to him from the soul;
that being grounded and established in holy certainty of his presence,
neither flattery nor derision may ever lead thee into the dark paths of infidelity;
but that thou mayst ever rejoice, with joy unutterable and full of glory,
in the knowledge of Him in whom thou hast believed.

I greatly tender thy welfare;
I feel for thee sensations stronger than nature can suggest;
and in the warmth of this best love,
I commend thee to the protection of the Preserver of men.
I earnestly wish thee a safe hiding-place, as under the hollow of His hand,
and a hope in his salvation on thy account accompanies my wishes.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to James Pemberton.

[.signed-section-context-open]
London, Third month 28th, 1764.

Those warm sensations of friendship which I have entertained for thee,
I with pleasure often feel renewed in my mind, and afresh at this time.
I make no other apology for my past silence than this--a variety of
engagements have confined me very much to such as are necessary.
The last winter hath been a state of confinement, through a tedious indisposition,
I dedicated the first fruits of returning health to this city,
to which I thought I owed a visit.
I have been here three weeks, and though in a state of precarious health,
yet upon the whole satisfied with my journey, believing, when I have done what I can,
I have done what I ought.

I cannot but deeply interest myself in whatever attends a province and a people,
to whom my mind is often united in the strong ties of brotherly union,
and for whom I feel the warm attachment of that love, which, when present with you,
was mutually and richly shed abroad in our hearts.
There remain amongst you a number who will profit by these alarming circumstances,
and quicken your minds to a frequent recourse to the strong Tower of all the righteous;
a number who considered it their alone safety in days of prosperity,
and were concerned in those seasons to cleave in soul to the never-failing Good,
as their principal riches; and now, in the day of calamity and violent commotion,
know the inestimable value of the Father and Friend of
his people being their stay and succour.
Oh that more of the minds of the divinely visited among
you were centred in the calming virtue,
and had been kept out of the hurries and bustle;
surely the canopy of salvation would have eminently overshadowed many,
and they would not now have been left to dispersion,
and wandering as sheep without a shepherd.
May the hitherto preserved of God dwell in the hiding place of His power,
that if yet the skies gather more blackness,
and the tempest break forth with redoubled violence,
these may be kept under the hollow of an Omnipotent hand, until the storm be overpast.

Some reports have circulated here, that there hath appeared among many under our name,
with you, a sorrowful defection from our religious testimony, by taking up arms;
and this is affirmed concerning some, for whom I hoped much better things.
If this be the case, it will be an additional affliction.
I earnestly wish the minds of the living may be
influenced by that wisdom which is from above,
and put on fervent charity one towards another,
endeavouring to restore in the spirit of love and meekness,
but ever mindful of that testimony to the Prince of peace,
which was delivered to us to maintain to the world.

[.signed-section-closing]
Thine affectionately.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Henry Portsmouth.^
footnote:[Henry Portsmouth died at Basingstoke, tenth month 17th, 1780,
aged seventy-seven.]

[.signed-section-context-open]
Warrington, 1760. Eighth month 16th, 1764.

Since our first acquaintance, which is now of many years`' standing,
thou hast possessed a share in my affectionate friendship,
and a hope accompanied my earnest desire for thy preservation
in the Truth as it is in Jesus to a happy conclusion.
Great was my concern, therefore, when I had a manuscript transmitted to me,
signed by thy name, and which I am since fully confirmed, was thy performance;
a manuscript which militated against a material and
fundamental testimony received amongst us as a people,
and which, I fully believe, is of Divine original.
But, inasmuch as reasoning and argument laid not the foundation of our dissent,
but the secret influence of the pure, holy principle of truth and righteousness,
it is not in my mind so much to attempt a refutation of thy arguments,
as to endeavour to turn thy mind to that which first visited thy soul,
and drew thee into communion with us.
I beseech thee,
call to mind the discoveries and impressions made in the days
of tender inquiry after Truth and peace with God;
what it led to, and what it led from;
and diligently examine whether thou hast kept thy first love;
whether the spirit of this world hath not entered, and allured thee from that holy,
circumscribed frame of spirit, in which we can alone abide in safety,
and witness the salvation of God to be as walls and bulwarks about us.
A frequent, impartial scrutiny of this kind appears to me necessary for us all, lest,
having run well for a time, we should unhappily miss our way,
and stumble on the mountains of error, and fall to rise no more.
Most necessary, therefore, is the advice,
"`Walk in the light,`" that ye may become children of the light, and of the day of God,
and be preserved through the jeopardies of time,
and from the deceivableness of unrighteousness,
to a happy possession of that crown of life,
which is reserved for all those who fight the good fight, and keep the faith.
If, upon a most serious anticipation of that solemn day,
when every secret shall be disclosed, and true judgment administered,
thou findest not the testimony of Divine approbation sealed upon thy spirit,
in this dissent from thy former friends, I entreat thee,
by every consideration which happiness in time or in eternity can suggest,
stand open to conviction.
It is infinitely better to retract an error, though we may fall into the hands,
or under the censures of men,
than to persist in any doctrine or practice repugnant to the holy Witness,
and thereby incur Divine displeasure.
If we fall upon the stone, which is a stone of offence to the wisdom of this world,
it will break us to pieces; but if it fall upon us, it will grind us to powder.
Oh, may thy mind be turned to the light,
and witness the searching of heart for the divisions of Reuben,
that natural might and strength,
and boasting excellence which subtilely spreads itself through the incautious mind,
but God hath determined, that in his kingdom and work it never shall excel.

When I was last in London, I saw a long letter from thee, addressed to Jacob Hagen,
which added to my sorrow on thy account; the intention of this letter seemed to be,
to intimidate Friends from dealing with such amongst us
as renounce the testimony we were raised up to maintain.
I ever wish to see love, tenderness, and long-suffering exercised in the Society,
one towards another; and as far as in my power, have endeavoured to promote it,
that that which is weak may not be turned out of the way, but rather restored.
Nevertheless,
there is a necessity for a steady regard to be paid to
the prime end of our being raised up as a people,
viz: the supporting a testimony to the coming of the reign of the peaceable Saviour,
whose kingdom is not of this world.
Our worthy ancestors received this testimony, and were called to bear it;
and harmonizing together in the truths of Christianity, they united in one body,
being of one heart, and under the dominion of one spirit.
A people thus formed for the Lord`'s use,
in carrying on the work of glorious reformation in the earth,
and whose testimony contradicted the received maxims of the world and its policy,
had to expect the opposition and suffering which ensued; first,
from the powers of the world, which raged at the birth of the Man-child,
and sought to swallow him up; but He who had called them to show forth his salvation,
and to step forward to the perfection of Christianity,
supported them under cruel persecution, to his own praise,
and the promotion of his name on earth.
The second and most painful cause of distress and sorrow, was the apostacy of some,
who kept not their habitations in the light, but departing from the union of the spirit,
lost their places in the body, and became its most invidious opposers:
their plea was liberty--their design licentiousness, to introduce confusion and anarchy,
and sap the foundation on which our union stands,
and rend the seamless garment of our Lord and Master.
After much waiting and tender advice, the church testified to the world,
that these were not of her.
No injury was done to the person or persons who ceased to be of us,
by disclaiming our essential principles; it was justice due to the testimony of Truth,
and to the Society, to declare to the world that these first forsook us, and not we them.

Some part of thine to Jacob Hagen,
seems to render it not improper to vindicate
that part of the Society thou stylest zealots,
from any imputation of endeavouring to lord it over their brethren`'s faith.
I believe many of those Friends in Philadelphia,
who precipitated by their fear in time of great alarm, took up arms, will,
on cool reflection, and by tender dealing,
be brought to see the inconsistency of their conduct,
and return to their places in the house of the Prince of peace;
and I doubt not the tenderness of their brethren towards them.
But great is the difference between these,
and a person who coolly and deliberately forsakes the testimony of Truth, and teaches,
as far as he can, others to do so.
The cause is not ours--it is not of the flesh, nor of the will of the flesh, but of God;
the longer I live, the clearer I see it, and it is a testimony which will gain ground,
and yet spread more and more amongst mankind.
I am convinced of it as a most certain truth,
not only from faith in the progress of the spirit and power of our Lord Jesus Christ,
towards the redemption of the world, and beautifying the place of his feet,
but even from the conversation I have had with some of eminent stations in the world.
A person of high distinction as a warrior told me some time ago,
that though he was a soldier,
no part of our principles was more just in his apprehension,
than our declining war in every respect.
He said he believed the day would come when
nation should not lift up sword against nation,
and when they should not learn war any more.
He remarked, that so mighty a change must be gradually brought about,
and the morning of that glorious day had, he believed, dawned amongst us as a people.
Happy are they who abide in their ranks in the Lord`'s service;
they will mingle at length with the conquerors, and inherit all things.

I beseech thee, my friend, consider things deeply; if thou cease to be one of us,
as a society raised for the purpose intimated above,
why shouldst thou endeavour to draw others after thee from the Lord`'s cause?
a work which on a dying bed will not be crowned with peace.
Blame not Friends for their faithfulness to their avowed principles,
and steady adherence to the cause of God.
If the way is become too strait for thee to walk in,
censure not those who dare not leave it, whatever suffering may arise,
from the power of this world,
or the defection of such amongst us from whom we hoped better things.
I cannot easily omit mentioning how my mind was struck
on hearing thy name read in the correspondent book,
the last yearly meeting, as a correspondent for Hampshire; how inconsistent this is,
must at once appear to any considerate person.
What advice couldst thou give to a tender Friend in distress on the militia law?
or how couldst thou represent it, if necessary, to the Meeting for Sufferings in London,
when thyself hast ceased to maintain that branch of our testimony?
Surely, thy prudence as a man will suggest the propriety of having thy name discontinued.
The bulk of this letter hath greatly exceeded my intention;
I make no other apology than my true love for thee and thy family,
and earnest desires for thy recovery and restoration; and this rests with me to add,
that nothing but a close dwelling with the Spirit of judgment,
and the holy fire which refines from dross and tin,
can prevent thy farther declension and deviation from the way to the kingdom of rest.
Other branches of our religious testimony will be called in question and despised,
to the deep wounding of thy own soul, and to the grief of thy family and friends;
but the cause of God, and his holy eternal Truth,
will remain unhurt by the defection of those who forsake him;
for the foundation of God standeth sure,
having this seal--The Lord knoweth them that are his.

[.signed-section-closing]
I am thy sincerely well-wishing friend,

[.signed-section-signature]
Samuel Fothergill.

--

In 1764,
Samuel Fothergill was engaged in a general visit to the meetings of Friends in Scotland;
in which he was accompanied by Isaac Wilson.
This visit was not, like that to Ireland, two years previously,
by appointment of the yearly meeting, yet it was somewhat of the same character,
being to inquire into the state of the Society,
and also in the present case to endeavour to improve
and restore the discipline in that country,
which was at that time reduced to a very low slate.
In several places, the monthly meetings had almost ceased to be held,
and it could not be ascertained who were, and who were not,
entitled to membership in the Society.
This lamentable condition continued for about twenty years after this period; when,
in 1784, the late John and Elizabeth Wigham, from a sense of religious duty,
went to reside in Scotland.
This tended much to the revival of the Society there;
some other ministers were about the same time led to
visit this nearly desolate part of the heritage;
amongst these were George Dillwyn and Henry Tuke,
who visited Scotland more than once about this time;
John Pemberton also was much engaged in that nation.
Soon after this, the discipline was in good measure restored,
and a few solid Friends were raised up to conduct the affairs of the Society.^
footnote:[At the time of Samuel Fothergill`'s visit,
the meetings for discipline in Scotland were, First,
the yearly and quarterly meeting of Aberdeen, consisting`' of three monthly meetings, viz:
Aberdeen, Kinmuck, and Urie.
With Kinmuck was joined the meeting of Old Meldrum, and with Urie that of Stonehaven.
Second, the yearly and quarterly meeting of Edinburgh,
also comprising three monthly meetings, viz: Edinburgh;
consisting of the particular meetings of Edinburgh and Preston-pans; Glasford, Hamilton,
and Garthshore; consisting of the meetings of Glasford, Douglas, Hamilton, Badcow,
and afterwards Glasgow: Lessenden, formed of Lessenden and Kelso particular meetings.
They so continued until 1786,
when a Special Epistle was received from the yearly meeting in London,
confirming their being united under the name of the Half-year`'s Meeting of North Britain,
to stand in the same position as the quarterly meetings in England:
this was then concluded upon, and the first of such meetings,
afterwards designated the General Meeting for Scotland, was held at Aberdeen,
in the tenth month, 1786.]

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to his Brother John.

[.signed-section-context-open]
Old Meldrum, Ninth month 8th, 1764.

We staid first-day at Edinburgh.
The meetings there are composed of a very few of our Society, and few, very few,
of these worthy of the name.
Several came in, and behaved civilly; the state of the meeting is indeed very low,
but I need not particularize that place, the state of the Society in general is so,
though I trust there is a little remnant preserved living.
We went from Edinburgh to Stirling, where I appointed a meeting;
the magistrates freely granted the town-hall, and mostly attended.
The meeting was to good satisfaction, being favoured with the extension of heavenly,
humbling virtue.
We passed through Perth, Dundee, Montrose, and some other towns of less note, to Ury,
visiting a few scattered, poor individuals, where we could find them,
but had no concern but for the lost sheep of the house of Israel.

We had a meeting at Ury on fifth-day evening;
the particular members of that meeting amount to about thirteen or fourteen.
A sister of the late, and aunt to the present Robert Barclay, appears a steady,
solid Friend.
He is very kind.
We propose to be here tomorrow, where is the largest body of Friends in Scotland.

Our visit will, I believe, be peaceful in the event to ourselves,
comfortable to a very small number, and a pleasant amusement to divers others,
who would avail themselves of Truth being exalted, from motives of self-love.
The prime end of our visit, the re-establishment of the discipline,
and a close inspection into the state of the Society will scarcely be obtained.
The Queries are sometimes read in the quarterly meetings, but rarely, if ever,
considered in the monthly meetings,
which are in several places reduced to three or four persons;
but each having separate bequests are determined against any junction,
and for the same reason the two yearly meetings are determined against a union,
which we have urged upon them as much as prudence admitteth; for I would not exasperate,
by pressing too vehemently a matter the active members are determined against;
for I find W. M. and R. B. inflexibly bent against uniting the meetings.

It is not right to complain of the anxiety our prospects and feelings afford us daily;
we ought to accompany the Seed, and it is in this nation much depressed.
The division amongst the Presbyterians is great; Seceders, and Seceders,
and Seceders from them, are almost daily making their appearance;
I sometimes hope this is a previous step to better times,
and that the commotions and overturnings may be a means to raise a sense of danger,
and a secret cry for relief to Him who is alone able to afford it.
How happy the lot of those who know the tried foundation,
and with diligence and watchfulness wait to feel themselves established thereon.
May it be our continued experience,
until the time come that we shall never again be moved.

My companion, Isaac Wilson, is truly acceptable and helpful.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to his Sister.

[.signed-section-context-open]
Warrington, 1760. Tenth month 19th, 1764.

I have no conversation which furnishes equal satisfaction with that of now
and then renewing an agreeable intercourse with thee and dear brother,
and you are kind enough to accept in good part the proofs I
sometimes give of my most affectionate remembrance.
My late journey into Scotland hath furnished me with some experience, and I hope,
improvement.
I went in great weakness and simplicity.
I seemed prepared for distress and sorrowful sympathy.
I had a secret hope that it was not inconsistent with Christian
charity to visit the small remains of the Society in that nation,
though I could say or feel little of that injunction
and duty which I have often felt for other services,
but a secret draught of mind hath accompanied me for some time.

We were favoured with good weather, fine roads, and every accommodation necessary:
and what is more to be valued,
with the presence and help of that Helper who alone is able to stay and succour,
under the pressure of every painful circumstance.
May a deep sense of his mercy, and my constant need of such relief, ever possess my mind,
and then I have grounds of hope in the descending of the latter,
as well as in the trembling remembrance of the former rain.
The state of the Society is very low in that kingdom;
so low as to render it very difficult to see how to labour amongst them,
with regard to the reestablishment of discipline; and such is the genius of the people,
that overloading or overdriving would effectually defeat the intention of our visit.
We have had divers opportunities of conference with the few Friends who remain,
and hope to the help of some few individuals;
the event must be left to the Disposer of all.

I went from our General meeting at Manchester directly to Kendal,
where I arrived on second-day night,
and found my mind engaged to stay the funeral there of a Friend,
not unknown to the Doctor and me, when at Brigflatts school.
Isaac Wilson and I reached Edinburgh by way of Carlisle, Langholm, Hawick, and Selkirk.
On first-day we were at the meetings at Edinburgh,
which were small and poor respecting Friends, but pretty many others came in,
and we were favoured; and remarkably so in the evening, at the burial ground,
on occasion of the interment of one under our name,
who came to that city a few days before, and died suddenly.
Next day we went to Stirling, and had a large and satisfactory meeting in the court-house.
Isaac Wilson and I then proceeded to Ury,
where we had a small meeting with the few of our Society.
On first-day we went by Aberdeen to Old Meldrum,
calling to visit some odd stragglers under our name by the way.
At Old Meldrum and the neighbourhood is the largest body of Friends in Scotland.
We had some close, beneficial opportunities with them,
and left them with the evidence of having done what we found to do.
On our return we had a very large meeting at Aberdeen, which was to good satisfaction.
Our mutual friend, David Barclay was with us, at Ury and Aberdeen.
He treated us with great affection,
and was the means of great relief to my mind in
procuring us a very large meeting at Aberdeen.
I attempted, about eighteen years since, to see the inhabitants of that city,
but none would then give me their company.
With close travel we reached Edinburgh on the fifth-day evening,
and stayed over the ensuing first-day,
endeavouring to spend our time not remote from the intention of our visit.
We had a meeting, consisting of the members of our Society, to good satisfaction,
as the result of faithful labour,
though afflicted to see and feel the extremely low state of things amongst them; but,
through Divine favour, the testimony was exalted, the disobedient warned,
and the little which remained alive encouraged.
But upon that city,
a cloud of darkness and the shadow of death seems to me
to remain in a distinguishable manner;
and I think, though their number may amount to near thirty,
there is scarcely one bound in heart to the testimony.
We went to Glasgow, where we had a large, open meeting;
many principal people of the city were there, and Truth mercifully owned us.
We met with much civility there; the magistrates treated us with great regard,
and in a manner I could not expect.
Several of the principal people earnestly requested my longer stay,
as they alleged they knew nothing of Quakers but through the medium of misrepresentation,
and were astonished to find our principles so different from
those which their ministers generally ascribed to us.
But finding our minds clear, we left the place, and went to Edinburgh, and Guyle Kirk,
and so to Kelso, where we had a pretty open meeting,
amongst a few unworthy people under our name, accompanied by a few of other societies,
who seemed nearer the kingdom.
On seventh-day we reached Newcastle, and came thence to Kendal.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to his Brother and Sister.

[.signed-section-context-open]
Warrington, 1760. First month, 1765.

I am, through mercy, in good health, a cold excepted,
which I got in our arduous labour of visiting families; it is not very troublesome,
except when I write, or should sleep.
I am content with this indication of a frail tabernacle,
I know it will soon moulder to its original.
I am thankful the loins of my mind are girded up,
at least strongly to wish to run the race successfully, and finish in peace.
I look towards a release from temporal concerns with increasing ease;
I believe it is quite right I should dress my wings,
to take my flight to the land of peace,
through those paths of light which may be assigned, but not yet clearly unfolded.

[.signed-section-signature]
Samuel Fothergill.

--

About this time, Samuel Fothergill retired from business altogether.
His trade was that of a tea-dealer, with which he combined some other articles;
and he had occasionally mercantile transactions with America,
sending out thither manufactured goods, and importing the produce of that country.

[.embedded-content-document.letter]
--

[.letter-heading]
Dr. Fothergill to Samuel Fothergill.

[.signed-section-context-open]
Lea Hall, Sixth month 28th, 1765.

I am thankful, repeatedly thankful, for this recess;
it was not of my own contriving or willing; but I esteem it as I ought,
a favourable prospect of escaping by degrees from labour next to oppression.
Much I owe to the public, and honestly have I endeavoured to repay the obligation.
May they never want persons better qualified than myself to serve them.
To me the world has not frowned; I courted not its favours, nor feared the reverse.
It is time, however, to think of getting into port, and as the wind serves,
I hope to make use of it for the best of purposes--security.

[.signed-section-signature]
John Fothergill.

--

Lea Hall, whence the foregoing letter is dated, is about three miles from Middlewich:
it was occupied by Dr. Fothergill for several years.
His object and wish in thus occasionally secluding himself,
he states in a letter to his brother Samuel, written in 1764.

[.embedded-content-document.letter]
--

"`A desire has of late risen in my mind to retreat for a few months next summer,
into Cheshire, and some part of the county not far from Middlewich appeared suitable;
I wish by a few months`' recess to get some time to breathe,
and to let the dependence that many have upon me here, gradually die away,
rather than break it off abruptly.
I can only look for quiet in a place where I have no acquaintance,
yet not too far from those I most love.
If we can procure some respectable abode, not far from a meeting,
in a situation not unhealthy, nor very populous,
where there is room comfortably to accommodate my sister, myself,
and four or five servants, with a bed or two for our friends, I shall be satisfied.
In this part, there is the forest (of Delamere) on one side,
which is but thinly inhabited, and there is a meeting,
and I can see you all occasionally.`"

--

In pursuance of this plan, Lea Hall was engaged, and here with his sister,
and frequently other relations and friends,
he was accustomed to pass a part of every summer, for several years;
enjoying in this retreat, a season of needful repose from the fatigues of his profession.
In this retirement he had an opportunity,
which his incessant engagements in London did not afford,
of indulging in the pursuit of science,
and more particularly in the study of Natural History, and Botany;
to these he was much attached, and in various ways a munificent promoter of them.
The place, though much gone to decay, still bears in its ancient garden,
marks of his love of, and taste in planting.

One day in each week he attended at the neighbouring town of
Middlewich to give gratuitous advice to the poor.

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Israel Pemberton.

[.signed-section-context-open]
Warrington, 1760. Twelfth month 10th, 1765.

My correspondence on your side the water is almost dropped,
owing principally to my incapacity of sustaining it as I could wish sometimes,
for I am sure I often feel the same animated love of the brethren
extend itself towards the children of the Father`'s family,
which was often my crown of rejoicing when amongst you.
But as my engagements and labour become various and diffusive,
my mind necessarily admits of various objects of solicitude,
and the individual is swallowed up in the general.
Thus I feel myself frequently,
and am obliged to postpone the offices of private friendship,
to the more urgent obligations of general duty.
I would not have made so long an apology for my silence,
had it not been the true state of my mind,
and to remove any apprehensions of forgetfulness or neglect of
a person and family I remember with great affection,
and for every branch whereof my spirit ardently wishes every happiness.

Dear friend, we are not strangers to the commotions of your land,
the report whereof hath reached our ears, yea, and many of our hearts,
whereby deep inward sympathy, as becomes brethren, has been raised,
and a secret strong travail before the Lord of the whole earth,
for the preservation of his family in this
dispensation of the hour and power of darkness,
which has come upon many amongst you, and is endeavouring to introduce ruin,
and desolation, and every evil work.
In such a season as this, it is next to impossible to stand neuter;
the conflicting powers of light and darkness, according to their prevalence,
enlist the spirits of the people under their respective banners;
some to endeavour to build up and repair the breaches,
and to be bound in heart to the holy testimony,
and earnestly contend for the faith once delivered to the saints.
Now, saith my soul, "`Peace be to thee, O Zion, and peace to thine helpers;
and may these evermore remember,
it is the Lamb and his followers which shall have the victory.`"
Though this expression may have become trite by frequent repetition, yet it is a great,
instructive and important truth.
Neither the most ardent zeal of the cherub or the seraph,
nor the sagacity of the living creature, though full of eyes before and behind,
nor the strength of the lion can overcome, unless the meekness, gentleness,
and patience of the Lamb, suffering, yea slain, from the foundation of the world,
have the ascendancy, and be diffused through all our labour.
A vivacity of mind which is natural,
and a solicitude of mind for the cause of Truth which is from a higher source, are,
I believe, distinguishedly possessed by us both, and I feel, for myself,
the absolute necessity of deep attention to His
direction who has engaged me in his service,
in order to experience him to put forth,
having reduced the creaturely part into a humble dependence upon Him,
whose is the power and the wisdom.
We are now, my friend, arrived at a date of life when the fuerte which attends youth may,
by the laws of nature, be supposed to abate, and cool, deliberative wisdom,
confirmed by experience and long observation, take its place; and I hope,
we have not so lived and laboured, as to be destitute of a portion of Divine wisdom,
to correct the mistakes and inadvertencies into
which we may have been hurried in past time,
which I acknowledge with regard to myself have been various.
Oh that our minds may sufficiently cleave unto that Hand of power,
which will effectually convert us from every error in judgment and practice,
and then properly enable us to strengthen our brethren.

Dear friend, I beseech thee, by the mercies of God, whereof thou hast largely partaken,
abide in the quiet habitation, whose safety and beauty thou hast often beheld,
and desired thy portion in it.
Let neither the commotions without, nor defection within,
carry thee away from the quiet rest;
a greater degree of fitness and wisdom to act rightly, when necessary in both,
will be hereby attained.
I feel inexpressibly a sympathy of spirit with Friends in your parts;
the faithful and unfaithful are the companions of my mind almost incessantly;
to the former, I wish that wisdom and knowledge may become the stability of their times;
for the latter, that through the prudence, patience, tender compassion,
and steadiness of the faithful, they may be restored upon the proper foundation,
and the holy testimony preserved inviolate.

I have need to apologize for my freedom in thus expressing the
feelings and ardent wishes of my mind towards thee,
for whom I retain the longings of heart that friendship of the highest kind inspires;
a similarity of natural disposition begets a peculiar attention,
united in wishes for the prosperity of the great and mighty cause of religion and virtue.
May we both seek the only means to obtain our wishes,
and never be the means of defeating, by our haste and imprudence,
the end we professedly and really aim at.
With a heart replenished with near affection and sympathy, I remember,
and often in spirit visit, thy dear wife, my beloved friend;
I have often essayed to write to her, but my feelings baffled expression.
Heaven`'s peculiar favourites are often the most tried, that they may be rendered perfect,
lacking nothing, and shining examples of every Christian virtue to others.
Salute her in my name,
and assure her of my tender and affectionate sympathy and remembrance.
As to my health, it has for divers years been precarious; something of a gouty nature,
but not the disorder regularly.
I have been confined eleven weeks, and have scarcely strength to walk five minutes;
yet I am slowly recovering, but very feeble; this has been the labour of almost a day,
my hand being too weak to write many lines at once.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to his Brother John.

[.signed-section-context-open]
Warrington, 1760. Twelfth month 16th, 1765.

I lately rode as far as Congleton,
to the funeral of a person who had some relation to the Society,
though not strictly a member; the journey was of use to me, for I travelled slowly.
I was much favoured amongst a multitude of people, of various ranks;
and humbly thankful I am for every instance of merciful regard extended to my own spirit,
and the gracious extendings of Heavenly help to others.
I feel time to slide away apace; little of it seems before me,
until it change its name to eternity.

I am now just returned from paying the last solemn act of friendship
to the memory and remains of our mutual valuable friend,
Joseph Hobson,^
footnote:[Of Macclesfield.]
who was yesterday interred.
His death was occasioned by lying in a damp bed a few weeks ago.
A very great number attended the solemn occasion,
and the voice of the people proclaimed him a valuable, good man.
I never saw a person more regretted;
the eminent overshadowing of the Father of spirits gave room
to hope human approbation is not his sole happiness.
I have heard also of the decease of our worthy friend, David Coulson.
I need not enlarge upon this breach into the near
circle of our mutual friends and acquaintance;
neither, indeed,
doth the present collected state of my mind allow of
much expression;--I feel more than I can write,
and the bare account is sufficient to awaken and quicken every
proper sentiment and resolution in thy mind.
Others will soon, very soon, write the mournful account of our removal!
Oh, may our minds receive the proper instruction, and be renewed in necessary assiduity,
that our example and close may be happily instructive.
May the work be accomplished, when the awful summons comes:
I hope my whole heart is renewedly bent in fresh ardour
to attain this important and most interesting prize.
The situation of my health is comfortable,
a constant soreness and weakness in my feet excepted; however, I am content and thankful,
in an humbling sense that best health is renewed at times; and I wish no more,
here or hereafter, than heavenly regard.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Joseph Baker, Jun.
of Warrington.^
footnote:[He died at Penketh, second month, 1809.]

[.signed-section-context-open]
1766?

A degree of anxious concern for thee induces me thus to address thee,
and from the warmth of an affectionate heart, to open something for thy consideration,
to which thy temporal and eternal welfare require thy attention.
Notwithstanding many of our youth, and thyself among others,
have despised the simplicity of a plain appearance, like Friends, yet I am satisfied,
from the neglect of that distinction being maintained,
they and thou have been laid open to the inducements of that destroying
enemy who hath great power over the inhabitants of the earth,
and then have leaned to an earthly spirit.
Thou hast fatally found the truth of this remark:
if thou hadst appeared like a religious, sober Friend,
those companions who have exceedingly wounded thee,
durst not have attempted to frequent thy company.
Thou seest Henry Fothergill; his conduct and appearance are consistent and sober;
none of those wicked young men dare approach him, such is the dignity of religion,
and its superiority over vice and folly.
I mention him, not for any partial regard for him as my kinsman,
but as a person I have had frequent opportunities to remark.
Thou knowest the esteem he has justly obtained, his usefulness in his father`'s family,
and that he is more justly honoured than I think any young man in town.
I mention him, not to upbraid thee, but to intreat thee; his manners are virtuous,
his mind serene and peaceful; the contrary, thy own experience will tell thee,
hath been thy lot, and it results from a conduct opposite to his; nevertheless,
I am persuaded the regard of Divine Providence is not totally withdrawn from thee;
his mercy is extended to recover thee, as from the gates of hell,
and pluck thee as a brand out of the fire.
My concern for thee, the kind reception thou hast met with at +++_______+++,
and the dispositions of the worthy friends there in receiving thee,
are to me proofs of the interposition of a providential hand yet stretched out to save;
and these things ought to be humbly marvellous in thy eyes,
and induce thee to walk answerably to the favours received.
I earnestly wish thee to abstain from any company that may be improper.
Thy resolutions are weak; the poison of evil company very ruinous.
If thou hast no other inducement to alter thy dress, I beseech thee to do it,
to keep the distinction our principles lead to, and to separate thee from fools and fops;
at the same time that, by a prudent distinction in thy appearance,
thou scatterest away those that are the bane of youth,
thou wilt engage the attention of those whose company
will be profitable and honourable to thee.

Thus, dear friend, my heart longs for thee and for thy help,
that thou mayest improve the present providential allotment to the best purpose,
that it may be of lasting advantage to thee.
It will be good for thee to bear the yoke in thy youth;
if thy mind be rightly subjected to it, thou mayest have cause to say.
It was good for me that I was troubled.
I beseech thee often to read the Holy Scriptures; remember the prodigal son,
and imitate his penitent example,
and the same gracious reception from the Everlasting Father will be thy portion.
With what joy would thy anxious parent, thy affectionate sister, view thee reformed,
steady, and prudent; but if, which God forbid,
thou shouldest slight this providential opportunity of retrieving thyself,
and relapse into those things which have hitherto ministered much to thy hurt,
and if continued in, must effect thy total ruin,
how shall I meet those friends to whose care I have been instrumental in committing thee]
And what will be the sentence from despised mercy?
I am shocked at the mere supposition; but what must be the suffering of such a state?
Dear Joseph, what shall I say?
what can I say, that will tend to thy help,
but earnestly press thee to seek Him who is mighty to save,
and to whom Jonah cried out of the belly of hell?
Cherish every impression of good; place thyself frequently before that tremendous bar,
to which thou art hastening, and bring every thought and action to judgment;
be diligent and faithful in business, but above all,
be diligent in making provision for thy poor soul.
Farewell.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Dr. Fothergill to his brother Samuel.

[.signed-section-context-open]
London, Sixth month 10th, 1766.

The enclosed is from the Countess of Huntingdon,
and I apprehend it relates to the convincement of a person high in her esteem,
and a kind of recommendation of her to thy notice.
I am informed that this is no sudden start, but has been gradually ripening some time.
The countess saw her friend engaged,
and went with her to the meeting the first time she gave up to join the Society.
This circumstance, I mean the convincement of a person so peculiarly situated, will,
no doubt, become the subject of much conversation, at least amongst ourselves,
and I think we ought, as much as possible,
to restrain the imprudent amongst us from acting imprudently.

Thou wilt impart this to nobody; let the account spread by other means, not by ours:
it is a lesson we ought to profit by, not to amuse; a simple,
upright devotion of heart to do the will of Him,
whom to serve is our interest and happiness.
Great example! let us follow it; and those who do it most, will say the least about it.
In dress, in conduct, she studies simplicity: perhaps, in the guise of zeal,
an enemy may steal in, but the integrity of her heart will, I trust, befriend her.
I know her not; I know some of her family: her husband allows her a sufficient support,
so that interest has no share.
About Brightelmstone, where she now is,
there is a large number of those called Methodists,
many of whom are dissatisfied where they are; if they follow on to know,
whether they join us or not, they will be happy.

We were glad of thy safe arrival at home,
and received thy kind intimations with the affection they deserve.
If they produce the fruits thou wishes, they will be to our mutual happiness,
and our own peculiar advantage.
Create in me a right spirit, renew a clean heart, is oft, my wish;
I know these are not the words as they stand, but I want to know the full completion.

When I tell thee that this is written after the incessant labour of seventeen hours,
thou wilt readily excuse its defects, and think me, however weak,
yet not wholly without a claim to the title of thy affectionate brother,

[.signed-section-signature]
John Fothergill.

--

In the seventh month, 1766, Susanna Fothergill again paid a religious visit to Scotland;
she was accompanied by Joseph Harwood, of Manchester, also a minister.
Near the close of the year,
her husband was engaged in a religious visit to Friends of London.
Whilst in that city,
he was seized with an illness which obliged him to relinquish his engagement,
and retire to his brother`'s country house at Upton; where, under the care of his sister,
he was confined for some time.

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to his Sister.

[.signed-section-context-open]
Warrington, 1760. Tenth month 18th, 1766.

I have been to Nottingham, and went by Manchester,
where I found brother Isaac Crewdson very much indisposed,
and every symptom of approaching dissolution, which ensued last first-day night.
I was at his burial on fourth-day; it was large, and the opportunity was a favoured one.
I cannot but regret his loss, though I fully believe his removal is a happy exchange,
and agreeable to his own last intelligible words, "`To rest, to rest, for evermore.`"
What more desirable, my dear sister, than such an issue of our pilgrimage!
May our minds be exerted to pursue this glorious mark,
with a diligence proportioned in some degree to its unspeakable value.
The circle of our acquaintance is almost daily invaded, and we, also,
shall soon furnish the opportunity or occasion of instruction,
now almost daily put into our hands;..., How safe is diffidence,
even if obtained through chastisement for error!

I am, through mercy, bravely, my hand excepted, which is still sometimes weak,
and often painful, but I am content and thankful.
I have more good than I have merited, and less affliction than is justly due.

You are returned to the trammels again, I believe with reluctance;
you can taste the sweets of retirement with pleasure, and dare be alone with yourselves.
I hope never to result in indolence, but my love increases to solitude;
not that I dislike converse with mankind,
but I am very desirous to improve it with something I at times feel in myself.
The silent, solemn step of time advanceth fast, and carries us along with it,
to a place whence there is no return, to do or undo.
May it become our chief concern--nay, I hope it is,
and may we retain it--to have our accounts in readiness; and even then, mercy,
not merit of ours, must be the ground of our hope in the ordinance of peace.

Lively are my desires for all our safety and establishment;
desires wherein I know thou joins me, with an ardent mind;
we have ground of hope that He who hath wrought the will, will also enable to do,
as we cleave to him in simplicity and uprightness.
But how much goes to constitute the character of upright?
There is so great a mystery of iniquity in the
transformations of seemingly laudable self,
that I look upon it as the crown of true Christianity,
and to exceed all the beauty of visibles, whether respecting religion or this world,
to obtain this character.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Catharine Payton.

[.signed-section-context-open]
Warrington, 1760. Third month 25th, 1767.

With thee, my dear friend and sister in the pure Truth, I am more sympathetically united;
as my own, I tender thy good,
and preservation through the various vicissitudes of thy passage,
whether relative to the temporal or spiritual probations which may be assigned thee,
in either relation.
Thou hast in many trials found the all-sufficiency of the divine Hand;
and we have nothing else to rely upon, equal to the labour of the day.
He who rides upon the wings of the wind, in his triumphant glory,
dwells in the lowest valley of humiliation,
and is there more sensibly experienced to sustain under every stripping,
than distinctly discovered when he makes the clouds his chariot.
I have, of later times, been very deeply exercised,
and often in the most stripped poverty.
I have, as yet, seen nothing clearly,
respecting public service which may be required and
this humbling season preparatory to it--but so it is;
and may my heavenly Father`'s will be done,
and issue in a still more enlarged degree of sanctification,
though I wear sackcloth on my loins,
until I am clothed upon from heaven with the garments of immortality.

And now, my dear friend,
in the sense of that condescending goodness which hath mercifully favoured us,
in calling us out of darkness into his marvellous light,
and hath joined us to all the living, and been as our song and our strength;
who has fed us with food, and remembered us in tender mercy; my spirit salutes thee;
with earnest breathing for our preservation and increase in holiness and sanctification,
that He who has called us may be honoured by us, and we, finally, honoured with him.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Israel Pemberton.

[.signed-section-context-open]
Warrington, 1760. Fourth month 1st, 1767.

My affection remains undiminished.
I love you all tenderly, and with equal solicitude desire your essential happiness,
as when my leisure and bent of mind allowed me more
frequent opportunities and occasions of telling you so.
My health hath been precarious, or rather below that, generally impaired;
and though my mental faculties may not be much affected,
the corporeal powers seem not likely to continue to advanced years.
My principal complaint is a weakness and pain in my right hand; I believe,
owing to a fall from my horse several years ago.
I cannot write much without respite,
and this often breaks the chain of sentiment and sensation,
which I ever wish to be the soul of my correspondence.
For though I am often poor and debilitated, both in body and spirit,
I feel an ardent desire to be preserved alive in the best things.
My affection for Friends in Philadelphia is strong,
and often of late revives with great animation.
I run from house to house with sympathy; I rejoice with the few who can properly rejoice;
I mourn with the many who pensively muse on the
roll written within and without--Mourning,
lamentation, and woe!
What further respects you and me is at present behind the veil.
My dear wife is cheerful, and not destitute of best health:
that thine hath been favoured with health, is a pleasing account; I love her tenderly,
and wish the consummation of every desire she forms for her own and others`' good.

[.signed-section-closing]
Thine in undiminished regard and affection,

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Dr. Fothergill to His Brother Samuel.

[.signed-section-context-open]
London, Twelfth month 10th, 1767.

Samuel Emlen is here; a reputation to his country, a help to society,
the pattern of innocence, wisdom, and simplicity.

I hope gradually to lessen both my business and all other incumbrances.
I have been preserved through many dangers,
and my life mercifully prolonged to this time;
and it is not the least of the favours that I have to acknowledge,
that I am kept in a degree, alive to gratitude.

Do not regard the expense; at our time of life,
two years of exemption from great inconveniences are not to be valued at a low rate.
Had we children dependent upon us, other considerations might justly take place.
In the course of Providence, it is so ordered that we have none to look up to us,
and call us father--an exemption from numberless anxieties.
It is then, but justice that we use the favours of Providence granted to us,
whether the fruits of our own industry, or, by a more special favour,
of easy inheritance;
to the proper purposes--for our own accommodation
according to the station in which we are placed,
the benefit of the community in general, and of our brethren in particular.

[.signed-section-signature]
John Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Samuel Emlen.

[.signed-section-context-open]
Warrington, 1760. Second month 1st, 1768.

Thy acceptable favour of the 19th of last month came safe to hand in course,
and I had sooner acknowledged it, had not an event, daily expected for two weeks,
suspended my writing till I saw the issue.
Our worthy friend and kinsman, Gilbert Thompson,
hath been in a declining state for some time,
and of late seemed to decay so very fast as to
call in question his surviving for one day.
He finished his course about mid-night, last sixth-day, and is to be interred tomorrow.
I have often been with him to my humbling instruction;
for some time his journeying was in the region of the shadow of death.
I have sat by him, accompanied his spirit under the load of death,
and the heavens as brass, sensible of deep distress, but seemingly excluded from good.
This led to deep searching of heart, even, as he said,
of holes and of corners he had not suspected;
he saw that he had been short in the performance
of that service Truth would have led him into,
had he been fully dedicated in heart to know and to do his Master`'s will.
But adorable condescension visited afresh, revived a degree of hope,
fed him with a little bread when nigh to faint, and caused a part of that crystal stream,
which is the satisfaction and consolation of the whole city of God, to arise in his soul,
and it increased from time to time,
until it became like the water Ezekiel saw issuing out from the threshold,
a river to swim in, a river that cannot be passed.
The holy canopy was often over our spirits when I visited him,
which I often did to my comfort.
I never, my dear friend, so fully understood the force of the expression,
"`If the righteous scarcely are saved:`"--the
applause and esteem of judicious and injudicious,
regularity of conduct, his arrival at Bethel, the remembrance of many bedewing seasons,
all proved insufficient for his repose,
and were amongst the heavens that might be shaken, and must be removed,
that that which cannot be shaken may remain.

He languished long, in much pain;
great was the conflict previous to the separation of body and soul,
and it feelingly opened to my mind, with the conviction of an audible voice,
had his spirit been more disentangled from the love of lawful things,
his warfare would have been sooner accomplished,
the fetters of mortality more easily broken,
and his spirit would sooner have risen triumphant over death, hell, and the grave,
and on the wings of seraphic love ascended, with holy ease, to the realms of purity,
peace, and love.
But all is well--he is admitted to peace, and through his deep wadings,
instruction is given to us, with diligence, yea with all diligence,
to fill up the measure of revealed duty,
and to stand on the watch for further discoveries,
what is the will of the Lord our God respecting us.
I may have been too prolix on the subject--but oh!--my heart
is full--fuller than to obtain adequate vent by my pen.

I heard of thy being in London; it gave me pleasure;
may the Lord preserve thee to the end, in powerfully preserving simplicity,
and direct all thy steps to peace.
I cannot at present set thee at liberty to leave England.
I feel something that desires thy longer stay,
and I think it is something more weighty than the mere dictates of natural affection.
I have little prospect of much absence during this or the next month;
I believe it would tend to the confirmation of my health,
now through mercy pretty well restored,
could I spare two or three weeks to stay at Bristol;
but much rests upon me by the removal of Gilbert Thompson.
His place, as clerk of the monthly meeting, devolves on Henry Fothergill, who, I hope,
grows in the best things, and will come up in service.
Oh, that I could have the same hope for his often visited
and highly favoured sister S+++_______+++!

Need I add, I should be rejoiced to see thee here, as soon as is easy to thyself;
here is some work to do; we have in prospect a visit to Friends in their families.

[.signed-section-signature]
Samuel Fothergill.

--

Gilbert Thompson, whose last days are, in the preceding letter,
so powerfully and pathetically described, was the son of Gilbert Thompson,
mentioned at page 88. He assisted, and afterwards succeeded, his father,
as master of the school at Penketh,
over which he presided for nearly forty years with much reputation.
He was a Friend greatly esteemed, and very useful in the Society;
he was in the station of elder, and filled several other offices.
Yet it appears from this letter, and from other allusions made to him,
that he had not yielded so full an obedience as he ought,
to that which the Lord had required at his hands,
and that if he had made a more full surrender of all his talents,
and had more fully kept that which he once possessed,
it would have yielded him more peace at last; great, indeed,
was the conflict through which he had to pass.
He died at Penketh, first month 29th, 1768, aged sixty-eight years.

Henry Fothergill, mentioned in the foregoing letter,
to succeed G. Thompson as clerk of Hardshaw monthly meeting,
was the nephew of Samuel Fothergill, being the only son of his brother Joseph.
On the death of his father, in 1761,
the care of the business and of the family devolved upon Henry,
then twenty-five years of age: these duties he discharged faithfully and affectionately;
to his six sisters, all younger than himself, his care was truly paternal.
He was, from his early youth, of an innocent, cheerful disposition, quiet and studious;
he possessed good abilities, had made proficiency in the Latin and Greek languages,
and had a natural taste for poetry and drawing.
As he advanced to manhood, he increased in seriousness of character,
was of a grave and solid deportment, and of exemplary life and conversation.
He was kind and helpful to all,
and gave great promise of becoming very useful in civil and religious society;
but his health failed; he was attacked with rapid consumption,
and after an illness of a few weeks, he departed this life at Warrington,
on the 15th of fifth month, 1769, at the early age of thirty-three years.

The following account of his last illness was drawn up by his sisters,
who attended upon him with affectionate and anxious solicitude.

[.embedded-content-document.testimony]
--

As the memory of our beloved and truly valuable brother, Henry Fothergill,
must ever be precious to his near friends,
we think it desirable to record some particulars,
that (we hope) have made a lasting impression upon our minds,
who were with him during his illness and last moments,
that those allied to him may reap the advantage of his truly Christian example,
and follow his footsteps; for we are assured they led to peace.

In the beginning of his illness, he had many deep and painful conflicts,
and was very desirous, if it pleased the Almighty, that he might be restored to health.
But that Power that knew the innocence, the integrity, and uprightness of his heart,
after deep trials and searchings, was pleased to set his mind at liberty,
and give him an earnest that all would be well.
Oh, may we never forget with what calmness and resignation he looked
forward towards that blessed hope that maketh not ashamed.

For some weeks he was perfectly sensible that he should not be long here, and once said,
"`he could not look beyond five weeks, and perhaps his time might be a good deal shorter,
but he was quite easy;`" and often tenderly
desired his sisters not to afflict themselves.
One of our brothers-in-law coming over to see him, he was much pleased,
and spoke many comfortable things.
He said that,
for more than a year past he had a sense upon his mind that he should not live long;
and the words that were sent to good king Hezekiah frequently passed through his mind,
"`Set thine house in order, for thou shalt die, and not live;`" and added,
he hoped his house was in order, both inwardly and outwardly,
and that he had nothing to do but to pray for an easy passage.
Seeing his sisters greatly affected, he cheerfully said, "`Do not afflict yourselves,
I hope Providence will care for you, and that he will be your God,
as he hath been mine.`"
The inexpressible sweetness and innocence that accompanied his mind,
particularly during the last week of his life, was highly consolatory,
and though he had little absences and wanderings,
the solemnity of his spirit was easily felt; he frequently, in the night,
was quite melodious, and once particularly broke into expression, and said,
as though speaking to himself, "`I have many amiable engagements, but I must leave them;
I cannot stay, and blessed be the name of the Lord, who has removed these things.`"

Four days before he died, he was much altered,
and seemed to take little notice of any thing in this world.
As he sat in his chair,
with all that heavenly sweetness and serenity that were with him to the last, his voice,
which was greatly broken and inward before, was suddenly exalted; and he said,
with a kind of triumphant melody--"`When, oh, my soul, shalt thou enter into rest;
where peace and everlasting gladness shall be thy portion?`"
But no language can convey an adequate idea of the sweet serenity of his countenance.
The following morning he came down stairs,
but was so much worse that he was soon carried up again,
and in the afternoon of that day he seemed to be very deep in his mind,
and to feel more perturbation of spirit than we had ever before perceived;
at length he broke out into lamentation, and seemed greatly agitated,
saying--"`I do not feel that virtue to arise in my mind I used to feel,
and the pillars of my house are shaken, and I may go to the land of darkness.`"
One of his sisters, against whom his head was leaned, deeply affected, said, "`No,
my dear brother, if thou be removed from us, it will, I believe, be to a land of light.`"
He said--"`Oh sister! thou dost not know what I feel, but pray for me! pray for me,
sisters;`" and clasping his hands together, he fervently uttered--"`My God! my God!`"
The solemn appeal was, we believe, accepted, and after some pause, he said:
"`There is a house whose pillars are immovable, let us lay fast hold on their bases.`"
He continued sweetly serene, now and then uttering an articulate word,
which showed his conversation was in heaven; he frequently repeated,
in a low voice--"`Deep unto deep utters, deep unto deep utters.`"
On first-day, he was extremely weak in body, and we thought he was going,
but he again revived a little, and expressed great affection for his sisters.

The following evening, being the 15th of the fifth month, 1769,
he was very desirous to be got to bed, which was contrary to his usual inclination;
he was placed there about eight o`'clock, when a fresh eruption from the lungs came on,
to a great extent, which totally subdued his small remaining strength.
In that awful hour, the only alleviation of our deep sorrow was to see him quite still;
and after several times repeating, with great fervour:
"`Lord God Almighty!`" he continued about half an hour,
and though the difficulty of his breathing was great, he expired without a struggle,
and is gone, we trust, to endless felicity and peace.`"
"`Let me die the death of the righteous,`" and may our life be like unto his,
which can only entitle us to hope for the same happy conclusion.

The following "`Reflections on Death`" were found amongst his papers, after his decease:

[.small-break]
'''

"`Oh death, how awful is even the remembrance of thee, at an uncertain period;
how much more striking when thou certainly approaches,
and by the vehicle of disease art near, to take possession of these tabernacles of clay,
and about to consign them to the silent grave,
never more to appear in the busy scenes of life, but, as we are told,
our place will know us no more.
O, what can give peace in the dreadful hour which will inevitably overtake all,
sooner or later?
The courage of man, his fortitude of heart,
and all worldly comforts cannot support him in that moment,
when the soul stands shuddering on the brink of eternity,
ready to launch into that unknown state whence none return.
Can riches bribe him?
Will he respect the greatest titles?
Can our friends do any thing but pour out their silent grief?
What then can this world, and all things in it, do for us,
to make the tyrant`'s approach be without horror, and a bed of languishing tolerable?
Can human reason with all its boasted power and rectitude, give peace in that awful hour,
when it is with difficulty that the body can support the pains of sickness,
and preserve the mind free from its effects?
Can reason alone?
Can philosophy mitigate the pain both soul and body must feel,
when ten thousand worlds would not avail to give a moment`'s peace to the soul?
What then must help poor, frail man in that hour?
and what has he to rely on, when time is about to close,
and the veil of eternity to be opened?
Religion, if truly practised, will then stand his friend,
and peace of mind will accompany him to the last;
not the religion which is of this world--airy speculations, shadowy forms, which,
being of man, will perish with man; but real, practical religion,
whereby the soul is lifted up to God through Jesus Christ, communicates with him,
is enabled to pray to him, and to know the baptism of the Holy Ghost and fire,
to cleanse and purify our hearts,
whereby we are strengthened to perform what is pleasing in his sight,
and to take up the cross to our corrupt wills and inclinations,
to walk righteously and soberly in this corrupt age,
to keep ourselves unspotted from the world, which, if adhered to,
assuredly brings that peace of mind which will
accompany us through this vale of existence,
and cause us to tread the paths of life with safety and pleasure.
It will support us when afflictions may be our lot, and a bed of languishing our portion;
and finally, in that thrice awful period,
when it maybe said--"`It is finished,`" and all the enjoyments that
the mind could have wished for will terminate in empty nothings;
then, then, it will be a fountain, never to be exhausted,
of holy joy to the conscious soul; and enable it to triumph in the last moment,
and say--"`O, death, where is thy sting?`"
and "`O, grave, where is thy victory?`"
and even accompany the soul to those immortal shores,
where peace shall be its portion for ever.`"

[.signed-section-signature]
Henry Fothergill.

--
