== Chapter XI.

Although in feeble health, Samuel Fothergill attended the yearly meeting in London,
in 1768.
He is thus mentioned by a Friend, who also attended that meeting:
"`Samuel Fothergill came to town this week; he is, indeed, greatly altered;
I apprehend he will be able to attend the meetings but little.
He was present this afternoon, and had a very fine and high opportunity,
after the answers to the queries were gone through, on the state of the Society,
and the duty of individuals.
He is much more altered than I could suppose.
Unless he gets better, his public service will be much lessened.
He has a hollow cough, hoarse, and appears very feeble.`"
-- (John Gurney, fifth month 24th, 1768.

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Abraham Shackleton.^
footnote:[Abraham Shackleton was born in Yorkshire,
and was very early deprived by death of the care of his religious parents.
Though then so young as eight years, he remembered, and used to commemorate,
the tender concern of his pious father, in following him to his bedside,
and on leaving him to repose, awfully recommending him to seek the Divine blessing.
This blessing did remarkably attend him during the course of his life,
and preserved him from evil in many times of temptation and danger,
leading him aside from careless companions into solitary places, there to seek the Lord,
who graciously nourished him by many precious visitations of Divine grace,
and through various conflicts and exercises,
formed and sanctified him for a vessel of honour in his house.
{footnote-paragraph-split}
Having mental powers competent,
he applied himself to literature, and was encouraged to remove to Ireland,
where he undertook the tuition of Friends`' children,
in great simplicity of heart and awful fear, under which, as he humbly kept,
he was enabled to discharge his important trust faithfully,
his instruction and example tending much to improvement and edification.
In a few years, he married a valuable and religious young woman from Yorkshire,
and they opened a boarding-school at Ballitore,
in which he conscientiously and successfully laboured for many years.
{footnote-paragraph-split}
He was solid and exemplary in demeanour,
an eminent pattern of humility and temperance, much grieved when he beheld levity in any,
often saying,
there was a fear which would keep the heart clean--expressing his
desires that his successors might be a generation to serve God.
As age advanced,
he found his spirit in a greater degree sequestered from the concerns of this life,
and after the decease of his aged wife,
he gave up housekeeping and went to live with a relation, where, tenderly cared for,
he quietly departed this life in great peace, at Ballitore, the 24th of sixth month,
1771, aged seventy-four years.]

[.signed-section-context-open]
Warrington, Sixth month 18th, 1768.

I send thee the salutation of my most sincere love,
not without a sense of our heavenly Father`'s love,
with which I hope thou art often comforted, now in thy declining years,
and favoured with the evidence in thyself of having in thy measure,
through Divine assistance, walked with God.
I need not attempt to express to thee the importance of such an evidence,
when the soul draws nigh her flight to the land from whence there is no return.
It hath been the mark for the prize in thy view,
and I am thankful to feel my heart stirred up to follow such examples; animated,
by their success and the importance of the subject,
to use all diligence to fill up my duty, that I may finish my course with joy.
My shattered constitution often gives me instruction, and intimates the graves are ready;
yet it hath been consistent with Divine mercy and wisdom to raise me up again,
beyond my expectation; and I hope I am bettered by my affliction,
not only in what belongs to me as an individual,
but also in that wherein I am joined by all the living,
in the view of the state of the church in most places.
The use I would have us make of this view is, to gird up the loins of our minds,
that our example may be a strong reproof to the unfaithful; and thus collected in spirit,
we may deeply feel after the putting forth of the Divine hand in service;
for though it can work effectually without instruments, yet it will also work by them;
and if the visited of God were enough devoted in heart to his service,
in all the manifestations of duty, we should have more useful instruments in the church.
But alas! for many, who, if they have followed to Bethel, content themselves there,
and attain not a double portion of that spirit, which those who steadily follow on,
even through Jordan, are favoured with.
This imperfect work bears undoubted traces of the Creator`'s hand; but,
like half baked cakes, they seem to me to be no inconsiderable eclipse to Zion`'s beauty,
and are often great obstructions in the way of others,
as such who neither enter the kingdom of God themselves nor suffer others.
Nevertheless, the God of the whole earth is mindful of his family,
and eminently favoured us in our last yearly meeting in London,
from which I returned with my mind replenished with precious dew.

Salute, in my name, thy son and daughter.
May those who are of the younger class look to the business of
the day! the building up of the Lord`'s house,
more than their own.
Unto him all our utmost dedication of spirit, time, and labour is justly due.

[.signed-section-closing]
My dear love attends you all,

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Lydia Hawksworth.^
footnote:[She was the daughter of Samuel and Deborah Waring, of Alton, in Hampshire;
and in 1768 was married to Abraham Richard Hawksworth, of Bristol,
a Friend eminent for his usefulness and great benevolence.
Their union was short, for in a few months he was removed by death, and at his interment,
she,
standing up and laying her hand upon the coffin which
contained the remains of her beloved partner,
bore her first public testimony as a minister.
Having thus devoted herself to a service for which she had long been under preparation,
she continued exercised in spirit, and humbly waiting for the renewal of power,
by which she was made an able minister of the gospel.
She departed this life in London, on the 17th of twelfth month, 1788,
aged fifty-five years.]

[.signed-section-context-open]
Warrington, Seventh month 11th, 1768.

It hath, my dear friend,
often been my request to Him who hath the hearts of all men in his hands,
that He would give me a sympathizing mind,
and the effect of various exercises in the course of my
pilgrimage hath been so far rendered useful,
through his gracious help, as to obtain my earnest wish; and in this sympathizing sense,
I have dropped the tribute of a tear to the dear memory of our beloved friend,
now no more, and that of affectionate condolence with thee,
who feels unspeakably the dissolution of the most tender tie.
Religion authorizes the injunctions of nature to feel deeply on such
occasions--it cannot be culpable in the sight of the Author of our being;
for if the holy Jesus wept for Lazarus his friend, shall the tears of the widow,
poured forth on the removal of a most affectionate husband, a tender friend,
an agreeable companion, a friend with whom thou hast had sweet society,
and gone up to the house of God in his company, be offensive in the sight of our Creator,
who well knows our frame,
if an humble labour after acquiescence in sovereign disposal cover thy anxious,
painful mind.

As a man,
I feel and view with sorrow the mighty chasm his
removal hath occasioned in various useful relations;
my own particular affection hath lost a pleasing object,
and the circle of my most near connexions in pure friendship is invaded.--Yet,
my dear friend, let us look on the other side of the question--for whom we are afflicted?
One now for ever free from it.
Recollect we his memory.
It is precious.
His conduct in every station?
It was uniform.
He hath left this world crowned with a diadem of religion and virtue,
and is gone before us, sooner than we wished it, to the rest of souls,
and has cut off many meanders and intricate mazes in
the pilgrimage through advanced years and old age,
by a shorter passage to the New Jerusalem, than many others are exercised in.

Endeavour patiently to submit to His hand, whose wisdom is unsearchable,
and who knows best what is essential to our happiness, and will ever promote it,
with a wise and fatherly care, if we, as dutiful children, kiss the rod,
and cast our care and confidence upon him.
May thy mind be stayed in holy quietude and resignment,
and thy hold confirmed on that All-sufficiency,
wherein all the deficiencies attending mortals are made up.
Walk thou before thy everlasting Helper in steady obedience,
and He will be thy sun and thy shield.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Dr. Fothergill to His Brother Samuel.

[.signed-section-context-open]
London, Twelfth month 6th, 1768.

We can only acknowledge thy kind attention to us,
in giving us such frequent intimations of thy health;
to help it at present seems scarcely in my power.
It was prudent to leave Buxton; a longer stay there would have been of no advantage,
but much discomfort to thyself.
Nor can I at any time advise thee to go thither under doubtful circumstances of health.
This kind of remedies is more fit to establish good health, when it is recovered,
than to recover it when lost.

When well, make it a rule to drink no wine before dinner, nor between meals,
nor any other fermented liquor.
I know the pernicious custom of the country in many places is to bring out these things,
and urge their acceptance as a test of friendship; but it is a bad one.
I don`'t say this as in the least doubting thy care in this respect,
but to strengthen thy hands against imprudent importunity.

I have been twice this day at Clapham, twice in the city, from end to end,
and have not a moment`'s respite from intense thought the whole day,
but while I get a little abstracted in passing through a crowd from place to place.
Make, therefore, every allowance for me thou canst.
I do this, because it seems at present unavoidable.
I have no reason to doubt but what is best will follow,
if I am happy enough to look after it.

Dr. Russel is no more;^
footnote:[Author of the History of Aleppo, and an intimate friend of Dr. Fothergill,
who wrote a sketch of his life,
distinguished for the elegance of its language and the justness of its sentiments.]
and on seventhday last, I was sent for, in great hurry, to Clapham,
to see our friend C. H., who, from being quite well,
was suddenly seized with a stroke of the palsy on his expressive faculty.
He knows every body, has the power of sense and motion,
but expresses himself very imperfectly.
This is the effect of a most uniform, intense application of a capacity inferior to few.

I accept this as another hint to necessary care respecting myself;
and I labour to abandon every pursuit that is not
conducive to the purposes for which we ought to live.
One friend, another companion, a third acquaintance, able, sensible, affectionate,
all gliding from our sight!
What have I lost within this year!
Do not let this make thee melancholy.
Let it cheer thee to think the brother whom thou lovest hates not instruction.
Farewell, and tell us thou art better when thou canst.

[.signed-section-signature]
John Fothergill.

--

The health of Samuel Fothergill had, by very slow degrees, improved,
and his strength was so far returned, as to enable him, in the first month, 1769,
again to pay a religious visit to the city of London:
and on this occasion he was engaged in the important service of visiting the
families of Friends in Gracechurch street monthly meeting,
in which he was accompanied by his friend Samuel Emlen.
This engagement,
with the attendance of the various meetings which occurred during the time,
occupied twenty-eight days.
The number of visits, according to a record kept, was one hundred and twenty-seven:
afterwards, viz:--"`On third-day, second month 25th,
visited the Countess of Huntingdon and Lord Dartmouth, at Thomas Stackhouse`'s,
several other religious persons were present.`"
(MS. written by Ann Fothergill.)

[.embedded-content-document.letter]
--

[.letter-heading]
Dr. Fothergill to Susanna Fothergill.

[.signed-section-context-open]
London, First month 26th, 1769.

Just to save my brother the labour of writing,
I take pen in hand to acquaint thee he is well.
He has entered upon the service he came up for, and I trust with satisfaction to himself,
and to the objects of his mission.
He finds that Friends in general open both their doors and their hearts to the visit,
and a more acceptable companion could not perhaps have been found than Samuel Emlen.
We have both been labouring pretty hard today in our different vocations,
but as I think his is of much greater moment than my own,
so I should readily bring his cloak from Troas.
Do not think that because I write he is not able or not willing to do it.
He is both one and the other; but I thought it an agreeable employment,
just to let thee see that neither my brother nor ourselves are forgetful of thee,
though under a multiplicity of engagements.
My chief solicitude is, that my brother may not be more in haste than he ought.
I love diligence, and am not apt to discourage it;
but there is such a thing as being too eager and earnest.

[.signed-section-signature]
John Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Dr. Fothergill to His Brother Samuel.

[.signed-section-context-open]
London, Third month 2nd, 1769.

We have received the account of thy return with great satisfaction.
Remember the motto, ne quid nimis:^
footnote:["`Id arbitror Ad prima in vitae esse utile, ne quid nimis.`"--Terence.
That is, "`We should not pursue any object too far.`"
No doubt intended by Dr. Fothergill as a caution to his brother,
to restrain the natural energy of his character,
and as a salutary advice to be careful of his little remaining strength.]
write it in capitals every where.
I endeavour to attend to it, in the midst of seerning hurry.
With grateful reverence I acknowledge it; not from myself, but I trust,
from the secret motions of better help.
I receive the intimation of it with thankfulness, and daily wish to follow on to know.

Thy health is the most material article.
Be content with thy slow recovery.
Whilst thou art acting the part thy best discretion directs, think it is for the best,
and not an argument that nature is unhinged or inactive.

Thy remarks on addressing have had my attention.
Previous to thy mentioning it, I have thought of a less exceptionable, more necessary,
and more consistent measure.
Let a strong paragraph be inserted in the printed Epistle,
advising Friends to beware of entering into that warm party spirit that has sprung up,
in this country and elsewhere;
charging all to remember the obligations we are under to honour and obey the king,
and especially the present royal family,
from whose progenitors we have received so many favours.
I leave the attempt to thy leisure, and think such a paragraph both proper and expedient.^
footnote:[See the printed epistle from the yearly meeting in 1769.]

The space to be allowed us in the Scotch dictionary is six or seven folio pages,
if we please.
I am pleased that it engages thy attention, and I shall do more at Lea Hall,
when thou hast sketched the plan.^
footnote:[This relates to an account of the Society of Friends, in a dictionary,
published at Edinburgh, which, as appears from this letter,
was written by Samuel Fothergill and his brother.
It was afterwards published separately,
with this title,--"`A brief account of the people called Quakers, their doctrines,
and discipline, taken from a Dictionary of Arts and Sciences,
lately published at Edinburgh.`"-- London, 1772.]
I would not advise thee to go to Kirby Lonsdale, to the Northern yearly meeting there,
unless thou cannot help it.
I know the consequence, if otherwise.

May a person who needs advice as much as most,
and at the same time does not profit by it so much as he ought, presume to give any?
Thy affection for me will throw a mantle of oblivion over me,
if I say any thing that does not correspond with thy own reflections.
Be short in supplication; use no words not of common use,
and the same words as seldom as possible.
The ineffable majesty of Heaven is enough to dazzle all human conception;
yet the "`Our Father which art in heaven,`" is indeed a complete model.
Stray from its simplicity as seldom as possible; but I speak with unhallowed lips,
and therefore forgive me.
My wish is strong that the Father of all mercies may long preserve thee,
a choice instrument, a silver trumpet, that gives a certain sound, as thine is;
that I may be conducted wisely through a thorny, slippery, arduous track,
to safety and happiness at last.
So let it be for us both, saith all within me.

[.signed-section-signature]
John Fothergill.

--

Samuel Fothergill attended the yearly meeting in London, in 1769,
but became very unwell before its close,
and was accompanied on his journey homewards by J. C. Lettsom, a young physician,
to whom he was guardian.
They travelled by short stages to Lea Hall.

From this period to the close of his life,
the health of Samuel Fothergill became more and more precarious;
his constitution failed rapidly; the attacks of his complaint were more severe,
and returned at shorter intervals,
leaving him on each succeeding occasion much reduced in strength.
The effect produced upon his mind by these repeated trials,
was a still larger growth in experience, in humility, and patience.
It was the frequent remark of his friends,
upon his re-assembling with them in their religious meetings after these afflictions,
that whilst his ministry was more and more bright and instructive,
humility was also the clothing of his spirit,
and that he came '`forth from these painful seasons as one refined in the furnace.

In the autumn of this year, having regained a portion of strength,
he again visited London with a certificate,
and was engaged in a visit to the families of Friends in Horseleydown meeting,
now Southwark, again having his friend Samuel Emlen as a companion.
In the course of this service, upon visiting two young Friends, then recently married,
he addressed them as follows:

[.embedded-content-document.letter]
--

"`As you are both young, and it is very probable,
may be at times solicitous for your future advancement in life,
I would just propose one thing to your serious consideration,
without which no one was ever happy, or any one unhappy with it; which is Godliness:
it is the soul`'s health.
Godliness is profitable in all things; it is profitable in health,
it is profitable in sickness; it is profitable upon a languishing bed,
it is profitable in death: it initiates us into the company of glorified spirits,
in the boundless and beatific regions of immortality.

And, my dear young friends, I earnestly address you on this occasion,
with a degree of the tenderest affection,
sincerely desiring your happy introduction therein,
when these few fleeting moments of your existence shall terminate,
and you shall be summoned from this stage of action,
to appear before the tribunal of immaculate purity.
You are placed here only as delegated stewards;
accountable beings to your bountiful Creator for every talent committed to your care;
and your eternal interest depends upon your
consecrating those talents here to his service,
who created you as vessels for his honour,
and to whose guidance and protection I warmly and affectionately recommend you,
my beloved friends;
sincerely wishing your establishment and growth in the blessed and unchangeable truth,
through the bounty and favour of our Father who is in heaven.

Godliness is profitable in all things,
and I most earnestly intreat and recommend you
to a due consideration of the importance of it;
seek, in your early days, seek a friend that will never forsake you;
for if you apply to him in sincerity, he will be found of you.
His Divine goodness will preserve you as in the hollow of his hand,
and conduct you through the various difficulties and dangers of a tempestuous world,
to an everlasting habitation in glory.
Oh! seek him early, above every consideration; he will be a father and a friend,
when no terrestrial objects can administer the least consolation,
and every pleasant picture shall be stained in your view.

Godliness is profitable in all things.
It is the soul`'s health,
it is the never-fading support of the righteous under every difficulty,
and the sovereign antidote to the evils of life.
I could wish our dear youth were more generally
engaged in pursuit after substantial happiness;
that they would cultivate an acquaintance with
their Creator as in the morning of their day;
for the sands of life are hastening to a close,
and the coming of death is approaching with unremitting swiftness.
Alas! alas! what are the riches and the splendours of these perishing, sublunary objects,
in comparison of our everlasting well-being hereafter?
The one is transient, fleeting, and momentary, and altogether uncertain;
the other is the permanent fruition of uninterrupted felicity forever,
amongst an innumerable company of saints and angels,
and the spirits of just men made perfect, continuing the inexhaustible theme of praises,
dominion, and worship, to the sovereign Lord of the whole universe.

I have had to remark, in passing through divers parts of this city,
many loitering as upon the skirts of the camp;
and the sword of Amalek hath destroyed numbers.
I beseech you, my beloved friends, let your eye be unto godliness;
and though it falls not to the godly to be always
gifted with the affluence of worldly riches,
yet you will assuredly find unspeakable consolation resulting
from the Divine favour and goodness towards you,
which will abundantly counterbalance every worldly consideration.
Be not of this world, but let your views be directed towards a better country, even,
a pure, undefiled, holy habitation, a house not made with hands, eternal in the heavens.
Seek not after riches--suffer not your attention
to be diverted from the pursuit of virtue,
nor be desirous after the vain, foolish, transitory amusements of a degenerate age;
for all these things will terminate in sorrow and distress of mind,
and riches make to themselves wings and flee away;
but godliness is profitable in all things: it will be your support in every trial,
your never-failing consolation under every difficulty,
and ultimately afford you a comfortable evidence
of admission into the permanent joys of eternity,
in a glorious and unfading recompense,
which the Father and Fountain of unlimited mercy and goodness
has prepared for all those who diligently seek him.
Therefore, my dear young friends, suffer me once more strongly to recommend you,
in the early part of your life, to seek the God of your fathers,
the never-failing help of those who seek him in sincerity.

And I will say this for your encouragement, that though the heavens should pass away,
and the earth should be removed out of its place,
the lofty mountains should dissolve and be no more,
yet the promises of the Lord are amply verified to them that fear him.
It is a blessing which makes truly rich, and adds no sorrow with it;
it will assuredly attend the humble efforts of a life dedicated to his service,
administer comfort under every trying dispensation of his providence,
and be your exceeding great reward;
for godliness is riches in poverty--it is profitable in all things.`"

--

His friends, in speaking of these services,
have given the following testimony--"`He was divinely strengthened,
and enabled to extend a helping hand to many, in close and necessary labour,
for their increasing care to live and act consistently with our holy profession,
to the comfort of many, and to his own peace of mind.`"

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to His Sister.

[.signed-section-context-open]
Warrington, Twelfth month 11th, 1769.

I may tell thee that I am favoured with the lively hope,
that in my late labour I have been in the service of him who is a rewarder of feeble,
well-intended service, for the promotion of his good cause;
and I am comforted in the hope that I have done
what I ought in my late visit to your city.
I am thankful to feel the chain of fraternal and Christian union,
brightened by the spreading of best love upon it.
May no spot of rust ever impair its lustre.
I have been, with respect to my health, much as when in London, until last week,
when my complaint fastened on my ankle and foot,
not without some considerable uneasiness in my breast.
But I was enabled to get a little about.
On seventh-day last, I got in a post chaise to Penketh, to the burial of Ann,
the wife of Joseph Key; she finished, I hope, well.
This forenoon, our worthy, innocent old acquaintance, Esther Key, was removed from us;
I have no doubt that she had clean hands and a pure heart,
and that she has ascended the hill of the Lord, and stands in his holy place.
Thus are the ranks of our acquaintance thinning fast,
and from many occasions we may hear the summons--"`Prepare to meet thy God.`"

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to his Brother John.

[.signed-section-context-open]
Warrington, First month 20th, 1770.

With respect to the present agitated state of the nation,
I am pleased and thankful when my own mind, and those that I love,
are kept from its vortex, and quietly staid on him, who makes the clouds his chariot,
and walks on the wings of the wind.
He knows best how to fix instruction on the minds of
people deaf to the language of multiplied mercies.
I love my native country, and ardently wish for its sake, and our own as a people,
that we might be found amongst the interceding righteous,
for whose sake the day of national safety might be protracted.

I rejoice in thy account of a revival in Gracechurch street monthly meeting.
I often feel a warmth towards your city, which un-aided nature cannot raise,
and a hope is vouchsafed, at times,
that a precious divinely prevalent visitation of good will better many amongst you;
and animate to shake yourselves from the dust,
and put on the beautiful garments of sincerity and godly zeal.
May the Lord of all power, in his own time, thus prosper his great and good work;
and if individuals walk in the light with full purpose of heart,
their walking will terminate in their own security and the recompense of Well done,
and be most signally useful to encourage others.
Thy time is precious, I will not much further encroach upon it;
thou needs not information, thou knowest these things.
If by a happy collision we may fetch out the sparks of divine fire from each other,
and preserve the everlasting fire in its genuine nature, it will be mutually beneficial.
But such powers, times, and seasons are not in our hands.
My hand refuses more labour than just to salute you all with the tenderest affection.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to S. L.

[.signed-section-context-open]
Warrington, Second month 13th, 1770.

Thou hast been very frequently the companion of my mind since I saw thee last,
with hope and secret fear so tempered together,
as furnish me with a solicitude on thy account,
distinguished from what I have felt for almost any other.
And as I believe the Lord of all our sure mercies hath
caused his blessed day to dawn upon thee,
and I trust hath engaged thee sincerely to walk in it, permit me,
from the motions of affection stronger than nature suggests,
to offer thee such hints as occur to my mind.
My hope is raised in this confirmed belief, that He who is the restitution of all things,
and ever equal to perform his own work, hath visited thee for this end,
even thy redemption, and hath measurably prevailed with thee to avow his work,
by a degree of submission thereto.
He is the Lord of perfection himself, and would make his sons and servants like him;
would beautify them with his salvation, and make them strong for himself.
I am unquestionably assured He would thus work effectually with and in thee,
to establish his own kingdom in thy heart, and bless,
not only with the glimpse of his salvation, but the stability thereof,
and dignify with a possession therein ior ever.

But what are the terms on which this treasure is attainable?
They are expressed in the term redemption, that most necessary work for all men,
without which there can be no possibility of admission amongst the saved of God.
Here many have fatally stumbled, and turned back at the hard, yet true,
sayings of Christ, to be reduced to death, and even annihilation,
to the varied corruptions of flesh and spirit,
that the old man with all his works may be put off, and the new man, Christ Jesus,
put on; it is, indeed, putting the axe to the root of the tree,
and alas! the place where many have gone sorrowfully away.
Here my secret painful fear respecting thee hath kept my heart awake, at times,
in prayer for thy establishment and perfect safety.

Thou art favoured with a good understanding,
mayest thou wait to have it replenished with best wisdom,
nor admit a thought that He who hath the key of David
hath delegated it to the wisdom of flesh and blood:
in him are hid the treasures of wisdom and knowledge, and he will be inquired after,
and sought to, to open them.
It was, and is, a truth of undeniable authority,
that it is hard for a rich man to enter the kingdom, whether in affluence of riches,
or superiority of understanding.
The reason seems obvious--they have a tendency to lead from a single
dependence on Him who fills heaven and earth with goodness and truth,
and demands the tribute of love and obedience from all.
No eye but that strengthened by faith can pierce
through the clouds which cover this lower system,
and intercept the prospect of more excellent riches on high.
But the eye opened, by Him who gave sight to Bartimeus, sees its own weakness,
and the imperfection of all that is finite;
and looks with suitable expectation to Him who is infinite--his help in time,
and his song for ever.
I behold thee on a slippery sea of glass, yet mingled with fire;
there is ability to stand thereon, and thereby be purified, but not consumed.
Have a care of thy steps; wait to have them directed right, and they will issue in peace.
I see thee surrounded by foxes, which want to nip the bud of that vine,
which the Lord of the heritage hath planted, and which, if properly cultivated,
and vigilantly guarded, will bring forth grapes productive of wine,
even that wine which makes glad the heart of God and man.
Methinks I see thee at times, allured by the attractions of Divine love,
to a total surrender of all to the ever worthy Sovereign; at other times,
irresolute and wavering,
reluctant about parting with the honours and greatness of this world,
and its vain applause, even for His sake, who, for thine trod the wine-press alone,
and suffered his sacred head to be crowned with thorns, to which, of proper right,
belongs the diadem of heaven.
Sometimes, the painful soliloquy may run on this wise--I will tread the middle path,
and walk in all the lustre of moral rectitude,
blameless to the most scrutinizing mortal eye; and--"`Are not Abana and Pharpar,
rivers of Damascus, better than all the waters of Israel?`"
cannot I be clean enough by washing in them?
Here mystery Babylon presents itself, a transient rest,
procured at less price than the rest of Zion, and lulls, by its deception,
the unwary pilgrim into a rest short of the true rest.
Peradventure, at other moments,
distressing apprehensions of thy own imbecility
may so prevail as to discourage and afflict,
and perhaps, suggest a diffident thought, as though victory was not attainable;
and thence the unwearied enemy would draw conclusions to drop the warfare,
and content thyself with thy inevitable lot.
Under all these besetments who can stand, and stand fast without fainting?
The armour of our defence, human resolutions and conclusions, will vanish into empty air.
Innocence towards God as well as man is impenetrable armour,
and unmixed sincerity is the white linen of the saints.
Sampson never met with more timely, substantial relief,
than from the fountain proceeding from the jaw-bone of an ass;
he cast it away at Ramath-lehi, but found it again at En-hakkore.
My soul craves thy help and safety; may the Rock of Israel be thy refuge,
and may thy mind be established in covenant with him.
All earth will vanish, its glory be like a dissolving bubble,
its connexions be fleeting as a dream;
but the soul which patiently bears the turning of the redeeming Hand,
and leaving momentary things, cleaves to that which is eternal, will be supported,
and know its riches to be unchangeable in their nature, and eternal in their continuance.

Let the warmth of my heart plead my excuse for the incorrectness of my style.
I write because I feel, and to be felt, and not for amusement.
Farewell, dear S.; remember, life is short, its business arduous,
the prize immortal glory, the failure eternal misery.

[.signed-section-signature]
Samuel Fothergill.

--

In 1770,
the state of Samuel Fothergill`'s health did not permit
him to attend the yearly meeting in London.
The following letter relates to that meeting.

[.embedded-content-document.letter]
--

[.letter-heading]
Dr. Fothergill to Samuel Fothergill.

[.signed-section-context-open]
London, Sixth month 4th, 1770.

I thought it would not be disagreeable to thee to hear from the camp.
This afternoon we met at four, and proceeded in the business as usual.
Henry Gurney is clerk, and is both an able and expeditious one.
The committees are appointed as usual,
and I think that of appeals is as well as we have had for some time.
There is a large concourse of Friends,
and most of the few ancients we have left are present.
Catharine Payton is with us; Jonah Thompson is in town, John Griffith, Isaac Sharples, etc.
The Epistles are laid upon proper shoulders.
Before the meeting ended, I wished Friends to consider the value of their time,
and the necessity of being collected, both in meetings and out of them,
that they at their return, and we when we were left,
might be able to look back with some degree of satisfaction.
James Gough soon afterwards stood up, with a good degree of warmth,
and I think this first sitting as solemn as many we have had.
The appointment for the General Epistle is numerous, and of solid Friends.
Joseph Phipps will have the compiling of it,
and I trust that better help than our own will be afforded.

I should, we should all, have rejoiced in thy company; I know thy mind will be with us,
though thy body, retarded by, perhaps, unreasonable services,
is forced to submit to confinement.
But there may be some instruction in it, and if we learn wisdom, acquire docility,
abate of our natural impetuosity, and grow in patience, much advantage is reaped.
We were at the Savoy yesterday; Catharine Payton was with us, J. Stephenson,
Edmund Gurney, all appeared; all in a line, but all, I think, right; low,
but as high as they ought to be--and convincing.

[.signed-section-closing]
Farewell, dear brother; accept our united affectionate remembrance.

[.signed-section-signature]
John Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to John Coakley Lettson, on his Marriage with Ann Miers.

[.signed-section-context-open]
Eighth month, 1770.

I was duly favoured with thine by my sister at Lea Hall,
and should have written sooner had ability and leisure united,
for there has lived in my mind a salutation to thee, the object of my tender solicitude,
and to thy wife, thy companion in every tender sense,
the joint object of my affectionate well-wishing.

I consider you as now entering upon the more arduous scenes of this life,
and filling more important stations than in your single state,
and most earnestly desire you may now,
on your first entering into the more arduous paths, be wisely directed,
for much depends on this important crisis.
With a heart replenished with the warmest affection, I recommend the Psalmist`'s words,
representing the wise of all ages, "`In the name of our God we will set up our banners.`"
This is a proper allusion to your state,
who have entered together into the most delicate and tender bonds of union,
to be each other`'s help-mates, to soften every care, to enhance every comfort,
to divide every burthen reciprocally and mutually,
and to help each other in every temporal respect; and not only so,
but to go up hand in hand together to the house of God,
and to the mountain of his holiness,
in order to enjoy this permanent felicity of the conjugal state.
In the name of our God, now set up your banners;
let nothing divert your minds from an humble,
attentive care to put yourselves under his protection;
implore his guardianship and tuition, he alone can help you in times of probation,
and defend you in the perilous hour;
guard you from the dangers of unsanctified seeming prosperity,
and place his everlasting arm underneath in the time of adversity.
Place in him your confidence, that you may not be moved.
The world, with a variety of blandishments, will present its schemes of happiness,
and make large promises of a good it has not in its power to bestow;
but may you carefully remember, that in the world, or under the prevalence of its spirit,
you will find disappointment and trouble, but in the name and under the banners of God,
peace; peace flows as a river,
and all the cross events and painful allotments are sanctified and sweetened.

Beware, therefore, my dear friends, of rushing into the world of dissipation,
which often attends a circumstance similar to yours;
beware of a vain confidence in the smiles and
caresses of men and women of this world`'s spirit.
Beseech the protection and guidance of Him who ought to be placed supreme in families,
and buildeth up a sure house to those who in all their ways acknowledge him,
and cast themselves under his protection.
I trust a holy visitation hath given you an understanding,
what it is that makes for true peace;
enter not into selfish deliberations how to avoid plain duty;
protract not your stay in a land of jeopardy and danger, by taking counsel,
but not of God, and covering yourselves with a covering, but not of his spirit.

The state of the church in that city requires of you to come up to the help of the Lord,
against the mighty inundation of folly and forgetfulness which prevails;
there are no wages equal to those he gives his servants,
for surely the reward of the faithful labourer is exceeding great; peace, tranquillity,
and glory are upon their heads for ever.
Thus, beloved friends, my soul travails for you,
for your present and everlasting welfare,
that the solemn engagement you have mutually entered into, may be truly fulfilled,
and your happiness established upon a most durable basis.
The eye of passion, in the short-lived fever of the mind,
sometimes improperly called love,
flatters itself with objects of imagined amiableness and beauty;
this is transient and mutable; but affection, founded on mutual esteem,
for an object which religion and virtue have rendered truly estimable,
hath a permanency in it equal to the causes which produced it.
It is not in my mind to descend into every particular
point of conduct necessary for your happiness;
these will be clearly opened as occasion requires,
and help administered to come up in every duty,
to render you truly comfortable and happy,
useful and honourable in the church and in the world,
and objects of Divine favour and acceptance.

But allow me to recommend a close attendance of meetings,
both for worship and discipline;
in this most reasonable service the soul has
often been unexpectedly replenished with good,
and its strength renewed to step forward in the holy path.
Dare not to live without God in the world, lest he withdraw his blessings,
and then who can make up the deficiency?
My health continues precarious; my ancles and feet are weak;
this is also the case with my right hand.
I have been obliged to drop my pen several times in this essay to salute you,
which may account for several inaccuracies besides those in writing; nevertheless,
warm affection fills and strengthens my mind you-wards,
in which I wish your present and everlasting welfare,
with a tenderness as nearly paternal as I am capable of.

[.signed-section-signature]
Samuel Fothergill.

--

J+++.+++ C. Lettsom was the son of Edward Lettsom,
the proprietor of three of those small islets or
keys which surround the island of Tortola.
On one of these, called the Little Vandyke, he was born on the 22nd of eleventh month,
1744.
Here his father cultivated cotton, with the assistance of about fifty slaves,
whose cottages were placed around the mansion of their master.
Edward Lettsom was a member of the Society of Friends,
and had dealings with Abraham and T. H. Rawlinson, of Lancaster,
and to their care he consigned his son, when six years old.
An early instance, probably the first from those islands,
of this sacrifice on the part of the parent, for the benefit of the child,
that the latter might receive the benefit of a European education.

It was at Lancaster, at the house of one of those Friends,
that J. C. Lettsom first saw Samuel Fothergill, who afterwards, with John Pickering,
of Tortola, became his guardian.
The youth was placed at Penketh,
and was several years a scholar there with Gilbert Thompson.
The pupils, fifty or sixty in number,
were most of them boarded out in the houses of Friends in the neighbourhood.
The schoolhouse was contiguous to the meeting-house, and continued,
with some short intervals, to be used for the same purpose, down to the year 1828.
This school,
under the able government of Gilbert Thompson and has hither enjoyed a high reputation;
and it is recorded,
that during the forty years that the son "`presided in this happy place,
one death only had occurred amongst the scholars.
This was Springett Penn, the son and heir of the then proprietor of Pennsylvania, and he,
it is said, was consumptive, when he first entered the school.`"

When sixteen years of age,
J+++.+++ C. Lettsom was placed as an apprentice with Abraham SutcIifF, a surgeon, at Settle.
To this place he travelled, from Warrington, upon a packhorse,
which used to pass from Lancashire into Yorkshire.
In after life he thus mentions the circumstance; "`I went to Settle, a fatherless lad.
I rode alone from the house of my guardian, Samuel Fothergill, at Warrington.
When we parted, he addressed me thus: '`Please thy master; and if thou turnest out well,
I will recommend thee to my brother, the doctor; and never forget,
that to be good is to be happy.`'

On completing his apprenticeship, he went to London, and thence to the island of Tortola,
where he practiced as a physician.
He returned to England in 1768, and finally settled in London,
where he commenced practice, under the protection of Dr. Fothergill,
to whom his guardian had recommended him; and, by the introduction of the doctor,
he advanced rapidly in his profession.
In 1770, he was married to Ann Miers, with whom he received a considerable fortune.
In 1774, Dr. Lettsom, Dr. Harvey, and a few others, formed the Humane Society,
for the recovery of persons apparently drowned.
Twenty-two years before this,
Dr. Fothergill had addressed to the Royal Society a paper on the same subject,
but it was not then pursued.

By the decease of Dr. Fothergill, in 1780,
a great accession was made to the medical practice of Dr. Lettsom, who has acknowledged,
in warm and grateful terms,
how largely he was indebted to his departed friend and patron.
He continued, for a long course of years, actively engaged as a physician,
and in the establishment and management of various medical, scientific,
and benevolent institutions.
To the popularity thus acquired,
to the standing he so rapidly attained by the patronage of Dr. Fothergill,
combined with his own kind and amiable temper,
and the active benevolence of his character,`"
may be ascribed the success which attended him,
and the lucrative practice which he enjoyed for many years,
rather than to the possession of great natural talents, much depth of medical knowledge,
or peculiar skill in his profession.

He died in London, on the 1st of eleventh month, 1815,
in the seventy-first year of his age.

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to A. T.

[.signed-section-context-open]
Warrington, 1770.

Had my bodily ability been nearer equal to my affectionate solicitude for thee,
and more particularly on thy late very dangerous illness,
I had ere now paid thee a visit.
Thou hast been the almost constant object of my attention,
and as I feel a tenderness for thee as if my own child,
permit me a little to relieve my thoughts, by an attempt at expression.
Thy own reflections will instantly suggest the subject--that
dangerous habit of drinking more strong liquor than nature requires,
and than thy constitution can bear.
A custom which hath grown upon thee, until it has become habitual, and which I,
along with many others,
look upon as the cause of those dangerous attacks in
which thy life hath been imminently endangered.
I have not been frequent in advice to thee on this head; I have silently observed it;
and a hope hath at times arisen, that thy own good sense,
aided by many a secret conviction of misconduct in this respect,
by that Power which hath often and mercifully striven with thee,
might have fully opened thy eyes,
to see and to rouse all within thee to seek to avoid that wreck of peace, reputation,
comfort, and happiness, to which intemperance inevitably leads.
Thou hast not the plea which many others allege for it;
domestic disturbance and infelicity.
Thy wife is most affectionately disposed to make thy moments happy and peaceful,
and to remove every occasion which might lead to seek a temporary relief by intemperance.
Her relations love thee, as much as if the relation was by consanguinity:
we know no difference;
and with the utmost solicitude interest ourselves in thy happiness.
The allurements of company, the progression of custom to habit, have been too prevalent,
and almost rendered drinking necessary to thy constitution;
at least induced thee to think so, and to act in consequence.
Time after time, painful conviction of its tendency, by the decay of thy health,
hath attended; and I believe desires and resolutions have taken place,
for wiser conduct in future time.
But, alas! too fleeting have these proved,
and returning health been sacrificed to the gratification of
an irregular desire and the solicitations of companions.
Bear with me in these remarks--thou knows they are too true.
I want not to upbraid thee, but to aid and strengthen those wishes, which, I believe,
thou entertains, after more peaceful times.
This last affecting crisis hath united in it all the
instruction and alarm which can possibly be given in time;
a recovery from the brink of the grave--a reprieve from an eternal,
unchangeable state--a restoration to thy family, thy friends, and thy connexions,
now seems to us a pleasing prospect, and an opportunity, I trust,
once more put into thy hands, to retrieve thy peace of mind, thy health, and reputation,
all of which have been deeply affected.
This seems to me like a new beginning.
Thou hadst nearly paid the debt of nature--thou art unexpectedly raised up.
Life or death, peace or dismay, honour or reproach, await thy choice.
In this situation I view thee with the tender anxiety of a friend, nay, of a father,
earnestly desirous thou may lay hold of offered mercy, and become so wise and steady,
as to evince thy gratitude to a gracious Benefactor;
that he who hath been thy resurrection, may also become thy life.
Frequent, I believe, have been thy resolutions, and strong thy desires, in past times,
for better conduct; but, alas! what is man, unaided by that Power from above,
which alone is sufficiency, and who will be sought unto for his help,
and with whom we must be co-workers,
and take up the cross to those inclinations which lead to evil.
May all within thee be excited to look up to Him, to beseech his protection,
to walk in watchful care and diligence the residue of thy uncertain continuance here.
This will certainly become thy duty, and present an eternal interest;
and although it may expose thee to the disregard, perhaps derision,
of some who glory in their shame, yet the Divine peace,
the pure and pleasing evidence of well done, will make abundant amends.
If ever we attain to sit down with the Captain of our salvation in his kingdom, we must,
for the joy set before us, despise the shame and endure the cross.
And oh! that through this path thou may secure
what the world can neither give nor take away.

My heart is filled with love and strong desire for thee;
my feeble hand is incapable of using my pen but for a short space of time:
this may render the letter incoherent; but it is in truest affection.
Oh! that it may please the Almighty to bless to thee thy escape from death.
May he give thee a heart to seek and fear him, lest, upon a relapse into indiscretion,
a worse thing befall thee than hath hitherto proved thy lot.
I am, in the greatest sincerity, thine in every bond of affection, natural and divine.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Dr. Fothergill to The Meeting for Sufferings.

[.signed-section-context-open]
Near Middlewich, Cheshire, Eighth month 20th 1770.

[.salutation]
Dear Friends,

As you are frequently in my thoughts when absent from you,
an inclination seemed to arise in my mind,
just to express the cordial regard I feel for you, both as a body and as individuals.
Often have I been filled with thankfulness, that my lot has been cast amongst you.
Much benefit have I received from the wisdom that hath
been manifested in the conduct of your affairs;
and I often consider you as an assembly of some
of the most favoured people in the whole city,
may I not say in the whole Society.
It seldom escapes me, when I sit down with you, fervently to desire that we may always,
when we meet, feel a degree of that solemn awe, which I am sure is often felt among you,
and that none may go away without being the better for their meeting.
I esteem it a signal mercy, that in the midst of so many unavoidable engagements,
in the increase of which I think my heart has no delight,
a desire is kept alive to be united nearer, if possible,
to every tender mind amongst you; to profit by their example,
and to be divested of every thing that might not contribute to the help of individuals,
or advantage to the whole.
May I just say,
that I fervently wish an awful reverence may
clothe every mind when we are collected together.
The more closely and steadily we can unite here,
the better we shall be enabled to judge properly, and act wisely,
concerning the things that are brought before us.

It is not in my thoughts to esteem myself proper to
give advice to such a body of sensible Friends,
whom I honour in the truth; but it seems pleasingly to arise in my mind,
to testify my brotherly remembrance by these few lines, and to be a kind of prompter,
though at a distance,
to consider your importance in regard to the well-being of the Society,
as instruments in the hands of Providence for much good;
and to consider what frame of mind such meetings should be held in.
I know, from experience, that many of you come together with such dispositions;
and that I may do so likewise,
that others who may even be behind me may come up in
the same earnest endeavour to be what they should be,
is now, and often has been, my desire.

It is not boastingly, but with a degree of humble gratitude, that I can mention,
though absent from you, my heart is with you often.
This favourable recess is not granted that it may be spent in dissipation or indolence.
I wish to renew my strength both of body and mind,
and to seek after that which can renew it properly.

[.signed-section-closing]
I salute you in much affection, and am your friend and brother,

[.signed-section-signature]
John Fothergill.

--

In the eighth month, 1770, Samuel Fothergill was again at Scarborough,
and experienced some benefit to his health from the visit: he was as usual,
much engaged in the ministry; he thus wrote to his wife:

[.embedded-content-document.letter]
--

I got safely to this place, yesterday, and have borne my journey well,
beyond my expectation, though the weakness continues in my hand and feet.
I was enabled to attend the meetings here today, which were large,
this afternoon especially; a great number of persons of distinction,
from divers parts of the nation, were present, and it was a time of memorable favour.
I am humbly thankful to feel reason to believe that I am where I ought to be;
and of this I am assured, that if we forget not our God and ourselves,
he will never leave us, but will be merciful,
and will condescend as a tender father to our frailties.

[.signed-section-signature]
Samuel Fothergill.

--

In the twelfth month,
he was engaged in religious service in the city and neighbourhood of London;
during which, accompanied by John Eliot,
he visited the families of Friends in Westminster meeting.
The number of visits on this occasion was upwards of fifty.

The visits thus paid, in three successive years,
to the families of Friends in different meetings in London, may be regarded as,
on his part, a sacrifice of dedication in the evening of his life,
and as setting a seal to his former abundant labours in that city.

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to His Brother and Sister.

[.signed-section-context-open]
Warrington, Second month 2nd, 1771.

I have been prevented writing to either of you again, before now.
And, indeed, I have silently fed on the pleasure arising from our late interview;
something language cannot express hath often covered my spirit,
in humble thankfulness to that Hand which hath preserved us hitherto,
mutually dear to each other,
and not strangers to the most durable ties of
the universal family of our Heavenly Father.
May we carefully guard against every thing, however pleasing,
of which the tendency is to enfeeble that life which is everlasting and precious.
We are hastening through mutable to immutable things,
and we have all great need to have the pure mind often stirred up,
lest the Master of the house come, and find us either sleeping or ill employed.

My return home was in much quiet; I endeavoured, in the course of my labour,
to keep close company with the Seed.
Few are the places where it reigns.
I was thankful to feel I had not forgotten it in prison;
and whatever may be the consequence to others,
the peaceful evidence of the discharge of my duty sweetly stays on my own mind.
I never felt more renewed in that love which is stronger than death,
with a comfortable assurance that our father`'s God and
ours is graciously mindful of us hitherto,
and wills our preservation to our latest time.
May a just sense of the value and necessity of this
important favour ever rest so properly on our minds,
as to quicken our diligence to know and to do his good and acceptable will,
that we may arrive at the recompense of a happy reward.
The times require labour; and it ought to be often on our minds,
as a powerful inducement to it,
that we have received from the Lord of the vineyard abilities for service,
superior in some measure to some of our fellow servants; and where much is given,
much will be required.
There cannot be any employment or acquisition equally beneficial,
to us and to the church, with that which results to a devoted mind,
solicitous above all to fill up our duty in the highest service.
May we ever consider it,
and at the close of our time experience it as a most necessary truth.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to John Hustler.^
footnote:[John Hustler resided at Undercliff, near Bradford,
and was distinguished by his usefulness and public spirit.
Benevolent and indefatigable in his exertions to promote the interests of his fellowmen,
to him the town of Bradford owed its public hall for the sale of worsted stuffs,
the staple manufacture of the neighbourhood;
and to him the nation is indebted for the
project of uniting the Eastern and Western seas,
by the formation of the Leeds and Liverpool canal, to the completion of which he devoted,
with unwearied attention and perseverance, many years of his life.
He died eleventh month 6th, 1790, aged seventy-five.]

[.signed-section-context-open]
Warrington, Fourth month, 1771.

The contents of thine respecting Cornelius Cayley,
and the copy of his application to Friends of Leeds meeting,
have been much in my thoughts.
I have hitherto been a stranger to the person and his case.
I read, some years ago,
many of the journals of those exercised in endeavouring
to promote the revival of Christianity,
but there appeared to me so much of the nature of those
things that the day of the Lord should come upon,
so fully described--Isaiah 2:10, to the end of the chapter, that I declined the search,
in hopes that the winnowing power of Truth would separate the wheat from the chaff,
in minds pure, upright, and sincere;
and that the Power which prepared the eyes of the man blind from his birth,
by spitting on the clay,
and finishes his marvellous work by sending him
to "`the pool of Siloam,`" or to the Sent,
for washing, might, in the same line,
and by the efficacy of the word of his mouth -- which is as a two-edged sword,
and whose entrance giveth light and life--have
led them into that which is within the veil,
and impenetrable to the eyes which have only
been anointed with the spittle on their earth;
and for this my soul hath often been baptized in humble, fervent prayer.

The person under immediate notice claims, and hath my sympathy;
I believe him joined to all the living,
through the quickening virtue of the life-giving word,
and I earnestly pray for his complete formation, as a vessel meet for the Master`'s use.
Yet a secret and painful jealousy affects me,
that patience hath not had its perfect work,
to lead him into all the unutterable depths of the Lord`'s preparing day,
nor all the idols cast to the moles and to the bats;
my jealousy arises from the activity of distinguished self, which loves the splendid,
pleasant picture; an easy purchase,
in comparison of the deep-hidden pearl of substantial Truth.
We sorrowfully know that we have amongst us traditional formalists, having a name only,
by outward inheritance; yet there remains a worm Jacob, the feeble,
yet faithful wrestler with God amongst us, whose life is hid with Christ in God, and who,
through the virtue of the sacred unction, have not an absolute need of man`'s teaching,
but are gathered in spirit into the Lord`'s mountain,
where the Lord of Hosts makes unto all his people a feast of fat things,
and where he destroys the face of the covering,
and the veil that is spread over all nations.
But the formalists amongst us are in the same life, with all the family under the veil,
and the face of the covering, and not having on the garment of needle-work,
wrought in a course of experience, have not a right to this feast on the Lord`'s mountain,
but feed on perishable husks; and a superficial ministry, of the same birth,
and moving on the same ground, feeds itself with the like food,
fills its belly with the east wind,
and empties its chilling qualities on the superficial dependents on human help.

The testimony given us as a people, in various branches, hath been a stone of stumbling,
and a rock of offence, to many, who have wished for our crown, without our cross,
and have overlooked and despised the peculiarity of our testimony,
or the Lord`'s testimony by and through us.
The language, fashions, and customs of the world, though by many esteemed indifferent,
are not so to us, but are a part of the growth, the underwood of the lofty Lebanon,
which the day of the Lord is to come upon, as well as upon the tall cedars;
and when that day comes, it will burn as an oven, indiscriminately, with prevailing heat,
and leave them neither root nor branch.
All who have entered into fellowship with us, through the baptism of Christ,
the true door of entrance, have, not from imitation, but clear conviction,
found this compliance their indispensable duty.
We might have many preachers break in upon us,
were we at liberty to admit them upon the partial
foundation of general speculative truths,
without their coming to the unity of the Spirit,
which unites faithfulness to the Lord`'s statutes and testimonies to us,
and by us to the world.
How far the person in question may have seen into this testimony I know not,
but this I know, many of those called Methodists, their preachers especially,
rather contemn than approve this peculiar dispensation, which, the longer I live,
the more clearly I see to be from Heaven,
against that spirit which rules in all carnality, whether notorious in obvious evil,
more concealed in the walks of formality,
or more refined and fallacious in the outward court of the temple.

I cannot well omit a passage in Cornelius Cayley.`'s letter,
expressing that "`the life begins to send up fresh sap into my dead earth,
and the blind in me begins to see, the deaf to hear, and the dumb to speak.`"
I believe this is really the truth, and a strong description of an infantile state,
a resurrection from being buried in a baptism of death, into a new life,
and yet scarcely grown up into a capacity of
preaching the everlasting gospel of salvation.
The forty days`' retreat into the desert, previous to the ministry of the Holy Jesus,
seems to me not fully accomplished.

I feel much for Cornelius Cayley; I love him;
I wish to give him the right hand of fellowship in the Lord Jesus;
his spirit is near my life;
and oh that he may endure the Lord`'s preparing day! that he may come out of Egypt clear,
and unmixed with any of those things which veil the beauty of the Lord`'s workmanship.
I hope Friends will be tender towards him, yet, for his own sake, and the testimony`'s,
firm and steady, for this will be beneficial to him,
if he ever come in at the right door.
I recommend Friends concerned, and this person,
to a deep inward attention to the great Minister of the sanctuary,
that in his counsel and wisdom all may move,
and the precious unity of the one Eternal Spirit may be
known to run to the nethermost skirts of their garments.

I am, thy affectionate friend, in deep travail for Zion`'s beauty,
that none who love her may fail of the salvation within her gates.

[.signed-section-signature]
Samuel Fothergill.

--

Cornelius Cayley, to whose case the foregoing letter relates,
had addressed to Friends of Leeds, where he then resided,
a letter setting forth his religious state and past experience, wherein he mentions,
that for thirteen years he had preached whenever he could,
"`not having freedom to be in any particular connexion of people;`" but,
having been brought to a closer unity with the principles of Friends,
he requested to be united with them in religious membership.
Some visits were made to him by the Friends appointed,
but after a few months he ceased to attend the meetings of Friends,
and the case was therefore ended.
Samuel Fothergill evidently had some fears that this
individual was not yet clear of the activity of self.
The views contained in his letter are deep, weighty and instructive;
whilst his feelings and tenderness manifest that he was actuated by pure gospel love.

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to his Sister.

[.signed-section-context-open]
Warrington, Fourth month 8th, 1771.

Our Northern yearly meeting at Chester approaches fast,
and brings along with it an anxious travail that the
good cause and glorious name may be magnified.
It is the Lord`'s work, and his is the strength; and I believe, if all flesh be silent,
and the will and wrath of man be thoroughly abased, he will pity his people,
and arise for his own name`'s sake.

With respect to Ireland, I cannot see myself at liberty to be elsewhere than at Chester,
the first-day after the yearly meeting there.
If a good opportunity and a fair wind serve, we shall go down to Parkgate; otherwise,
by Holyhead,
and have no doubt of our being in Dublin time enough for their national meeting.
But all this with filial, reverent submission to my Heavenly Father.

[.signed-section-signature]
Samuel Fothergill.

--

The allusion made to Ireland, in the preceding letter,
related to a visit which Samuel Fothergill made about this time.
He accompanied two of his nieces to Dublin; one of them, Mary Watson,
having been then recently married, was on her way to her future residence, at Waferford.
He attended, whilst in Dublin, the National meeting,
and his services on that occasion are thus mentioned by Richard Shackleton:

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Shackleton to his Father, Abraham Shackleton.

[.signed-section-context-open]
Fourth month 30th, 1771.

"`I would give thee a further detail of our meeting, if I could remember it; but,
as one billow succeeds another,
so one exercising opportunity follows so closely upon another,
in my deep wadings and weary steppings along,
that I cannot always retain particulars in my remembrance.
The meetings have been uncommonly large and crowded.
It has been almost wholly the lot of our friend, Samuel Fothergill,
to burn incense publicly.
He is indeed carried on wonderfully.
His Master dignifies him, and exalts his testimony through him.
He is made like the shew bread on the altar--some sacred symbol,
that is eminently conspicuous, attended with a degree of glory,
in order to attract and engage a people too much outward, and if possible,
by instrumental means, enamour them with the beauty which is in the Truth.
Such is the mercy and condescension of the Creator, who uses various means in wisdom,
that his creatures may not perish for ever; and leaves all without excuse,
that their perdition may be of themselves.
The London queries, as proposed by Samuel Fothergill, were read and answered yesterday,
in the meeting of conference of Friends of both sexes.
Samuel was beautifully drawn forth upon this occasion, as usual.
The public meeting today was very large, and he was concerned in testimony,
also feelingly and fervently in supplication.

I have had close employment upon committees, etc., so that, at home or abroad,
there seems little rest to the sole of my foot.
Neither is it in oil that I dip it when it does rest;
but if it returns to the ark of the testimony, and sinks or swims along with it,
I may be satisfied.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Mary Watson.

[.signed-section-context-open]
Warrington, Sixth month 13th, 1771.

Often, very often, since we parted,
hath my heart expanded in the tenderest affection towards thee, my dearly beloved niece,
and all the affectionate feelings of a mind solicitous for thy happiness,
from the united ties of nature and Divine love have been strong with me.
Thou hast been the daily companion of my mind.
Often have I wished to write to thee; as often, hitherto, prevented,
by many intervening avocations, and indeed, an incapacity of expressing what I feel,
and what I want to say.
My experience hath taught me to believe,
that the lighter sensations of the mind flow from the tongue or pen with ease;
but there is known to a delicate mind certain seasons,
when all the powers of language are baffled,
and the most copious expression is very imperfect.

For thee my beloved relative, this is much the state of my mind.
Fervent beyond the force of mere nature are my desires for thy happiness,
in the most extensive sense of the word;
and a hope accompanies my wish that it may be granted thee.
Let the language of the experience of thy progenitors powerfully
prevail--let the language of truth to thy own mind in the cool of the
day confirm it--that religion and happiness are synonymous terms.
In the name of the God of heaven and earth set up thy banner.
Now, in thine entrance on the public walks of life,
seek carefully after the durable riches of righteousness--after the blessing of
that Hand which builds up families on the solid foundation of unshaken peace,
and sanctifies every dispensation, whether joyous or painful;
for great is the necessity of having our prosperity sanctified, lest we grow full,
and forget the giver,
and prostitute his favours to purposes repugnant to his design and our essential good.
Happy is the cabin of sorrow and penury,
in comparison of the palace of unsanctified affluence.
Thy mind happily established in the pursuit of the Divine blessing,
thou wilt not be unmindful of thy duty as an individual,
nor insensible of the obligation to fill it up before God and his church.
Oh, that now in the bloom of youth,
and having before thee the lengthening prospect of all the world calls good,
thy mind might be turned steadily and fervently to His service,
who hath called thee with a high and holy calling; that,
by a religious dedication of all thy faculties,
thou mayest be rendered an instrument of good,
in these days wherein the gates of Zion do mourn.

Thy beloved companion, thy bosom friend, in an inexpressibly dear relation,
claims thy help, thy sympathy, and thy assistance in the most interesting concern.
Prudence, economy, and the domestic offices, are to be filled up with propriety,
that thou mayest fill up the valuable relations, and be adorned with the qualities,
so beautifully described, Prov.
chap, xxxi.
verse 12 to the end.
And, above all, to promote his truest interest,
for which I believe he is at times properly anxious to
go hand in hand up to the house of the Lord,
to the mountain of the house of the God of Jacob.
Associate with such amongst you who may strengthen thee in the best things;
be diligent in the attendance of meetings for worship and
discipline--make a point of it to attend week-day meetings.
Evidence to others, my dear child,
that the precepts I have wished to instil into thy mind have not been disbelieved,
nor my anxious solicitude for thee an unavailing care.

Cherish the affection of thy dear companion with a delicate solicitude;
give him no pain in things seemingly trivial; anticipate his desires with alacrity;
this will secure mutual esteem, and establish reciprocal happiness.
Esteem is looked upon as a cool word in comparison with many others,
as relative to conjugal felicity; but if it seem not sufficiently ardent,
it is the permanent basis of union.
When the short-lived fervour of the passions hath subsided,
and cool judgment opened its discerning eye, affection, deliberate, steady affection,
hath selected that which is estimable as its treasure,
and laid a deep foundation to build upon, which hath stood the shock of future trials,
and supported in the various perturbations of life, and blessed in every allotment.
But where an exterior hath been the chief good,
and this not supported with really estimable qualities,
short-lived hath the comfort of such been;
for no mind can long love the object the judgment cannot esteem.

Imagine not, my dear Mary,
that I write this from any jealousy of its being necessary for thy guard.
I revive sentiments thou often entertains,
and indulge myself with familiar conversations
with one I love as a father does his child.
I am, dear Mary, with the assurance of best affection, thy uncle,
truly solicitous for thy welfare,

[.signed-section-signature]
Samuel Fothergill.

--

Mary Watson was the daughter of Joseph and Hannah Fothergill, and was born at Warrington,
in 1750.
Her parents both dying when she was young,
she was much under the care and guardianship of her uncle Samuel,
whose tender and religious concern for her welfare,
added to the effect of his pious example,
proved instrumental in turning her feet into that path
wherein she afterwards so conspicuously walked.
In very early life her mind was susceptible of the immediate influence of Divine grace,
and she derived advantage from the perusal of the dying sayings of Friends.
In the year 1771, she was united in marriage with Robert Watson, of Waterford,
in which city she resided until her decease.
In 1783, she was deprived by death of her husband; but in this and some other trials,
through which she had to pass about the same time,
she was enabled to cast her care on Him who
graciously condescended to sustain through all.
About this period,
it was sealed on her mind that she would be called to the work of the ministry,
in which she first appeared in the year 1786,
and being obedient to the call and requirings of her Heavenly Master,
she became valiant in his service.
She was recorded as a minister in 1789, and from that time,
until within a few years of her decease,
was diligently engaged in the work of the gospel, and travelled much therein,
both in England and Ireland.
She was gifted with a sound judgment, and although possessed of good natural abilities,
she was often led to testify that it is only through the power
of Christ that any can rightly labour in his church.
For the last nine years of her life she was deprived of her eye-sight,
a trial she was enabled to bear with Christian resignation and cheerfulness,
and being endued with superior talents for conversation, united to much kindness,
generosity, and the exercise of hospitality,
she was greatly beloved by a large circle of friends, especially the young.
Her expressions during the few weeks which preceded her close, evinced,
that while the outward tabernacle declined, her spirit was strong in the faith;
and that He who had been with her from early life, was still her support in advanced age.
In the morning of the day of her decease, she audibly supplicated to be released,
soon after which there was an evident sinking,
yet she was still favoured with clearness of intellect, and apparently,
in tranquil slumber, she quietly breathed her last, on the 20th of twelfth month, 1834,
aged eighty-four years, having been a minister about forty-eight years.

Excepting William Fothergill, who died at Carr-End, in 1837,
she was the last surviving grand-child of John Fothergill.

In the fifth month, 1771,
Samuel Fothergill attended for the last time the yearly meeting in London.

[.embedded-content-document.letter]
--

[.letter-heading]
Dr. Fothergill to His Brother Samuel.

[.signed-section-context-open]
London, Sixth month 7th, 1771.

A public Friend from North Carolina has arrived; his name William Hunt.
I have an acceptable account of him from Thomas Nicholson and James Pemberton:
he intends to visit the nation, and has got a safe retreat,
at John Elliot`'s. If no particular service is before thee at present,
let it be thy especial care to regard thy health;
and consider how to repair the strength that has been so unremittingly expended,
and lay up a little stock for the future.
Let us waste as little as we can unnecessarily.
I curb myself often, however, seemingly, I am engaged.
Let us hear from thee frequently; it does us all good, and draws us nearer together,
and to the spring of all good.
The publisher of thy declaration at Leeds has done thee great justice.^
footnote:[A sermon publicly delivered at a meeting held in Leeds, 26th of sixth month,
1769.
London, 4to., 1771.
Several editions of the discourses of Samuel Fothergill have been published;
the most complete is that of 1792, long since out of print.
It was remarked, by some of those who had heard them delivered,
that when in print their beauty and force were much lost.]
Neither be afraid to follow the Divine enlargements of thy heart in public service,
nor fear to be little and simple, when the pure, holy language of Truth stops short.
Let us animate one another (I need it much) to more fervency, more inwardness,
and stronger wishes to be what we ought to be.

We are favoured with health, and a degree of contentment,
feeling desires after a release from bondage, and a fuller enjoyment of true,
spiritual liberty, which exceeds the temporal, as heaven is higher than the earth,
or as eternity surpasses the limits of time Often are we followed,
inexpressibly followed, with gracious regard from above:
may our hearts be as often humbled in reverence
and gratitude to the source of every blessing.

[.signed-section-closing]
Farewell, dear brother,

[.signed-section-signature]
John Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to James Jolley.^
footnote:[A Friend, of Warrington, then about to embark for the island of Tortola,
where he soon afterwards died.]

[.signed-section-context-open]
Warrington, Tenth month 9th, 1771.

Desires for thy welfare have frequently suggested sentiments,
which indisposition or a variety of engagements have prevented my intimating to thee;
this consideration has also prevailed--What can I say to him which he knows not,
either with respect to his present or future well-being?
The opportunities of information outwardly,
and the impressions of essential truths inwardly,
have foreclosed every plea of ignorance of duty, or of what makes for peace.
But remember, that happiness consisteth not in knowledge;
the words of our Lord are--"`If ye know these things, happy are ye if ye do them.`"
My soul seeks earnestly that the blessing of
faithfulness may accompany the privilege of knowledge;
otherwise, the greater will be the condemnation.

Thy lot is changed from the warm bosom of society to a land of drought,
where the distilling of heavenly doctrine outwardly as the dew, is little known,
and with many, little desired.
Nevertheless, those who seek wisdom, so as to be made wise unto salvation,
may find in themselves the flowings of that river which makes glad the whole city of God.
Feel after this in thy own heart to preserve thee among
the few names in that Sardis who walk in white,
and have not defiled their garments; that so thy peace may be promoted,
and others helped.
Think of this awful query--What is a man profited, if he could gain the whole world,
and lose his own soul?

The climate is often unhealthy; let it put thee upon thy guard, in every respect,
and raise fervent care, that whenever the Master of the house cometh,
he may not find thee sleeping, or worse employed.

[.signed-section-signature]
Samuel Fothergill.

--

In the tenth month, 1771, upon his return from the last quarterly meeting at Lancaster,
which he ever attended, Samuel Fothergill was seized with an alarming illness:
extreme faintness and loss of strength, under which it was thought he must have sunk,
were succeeded by difficulty of breathing; his nights especially were, from this cause,
alarming, and were nearly sleepless, or passed in broken slumbers,
distressing to himself and his attendants.
Some of the symptoms and particulars of his illness are
mentioned in several of the following letters:--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to His Brother and Sister.

[.signed-section-context-open]
Warrington, Twelfth month 2nd, 1771.

At the time I wrote you last, and for several days since,
I thought there was little probability of my corresponding more with you,
in a manner suited to our present state;
and under the feeling of what neither tongue nor pen could express,
I was enabled to offer my sacrifice on this manner.
Into thine hands, O Lord, I commit our spirits: mine,
for its refuge and hiding in safety; yours to fill up your militant allotment,
that far distant years of faithful services may be by you accomplished,
before you fully enter into your Master`'s rest.
But the prospect seems rather more open with some expectation of longer continuance;
in which I feel much resignation and quiet,
my spirit being humbly committed into His disposal who cannot err.

I feel no external pain, nor any external strong pressure about my throat,
yet a constant uneasiness affects the upper part of my stomach with heat and soreness,
which is constant, more or less.
I am restricted from most liquids for drink,
and am thankful my occasion for them is less than at some other times.
My blisters confine me, they contract the vessels in that limb like the cramp:
I cannot walk without two crutches, and that with pain.
My sleepy disposition continues; I have had many nods over this,
which I cannot continue with any ease to myself or you.
Your affectionate,

[.signed-section-signature]
Samuel Fothergill.

[.letter-heading]
Addition by Sarah Taylor.

I came here today to see my justly beloved relation, your dear brother,
and have passed the afternoon with him, much by ourselves.
He is quiet, composed, and wholly resigned to Divine disposal, yet thinks, at times,
a prospect opens towards some degree of health for a little future service,
though he is much reduced, and labours under various complaints,
quite out of my knowledge as to their nature or danger; yet,
when I heard him intimate this,
methought the feelings of my mind renewed some ground of hope
that he may be spared a little longer for the church`'s sake;
but if not, submission is our duty, without repining,
or calling in question the rectitude of Divine Wisdom in his varied dispensations,
though to us deeply cutting and afflictive;
it is needless to say how trying and painful that will be to many of us,
if ministered in our day; however, it behooves us to step, with humble care and fear,
in the line of manifest duty, that we also may be ready for the solemn close,
and may centre in that happy,
peaceful rest which remains for the humble followers of the Lamb.

[.signed-section-signature]
Sarah Taylor.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Dr. Fothergill to his Brother Samuel.

[.signed-section-context-open]
London, Twelfth month 7th, 1771.

We received thy lively and affecting remembrance of us with
much thankfulness to the great Helper and Preserver of us all.
We trust it will not soon be removed from our minds,
but that we may grow in desires to be made fit receivers of such unmerited mercies.
I trust thy health will be gradually re-established;
the most formidable symptoms are at least at a stand.
There are many, many Friends here very anxious for thy recovery,
and often inquire after thee, I believe, with godly solicitude.
At present, mind only the recovery of thy health, looking often, as I know thou dost,
to the Arm that secretly sustains, and under much bodily weakness,
vouchsafes to renew the holy covenant of love,
to the increase of thy faith and thy further purification.
Desire thy assistants, when they observe thee to begin to breathe with difficulty,
when thou art asleep, to awake thee gently, and bring thee some sustenance immediately.
That terrible distress upon waking is the effect of weakness,
and may be lessened much by awakening thee gently,
when that struggle begins which will at length awake thee in a hurry not to be described.

[.signed-section-signature]
John Fothergill.

--

In the twelfth month, 1771, on account of the continued illness of her brother,
Ann Fothergill went down to Warrington, to visit and assist in the care of him;
and after her return, wrote the following letter.

[.embedded-content-document.letter]
--

[.letter-heading]
Ann Fothergill to her Brother Samuel.

[.signed-section-context-open]
London, Second month 22nd, 1772.

I cannot well portray my feelings.
I have revisited Warrington often in idea,
and sympathized with thee in thy infirmities and various distresses.
I am too distant to step in, and know the particulars of thy situation,
whether thou hast gained even the least advantage,
to observe it with proportionate satisfaction and thankfulness, or if the contrary,
to represent it where I hope for aid.
But what avails our solicitude or our anxiety?
We are in the disposal of superior Power and Wisdom, who does all things right.
'`Tis ours to study to co-operate, whether for the benefit of mind or body;
doubtless both are under his gracious care and notice,
with the means extended for our help and benefit;
this brings to a quiet acquiescence and peace of mind,
that supports in the deepest trials,
and is aptly expressed "`a rest to the soul,`" when we can,
in a reverent sense of his power, love, and goodness, resign ourselves,
and all we hold dear, into his hands,
as the most faithful helper and everlasting sufficiency.
May this be our ardent pursuit, and then it will be our support and quiet resting place.

[.signed-section-signature]
Ann Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Elizabeth Jolley.^
footnote:[She afterwards became a minister in the Society,
and was married to John Bludwick, of Warrington, a valuable elder.
They were both much esteemed,
for their conscientious endeavours to walk as became their religious profession,
for their devotedness to the service of the Society, and their lively concern,
for the support of its discipline.
She suffered much from bodily disease for several of the latter years of her life,
with great patience and sweetness of spirit; and when near the close, she said,
"`I shall die in peace with all, feeling inexpressible love to every one:`" and again,
"`Now, Lord, let me depart in peace, for mine eyes have seen thy salvation.`"
In this heavenly state of mind she quietly departed this life, on the 3rd of first month,
1828, at the age of eighty.]on the Death of her Brother.

[.signed-section-context-open]
1772.

There is not one among thy sorrowful acquaintance,
who hath felt the force of sympathy with thee, on the present afflicting occasion,
with greater tenderness than myself.
I own, I seldom choose to meet the painful gush of sorrow with calm advice.
I would rather mingle the tear of sympathy,
and aid the solemn tribute due to those who are no more.
Religion allows it--for his friend, Jesus wept.
But it is now high time for the violence of sorrow to subside,
and the mind to endeavour after a calm acquiescence in
the disposition of unerring Wisdom,
which hath numbered the hairs of our heads,
and not one of them falls to the ground unnoticed of him.
I know some mournful considerations urge for a place with thee: a beloved brother dead,
on a distant shore, uncertain whether every act of tender assistance was yielded him.
But remember, dear friend, the provision of the Highest reached him there;
and that the everlasting arm supports and succours the islands afar off!
I have not a doubt of his being admitted where the wicked cease from troubling,
and the weary are at rest.

Endeavour, therefore, to suppress the sigh and the tear, which border upon murmuring.
Good is the Lord in all his works;
he deals with his family in a wisdom we cannot comprehend.
My heart is too full for language to discharge,
and my feeble hand hardly sustains this labour.
But I wanted to mingle with thee the tear of condolence, on account of the dear deceased;
and to endeavour to lead to a calm resignation, and to a pursuit of riches,
unchangeable in their nature, and everlasting in their duration.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Ann Fothergill to Her Brother Samuel.

[.signed-section-context-open]
London, Fourth month 18th, 1772.

My brother is much engaged, he is mostly out from nine o`'clock in the morning,
until the same hour or later in the evening; when he comes home greatly fatigued,
and not seldom in apparent anxiety and distress, from various causes.
Yet it is neither in accumulating this world`'s knowledge, its various productions,
the good things belonging to it, its friendships nor its flatteries.
None of these things will afford lasting peace and comfort to the mind.
I think they all tend from it, as they gain upon our inclinations and attention,
if I know any thing of the way to solid peace.
I find, for myself at least, the absolute need of more abstraction, and often to watch,
lest the thief insensibly break in and steal away, by little and little,
our attention and entire love for the alone worthy and adorable Object.
Our dear brother is exposed to an arduous warfare;
his provocations and temptations are very many,
and his time is spent in a continued scene of hurry,
that his preservation is of peculiar favour, mercy, and grace; in a sense of which,
as well as of fear and care for my own safe standing, my mind is,
through continued mercy, at times deeply humbled,
and my heart made to tremble for our preservation to the end,
which is hastening fast to the youngest of us.

Sarah Morris, and her niece Deborah, are arrived in town.
She is a sensible, cautious, weighty woman, and her niece a valuable friend,
an affectionate companion, and nurse to her worthy aunt, who seems feeble and diffident.
They lodge at Thomas Corbyn`'s.

[.signed-section-signature]
Ann Fothergill.

--

As the spring of the year advanced, the health of Samuel Fothergill a little improved,
and though still very weak, he was able, a few times, to go out in a carriage.
In the fourth month he thus describes his situation, in a letter to his sister:--

[.embedded-content-document.letter]
--

"`Yesterday, I was remarkably languid and faint;
today the weather allowed me to get out for an hour.
I am better, but very low and languid, and know not how to exert myself;
there seems in every case, a lion in the streets, but when I am roused,
I move with less difficulty than I feared.
I am very weak, though able to rise from my chair and walk across the room alone;
my flesh is much gone.
Farewell, dear brother and sister, may every blessing rest upon you for ever.`"

--

This improvement in his health was transient; in the following month he became worse,
and symptoms of confirmed dropsy came on.
He was attended by Dr. Pemberton, a kind and skilful physician, of Warrington;
his brother also came down to see him; every remedy,
and every application which the eminent skill and long
experience of Dr. Fothergill could suggest,
prompted by his strong affection for the brother whom he so tenderly loved,
were all exerted for his help and restoration--but in vain;
his constitution was worn out, the bodily powers were far exhausted,
and the period of his release was now near at hand.

[.embedded-content-document.letter]
--

[.letter-heading]
Ann Fothergill to her Brother Samuel.

[.signed-section-context-open]
London, Fifth month 27th, 1772.

Thou hast my affectionate remembrance and tender sympathy, in this long time of trial,
pain, and difficulty, more than I can express;
and I have often remembered thee when on my pillow,
in such a disposition that I could offer myself in thy stead,
if Providence would please to accept so mean an offering,
and restore thee to health and service.
This is not, my dear brother, a rash, inconsiderate, or presumptuous thought,
but in humble, reverent fear, and a sense of my own nothingness, either to do good,
or persevere safely, but by the aid of infinite mercy,
and the just preference to an instrument eminently qualified to be serviceable,
and a beloved brother.
But the disposal of all events is in the wisest hands, to whom belong, worthily belong,
submission, worship, and fear; may we in sincerity of heart say,
"`Thy will be done,`" which is no more than our reasonable duty; in this disposition,
our complainings are silenced, and we confide with alacrity in his wisdom and mercy,
and render the tribute due of love and praise.
May this, both here and hereafter, be our everlasting employment.

I wish we may endeavour to receive our different trials in such a disposition,
as that they may be effectual for our help, and sanctified to us, and then it is enough,
if we have a well grounded hope hereafter, and it is a stay and support whilst here.
Many Friends inquire after thee with affectionate sympathy and regard.
The unity of worthy brethren is as a comfortable
cordial to our minds in times of difficulty,
and I believe few share it more than thyself.

[.signed-section-signature]
Ann Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Dr. Fothergill to His Brother Samuel.

[.signed-section-context-open]
London, Fifth month 20th, 1772.

Though I have shut up the intercourse on thy part,
it ought not to deprive thee of every little comfort which our
near and affectionate remembrance can afford thee,
under thy deep distress--distressed in body,
and often weighed down with affliction and trials within;
but be of good comfort--receive that consolation from others which thy feeling,
sympathising heart has been the means of conveying to many.
I am with thee often in mind,
and if I knew how to add to thy ease and help in the least degree,
I need not tell thee how much it would add to my own happiness.
Many, many Friends here, are very anxious about thee,
and I believe the prayers of many honest hearts are for thy preservation amongst us.
But the event must be left where it ought to be--to the direction of sovereign Wisdom.
Express to those about thee all thou wouldst wish to say to us;
some of them will convey it to us.
If I should mention all who inquire after thee, I must fill a volume.
Let it suffice that the living part of God`'s heritage sympathise with thee.

Farewell, our brother, our friend, our joy, in that which alone deserves the name.

[.signed-section-closing]
Farewell, affectionately; from thy,

[.signed-section-signature]
John Fothergill

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to His Brother and Sister.

[.signed-section-context-open]
Warrington, Fifth month 30th, 1772.

Though I am at present attended with great weakness, both of body and mind,
yet I thought I felt towards you, who are dearer to me than the ties of nature,
merely as such, my beloved brother and sister, a salutation,
in all probability the last you will ever receive from me, in inexpressible affection;
and although my house has not been so with God as that of some others
who have walked with greater care from earliest youth with him,
yet now, though in great bodily weakness, his candle shines around mine head,
and at times an unshaken hope that the God of our fathers will condescend,
in the multitude of his mercies, to receive me into his rest,
and that I shall not die as the fool dieth: and this abundantly supports,
and enables me to give what, I think, is my dying testimony:--That He is good,
and his mercy endureth for ever.

And most nearly beloved, with a love that hath not its foundation in nature,
my heart`'s desire and prayer to God is--That you may be saved.
I see in part the vast extent of the meaning of this word--saved.
I need not remind you of it, as a thing unknown or unconsidered,
but earnestly wish it may often recur to your minds, particularly of thine,
my friend! my brother! my companion! who stands as on a slippery sea of glass;
surrounded by the flattery of the injudicious, and the poison artfully conveyed,
through the flattery of those who may assume the guise of knowledge, understanding,
and sincerity.
He hath signally preserved thee hitherto;
but they that follow on to the end shall be saved.

What rested upon my mind, in the visit to your family, was, I believe, of the Lord:
"`This people have I formed for myself; they shall show forth my praise.`"
Thou hast known his forming hand, even from thy youth upward;
the natural and spiritual endowments with which thou hast been singularly favoured,
and the purpose of this favour, for his own praise,
ought to teach thee to look to the rock from whence thou wast hewn,
and to the hole of the pit from whence thou wast digged,
that thou mayest be effectually formed to His praise, and the end fully answered.
Thy station, thou knows, exposes thee to many things that wound the secret, hidden,
innocent life of Jesus.
O, watch over it as thy chief treasure, for peace and immortality are in it,
and salvation, in the most glorious sense of the word, is bound up in this life.

And dearly beloved sister, with whom I have taken sweet counsel,
and walked to the house of our God in company, thou art inexpressibly near to my life;
the Lord bless and preserve thee, in patience, in hope, in light,
and in the blessed fruits of the Spirit, in peace, and in the joy of the Holy Ghost.
For these favours, he will be sought unto, and thou knows the place where prayer,
as well as the giving of thanks, is wont to be made.
I cannot express what I feel; I cannot add to your experience;
you were in Christ before me: but I leave to you this brief salutation,
as a token I love you to the end; and in that love I tenderly salute you, and wish, pray,
and hope for your eternal welfare,

[.signed-section-signature]
Samuel Fothergill.

--

In a solemn and affecting interview with some of his relations,
who were about to set out to attend the yearly meeting in London,
he addressed them in the following expressions, which were read in the yearly meeting,
by Jonah Thompson.

[.embedded-content-document.letter]
--

Our health is no more at our command, than length of days;
mine seems drawing fast towards a conclusion, I think;
but I am content with every allotment of Providence,
for they are all in wisdom--unerring wisdom.
There is That, which, as an arm underneath, bears up and supports;
and though the rolling, tempestuous billows surround, yet my head is kept above them,
and my feet are firmly established.
Oh! seek it--press after it--lay fast hold of it!
Though painful my nights, and wearisome my days,
yet I am preserved in patience and resignation.
Death has no terrors, nor will the grave have any victory!
My soul triumphs over death, hell, and the grave.
Husbands and wives, parents and children, health and riches, must all go!
Disappointment is another name for them!

I should have been thankful, had I been able,
to have got to the ensuing yearly meeting in London, which you are now going to attend,
where I have been so often refreshed with my brethren; but it is otherwise allotted.
I shall remember them, and some of them will remember me.
The Lord knows best what is best for us;--I am content, and resigned to his will.
I feel the foretaste of the joy that is to come;
and who would wish to change such a state of mind?
I should be glad if an easy channel could be found to inform the yearly meeting,
that as I have lived, so I shall close,
with the most unshaken assurance that we have not followed cunningly devised fables,
but the pure, living, eternal substance.
Let the aged be strong; let the middle-aged be animated, and the youth encouraged;
for the Lord is still in Zion; the Lord will bless Zion!

If I be now removed out of the church militant,
where I have endeavoured in some measure to fill up my duty,
I have an Evidence that I shall gain an admittance into his glorious Church triumphant,
far above the heavens.
My dear love is to all them that love the Lord Jesus.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Dr. Fothergill to His Brother Samuel.

[.signed-section-context-open]
London, Sixth month 9th, 1772.

Oh, dear brother, what comfort did thy letter,^
footnote:[The letter here mentioned was thus endorsed by Ann Fothergill;
"`The last lines we received from a dearly beloved brother,
who departed this life in peace, the 15th of sixth month, 1772.`"]
announcing some little improvement in thy state, give to us;
we rejoice with thankfulness and trembling, and recover hope, which we had almost lost.
If our sympathy could lessen the weight of thy distress, it would be much alleviated.
Our minds are often with thee, and bended with desires for thy help and comfort,
be the event of this bitter dispensation what it may.
Thy vacant seat at our table, at the meetings, hourly reminds us of thee,
and of our own distress; but we leave this, and submit the whole to Divine disposal.

The affairs of the meeting go on well.
Joshua Slrangman, of Leek, is the clerk; he does his business pretty well, better,
I think, than most of the midland clerks of late.
I know thou longs to hear how matters are conducted in the camp.
The American Friends help us much.
John Woolman is solid and weighty in his remarks; he has some singularities,
but his real worth outweighs them.
William Jepson is with us, and is remarkably solid and composed.

Farewell, our dearly beloved brother!
Accept the united, strong, and affectionate remembrance of this family.
Again farewell! from thy

[.signed-section-signature]
John & Ann Fothergill.

--

His illness, and the painful symptoms attending it, increased, his strength diminished,
and the faint hope entertained of some amendment was lost,
in the greater certainty that the end was now approaching very near.

He made the following observations to a friend:--"`I have laboured while I was able,
and it is now my comfort.
It is not only the washing of regeneration,
but the renewing--the renewing--the renewing of the Holy Ghost,
that makes men and women for God.`"
After speaking of the advantages of steady conduct in the youth,
and how necessary it is for them to seek wisdom, he added, "`I wish it for thee,
dear friend, with the affection of a father.
Thou knowest in whom are all our fresh springs; He is at our right hand,
yet we may not perceive Him; at our left, and we may not behold Him.`"

The following communication was made by Samuel Fothergill, when near the close of life:
it was given as a parting charge to his beloved friends of Penketh and Warrington,
and of Hardshaw monthly meeting,
over whom he had so long watched with pastoral care and true affection.
After the expressions were written down, they were submitted to his inspection,
and approved, with an injunction that they should be preserved.
The friend to whom they were delivered^
footnote:[This was John Forster, of Warrington, a minister, who died in 1792.
He was convinced by the ministry of Samuel Fothergill,
and became his friend and frequent companion.
To his son, Samuel Forster, of Stockport,
I am indebted for some valuable information contained in the present work.--G. C.]
has added this testimony--"`But no words can convey the power, energy,
and life that attended his delivery of them;
the same spirit that animated him so often to declare
amongst us the whole counsel of God was with him,
and raised him above pain or weakness, whilst giving this solemn, weighty caution;
and not only at this time, but frequently during his confinement,
he manifested the strongest love and fervency of
desire for all his Friends in the Truth:`"

[.embedded-content-document.letter]
--

"`In returning from the last meeting I was at at Penketh,
my mind was deeply impressed with the words of the Prophet, '`Smite the Shepherd,
and the sheep shall be scattered.`'
-- Though at that time the meaning did not appear so obvious,
it hath since gathered strength upon my mind,
and a desire hath rested with me to leave a few
remarks to this monthly and particular meeting.
'`Awake, O sword, against my Shepherd, and against the Man that is my fellow,
saith the Lord of Hosts.
Smite the Shepherd, and the sheep shall be scattered.`'
Though I am not the Shepherd to whom the sword is threatened,
yet I have been a sub-shepherd, delegated to you by the great Shepherd,
and have laboured amongst you according to the ability received; in poverty, in weakness,
in nakedness, in strippedness; as having nothing, yet possessing all things.
My mind has ever been covered with love towards you,
both in my public ministry and in private:
where I have been engaged to deal closely and plainly with you.
I never used any unnecessary severity; but I have called, and ye refused,
and no man regarded; therefore, you shall call, and I will not hear;
for I will smite the Shepherd, and the sheep shall be scattered:
they have perverted the mercies bestowed; therefore,
I will take from them the delight of their eyes and the desire of their hearts,
and remove my delegated shepherd by the arrow of death, and the sheep shall be smitten.

But, in the extending of my prospect,
an encouraging hope rests on my mind towards the little ones,
those who are little in their own eyes.
I will turn mine hand upon the little ones, and I will bring them as through the fire,
and '`will refine them as silver is refined.`'
I will gather them as lambs by mine own power; they shall call on my name,
and I will hear them; and they shall know a place of feeding,
when the sheep may be scattered and the shepherd removed.
My spirit feels an evidence that I have laboured amongst you with acceptance;
that since I have been mercifully called to a part in the ministry,
I have not neglected to warn you; and that when the chief Shepherd shall appear,
I also shall appear with him in glory.`"

--

His heavenly Father was now pleased to say,
"`It is enough,`" and to release his spirit from farther trials.
He departed this life at his house in Warrington, on the 15th of the sixth month, 1772,
in the fifty-seventh year of his age, and the thirty-sixth of his ministry.

His remains were interred in Friends`' burying ground, at Penketh,
on the nineteenth of the same month.
The love which so many bore to him, and the respect in which he was held,
were testified by a very large attendance of friends and neighbours,
of all ranks and classes, on the occasion.
The solemnity of it was great, and it was favoured by the overshadowing of Divine love,
and by a large degree of that power which had supported him in life,
and had so eminently attended him in his labours as a minister
of the gospel of our Lord and Saviour Jesus Christ.

Thus died Samuel Fothergill, in the faith and hope of the gospel,
and having a happy assurance and foretaste of that
everlasting rest into which he was about to enter.

He was in stature tall; in person comely and graceful; in deportment dignified,
yet courteous; grave, but not austere; affable to all, intimate but with few;
in manners kind, and with a politeness, the result, as it ever will be,
of the practical application of the precepts,
"`Whatsoever ye would that men should do to you,
do ye even so to them;`" "`in honour preferring one another.`"
He possessed good natural abilities, and had improved them by cultivation;
he was well read both in books and men,
but his studies did not terminate in barren and fruitless speculations;
under the Divine blessing, they led him duly to appreciate the great truths of religion,
which shone forth in his life and character.
These qualities, combined with a retentive memory and an observing mind,
rendered his conversation cheerful and instructive, attractive to all,
and to the youth in particular.
With them he frequently indulged in an innocent pleasantry, mingled with instruction.
For this class he always felt much interest,
and whether in the freedom of social conversation,
or in discoursing on the important concerns appertaining to life and salvation,
or in the exercise of his gift as a minister,
he was ever particularly led into sympathy and feeling for the young,
and concerned to promote their welfare.
Of his style, which was strong and nervous, rarely diffuse,
the most striking character was,
the peculiar felicity and skilful adaptation of his metaphors,
and his happy illustrations of spiritual things by comparison with natural imagery;
some of these are eminently beautiful.
In his public discourses, his deportment was solemn and devout, his delivery graceful,
his language pure and correct, never grovelling or low, often elegant and pathetic;
his periods easy and flowing, frequently sublime.

As a minister of the gospel, he was careful to follow the injunction--"`Preach the word,
be instant in season and out of season, reprove, rebuke, exhort,
with all long-suffering and doctrine.`"
In the testimony given by his friends concerning him, it is said,
"`His ministry at times went forth as a flame,
often piercing into the inmost recesses of darkness and obduracy;
yet descended like dew upon the tender plants of our heavenly Father`'s planting;
with these he travelled in deep sympathy of spirit His
gospel labours being free from all affectation,
he, in this respect, commanded reverence; being in doctrine clear, sound, elegant,
and pathetic,
his gift being of that extent which made his service in
the church of Christ general He proposed to the people '`
no cunningly-devised fables,`' but full of charity,
he skilfully divided the word aright, speaking whereof he knew,
and what his own hands had handled, of the good word of life.`"
