== Chapter XII.

Susanna Fothergill, at the time of her husband`'s decease, was,
as she had for some time previously been, in a feeble state of health;
her infirmities increased, and she did not long survive him.
She received the tender care of kind relations, and much sympathy from her friends,
on the loss of such a valuable companion.

[.embedded-content-document.letter]
--

[.letter-heading]
Israel Pemberton to Susanna Fothergill.

[.signed-section-context-open]
Philadelphia, Tenth month 10th, 1772.

My mind being engaged in near sympathy with thee,
desiring thou mayest be favoured with the abundant supplies of Divine
consolation and strength in this time of deep probation and affliction,
a short salutation is, I think, due to thee, and will, I hope, be acceptable,
as it comes from the fervent love and respect of a
friend who loved and honoured thy worthy husband,
and to whom his memory will ever be dear.
I hope thou wilt be preserved in patient submission to the Divine will,
as thou doubtless hast full assurance of his glorious exit,
and that he is removed from all pain and uncertainty, to a state of permanent happiness;
yet, the near union which had long subsisted, and was cemented by the strongest bonds,
being now dissolved, I know from experience, must have caused a conflict in nature,
greater than can be expressed.
At such a time,
the remembrance that we have an High Priest who
is touched with the feeling of our infirmities,
through whom we may "`find grace to help in time of need,`" was to me a support and
relief which I have great cause with reverent thankfulness to acknowledge;
and I believe the renewed sense thereof will minister comfort and stability to thy mind.

My dear wife is yet spared to me, through much weakness and affliction,
both of body and mind: the loss of our beloved son hath affected us very deeply,
though I hope we are enabled to resign ourselves to this allotment of Infinite Wisdom,
and to desire it may be sanctified to us.
Many Friends were lately at our yearly meeting,
by whom thou wast remembered with much affection,
and united desires for thy preservation to the end in faith and patience.

[.signed-section-signature]
Israel Pemberton.

--

Her health and strength continued to decline, and after a few weeks of lingering illness,
she departed this life at Warrington, on the 8th of the fifth month, 1773,
in the seventy-fourth year of her age, a minister about fifty years.

The testimony concerning her, from Hardshaw monthly meeting, states,
that--"`Her labours in the gospel tended to the edification of Friends,
and to her own peace,`"--"`she was for some time
before her departure much confined at home:
nevertheless,
a large degree of that innocence and peace appeared to attend her to the last,
which had been her companion in the more active part of her life; laying down her head,
we doubt not, under the effects of that animating welcome sentence --"`Well done,
thou good and faithful servant, enter thou into the joy of thy Lord.`"

[.small-break]
'''

The few remaining years of the life of Dr. Fothergill were passed,
like many which had preceded them,
in the diligent performance of the duties of his profession,
in which he had long occupied a station of the highest eminence,
in the most enlarged benevolence,
and in a constant endeavour to promote in many various ways the good of mankind at large;
yet amidst all these engagements,
with a still increasing desire and care to keep the world, and all belonging to it,
under his feet, and to press forward in the path which leads to everlasting life.

He continued his annual visits to Lea Hall,
but the satisfaction derived from these retreats from the busy scenes of life,
and the fatigues of his profession,
was greatly diminished by the decease of his beloved brother,
and these visits rendered him more sensible of his loss,
and of the chasm which that event had made.
In 1772 he thus writes from Lea Hall:

[.embedded-content-document.letter]
--

[.letter-heading]
Dr. Fothergill to Dr. Lettsom.

"`I have been obliged to write many letters, which I am at present very unfit for,
or for any thing else; but I will not spend all in unavailing complaints.
I meet with many things to put me in mind how much I have lost,
and I feel such a void in my enjoyments of this life,
as reduces my wishes to a great mediocrity indeed.`"
"`I have enough to do to command myself, when I recollect my brother, whose countenance,
counsel, and sympathy relieved every anxiety, gave taste to every enjoyment;
but I will try to banish everything but a wish
to follow him through the remains of this life,
with submission to every difficulty, and gratitude for many blessings.`"

--

In addition to his retreat at Lea Hall, Dr. Fothergill possessed,
in his estate and gardens at Upton,
an opportunity of indulging his taste and love
for the pursuits of Botany and Horticulture,
though prevented by his numerous avocations from enjoying them so much as he wished.
The estate at Upton, purchased from Admiral Elliott, in 1762, he extended and improved,
planting it with the rarest trees and shrubs, and the choicest plants:
a glass door from the house communicated with an
extensive suite of green-houses and hot-houses,
in which were upwards of three thousand four hundred distinct species of exotics; whilst,
in the open ground, at least three thousand different species of plants and shrubs gave,
during summer and autumn, a constant verdure to the place.
To retire occasionally, even for a short time,
to direct and contemplate the extensive collection he had formed,
was a source of great pleasure to the owner.
Sir Joseph Banks in writing on this subject,
says "`At an expense seldom undertaken by an individual,
and with an ardour that was visible in the whole of his conduct.
Dr. Fothergill procured, from all parts of the world,
a great number of the rarest plants,
and protected them in the amplest buildings which this or any other country has seen.
He liberally proposed rewards to those who
brought hither plants which might be ornamental,
and probably useful to this country or her colonies,
and has liberally paid these rewards to all that served him.
if the troubles of war had not prevented, we should have had the Cortex Winteranus, etc.,
etc., introduced by his means into this country, and the Bread-fruit, Mangosteen, etc.,
into the West India Islands.
For each of these, and many others, he had fixed a proper premium.
In conjunction with the Earl of Tankerville, Dr. Pitcairn, and myself,
he sent over a person to Africa, for the purpose of collecting plants and specimens.`"

"`In my opinion, no other garden in Europe, either royal, or belonging to a subject,
had nearly so many scarce and valuable plants.
It was known all over Europe, and foreigners of all ranks, when they came hither,
asked permission to visit it.`"

In order to keep up and to increase this collection,
several persons were constantly occupied, some in making new acquisitions:
amongst others thus engaged, William Bartram travelled, in 1773,
at Dr. Fothergill`'s expense, "`to search the Floridas,
and the western parts of Carolina and Georgia.`"^
footnote:[See his travels, 1 vol., London, 1792.]
Nor was it merely the curious or the ornamental that were thus collected,
but whatever was likely to be useful, either in medicine or for more general purposes,
was not overlooked.
Ardent as was Dr. Fothergill`'s love of botany,
his pursuits were not confined to this branch of science;
his collections in other departments of natural history, as insects, shells, fossils,
minerals, corals, etc., were valuable and extensive;
he also possessed a large collection of drawings.
But while engaged in these elegant pursuits,
and when thus contemplating the productions of nature,
which his good taste had collected together, he never lost sight of their great Author.

"`In these, as in every other pursuit,
he had always in view the enlargement and elevation of his own heart;
having formed early habitudes of religious reference,
from the display of Divine power and wisdom in the beauty, the order,
and the harmony of external things, to the glory of their Almighty Former.
From the influence of these habitudes,
his mind was always preserved in a disengaged and independent state, enjoying,
but yet adoring.`"^
footnote:["`An affectionate tribute to the memory of the late Dr. John Fothergill,
by W. Hird, M. D.`" London, 1781, page 13.]

His encouragement of genius was not limited by
the bounds of any particular science or pursuit;
it was his delight to seek out, and to promote the advancement of merit,
and munificently to reward it.
Of this the ingenious Anthony Purver was an instance.
He had, by indefatigable self-exertion, acquired an extensive knowledge of the Hebrew,
and other Oriental tongues, and solely by the patronage of Dr. Fothergill,
completed a literal translation of the Holy Scriptures;
and though certain idioms used by the translator
have caused it to be less read and esteemed,
it is considered a valuable work.
Besides causing it to be printed at his own expense.
Dr. Fothergill, it is said,
presented A. Purver with one thousand pounds for his performance.

Many are the instances related, and many more there were, never recorded,
of the large pecuniary bounty, which,
in addition to the assistance gratuitously afforded by his medical skill,
he distributed to cases of distress with which his profession made him acquainted.^
footnote:[The work was published in two vols., folio, 1764.
Anthony Purver died at Alton, in Hampshire, in 1777, aged seventy.]

Whilst he was thus actively engaged in his profession, in the promotion of science,
and in benevolent pursuits,
his devotion to the interests and proceedings of the
religious Society of which he was so valuable a member,
increased with his increasing years; he had its prosperity much at heart.
In the year 1776, he was nominated one of a committee, appointed by the yearly meeting,
to make a general visit to the meetings throughout the nation.

On this occasion he wrote the following letter:

[.embedded-content-document.letter]
--

[.blurb]
=== To the Friends nominated at the late yearly meeting, to visit the quarterly and monthly meetings, etc., and to the members of our Society in general:

[.salutation]
Dear Friends,

Having been nominated on this service, I accepted of it with reluctance,
from an apprehension of my unfitness,
as well as from the confining nature of my employment.
But being desirous to acquit myself to the best of my ability,
I could not avoid considering, with much and deliberate attention,
the proposal made to the meeting, both in respect to the manner of it,
the nature of the service, and its object; all of which claim my hearty concurrence.
That it arose from the simple movings of Truth, I am fully, persuaded;
the prevalence of a holy influence over the minds of many, when it was delivered,
was generally felt and acknowledged.
The nature of the service is, to render us helpful one to another,
in promoting the growth and prosperity of every individual in the truth,
and by this means to advance the great end of true religion,
the glory of Him who created us, and the comfort and happiness of all.
The complaining language of many counties having deeply affected the minds of Friends,
fervent desires were raised that the life of religion might be renewed in the churches,
to their help in the maintenance of pure, unmixed piety.
And it pleased Divine Providence to open the way
to a fresh labour of love amongst his people,
and to make many willing to engage in this service; and oh I may it be blessed,
so as to make it a memorable season of Divine refreshment,
from the great Master of our assemblies.
A desire to contribute my mite to this great and useful labour,
prompts me to throw before my brethren the following reflections,
hoping they will be received as the fruits of a mind cordially disposed,
in the first place, to build up its own breaches, and in the next,
to join in repairing those which the enemy has made in the walls of our Zion.

I would wish to apply to my brethren engaged in this service,
and to recapitulate some parts of the wise, important,
heavenly counsel communicated to you, during your deliberations on this subject,
by many concerned brethren; that as you have given up your names,
and that with a willingness that bespeaks your zeal for the cause of truth,
and its prosperity among the people,
you will let the weight of the work take possession of your minds.
Let it be your fervent prayer, that you may be made deeply sensible of its importance,
as well as of the time and manner in which you are to proceed.
These considerations were earnestly pressed upon you,
and as you keep them in humility and fear before you,
way will be opened for your accomplishing the work, to the churches`' benefit,
and your own growth and experience in righteousness and truth.
Let it be your care, in this service,
to look to that Arm of power which gathered us to be a people, and has hitherto,
in a good measure, preserved us one in faith and practice.
Wait for a degree of that wisdom which led our ancestors to
establish a most wholesome discipline amongst us,
for our preservation: and be it your chief care, in much brotherly love,
to strengthen the weak, and bring back the scattered, and by an awful labour,
to awake them to a sense of the holy principle of light, life, and grace,
to an obedience to it, to a knowledge of its blessed effects;
this is the one thing needful: and oh! that they may wrestle and prevail, as Jacob did,
and obtain the blessing, for yourselves, and for the whole heritage of God.

And you, my dear friends, who are the objects of the churches`' care,
and amongst whom I rank myself, surrounded with many weaknesses, much imperfection,
far short of the excellency that adorned our predecessors,
yet struggling in hope after a belter life, freedom from entanglements, more love to God,
and his truth; yield to the word of exhortation;
receive this visit as a fresh renewal of the love of God,
and of help administered in the needful time.
Let us embrace the hand held out to help us, kiss the rod we may have deserved,
and give thanks to God for his mercy and loving-kindness,
in thus exciting a fresh concern in the church for the restoration of individuals.
Let us prepare ourselves, in sincerity,
to receive the word of exhortation in meekness and humility;
so shall we be made partakers of the benefits intended,
feel our strength renewed to run with alacrity the race that is set before us,
be made helpful to others in their progress, and having finished our course with joy,
leave a bright example to those who follow after us.

Under a sense of the great need we have to be afresh roused up to diligence,
I found a willingness to throw these few hints before my brethren,
as a testimony of my full unity with the proposition,
and my desire that it may be rendered effectual to the help of many,
and the general edification of the churches.

[.signed-section-signature]
John Fothergill.

--

He united with a part of the committee in visiting the
meetings of Friends in Lancashire and Yorkshire,
his sister accompanying him in the latter.
In a subsequent letter, he thus speaks of the visit,
in terms more suited to the well known diffidence of his character,
than to the part which he took in the service:

[.embedded-content-document.letter]
--

[.letter-heading]
Dr. Fothergill to Sarah Bird

[.signed-section-context-open]
Tenth month 17th, 1776

It was with much reluctance that I consented to be named on
such a service as that in which we took a small part,
I hope to our own help at least;
and if we either tended to hold up the hands of those who were qualified for the service,
or gave proofs that we had the fullest unity with it, we are glad.
We find, by several accounts, that the visit has been well received every where,
and many testimonies given of its utility.
I cannot forbear thinking, that times of distress are gradually, imperceptibly advancing;
the season may not be in my time, but I wish to be prepared for it if it should.

To my nephew and his family say,
that if they look back frequently to the worthy parts of their ancestry,
with a wish to follow their footsteps, they will be the better for it.
To all the progeny of our worthy father is the gracious regard of heaven extended,
and we ought to be abundantly thankful that so many are preserved from the
spots and stains of this life.

--

Amongst the many distinguished men who, from similarity of pursuits.
Dr. Fothergill ranked amongst his intimate friends, was John Howard.
They were both engaged, though in different spheres,
in lessening the miseries of human life;
and in attempting to prevent those injuries and diseases which contagion produces,
they united their labours.
They were desired to attend before the House of Commons,
where they gave such information,
that an Act was passed on the subject of the health of prisoners,
and for preventing the gaol distemper, also for building penitentiary prisons.
These two eminent men, with George Whatley, were appointed by the king,
commissioners for fixing upon a site, and directing suitable buildings to be erected,
for carrying this new system into execution.
Again,
when the Legislature was informed of the great mortality amongst the
French and Spanish prisoners then confined at Winchester,
Dr. Fothergill was consulted,
and he recommended Dr. J. Carmichael Smith to superintend the prisons, to avert,
if possible, the spreading contagion:
the success which ensued confirmed the discernment evinced in the selection.
When the empress of Russia wished to introduce into her
dominions the practice of inoculation for the small-pox,
and desired her ambassador in England to send over a competent person,
he applied to Dr. Fothergill, who recommended Dr. (afterwards Baron) Dimsdale,
and he was, in consequence, appointed to that distinguished employment.

In common with many other good men,
Dr. Fothergill deeply lamented the unhappy contest
between Great Britain and the American colonies:
he had exerted himself by writing, and in various ways, to avert it.
He and his friend, David Barclay,
were authorised to attempt a compromise with Benjamin Franklin,
before his departure from England; accordingly, several conferences were held with him,
and some correspondence took place,
in endeavours to arrange the differences and establish
a permanent reconciliation between the two countries,
but the attempt proved unsuccessful.

It would be difficult to enumerate the various ways by which Dr. Fothergill
endeavoured to promote the advantage and the general good of his fellow-creatures;
independently of the opportunities afforded by his extensive practice as a physician,
and his high standing in general society,
he was often engaged in proposing plans conducive to this.
His enlarged mind, capable of embracing every object of usefulness and benevolence,
was enabled to accomplish much by the order and punctuality
which pervaded and regulated all his conduct.

A benevolence so comprehensive and universal could not
overlook the important subject of the right education of youth.
It did not escape his observing mind, and he was occupied with it for several years.
He saw with concern how much the young were exposed to temptation, and he wished,
by promoting a guarded education, to strike at the root of the evil.
He would willingly have included the whole community; but,
conscious that the attempt on so large a scale would be fruitless,
he confined his hopes and his attempts within the bounds of his own religious society,
in which his influence was great,
and where he knew he should receive assistance and support.

To this desire on the part of Dr. Fothergill,
the Society owes its valuable institution at Ackworth.
The circumstances which led to the establishment
of that school are thus related by Dr. Hird:

"`On his return from Cheshire, in the year 1777,
he did me the favour of being my guest for a few days.
In one of the many interviews he then had with his friends,
the conversation turned on an institution at Gildersome,
a small establishment for the education of the poorer children amongst the Society.
Dr. Fothergill inquired into its state and management,
and how far it might serve as a model for a larger undertaking.
The present state of the Foundling Hospital at Ackworth, was also mentioned;
erected at a vast expense, it was then in danger of dilapidation,
and ready for public sale.
This struck him forcibly--'`Why may not this,`' said he,
'`serve the very purpose I am in pursuit of?`'
The building, with an estate of eighty acres of land, was purchased, improved,
and furnished by subscription.
The Doctor set a generous example, by his own contribution,
and an endowment by his will in perpetuity.

In thus coming forward to secure by immediate purchase,
what appeared so desirable for the object in view,
Dr. Fothergill was assisted by his friend David Barclay, and some others.
With a generous confidence,
they trusted to the Society for confirming and
perpetuating that which they had thus begun.
The event fully proved that, in so reposing their trust, they did not err.
This undertaking,
of which Dr. Fothergill was so far the author as to have first
proposed it to the consideration of the Society,
he had the satisfaction of seeing fully established,
with every prospect of its fully answering the design of its benevolent founders.
It remained with him a near object of interest for the rest of his life.
A few months before his decease, he broke the silence in a committee, by saying,
he "`rejoiced with trembling`" at the success and the blessing
which he considered had thus far attended their labours.
His opinions on the intentions of the school, the suitable objects for it, etc.,
are fully developed in his well known "`Letter to a Friend in the country,
relative to the intended School at Ackworth,
in Yorkshire,`" which has several times been printed.
He had also much correspondence on this institution,
in which his sagacity has included almost every subject
connected with the establishment of the school,
even to very minute details.

For a series of years, indeed for the greater part of his life.
Dr. Fothergill had enjoyed good health,
and time seemed but slowly to diminish the vigour of his body,
or weaken the exertions of his mind; but it was evident,
after the decease of his brother, that he was less capable of enduring fatigue,
and that his annual visits to Lea Hall, and the recess thus obtained,
did not yield him that renovation of strength which, in former years,
had been the result of this retirement.
In the eleventh month, 1778, he was attacked with a severe internal complaint,
accompanied with intense pain, and which much reduced his strength.
Dr. Lettsom says--"`In the height of this distress, I visited him,
and found him calm and collected.
He described, with wonderful serenity of mind, his acute misery,
expressing a pious and Christian resignation, and adding,
'`that if he had left any thing undone which he wished to have done,
it was perfecting the plan of Ackworth School; and likewise,
the complete arrangement of the rules of our religious Society.`'^
footnote:[This work, although not completed until 1782,
had occupied the attention of the Meeting for Sufferings, of which Dr. Fothergill.
was an active member for a considerable time previously.]

In a few weeks the complaint abated, and he was again able to see his friends:
and forced by the importunities of those who sought relief from his medical skill,
he again resumed the duties of his arduous and active life.

[.embedded-content-document.letter]
--

[.letter-heading]
Dr. Fothergill to Catharine (Payton) Phillips.

[.signed-section-context-open]
London, Twelfth month 5th, 1778.

Thy very affectionate letter to my sister,
revived the remembrance of that friendship which
has so long subsisted between my brother,
thyself and us, so strongly that I rather chose to answer it myself.
Through unmerited favour, I am in a probable way of recovery, though yet far from well.
My disorder was at first a common cold; I struggled with it,
under a necessity of great application, till at length it was accidentally increased,
and brought on other complaints.
I form hopes that by degrees it will give way.
My appetite and strength are gradually returning, and though yet unfit for going abroad,
I am easy and content.

I cannot express, in a short compass, the feelings of my mind on this trying occasion.
I have only to look back to that point when, if I had not been relieved,
I must in twenty-four hours have been numbered with the dead, and saw it most clearly,
with humbling gratitude for a degree of calm resignation to the Divine will,
secretly trusting in his power, goodness, and mercy.
And may I never forget the season.
Anxiety and fear united, presented themselves; but I endeavoured to be quiet,
and to trust in Him who alone is worthy to be confided in for ever.
What may now await me I know not.
I know too well my own inability to help myself, and to stay me, where I ought to remain,
without assistance above my own resolutions.
I shall wish, however, to detach myself from the world, as occasion may offer,
and to which this dispensation may, I hope, contribute.
I have not hurried into these numerous engagements, so far as I know of myself,
from any other motive than those which urged me on to
do the business of the present hour with diligence,
whether in the duty of my profession, the common calls of life,
or the affairs of the Society.

This plunge will oblige me to make some choice,
and its being so generally known will serve me as a just plea
for refusing many embarrassing distant engagements.
Such are my views and my desires at present, and I humbly trust that goodness and mercy,
which have given me my life as a prey, will not leave me.
Indeed, the general and cordial regard manifested to me, by Friends and others,
lays a strong obligation to gratitude upon me, and would prompt a desire to repay it.
But I must not give way.
I have hitherto done all I could to serve all within my reach,
and it is a satisfaction to feel that I have not
served an ungenerous or ungrateful public.

Thus, my dear friend, I have endeavoured to give thee a just state of our condition.
We know thy present desires for our good,
and may they be still continued when access is granted.

[.signed-section-signature]
John & Ann Fothergill.

--

Some time after his recovery from this illness, he visited Ackworth School,
to endeavour to perfect his plan, and to perpetuate its advantages.
He was accompanied by his sister, and they also went to Knaresborough,
and the burial ground at Scotton, "`to pay,`" as he describes their visit,
"`the grateful tribute of a tear, at the side of an honoured parent`'s grave;
to see that his sepulchre was not laid waste to the beasts of the field,
but secured from the ravages of neglect, was to us a pleasing duty.
Firmly persuaded that we had not the least cause to mourn on his account,
and nothing left, more becoming us, than to call to mind his precepts, and his example,
we left the solitary spot with hearts full of
reverent thankfulness that such was our father,
and that we were so far favoured as to be able
to remember him with gratitude and affection.`"

The burial ground at Scotton is still occasionally used by Friends.
It is beautifully situated on rising ground, amidst extensive woodlands,
and surrounded by aged trees which Dr. Fothergill had planted,
and which continue to show that they had been
placed there by the hand of judgment and taste.
In a visit made to this lonely and interesting place, in the autumn of 1842,
the fences were found in good order,
but cattle were allowed to graze amongst the ancient grave-stones,
now much overgrown with moss; the inscriptions might still be deciphered,
but none of them marked the spot where the venerable
remains of that faithful servant of his Lord reposed.

The firmest constitution, the most temperate life, must at length yield.
On the 12th of the twelfth month, 1780,
Dr. Fothergill experienced a severe return of his former complaint,
which the united efforts of several of the most eminent medical men could not remove;
and although he received some slight relief by surgical aid,
the intense pain which accompanied the disease throughout, remained unsubdued,
and under its effects his strength rapidly gave way.
Yet, in the midst of this extremity of suffering his mind was preserved calm and serene;
he expressed a hope that he had not lived in vain,
but had endeavoured in degree to answer the end of his creation,
by sacrificing interested considerations,
and by his care for the good of his fellow creatures.
His firm belief in his Redeemer did not forsake him in this trying hour;
and to his deeply afflicted sister he often addressed words of comfort, saying,
"`All is well with me; through the mercy of God, in Jesus Christ,
I am going to a blessed and happy eternity: my troubles are ended, mourn not for me.`"
In this peaceful state of mind he departed this life, at his house, in Harpur street,
on the 26th of the twelfth month, 1780, in the sixty-ninth year of his age.

His remains, attended by a large concourse,
who assembled to manifest their love and respect for his character,
and their sorrow for the loss of such a man, were conveyed to Winchmore-hill,
and interred in Friends`' burying ground there on the 5th of first month, 1781,
after a large and solemn meeting.

Much more might have been said respecting Dr. Fothergill,
but accounts of his life have been already frequently printed.
Soon after his decease, his relatives.
Dr. W. Hird, and Dr. G. Thompson, each wrote sketches of his character,
or tributes to his memory; his friend.
Dr. Lettsom, also collected his.
works, and published them, with a full account of his life;
this passed through at least four editions,
and is the fullest and best account of him that has appeared.
Another collection of his works, with a life prefixed,
was also published early after his death, by J. Elliott, M.D.;
but this abounds with errors--few of the particulars
respecting himself or his family being correctly stated;
some of these errors have been copied into other accounts of him more recently published.

From early youth, even when but eight or nine years old,
his love for the productions of nature was developed; and at that early period,
he took pleasure in studying the forms of plants,
and acquiring a knowledge of their qualities, with reference to their powers of healing;
thus early was he engaged in a preparation for that profession,
in which he afterwards justly attained to so high an eminence.
To an extraordinary sagacity and discernment in treating disease, he was accustomed,
as he has been reverently heard to say,
to seek the Divine blessing upon his endeavours to restore those under his care.
In the early part of this volume, it is stated,
that he and his brother Samuel were at school together at Briggflats;
subsequent information renders it more probable that
they were placed in the family of some friend there,
but attended the celebrated grammar school at Sedberg, not quite two miles distant.
The earlier part of Samuel`'s education he received at the grammar school of Yoresbridge,
near Askrigg, not far from the place of his nativity.

To his fondly attached sister, the death of Dr. Fothergill was a severe trial.
The loss of a tender and affectionate friend, and pleasant companion, was irreparable:
a near and close attachment had subsisted between them from childhood,
and with him was connected all her earthly enjoyments;
he brought around her the best society,
for the good and wise of every country sought and found in him a kindred mind.
She was now lonely, the solitary survivor of a numerous family,
and to her gentle and affectionate heart the stroke which severed them was sharp,
but she bore it with quiet and patient acquiescence in the Divine will.
She was a truly religious woman, for many years in the station of an elder,
well concerned for the good of our religious Society,
and earnest in the support of its discipline; kind, benevolent,
and much given to hospitality; every first and fifth-day she had a dinner provided,
for strangers who might attend Westminster meeting, to which she belonged,
whether ministers or others.
She was much respected and beloved, and a faithful, discreet counsellor to many,
who sought her advice in their various perplexities.
She survived her brother many years, and in old age became very feeble in body,
and her mental faculties much declined;
but it was evident that her mind was still visited and
sustained by the influence of Divine love,
which preserved her in a tender and innocent state to the latest period of a long life.

She died at her house in Great Russel street, on the 8th of seventh month, 1802,
aged eighty-four years, and was interred at Winchmore-hill.

[quote.scripture, , Psa. 37:39-40]
____
The salvation of the righteous is of the Lord:
He is their strength in the time of trouble.
The Lord shall help them, and deliver them, and save them,
because they trust in him; &hellip;
and their inheritance shall be for ever.
____
