== Chapter I.

In contemplating the characters and services of those chosen servants of the Lord, whom,
in his Divine Providence, he does, from time to time, raise up in his church,
as monuments of his mercy and instruments in his hand, we often feel desires raised,
that some record of their labors should be preserved,
and that their memories may be handed down to succeeding generations; that thus,
though being dead, they may still speak, and that their lives may tell of the goodness,
and proclaim the praise of Him by whom they were so eminently
qualified--who had called them out of darkness into his
marvelous light--who had sustained them through life,
and in the end mercifully granted an entrance into his everlasting kingdom;
so fulfilling the declaration,
that they that turn many to righteousness shall shine as the stars for ever and ever.

Amongst these may be numbered John Fothergill, of Wensleydale,
and his son Samuel Fothergill, of Warrington, members of the Society of Friends,
and both faithful and eminently qualified ministers of
the Gospel of our Lord and Saviour Jesus Christ.

In one of those small sequestered dales which are contiguous to,
and in some measure form branches of, the larger valley of Wensleydale,
in the north-west of Yorkshire, stands CarrEnd, a respectable looking mansion,
on the banks of the small and quiet lake of Semer-water.
Here John Fothergill was born, in the first month of 1676;
and this was for many years his residence, as it had been that of his ancestors.

He was the son of Alexander and Ann Fothergill, of whom he has left this testimony.
"`My parents +++[+++were]
not only convinced of the blessed Gospel dispensation of God to mankind in
sending the Spirit of Christ to enlighten and reprove for sin,
and to lead the believers in it into truth and righteousness
as testified unto by the people called Quakers,
but +++[+++they]
also endeavored carefully to feel after, and live up to,
this powerful principle of Truth,
whereby they were both instructed and enabled to be exemplary in life,
and in a religious concern to attend meetings for the worship of God, and in a humble,
steady,
diligent waiting upon him for the appearance of his enlivening presence and power,
to enable them to worship acceptably.
This also led them into a godly care to train up their children in the fear of the Lord,
and to take them to religious meetings, both on first-days and other days of the week,
which they seldom failed to attend; especially my mother, whose care herein,
and her spiritual, reverent travail of soul in meetings,
(often held in silence,) for the sacrifice of a
broken heart to be prepared in her by the Lord,
had very early a deep, affecting impression on my consideration.`"

From a very early age, great was his care and inward fear lest he should offend the Lord.
"`This,`" he says, "`with some heavenly touches of the life of truth,
enabled me to live more self-denyingly and gravely than some others of like years,
which my mother particularly noted to herself,
with some comfortable hope for the future.`"

The death of his tender, careful mother, which took place in 1689,
when he was about thirteen years old, proved a great loss to him.
Soon after this event he became for a time less watchful and
less thoughtful for his soul`'s everlasting welfare,
and the heavenly desire and looking towards God, which had previously been his care,
became stifled and neglected.
He was very young at this time, but these declensions were often a burden to him,
and occasion of much secret sorrow: strong desires after repentance ensued,
and by renewed convictions and visitations,
he was brought to see and consider his weakness and unfaithfulness,
and to mourn over them with secret lamentation.

"`Yet,`" he says,
"`as I was kept for a time thus low and watchful to this heavenly principle of Truth,
which let me see my sin and the danger of it,
I was favored with springings of hope for mercy and salvation,
and then my cry was frequent and strong, to be purged thoroughly, whatever I had to bear,
if the Almighty would but enable me.
Thus I wrestled for several years,
and dared not believe that I gained any effectual victory;
and as the baptism of Christ by his Spirit had begun to operate in me,
to bring a death unto sin and the lusts of the flesh,
that through faith and diligent attendance to
his power I might live to him in newness of life,
I had some hope that the fan in his hand would thoroughly purge me,
which was the very earnest cry and longing of my soul.
But the winnowing, refining work of the spirit of judgment, and of burning,
now kindled to take away my dross,
was so heavy upon me that I was often tempted to conclude that I was forsaken of mercy,
and that judgment and darkness were to be my portion;
a resolution in a degree of living faith, was firmly fixed in my heart,
to endeavor to lie and to wait as at the Almighty`'s footstool,
and as this desire after divine favor and mercy, and devotedness of heart,
to lean towards and wait for his arising, was of his own begetting,
so he was graciously pleased to stay my mind in humble resignation,
until he brought forth judgment unto victory by degrees,
and caused the Sun of righteousness at times to arise upon me with healing in his wings;
yet he often saw fit to hide his face from me again, and to strip me,
not only of any sense of his favor,
but even of hope of obtaining a place among the redeemed.
At this time, the Scripture which says.
It is good to hope and quietly wait,
to see the salvation of God in the land of the living, and some other like sentences,
were brought to my remembrance, accompanied with glimpses of heavenly goodness,
which graciously helped to stay me in some patient hope under the heavenly
refining hand the blessed presence of the Saviour of the world,
which at times filled and overshadowed my soul in my thus following him, though mourning,
is never to be forgotten by me.
This was about the seventeenth year of my age.`"

When he was about eighteen years old,
his father was prosecuted on account of his Christian
testimony against the payment of tithes,
and carried away from his family to prison at York,
about fifty miles distant from his own dwelling.
John being the eldest then living, the care of the (three) younger children,
and of the business and servants, devolved upon him: this,
with his father`'s imprisonment at such a distance, and in a poor state of health,
brought him into much anxiety and concern of mind.
One, coming to see him,
urged him strongly to give him liberty to agree with his father`'s prosecutor,
and thus procure his discharge from prison, and to have the money reimbursed afterwards;
but he says, "`when I considered a little,
my understanding was fully satisfied that it was the mind and cause of God,
that this testimony against tithes in this dispensation should be borne,
and that what suffering soever might attend our faithfulness to him,
he could readily make up, and I then believed he would; and so, on the other hand,
that he could soon blast and consume any seeming advantages
that might be hoped for by giving way to selfish reasoning,
or shrinking from the faithful and reverent bearing of that testimony.`"

After being imprisoned for conscience`' sake for about six months,
his father was released, but did not long survive his liberation;
he departed this life on the 6th of seventh month, 1695.
"`This,`" says his son, "`increased my exercise in several respects,
but as I endeavored to seek the favor and counsel of the Most High God,
he was pleased to remember me with merciful help many ways.`"
Yet many were the baptisms and deep conflicts of soul through which he had to pass;
at times much sorrow and distress was his portion; at other seasons, he says,
the Lord "`was pleased to deal gently with me, mixing mercy with judgment,
and filling my soul again and again with reverent hope,
as well as humble supplication that he would thoroughly purge me,
and spare nothing alive in me that was offensive to him.
Thus was my heart often exercised both by night and by day, often, likewise,
when about my business; and sometimes the brightness of the salvation of God,
and the enlargings of his love, were so abundant in my soul,
that I could scarcely (nor did I always) keep from falling down upon
the ground to adore and worship his glorious presence.
And at some times,
I apprehended it might be required of me to open
my mouth for the Lord in the congregation,
which was exceedingly humbling to me.`"

Abiding thus,
"`with some patient hope under the heavenly refining hand,`" John
Fothergill became fitted and prepared for service in the Lord`'s cause,
and in the twenty-first year of his age he came forth as a minister of the Gospel,
and continued a diligent and faithful laborer therein to the end of a long life.

He did not enter upon this important work until very
close and strict examination had convinced him,
that the call to this service was from the only true and right source,
and great was his fear lest he should be too forward, or proceed without right authority.
On this important subject he has left the following instructive remarks: --

"`I am not without fear that such a due waiting for, and distinct certainty of,
the immediate call or requirings of the Word of life,
have not always been suitably practiced, and for lack hereof,
some have appeared as ministers before +++[+++being]
ripe, and have brought forth fruit of very little service, if not detrimental;
because none can give what they themselves have not: whereas,
if these had waited with proper diligence for the living Word
to open and engage in the entire subjection of self,
they might have been great and good instruments,
as clouds filled by the Lord with heavenly rain.
And as the divine and certain requiring of truth
is the only right entrance into the ministry,
because the Lord said, '`Some run, and I sent them not,
therefore they shall not profit the people;`' so
it is only his fresh and renewed requiring,
not only opening the matter to speak, but engaging to speak at this time,
whereby the church, or individuals, are edified,
as our Father would have his children edified.`"

Having thus given up in obedience to the Divine command,
he was engaged in the exercise of his gift,
visiting sometimes one neighboring meeting and sometimes another;
yet still was he closely tried,
and many hidden sorrows were his portion under the weight of the refining season,
through which he had to pass, but a degree of living hope was often revived in his mind,
"`that in time he might, through humble attention and godly care,
be set more at liberty in the freedom of a son.`"

Great was his care and anxiety diligently to wait for
the distinct openings of the light of life,
and that all his proceedings might be in obedience to it.

In the twenty-second year of his age he felt a concern
of mind to pay a religious visit to Friends in Scotland,
which he accomplished to the satisfaction of his friends, and returned with peace.
About this time he believed it right to dispose of his business and to let his land,
that he might be more at liberty; yet,
while careful not to be so involved in temporal concerns "`as to
hinder him from true inward retiring often to feel the life of truth,
for the daily support of his soul;`" yet he also thought it
right not to be without suitable outward employment,
as therein "`there appeared,`" he says, "`both then and since,
a danger of being tempted to be easily drawn abroad,
before or without that distinct requiring of truth both to go and return,
in which only the ministers of Christ move in true safety, and to right edification,
and be in danger of missing, or losing,
the knowledge of the pure requirings of the everlasting High Priest;
and so make way for formality, a barren ministry, and unprofitable labor.`"
So careful was he to endeavor to avoid errors on either hand,
and to be found obedient in all things.

A few months after his journey into Scotland, he visited several parts of Yorkshire,
and the county of Durham.
Of this visit he thus writes:--"`Though this labor was like a fire to the house of Esau,
and, therefore, unpleasant to some;
yet the inward and living among the people were relieved and made glad in the Lord,
whose favor and peace often filled my heart with awful reverence towards him,
with strong desires purely to know, and to be helped to do his will faithfully.`"

About this time, several in the northern parts, where he had been led in gospel labor,
were convinced and gathered into a knowledge of the truth,
of whom some became valuable ministers.

His next service from home was an extensive visit to Friends in the western counties,
and the city of London, where he remained several weeks.
From there he went into Cornwall,
and on his return attended the yearly meeting at Bristol;
he also visited all the meetings in Wales,
and returned home through Cheshire and Lancashire.

In the year 1701, he visited Scotland a second time,
passing through Cumberland to Edinburgh, and so to the north of Scotland;
visiting the meetings everywhere in those parts, and returned to Glasgow.
In many places he was truly comforted with Friends:
"`They were encouraged and glad in a loving sense of the continued fatherly
regard and extendings of the love of God toward them in that nation,
amongst a hard, self-conceited, and, in some places, an envious people.`"
In Edinburgh and Glasgow a rude spirit prevailed,
causing them to disturb Friends in almost all their meetings, sometimes throwing stones,
etc.; some with all the noise they could,
endeavored to drown the voice of any who were concerned to minister publicly.
Yet, at times, the power and authority of Truth arose over those wicked endeavors,
and the evil spirit was overborne and weighed down, and some of the worst would go away,
and others lend some attention to the testimony of truth;
and Friends were the more edified, and their faith and hope in God strengthened.
At Glasgow, when I was there on a first-day of the week,
the people had very much disturbed us in meeting, in their usual manner,
and followed Friends along a large open street, some shouting and scorning,
others throwing stones and dirt.
The people who were gathered in great numbers about their doors, and saw what passed,
seemed rather to be pleased with the abusive behavior of the mob towards us,
than to offer any discouragement to them: whereupon, a soldier, an Englishman,
began to cry aloud three times, as if he had some public proclamation to make;
and when he had thus gained attention, he called aloud again:
'`Behold the godly town of Glasgow,
how they entertain strangers!`' and repeated it three several times.
This reproof made the people so ashamed, that they mostly took to their houses,
and got out of sight; and the more grown up people retiring, the rest soon left us,
and went off likewise.
I heard, when I was at this place some years after,
that the people had never offered the like disturbance again to Friends,
either in their meetings or in the streets.`"

From Glasgow he went into Ireland, and paid a very general visit to Friends there.
At Dublin, he says,--"`I met with our ancient and honorable friend William Edmundson,
whom I had a great desire to see, having a deep and reverent value for him.`"
He thus concludes the account of this journey:--"`With the love of my friends,
and a humble and thankful heart before the Lord of all true help,
I took leave of Friends at Cork, and went over to Minehead, in Somersetshire,
having something remaining towards a few places thereaway, and about Bristol;
and from hence came pretty directly home again,
with reverent awe towards the ever blessed helper.`"

In the following year he was engaged on religious
service in the eastern and midland counties,
also in the city of London.

A concern had for a long time attended his mind to pay a religious
visit to Friends in the several provinces of North America;
and, with the unity and approbation of his friends, he and his companion,
William Armistead, who was under a similar concern, embarked at London,
in the second month, 1706, and at the end of ten weeks arrived safely in Maryland.

After travelling diligently through those parts
of America where Friends were then settled,
they proceeded to the West Indies, and had religious service in Barbadoes, Antigua,
and Jamaica:
in the latter island there were at that time four meetings of Friends mostly kept up.
Amongst the Friends of these meetings, and the inhabitants generally,
they were engaged for about three months, and then embarked for England,
where they were favored to land in safety, in the first month, 1708.

Previously to this visit to America, he had become acquainted with Margaret Hough,
the daughter of Thomas and Ellen Hough, of Sutton, in Cheshire;
of a family in good esteem,
and Friends rightly concerned for the support and maintenance of the principles of truth.
She was herself at times engaged in the ministry,
and was greatly beloved and esteemed for her piety and worth.
The following letter, addressed to her during his absence,
presents a beautiful expression of affection proceeding from the surest source,
and based upon the safest foundation--a true love and unity in the fear of God.

[.embedded-content-document.letter]
--

[.letter-heading]
John Fothergill to Margaret Hough.

[.signed-section-context-open]
3rd of Twelfth month, 1706.

[.salutation]
My near friend,

Having you often fresh in my remembrance, in a near and tender manner,
for the truth`'s sake,
which brought our spirits into a degree of nearness many years since, which never yet,
I believe, has altogether worn away,
I have in my mind to give you a few lines with the salutation of inward love,
which sometimes has comfortably spread over my heart
when thinking of you since I left my native shore;
with increased well-wishing for you,
and the aboundings of immortal virtue in your tender, often bowed heart,
which I often think has more secret distress and
besetment to grapple with than many are aware of,
yet this I am satisfied of, that love and care from above are extended towards you.
Lean steadfastly upon that arm which has been with you, and has fed you,
and led you afresh to springs of water, sometimes when they have been almost hid.
Dear Margaret, methinks I feel it has been something after this manner with you,
yet the Lord`'s tender regard has been, and is towards you:
my spirit is sweetened in its reachings forth to you at this time,
as at many others these many years,
at times and seasons when we have been far absent in body.
I desire a place in your remembrance when it is well with you,
I am in an exercising country, yet have no cause to repine,
because that engaging life which brought me here, fails not,
but often makes the weak strong;
and I have yet some hopes to see my native land and near friends again,
though I fear not so soon as I hoped for,
but must leave it to the great and worthy Disposer.
And, dear friend, my heart says to you, lean carefully upon the truth, the virtue of it,
and it will keep your mind and spirit in dominion over the clogging,
loading things of this world,
and be as a stay to you in times of trial which you meet with in various respects.
I have written larger than I did intend,
because my heart is open towards you in true love,
which in a solid manner runs forth to you in sympathy with you in various straits,
and in the continuance of it does tenderly embrace you,
and remain your near friend and fellow traveller in many besetments.

[.signed-section-signature]
John Fothergill.

--

On the 5th of the third month, 1709,
John Fothergill and Margaret Hough were united in marriage.
They settled at his own house at Carr-End.

In the same year, accompanied by Gilbert Thompson,^
footnote:[Gilbert Thompson resided at Penketh, near Warrington,
where he conducted a boarding school, which, under his care,
and afterwards that of his son Gilbert, maintained, for a long period, a high,
and justly deserved reputation.
He was a man of great use and service in the church,
and in his station as a schoolmaster,
was eminently qualified for the instruction of youth,
being endued with wisdom and skill to govern them by mild and gentle means.
He was prosecuted for keeping a school,
and suffered on this account an imprisonment in Lancaster castle.
His labors in the work of the ministry were useful and edifying,
being pure and unmixed with the enticing words of man`'s wisdom.
He travelled in this work through most parts of Great Britain and Ireland.
He died on the 22nd of Fourth month, 1719, aged sixty-one years.]
the uncle of his wife,
he was engaged in an extensive religious visit
to the western and southern parts of England,
returning by way of London.
With this exception, he remained at and about home for several years,
diligently engaged in the care of his concerns, and of his increasing family;
frequently visiting the meetings in the immediate neighborhood of his residence,
as well as some more distant.

In the year 1719, a very close and affecting dispensation was permitted to befall him.
After a happy union of ten years,
during which he had indeed found in his wife a true help-mate,
a tender sympathizing partaker in his exercises and labors, and a careful,
watchful mother of his children, she was taken from him by death,
soon after the birth of their eighth child.

Of the particulars of this affecting event, and of her character and worth,
an account was drawn up by her husband, of which the following is an abridgment.

Margaret Fothergill was of exemplary piety and prudence, even from her tender years;
and while very young, she not only delighted to attend Friends`' meetings,
but came under a concern of heart that she might
become acquainted with the Lord for herself,
and witness his quickening power and virtue in her own soul;
which concern he was graciously pleased to regard,
and visited her heart with his power and love; and as she grew up,
through the pure influence thereof,
she came to be remarkably clothed with a meek and quiet spirit, and was of a grave,
modest, and exemplary behavior,
and was at times concerned to exhort Friends to a close walking with,
and true dependance upon God, and to beware of an unconcerned mind.

After her marriage she continued in the same watchful state, a true lover of meetings,
and a humble waiter for the arising of the life and truth in them,
wherein alone is ability for the performance of acceptable worship.
Being often very weakly, and having several young children,
she was often unfit to attend meetings,
but would frequently express her care that the affairs
of truth might be conducted to the glory of God,
and was not without hopes of living to have more ability,
and to be more at liberty for these services,
and to discharge herself more fully for righteousness`' sake.
But a few days after the birth of her eighth child,
she expressed her apprehension that she should not recover,
speaking with much resignation and cheerfulness, saying,
"`I wonder that I cannot be troubled at being likely to
leave my little ones and my dear husband.`"
These expressions much affected her husband, and she added,
speaking to him -- "`They will be cared for, you will be helped,
and there is a place prepared for me.
They will not be left under the care of a father, who, like too many in these days,
will neglect their truest interest, but with one, who, knowing from where good comes,
will seek, I trust, with proper care, to the Gracious all-sufficient Helper,
both for himself and for his children.`"

She gave many exhortations to those who came to see her, to prize their time,
and to make a right use of the visitation of God to them;
often reviving what had been a prevalent concern in her mind,
that none should content themselves with a bare going to meetings, or sit down in them,
in a careless, unconcerned frame of mind, but sit as at the Lord`'s footstool,
and wait to hear his gracious words; and said,
she well remembered she had to advise Friends against an unconcerned mind,
and indifferency,
the last time she had any thing to say in meetings before she left her own country.
And, with great weight, further said, "`It is great or absolute mockery,
to go and sit down before the Lord in meetings in a careless manner.`"

After this, though her weakness much prevailed,
yet her strength was renewed in the power of truth, wherein she prayed in a very humble,
fervent manner for the church in general, and for her children,
saying,--"`Let me be bowed down before the Lord,
that the fruit of my body may he enriched with the same favor, love,
and goodness;`" and so continued praising and glorifying God,
in the aboundings of his love and mercy,
much to the tendering of the hearts of those about her.
Though she had a hard struggle with death, yet its sting was taken away:
she patiently continued in humble acknowledgments to the Lord for his goodness and mercy,
and in praises to him, who was, she said, worthy-- worthy of praises for evermore,
as long as her words were intelligible; and so departed in peace,
on the 16th day of the second month, 1719, in the forty-second year of her age.

Thus was her husband deprived of a faithful and affectionate companion,
and her seven surviving children, of whom the eldest was not ten years old,
of a tender and religious parent;
but her strong desires and the secret exercises of her
soul for their preservation and spiritual good,
her tears and her prayers for these,
her "`little ones,`" were not forgotten before God;--
they were seen and remembered by their Father in heaven;
-- His care and protection were extended to them, and in after years,
his love and power mercifully visited their hearts;
in an especial manner was this gracious visitation extended to her son Samuel,
who became an eminent and favored servant of his Lord.
