== Chapter II.

The loss of his beloved wife,
was to John Fothergill a great bereavement and very close trial,
but he submitted with holy resignation to the Divine will, saying,
in answer to a sympathizing friend, "`The Lord gives, and he takes away:
his will be done; he is worthy.
But what if I also must be called from my little ones?`"
Thus alluding to a belief which he then felt, that it would be required of him,
before long, again to visit North America and the West Indies.
The prospect of this religious service was a great trial to him,
as it is recorded that few, or perhaps none, ever exceeded him in tender,
paternal care and affection for his children.
Yet, when he became fully assured that the Lord required this sacrifice,
he gave up freely, saying to his children,
that though he had all the anxious concern of a father for them,
yet he must obey the holy call of the Lord,
who he believed would care for them in his absence.^
footnote:[See an affecting account of this and similar acts of tenderness and care,
related by Samuel Fothergill, during his visit to Ireland, in 1762.]

In entering upon such an engagement, and under his circumstances,
the important duty of committing his children, during his absence,
to the care of relations and suitable persons, obtained his close attention.

He left home in the spring of 1721, with the full unity and approbation of his friends,
and having the company of Lawrence King; they embarked at London,
and arrived safely in York river, Virginia, in the fifth month of that year.

After an extensive visit in America, they proceeded to Barbados, and while there,
John Fothergill wrote an Epistle to Friends of Dover meeting.
New England; and another to the professors of truth in Antigua, Anguilla, Jamaica,
or thereaway.

From Barbados they sailed for England, where they were favored to arrive safely,
in the fourth month, 1724, having been absent three years.
Upon landing, they proceeded to London; and to the yearly meeting, then just commenced,
an account was given by John Fothergill of their travels,
and of the state of Friends in America, of which the following is an abridgment.

"`We first acknowledge, in humble reverence to the Lord Almighty,
that he mercifully favored us with his love and countenance very often upon the sea,
and guarded us thereon from wicked men,
into whose hands some fell who were very near us.`"

"`After a moderate passage we arrived safely in Virginia, and entered upon our service,
and, going towards North Carolina, had many large and open meetings,
both among Friends and others.
In both these provinces we found great willingness in
the people to hear the truth declared,
many of whom appeared tenderly affected.
There seemed to be a comfortable opening among the youth,
and some growth in the elder as to religious care:
Divine mercy still reaches freely towards them,
and in some places there is an increase in righteousness, and truth is in good esteem;
but in others, the love and friendship of the world occasions a decay.`"

"`In Maryland we found great loss, by the decease of many of the elders,
and of the more zealous and concerned Friends;
yet there are in several parts some who are hopeful and religiously disposed;
yet a love of ease and vain liberties has prevailed,
and hindered the work and honor of truth.
There is some openness among several of the neighboring people,
and a gracious extension of Divine love to them,
as well as of a helpful hand in heavenly wisdom towards Friends.`"

"`In Pennsylvania we found an openness in many places,
among people of several professions; some were convinced of, and received,
the truth in the love of it.
There is a large body of religiously minded people among Friends,
who are growing up in a true care for the honor of truth;
yet these are mixed with many earthly-minded, and some loose, libertine people,
who occasion much exercise to the right-minded:
yet the Lord`'s goodness and care is near and over that country,
and his truth prospers in it.`"

"`In the Jerseys, Long Island, and New York Slates,
there are a considerable number of Friends,
and in some places a hopeful openness among other people.
Though vain liberties in some, and too much carelessness and indulgence in others,
have stained or obstructed the progress and dominion of the work and beauty of truth;
yet the visitation of heavenly love is freely extended,
in order to repair and build up in righteousness.
There are some honestly concerned Friends thereaway,
among whom we had a satisfactory labor in the
fresh visitation of Divine power and love.`"

"`In Rhode Island, New England, etc., we had many meetings and close labor,
but on the whole much to our satisfaction.
There is a considerable body of Friends,
and we believe they are increasing in the knowledge of the power of truth,
and in stability in righteousness and faithfulness to it, in those parts.
We had many meetings amongst the neighboring professing people,
especially in the eastern parts, and several, we hope,
were effectually reached by the power of truth,
and received and joined in with it in humility and gladness of heart.`"

"`We labored diligently, through the ability received, in most parts of this country,
and took leave of Friends in solid hope, on account of the Lord`'s work,
and much love and heavenly peace in ourselves, with holy thankfulness to the Lord,
the great helper of all his faithful servants.`"

"`Returning from there to Pennsylvania, etc., we had some comfortable service thereaway,
and Friends were encouraged and strengthened in the Lord.
We sailed from there to South Carolina, and had meetings with the few Friends there,
and among others.
The Lord our God was with us to our comfort and help,
though the generality of the people seemed but cold and indifferent about true religion.
There are but few Friends in these parts,
and but very few who seem to love the truth in uprightness;
yet some there are who do thus love it and remain in the simplicity:
these were very glad of our visit, and we were comforted together in the Lord.`"

"`We sailed next to Barbados, where Friends received us with gladness,
it being long since any Friends from England had visited them.
We had many meetings, both among Friends and others in the island,
which were to the comfort of the living amongst them;
many other people seemed glad of the visit, and behaved soberly and respectfully;
but a loose, lofty, and irreligious spirit has too generally prevailed, and,
to a sorrowful degree, has obstructed the spreading of truth,
and has brought on a decay and diminution of numbers amongst Friends;
yet there are a few, in different parts of the island, who retain their integrity to God,
and love and are concerned for his honor.`"

"`The Lord was pleased to own us with his help and wisdom to divide the word aright,
in warning the unfaithful, and in encouraging and comforting the lovers of truth;
and we were made sensible that the day of love and mercy from
God was yet freely extended to many in that unworthy place.`"

"`And now, feeling clear and easy, we took our leave of Friends in love and peace,
and were favored with a good passage to England.`"

"`To the Lord, the support, the defense,
and the rich rewarder of his people and servants,
in awfulness of soul be ascribed all glory and preeminence,
with fear and praise forever.`"

Soon after the return of John Fothergill from America, and in the same year, 1724,
he was engaged in a religious visit in Ireland,
including several parts of the nation where no Friends resided.
In a letter to a friend he says--"`I have travelled very closely during a month,
with great toil; but satisfied as much as I could wish,
that I was in the Lord`'s counsel and work.
I and three other Friends were seven days and nights,
and had meetings among other people, without coming to a Friend`'s house;
we travelled hard,
having in that time rode near three hundred miles in almost constant rain,
which hurt my health.
However, the glorious name of the Lord was with us and was magnified.`"

During his absence in Ireland, his son William departed this life,
at the age of twelve years.
A peculiar sweetness of temper,
often tendered and encouraged by a sense of Divine regard and heavenly support,
enabled him to bear his painful illness with exemplary patience and resignation.
Many affecting expressions he uttered during his illness,
and various and frequent were the instances of his care and fear, while in health,
not to offend the Almighty,
the sweet influence of whose awful presence seemed often to be near him.

The death of this promising youth,
in whom indications of so much seriousness and solid piety had thus early appeared,
was a great affliction to his father, who was, however, enabled to say,
that--"`being satisfied he was from him, in the counsel and service of the Lord,
he must submit all to the Divine disposal.`"

At the conclusion of a visit,
which about the end of this year he paid to some
of the southern and western counties of England,
he says--"`I returned home with peace and true satisfaction, through the Lord`'s favor,
whose holy and great name had and has the praise, who is worthy to be feared, served,
and magnified forever.`"

[.embedded-content-document.letter]
--

[.letter-heading]
From Joseph Pike to John Fothergill.

[.signed-section-context-open]
Cork, Eighth month 30th, 1725.

In that love which reaches over sea and land, do I at this time salute you,
even in that love which neither time nor distance can ever separate or wear out,
so long as we continue to be,
and keep in the cementing power and life of this heavenly love.
Here it is that we can truly sympathize together, with all the Lord`'s children,
in joy or affliction, especially in those things that relate to the prosperity of Zion,
or the contrary; in rejoicing when it flourishes,
and mourning when we see any thing that mars or stains the beauty of it;
as I can truly say I do with you,
and all those that are heartily and zealously concerned in soul--that
spiritual Jerusalem may become the praise of the whole earth,
and that her beauty may shine to the nations.

But that which has greatly obstructed this, at this day,
has very much proceeded from the lukewarmness, easiness,
or coldness of too many of her watchmen, that should at first have stood in the gap,
and endeavored to make up the breaches that the enemy was making in the walls of Zion.
And in a particular manner by their not standing their ground,
and joining hand in hand together to keep out that floating,
high and proud spirit of undue liberty on the one hand,
and a spirit of worldly mindedness and covetousness on the other.
Here I chiefly mean some of our elders, and, indeed, ministers too, who, some of them,
in time past were zealously concerned to stand as watchmen upon the walls of Zion,
and not only to give warning, but have themselves, for a time,
helped also to keep out the enemy.
But alas, for lack of due watchfulness, and giving ground by little and little,
another spirit has entered them, whereby they have grown indifferent, cold, and lukewarm,
and have in great measure quitted their post, and their companions,
and have left the burden the greater upon their
brethren that could not do the same for truth`'s sake.
And then the load became too heavy for them,
and they could not stop the torrent which the others had let in,
while yet these easy ones stood unconcerned at the sight,
and have let things go as they will for them.
Surely such as these will have a dreadful account to make in the end,
and far more dreadful than such as never knew the truth or the power of it.

The consideration of these things, more or less apparent in most places,
has often wounded my drooping spirit, even to the affecting my poor weak body.
And this great declension is very much owing also to the lack of stretching
the line of justice and judgment in due time upon offenders,
in the way of church discipline, which was left us by our first worthy elders;
and the same spirit that led them to it in the beginning, would lead us to it now,
if we all were truly led by it.
But oh! these easy and careless watchmen will tell us they must not overdrive the flock,
but must persuade and gain the lukewarm by love and softness.
And by their smoothing and daubing with untempered mortar so long,
and keeping off and fending the stroke of
discipline from taking hold of these unruly ones,
either in their families or others, as truth would lead to,
that in the end they have grown so strong and numerous, that they are past persuading,
bending, or ruling, and then, in a stout and sturdy spirit,
they will tell us they will be convinced of this, that, or the other thing,
which the testimony of truth has gone out against, before they will leave it off,
or do otherwise.
And this has been the effect of this lukewarm, indulgent, and smoothing spirit; whereas,
if in the beginning the discipline of truth had been strictly kept to,
I verily believe it had been quite otherwise than it is
at this day in most of the churches of Christ.

And, indeed, in the seeing and hearing the examples of these lukewarm elders,
even for many years past, when I was able to travel,
I have made the application to myself,
with earnest desires in my soul that it might never be my own case,
but that the Lord in his mercy would keep and preserve me to the end,
from that spirit which had prevailed upon many that I far esteemed above myself,
and who had run well for a season, and for a long season too,
and also were very zealous for the testimony of truth in all its branches, and yet,
for lack of due watchfulness, had not continued zealous to the end.
For we right well know that it is holding out to the end that crowns all,
and gives us an everlasting inheritance in the kingdom of God.
And it will be our own fault if we attain not to it, for the Lord has done his part;
he has given us a measure and gift of his Holy Spirit, that will lead us to it,
by which we may be preserved to the end.

But if, for lack of inward watchfulness, we neglect or go from it,
then the adversary gets ground, we are led astray by this enemy of souls,
and at last miss the crown.
And, therefore, it was that our blessed Lord,
knowing the aptness of our natures to frailty, says to his own beloved disciples,
watch and pray always, lest you enter into temptation.
This was our first parent Adam`'s case, though created in innocency;
for lack of watchfulness,
notwithstanding the Lord had given him sufficient power to keep his command,
yet by not obeying it, he therefore fell; and likewise,
it was for lack of due watchfulness that many very
great and good men of his posterity did miss their way,
and displeased the Lord, as great Moses, Aaron, David, Solomon, and others,
and all for lack of watchfulness, and keeping close to the Lord their guide.
And if we descend even to our own times, how many great, bright,
and largely-gifted men have greatly missed their way, and others totally fallen,
and all for lack of keeping close to this inward
guide of the Lord`'s holy light and Spirit.
And since we have so many and great examples,
we may draw from them this warning to ourselves,
to take diligent heed to our own standing, and keep upon our watch at all times,
lest at any time the enemy prevail upon our weak sides.
But, dear friend, I don`'t write any of these things for your information, who knows them,
as well or better than myself, nor yet that I have any ground or cause of fear of you,
but in the flowings of the love of God in my soul, as they came into my mind,
in order that it may contribute to our mutual love to one another,
and stir up our pure minds by way of remembrance.

I received your very kind and acceptable letter from your own habitation;
giving an account, with other things, you left this nation pretty cheerful and easy,
which was a comfort to me after so long a time and labor spent therein,
which I have often thought of with endeared love,
in that you left your outward concerns to freely spend your time in the Lord`'s service,
which I know was great in this nation,
and the more so in your continuance therein so long.
And though nothing that the best of men can do is meritorious,
yet surely the Lord will reward you,
and all those that labor and spend their time in his vineyard.
And to this I may add, in freedom,
that if it stood consistent with the Lord`'s divine Providence,
I should rejoice to hear your lot was likely to
be cast in this nation for the service of truth,
for we really need help here, though, as to my own part,
considering my age and great infirmity of body,
I cannot expect to live to see the benefit of it.

I find our dear friend H. Jackson is married, and I hope to a suitable companion,
and with it that the good hand of Providence has gone along with him therein;
for I truly love him, and desire his welfare every way.
Give him and his wife my dear love, and to all those who inquire for me,
both known and unknown to me, who truly love the Lord Jesus,
with whom I have fellowship in the holy seed of life, all the world over,
more especially those that are zealous for his name.

[.signed-section-closing]
I remain your truly loving and affectionate friend and brother,

[.signed-section-signature]
Joseph Pike.

--

In the year 1726, having accomplished the several services then required of him,
and finding himself at liberty to attend more to his temporal concerns,
he began again to keep house; he collected his children around him,
and industriously applied himself to the care of his family and business;
yet careful diligently to attend meetings for worship and discipline,
both those at home and some more distant, as he felt himself engaged,
and frequently the yearly meeting in London.
Services quite compatible with a due attention to outward engagements,
in business where a right exercise of mind is maintained;
thus fulfilling the injunction to be "`fervent in spirit, diligent in business,
serving the Lord.`"

In 1727 he was married to Elizabeth Buck, of Netherdale, a Friend of a grave,
becoming deportment, and of suitable age.
They lived together in harmony and affection during the remainder of his life,
she surviving him about a year.

Feeling an engagement to pay a religious visit
to Wales and some other parts towards the south,
he left home in the second month, 1732, and proceeded through Cheshire to Bala,
where at this time was held the yearly meeting for Wales;
"`and great was the concourse of people, who, in general, behaved civilly,
and were very attentive to the testimony of truth,
which was livingly declared by many Friends in the several services of that meeting.`"

After travelling through Wales, he proceeded to Bristol,
where their yearly meeting was begun, and he says,
"`it pleased the Lord of all our mercies, eminently to own and help his people,
greatly to our comfort and the exaltation of his own testimony,
which seemed to make impression on many hearts,
and the glorious name of the Lord our God was magnified.`"

From Bristol he went through Gloucestershire, Wiltshire, and to London,
and after attending the yearly meeting, returned home.
Near the close of this year, Thomas Fothergill, his second son, died,
in the twenty-second year of his age;
of whom his father has been frequently heard to say, that he never once displeased him.
And thus, as he had feared God and honored his parents from his youth upwards,
so he felt the approach of death without terror, and departed in innocency and peace.
It is recorded of him,
that so manifest was the religious awe and godly fear that was upon him,
both in meetings and in his general conduct,
as often to impress others with a sense of it, and to excite some,
who were less regardful of their duty, to more diligence.

In the following year he was again engaged in an extensive religious
visit to several of the southern and western counties of England,
having the company of Benjamin Bartlett.^
footnote:[Benjamin Bartlett lived at Bradford, Yorkshire, and died there,
Twelfth month 21st, 1759, aged eighty-two.]
From Bristol they went into Devonshire and Cornwall,
and returned through several of the midland counties.
From Port Isaac he wrote the following letter:

[.embedded-content-document.letter]
--

[.letter-heading]
From John Fothergill to +++_________+++.

"`My health is sustained mercifully,
and holy help afforded to live and labor in the service for which I am drawn hereaway,
in a manner which occasions reverent bowing of soul before the Lord,
and revives my faith in his name, who has, as it is his due, the praise of all:
and though it is a time of great lowness hereaway,
respecting that dominion which Christ should have in the hearts of his people;
yet the Father`'s love in mercy often strongly runs, and in part prevails,
to the comfort and joy of the truly inward; and the searching, piercing labor, at times,
makes some impression, giving to hope that it will not be quite in vain.
However, the arm of the Lord is working, and helps the truly honest,
whereof we have a share of rejoicing in him,
and holy thankfulness for his humbling help from day to day;
and my heart is deeply reverent at this time, in mentioning Divine mercy herein.
We have been through one side of Somersetshire, most of Devon, and at the Land`'s End,
in this county;
we expect it will be near three weeks before we get through Somersetshire,
from which we propose to go homewards pretty readily.`"

[.signed-section-signature]
John Fothergill.

--

For a considerable time after his return from this visit, he remained at and near home;
and during this period, as well as at many other times,
he was often engaged in writing letters to his children and others,
as well as to some meetings of Friends,
earnestly exhorting them to mind the day of their visitation,
and humbly and steadily to seek the Lord and his truth.
The following are some of the letters written about this time.

[.embedded-content-document.letter]
--

[.letter-heading]
John Fothergill to his Son John.

"`And some tastes +++[+++thus]
afforded you in the Father`'s good will, he will not neglect,
though he suffers a plunging into sorrow and doubt of getting rightly along to attend,
in order to keep best care and pursuit necessarily vigorous,
and secondary things in their places; which is the safety, beauty,
and true riches of men.
For heavenly care leads to a quiet and balanced sort of living and walking here on earth;
a favor and privilege of unspeakable advantage,
and which multitudes deprive themselves of by bending their chief,
and many almost their whole application to seek terrestrials,
and so lack the stay of all stays in needful times.
Thus, near love and care in my heart ceases not to prompt me
to desire and long for your right improvement,
which I am still given renewedly to hope will be granted.`"

"`My true salutation attends you,
under a continued desire that you may often reverently
and duly keep in mind from whom all lasting good comes,
and whose addition to our endeavors gives the valuable improvement;
and that laboring to walk and act in steady regard to and hope in God,
will bring the most holy quiet and serenity of mind at home,
and gain the most truly honorable regard abroad; and, at the same time,
help to walk safely on the sea of glass, to which this world may be well compared:
wherefore, look carefully to truth, and the beauty of its simplicity,
and you will have to behold the reeling, chaffy spirit, and ways of this world,
rather with an eye of scorn than love,
and be thankful that you are in measure already gathered and set above it.
And it will be good to consider also,
that though diligence is a great and necessary thing,
and in seeking the Divine favor the most profitable, because therein is all treasure,
both for time and eternity,
and there is certainly a blessing from God on the truly diligent;
yet it may likewise be necessary to remember,
that "`the race is not always to the swift,`" but patience,
with the exercise of faith in the hidden arm of power,
brings to see great things many ways.
And thus, dear child, may the hand of the God of the living be with you,
and guide you in his counsel, and to his praise:
and this is my earnest longing for you.`"

[.signed-section-signature]
John Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Fothergill to his Son John.

"`Therefore, dear son, as a wise man has exhorted, with all your getting,
get understanding.
I accordingly entreat you to seek principally after
improvement in acquaintance with the sanctifying hand,
and to learn the way and the end of its turning; and also that stillness is required,
when we see that no hand but the Lord`'s can open the way, and bring the longed-for help.
And yet that help and salvation is to be looked for reverently and with hope;
and in so applying on our part, the Lord our gracious God does, and will,
delight to regard, and work so that his arising may fill the soul,
and engage it in present gladness, and strengthened faith in his arm, and renewed trust,
yet to travel on.
And thus his gracious workings bring forth praise and
holy admiration to his great and mighty name,
wherein alone is that salvation, and those riches, that are good for all.`"

"`May the feeling knowledge hereof,
and a humble hope and trust to be guided and balanced by the invisible Holy One,
guard and stay you through the unsettling struggles that may attend you.
For, between the converse and pursuits of the unmortified world,
however polished by human endeavors, and the earthly nature in ourselves;
with the gilded appearance of penetration, comprehensiveness of reasoning and finesse,
of many among the more learned part of mankind, and the little, low,
yet pure and powerful seed, which at times makes itself known indisputably,
yet hides itself again; creatures are liable to dangerous tossings, and good beginnings,
ideas, and desires, of God`'s own begetting, have unhappily miscarried; and,
instead of coming nearer the experience of salvation being as
walls and bulwarks about them in a quiet habitation,
too many, for lack of carefully looking towards the true port, have been gradually,
by one wave after another, carried off to sea again, and shipwrecked in the loose,
unbottomed conceptions and interests of this world.
Wherefore, cleave close, I pray you, to the immoveable rock,
the spiritual appearance of the Father and the Son, in whom is all might,
and all sufficiency; and I fully believe he will be your God, your Saviour,
your Shepherd, to lead and feed you, your Shield, and exceeding great reward.
Amen.`"

[.signed-section-signature]
John Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Fothergill to his Son John.

"`As my mind has been concerned in much affectionate care on your account,
and sometimes a lively hope has affected my soul with comfort,
that you might become a man for God,
and so to walk in his fear that he might be
pleased to manifest his gracious care over you,
so I am under humble and anxious desires,
that you may watch against the pollution of the lying vanities of this corrupting age,
and the spirit of the world;
being well and thoroughly assured the Divine Being requires it at our hands,
and is only well pleased with those who walk uprightly before him,
and are truly afraid of, and, therefore,
steadily strive against leaning to any thoughts or
practices which are contrary to the Divine mind,
either in greater or lesser matters;
and they have the easiest work of it who are the most duly resolute in early time,
and firmly stand and walk according to understanding; whereas, bending a little here,
and a little there, for which excuses will be ready at hand,
but of the evil one`'s preparing,
and yielding and leaning aside always weakens and enslaves,
and renders that dwarfish which the Lord of all power would make strong, healthy,
and sound, and able to walk in his way with alacrity.`"

[.signed-section-signature]
John Fothergill.

--
