== Chapter III.

During this interval of comparative cessation from the more extended services in which,
as a minister of the gospel, John Fothergill had so often been engaged,
an exercise of mind which he had felt for some years,
once more to visit the churches in America, was matured,
and at the close of the year 1735,
being clear that the proper time was come for the
performance of this important and arduous engagement,
he made preparation for it, being then in the sixtieth year of his age,
and left his wife and family in the second month, 1736, proceeding towards London,
"`having,`" he says, "`many good meetings,
in the sense of the love and power of truth among Friends, in many places.`"

"`After some weeks`' stay with Friends in London, in the labor of the gospel,
under the merciful assistance of the power and love of God,
my spirit being clear and at liberty, and a ship being ready,
I went on board a vessel bound for Philadelphia.
We sailed the next day, and arrived there safe and well on the 6th of the sixth month,
having an easy, good passage, and more especially so,
because of the favor of the lively sense of the Divine presence being often renewed,
under which my soul humbly worshipped God, who is worthy forever.`"

At the time that he embarked on this his third and last visit to America,
he had five children remaining, who will be briefly mentioned here,
before proceeding with the account of his son Samuel,
whose life and labors form the more immediate object of this work.

Alexander, his eldest son, at this time twenty-six years of age,
was married and settled at Carr-End, which his father had relinquished to him.
He had afterwards a numerous family,
and continued to reside upon the family estate until his death in 1788,
when it was inherited by his son William Fothergill,
who also lived at Carr-End until his decease, in 1837,
when the property descended to his children.

John, the second surviving son, was born in 1712.
After leaving school, he was placed as an apprentice at Bradford, with Benjamin Bartlett,
a Friend and surgeon there.
He afterwards prosecuted the study of medicine at Edinburgh, where, in 1736,
he took the degree of M. D. He then passed some time at Leyden,
and other places on the continent, and settled in London.
Here he became justly distinguished for eminence in his profession,
and as a zealous promoter of science and natural history,
as well for his extensive benevolence and philanthropy,
and for his great use and service as a member of the Society of Friends.

Joseph, the next son, born in 1713, married Hannah Kelsall, of Warrington, where,
at the time of his father`'s departure for America, he was settled in business,
and where he continued to reside, respected and beloved, until his decease,
which took place in 1761, in the forty-eighth year of his age,
leaving one son and six daughters, some of them of tender age,
to lament their great loss, their mother having died a few years before.

Ann Fothergill, the only daughter of her parents, was born in 1718.
She was never married, but continued with her father until his decease;
she then passed a few years in the family of her brother Joseph, at Warrington.
In 1760, she removed to London, to reside with her brother John,
and with him she remained, his constant companion, friend, and helper, until his decease,
in 1780.
She survived him many years, continuing to reside in London, esteemed and beloved;
and in 1802, closed a long life of usefulness and benevolence,
being in the eighty-fifth year of her age, and was the last survivor of the family.

Samuel Fothergill, the sixth son of John and Margaret Fothergill, was born at Carr-End,
on the 9th of ninth month, 1715, O. S. He was very little more than three years old,
when the death of his mother deprived him of her tender care.
Of his early youth but little is now known.
He and his brother John were at school together at Briggflats, near Sedbergh;
and he also passed some time at Sutton, in Cheshire, the residence of his maternal uncle,
Thomas Hough, to whom, with others of his relations and friends,
John Fothergill committed the care of his children, during his second visit to America,
and when absent on other religious services.
Of this charge a large share devolved upon Thomas Hough,
who was well qualified for the trust, and discharged it faithfully.
In particular, the care and education of John and Joseph had devolved much upon him,
and through his means their brother Samuel was placed apprentice, as a shopkeeper,
with Henry Ardern, a Friend at Stockport.

Samuel Fothergill was at this time about seventeen years of age;
he was endowed with considerable talents; he had a strong mind, and was of an active,
lively, and even volatile disposition.
These qualities caused his company to be much sought after,
and early introduced him into society at Stockport,
of an injurious and hurtful character,
calculated to dissipate and eradicate those lessons of piety and virtue which his
worthy father had earnestly labored to impress upon the minds of all his children.

Yielding to the temptations to which he was thus exposed,
Samuel gave way to the indulgence of his evil passions, and, with his new companions,
abandoned himself to the pursuit of folly and dissipation.
This downward path he continued for some time, and the state into which it brought him,
as afterwards described by himself,
and the view which he subsequently took of his condition at this time,
is striking and affecting:--"`I wandered far from the garden enclosed,
and laid myself open to the enemy of my soul: I kept the worst company,
and subjected myself to almost every temptation,
broke through the fence of the sacred enclosure, and trampled it under my feet; and when,
for a time, I found the least inclination to do good, evil was present with me,
and I went on from one degree of iniquity to another.
My wickedness so far increased with my diligence, that at length, alas!
I beheld the strong wall broken down, the garden wall destroyed,
the mound left defenseless,
and no hope left of returning peace to my afflicted soul!`" "`I strayed to that degree,
that my life became a burden to me, and I wished that I had never been born.`"

The downward course which he thus pursued was not, however of long duration,
nor was he utterly cast off nor forsaken, even in the midst of this sinful career.
Many were the strivings of the Spirit of Truth with his soul,
and frequent the visitations of Divine grace.
He says--"`He who had kindled breathings in my soul after Him, would +++[+++even then]
sometimes break in upon me.`"
And again;--"`Though I had drunk up iniquity as an ox drinks up water,
although I had exceeded all others in sin, and had long done despite to him,
yet there was mercy with him that he might be feared.`"

Yet did he continue for a time to resist these offers of mercy,
and to turn aside from the visitations of Divine regard,
thus graciously continued to him;
and many were the deep trials and conflicts through which he passed,
alternately yielding and resisting,
until at length his spiritual state and his danger were very forcibly brought before him,
attended by a deep persuasion that these offers of mercy would be no more renewed,
and that if he now any longer resisted, the day of his visitation would be over,
and his destruction certain and inevitable.
So powerful was this impression, that it brought him into great trouble and distress,
and caused renewed and very earnest prayers for help and strength;
he cried mightily for deliverance, and says: "`My lips quivered, and my belly trembled,
that my soul might rest in the day of trouble.`"

This help and this strength were mercifully granted,
and he was enabled to maintain his ground: he was now twenty years of age,
and the altered circumstances in which he was placed were
favorable to the progress of repentance and conversion:
he was removed from Stockport,
and had found a shelter and a home in the family of his brother Joseph at Warrington;
here, and in the house of his uncle Thomas Hough, at Sutton,
he had many seasons of retirement, peculiarly favorable to the present state of his mind.

The intended departure of his father for America, and their parting interview,
were also conducive to his help.

Deeply afflicting to John Fothergill was the past conduct of his son Samuel:
the evil of his ways, and his grievous departure from those paths of truth and virtue,
in which he had, by long example and often inculcated precept,
endeavored to train all his children, caused him much sorrow and distress.
He was now about to embark for a distant land,
in the service and cause of his Lord and Master,
and the conviction that he was leaving behind him a beloved son,
for whose restoration and welfare he had often put up his prayers,
and yet who had so deeply revolted from the law of God,
was as the wormwood and the gall--bitter indeed to his soul.
Memorable and affecting was their last interview;
after once more imparting to his son deep and impressive counsel,
he took his leave in these words:--"`And now, son Samuel,
farewell!--farewell,--and unless it be as a changed man,
I cannot say that I have any wish ever to see you again.`"

These parting expressions, this powerful appeal from a father whom,
notwithstanding his disobedience, he still tenderly loved,
uttered during what might probably be the last time they should meet in this life,
together with the awful solemnity and deep feeling with which they were accompanied,
produced a strong impression upon Samuel Fothergill;
they remained as if engraven upon his heart,
and assisted to confirm and strengthen him in the path
of repentance and conversion upon which he had entered,
and which, happily for him, he now experienced to be permanent.

Thus, yielding to the powerful convictions of Divine grace,
and as the Spirit that convinces of sin, of righteousness, and of judgment,
wrought in his heart, he came to feel the terrors of the Lord for sin,
and was made willing to abide under his righteous judgment, because he had sinned,
and so was brought into a state of deep repentance;
and as a brand plucked out of the burning, and as one awakened from the sleep of death,
in due time, he witnessed a deliverance from the bondage of corruption,
and a being created anew unto holiness, the end whereof is eternal life,
through Jesus Christ our Lord.

Of the many conflicts and baptisms through which he passed during this work,
or of the advancement which he was enabled to make towards
that thorough establishment and settlement in the truth,
which he was favored afterwards so eminently to experience,
no distinct or separate account is now to be found:
such a record from his own pen would have been interesting and deeply instructive.
Yet there is ground to believe that after a time his progress was rapid and steady.

In his correspondence he was sometimes led to speak of his state,
and of the dealings of the Lord with his soul, as some of the following letters show;
they also contain proofs of the rejoicing which his return and
conversion produced in the minds of his friends,
mingled with excellent counsel and earnest solicitude for his stability and preservation.

Among those who thus extended towards him this care, was Susanna Croudson,
of Warrington; she was an acceptable minister in the Society,
of which they both were members.
She was some years older than himself, and by her religious experience, and the care,
advice, and judicious encouragement, which were early and frequently extended,
she was made peculiarly helpful to him.
He found in her a friend to whom he could unburden his mind of a portion of its distress,
and from whose sympathy and advice he often found relief, and with whom,
as he advanced in his spiritual path, he often took sweet counsel.

Some of his feelings under the change which had been wrought in him
were communicated to his friends in the following letter.

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to The Monthly Meeting

[.salutation]
Dear friends,

It has lain heavy upon me for some time to write
a few lines to you upon the following subject.

The Lord Jesus Christ, in his everlasting kindness, that has long strove with my soul,
has been pleased to unstop my deaf ear, that I might hear him, the Shepherd of his flock,
and to open my blind eyes, and let me see my state as it really was,
very desperate and very lamentable;
he has shown me the dreadful precipice I was at the brink of,
and breathed into me the breath of life, in order that I might arise from the dead,
and live: he has set my sins in order before me,
and shown me how far I had estranged myself from him,
raising strong desires in me to return to him, the Redeemer of my soul;
the consideration of which has raised in my
heart a just abhorrence of my former practices,
that induces me to make this public declaration of them,
which I desire to do in a few words.

I know my sins are so many, and so obvious to every one,
that it is impossible and needless to recount and remark upon them,
for I was then in the bond of iniquity,
though it has pleased the Father of mercies to
bring me since into the very gall of bitterness,
and into anxiety of soul inexpressible, yes,
not to be apprehended by any but those who have trod the same path,
and drunk of the same cup; yet, blessed be the name of God,
he who has kindled breathings in my soul after him, would sometimes break in upon me,
and though the waves of Jordan have gone over my head, his supporting arm was underneath,
that I should not be discouraged.
He, in his infinite love,
has given me to understand that the things which belong
to my peace were not utterly hid from my eyes;
that though I had drunk up iniquity as an ox drinks up
water---although I had exceeded all others in sin,
had long done despite to him, yet there was mercy with him that he might be feared.

Now would I address myself to the youth among you.
In a certain sense of the Divine extendings of that
love wherewith he has loved us do I salute you,
with sincere desires that that God which visited
our fathers while aliens and strangers to him,
may be our God, that we may embrace the day of our visitation,
and not turn our backs upon so great a mercy as he, I am sensible, is daily extending.
Oh!
I have tasted of his love; I have had to celebrate his name;
and though unfit for the work, I cannot be easy, nor discharge my known duty,
without entreating you to forsake the vanities of the world;
for the end thereof is unavoidable sorrow, and endless torment;
but happy are they who give timely application in earnestly seeking the Lord, who will,
I speak from blessed experience,
be found of those who earnestly and diligently seek him, for he has appeared to me,
when I was afraid I was forgot, as a morning without clouds,
to my exceeding great encouragement and consolation,
and strengthened me in my resolution to follow him who has done so much for my soul.

Bear with me yet a little, for I write not my own words;
that blessed Saviour has laid it upon me,
who is willing that all should be saved and come unto him.
Let him, I entreat you, have his perfect work in you; he will wash you,
or else you have no share in him.
I can truly say, that during the time of my first conviction,
my lips quivered and my belly trembled, that my soul might rest in the day of trouble.
I choose not to write this,
but I cannot be easy unless I call others to the like enjoyment.
In bowels of tender love to you do I again salute you, and take my leave of you,
with strong desires that you who are advanced in years, and favored in the Lord,
may remember me, when it is well with you; and that I may be preserved,
though beset with many temptations on every hand.
The Lord in mercy be near you, says my soul.
Farewell.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
William Longmire^
footnote:[The letters of William Longmire are dated at Kendal,
but I believe he afterwards lived at Sheepscar, near Leeds, and died there, first month,
26, 1763. G+++.+++ C.]
to Samuel Fothergill.

[.signed-section-context-open]
Kendal, 1736.

Your very acceptable letter came safe to hand,
and I am truly glad to find the happy remains of that holy visitation,
which I was very sensible, when with you, was fully extended unto you.
It was no small satisfaction to perceive the son of so worthy
a father brought to the baptism of the Holy Spirit,
though by your own will and actions far unworthy of such a favor,
as also many more have been.
And as I fully hope that you have long before this sorrowfully seen into the follies,
and wild extravagant ways of your youth,
and bitterly mourned over him whom you have pierced, so, I earnestly beseech you,
keep it often in your remembrance, frequently retire alone,
and let it become still your delight to meditate on the law of your God.
Seek always to arm yourself with the weapons of the Christian warfare,
which still are absolutely necessary to your preservation in the way of truth,
and your complete conquest over all the force of the enemy:
and O! think not that the work is already done;
since you have been favored with the glorious
day of our God to break forth and dawn upon you,
to open your understanding, to influence your will, and rectify your judgment,
and fill your whole soul with his precious goodness, he has made your mountain strong,
and the whole train of Christian graces have appeared
in their own amiable beauty and proportions,
and willingly attended; the enemy became baffled, and fell to a cessation of arms.

I am very sensible this is the respite that often the first gracious and
humbling visitation of the Holy Being affords to his favored children,
to give them a full opportunity to view their
own vile defilements and irregular passions,
and the purity, truth and harmony of religion,
with all its attractive qualities and perfections,
and that the soul may be filled with an abhorrence of the one,
and the pleasing prospect and delight of the other.

Thus as babes are we attended, taken by the hand, and gently led along; but after all,
it is expected that we grow in strength,
and in the more manly exercises of the soul than our infant state will admit of, and may,
perhaps,
be tried again and again with those very temptations which have formerly presented;
and who knows but they may a little harden upon our hands,
as we become more capable to determine our actions in favor of the Christian religion,
and a truly sober and virtuous life.
Enemies without may assail, and barrenness and poverty of soul within.

Then, oh! then, dear friend, patience, hope, and faith call in to your assistance,
and in the resignation be pressingly earnest with your God to lift up
his Spirit as a standard in your heart against the enemy,
and freely let him arise, and then shall the tempter,
and all his pernicious means that he may make use of, flee before you, but yet,
if this should not be in your own wish and time, pray fall not to murmuring and despair;
let the first of these before named virtues have her perfect work.

Dear friend, I heartily wish your preservation and prosperity in the blessed truth,
a joy to your parent, a comfort to your brothers, and a blessing to society.

[.signed-section-closing]
I am, dear Samuel, your sincerely affectionate friend,

[.signed-section-signature]
William Longmire.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Doctor Fothergill to Susanna Croudson.

[.signed-section-context-open]
London, Twelfth month, 1736.

I find by experience, that town or country is alike to me;
I am weak in the one as well as in the other, when I leave the good hand,
or it leaves me to stumble and suffer for offenses.
I find that when a degree of that power surrounds me, nothing is too strong for me,
I conquer all; but, alas! how few, how seldom are these seasons!
This, however, I find, that if we do stagger, our enemy very often gives us a push;
and if we fall, he mostly tramples upon us and covers us with mire and dirt, while,
perhaps, we think we are thrust down by another power.
The time, perhaps, will come, it is our part to wait with patience till it does come,
that we may be environed and folded with Divine love.

Dear friend, remember that whatever can stir up the pure mind in us will be of advantage.

[.signed-section-signature]
John Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to John Routh.^
footnote:[John Routh resided at Manchester; he was an elder,
and for many years an active and useful member of society.
He died first month 31st, 1791, aged seventy-six.]

[.signed-section-context-open]
11th of Twelfth month, 1736-7.

I write to you as to one who is regarded by the Almighty, and who has,
by regarding that visitation which I too long slighted,
been preserved from the snares and temptations of the enemy, and has,
though young in years, attained to a good stature in the truth; which,
oh! that it may be my chief care to press after, to seek for above all, is at present,
and I hope will continue to be, the earnest intent of my heart;
and though I find it my place often to be brought low and very poor, as it is at present,
yet I desire to wait my appointed time, until he please to dispel those darksome clouds,
which at times bring me yet near to a melancholy, drooping state.

But I desire to be entirely resigned to his will; that he may, if he please,
again and again turn his hand upon me, until he has purged away all my dross,
and made me what best pleases him, and not myself or others.
But the Lord, who has done wonderful things for my deliverance,
has mercifully regarded and reached unto me,
while in a state of open defiance to his tenderly striving spirit.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to his Sister.

[.signed-section-context-open]
Warrington, Second month 9th, 1737.

I could have been glad to have written a few lines to you,
but considering the distance my past behavior had justly
placed me at in respect to my friends`' and relations`' favor,
I was somewhat doubtful of its kind reception.
But, dear sister,
I have found it is the lack of inward peace that is
more grievous than the lack of my friends`' favor,
though that be very desirable.
I found, upon examining my state, that I was upon the very brink of destruction and ruin,
and it pleased the Lord to kindle in my soul earnest
desires to be delivered from my dreadful condition,
which the Lord in mercy showed to me as it really was,
thereby bringing me into deep and unutterable anxiety of soul,
that I often was ready to conclude my transgressions
were more and greater than any one`'s else,
and my state worse than any ever were in before.
O! the anguish of that day;
the weight of sorrow I daily labored under was more than I can express, or any,
not acquainted with the operation of the Spirit of judgment and of burning, can conceive.

It is like repeating an idle story to any that are unacquainted with it,
but I have a different opinion of you, and you have, I hope,
known a degree of the heart-cleansing power of truth,
though you have been preserved from those pollutions that
hinder us from being properly acquainted with the Almighty,
and finding thereby love and solid peace.
But through infinite mercy I can now say, with a humbly thankful heart,
it was a repentance never to be repented of;
for notwithstanding my open rebellion and defiance to
the tenderly striving Spirit of grace,
that long strove with me in order for my recovery, I have in a degree,
witnessed favor from the Almighty, and the knowledge of acceptance with him,
which is more to me than any thing else.

Great is my reason to be humbly thankful for his many mercies,
which my soul desires never to be unmindful of, but,
by a yet more humble walking and closer seeking after him,
seek to redeem my former misspent and lost time, by redoubling my diligence;
and with humble thankfulness press after him to
find my peace yet more and more confirmed,
now the Lord has given me to know they are not yet hid from my eyes,
but yet may be in a greater degree attained upon
my humble resignation to his divine will,
and proper and frequent application to him for the farther discoveries of it,
and strength to perform it acceptably to him.
Many yet continue to be the deep and humbling times I go through;
many the anxieties of soul I have to pass under;
yet the Lord in mercy is at times helping me over
everything that would hinder my spiritual progress,
and giving to find times of refreshment in his divine presence.
O! that it may be our care, dear sister, to seek properly after him,
in order to find renewing of strength and acquaintance with him,
that we may thereby witness strength to withstand the
enemy of our souls in all his attempts.
May it continue to be my care above all things,
in true thankfulness to wait for his appearance,
though it may be at times as a refiner with fire, and as a purifier of silver.
May we allow him to work effectually in our hearts;
great will be our satisfaction thereby to witness that the Lord`'s regard is to us,
and his love is near to us.
I cannot with too great earnestness recommend
this to both our consideration and practice,
as one knowing the judgment of the Lord for sin,
and by his help a learning to forsake it, and following him in the ways of his requiring;
this brings a true and lasting peace.
May I seek after him again and again, and enter into covenant with him;
if he will but indeed be with me in my way, and direct me aright,
I will fully follow him.
So marvelous and wonderful is the goodness of God to my soul,
I cannot sufficiently admire it, nor too often repeat it,
for I am as a monument of that mercy that would have none lost,
but that all should come to the saving knowledge of himself.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Alice Routh^
footnote:[Alice Routh was born at Hawes, in 1704;
she early received a gift in the ministry, in which she continued during a long life,
and died at Hawes, in the fifth month, 1791, aged eighty-seven.
A minister more than sixty years.]
to Samuel Fothergill.

[.signed-section-context-open]
Hawes, Third month 1st, 1737.

It was not because I feared your not holding out to the end, made me write as I did,
but it was in order to encourage you in your journey through this vale of tears;
for I am sensible of the many deep plungings that those meet with,
that have set their faces towards Zion.
Oh, I have thought sometimes I was quite forsaken, and even left to myself; yet,
it has pleased him in these times of affliction to appear again,
with healing virtue in his hand.

Dear friend, it is my earnest desire that you may be preserved to the end,
for it was that same arm that turned you which turned Saul,
when he was going to persecute the church.
I wish that it may have the same effect on you as it had on Saul,
for he reasoned not with flesh and blood, but was obedient to him that called.
I would not have you go into reasonings; for the enemy of our souls,
when he cannot lead into those things which we have been prone to,
then begins another way; that is, to bring us to despair of ever overcoming our enemies,
because they are so numerous.
But it was his arm that turned Saul, which brought salvation,
and can overturn all our enemies, and bring deliverance to his afflicted seed;
for they are as the apple of his eye; and although he may withhold his face for a time,
it is in order to try our love to him, and to see whether we love him above all or not,
for he will not admit of any rivals, but will have the whole heart or none.
So unto the Lord do I commend you, together with my own soul,
who is the sure rock to flee unto.

[.signed-section-closing]
I remain your sincere friend,

[.signed-section-signature]
Alice Routh.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Routh to Samuel Fothergill.

[.signed-section-context-open]
Manchester, Second month 12th, 1737.

+++.+++.+++.+++And, as the operation of the power of truth is given way unto in our hearts,
it will work out everything that is of a contrary nature;
that so we may become fit tabernacles for him, the Holy One, to dwell in, which,
that it may be our chiefest care to press after,
is many times the earnest breathing of my soul, notwithstanding the many buffetings,
and hard exercises that fall to my lot: for the adversary, at times,
strongly suggests the need I have of a more eager
pursuit after the lawful things of this life;
but I find that except the management of things temporal be kept in its proper place,
we shall lose ground as to religion, and our appetite after Divine consolation will fail.
Oh, that this may never be our case,
but that we may still breathe to the Almighty for
strength to undergo whatever we may be proved with,
in the course of our sojourning here.
When I have considered how some who have known the work of truth,
and have been in a great degree cleansed and enlightened, yet, for lack of watchfulness,
darkness has come over them again; this has many times bowed me very low,
in strong desires that I might always keep in a
sense of my own nothingness and insufficiency;
and as we keep here,
I am not without hope that he who was appointed to open the prison doors,
will in time set us at liberty to serve him in an acceptable manner.

[.signed-section-signature]
John Routh.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Joseph Brown.

[.signed-section-context-open]
Warrington, Third month 9th, 1737.

With renewed satisfaction do I now salute you,
desiring our mutual welfare in the best sense,
that by a close and diligent application we may have at
times to experience a being drawn truly inward,
and near to the Almighty helper and feeder of his people; there, in a secret manner,
to renew our acquaintance with him, and one with another,
in the uniting influences of best
regard; there, surely, dear friend,
stands our communion and nearest fellowship which flows
freely in our hearts one to and for another,
when outwardly far separated.

Your letter was very acceptable to me, and I perused it with a good degree of pleasure,
for I thought it gave me an idea of a mind steadily resolved in the pursuit of virtue,
the only lasting and durable treasure, which truly makes rich,
and brings no sorrow or sting with it.
This we have both, I believe,
frequently experienced to be our help and stay in times of deep and humble walking,
and low goings down, when we have been ready to say no one went so low as we;
that we had a path to tread few besides ever walked in.
Then, my friend,
this inward treasure has been richly manifested for the
support and strengthening us yet to wrestle,
in humble reverence,
if happily we might at last have to say with joy--"`I cried and you heard me, O Lord,
and helped me.`"
This I know is more the concern of a remnant than any thing in the world beside,
for it surely is only his appearance that can bring joy to the earnestly seeking soul.
I was very glad to hear you had so satisfactory an account to give of your journey,
every way, both inwardly and outwardly.
The first being chiefly to be regarded;
the welfare of the inward to be sought for in a diligent and
yet fervent waiting upon the Almighty for further discoveries,
and this will be more and more explained to us.
O, my dear friend, here surely stands our happiness,
in fulfilling and being made conformable to the will of God,
our wills being entirely brought into subjection to the Divine will.
Have not we, dear friend, in our low estate, when troubles came over us,
and exercises been like the waves of the sea,--have we not then been ready to say,
any way for peace, lead me in your own ways, and with your help I will surely follow you?
Let us, dear friend, not by any means fall short of true obedience, than which,
I can by experience assert, there is no other way to peace.
My mind is drawn out in an unexpected manner towards you,
yet with a good degree of hope that the same Eternal Being who first visited our souls,
while in a state of alienation from him, will in a continued merciful regard,
be near for our best help, and enable us to appear, if truly willing and obedient,
in his presence, with acceptance.

Now must I draw towards a conclusion,
with breathings of soul for our growth in the best state,
even to a measure of the fulness of our holy Head,
and that our expectations may be yet more and more upon him.
Then shall we be often engaged to seek him, and in private to retire before him,
the chief Beloved of our souls.
He will appear in these private opportunities,
to our abundant consolation and help over our enemies; which,
that it may be more and more our concern,
is the desire of your real friend in the unchangeable truth.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Routh to Samuel Fothergill.

[.signed-section-context-open]
Manchester, Third month 15th, 1737.

I join with you in real belief that we shall be
helped forward towards the heavenly Canaan,
as we are truly resigned in heart, to be made what the Divine Being would have us to be.
Notwithstanding the many exercises we may meet with, a great share of which,
I am many times ready to conclude, fall to my lot, I fully believe,
as we are concerned to press through the crowd of opposition, if possible,
to touch the hem of his garment,
we shall witness heavenly virtue in the least touch of his love.
If something of this were not witnessed at times,
what would become of us when we are bowed low,
under a sense of our own nothingness and insufficiency,
to step one step forward in that way, that is well pleasing in his sight.
I have often remembered the great strait that Israel of old was in,
when the sea was before, the inaccessible mountains on each hand,
and their old oppressing enemies pursuing hard after them,
from whose force they were altogether unable to defend themselves.
The command then was, stand still, and see the salvation of God: and,
blessed be his name, he is still showing his salvation to his poor afflicted Israel,
as they are ceasing from their own willings, and runnings, and actings,
and depending only upon his providential care.
It is, at present, my sincere desire,
that we may press forward after a close communion with him,
and that our pursuit after the necessaries of this life may be bounded by his will,
which, as we have an eye unto,
I do not doubt that we shall be favored with all that is necessary for food and raiment.

[.signed-section-signature]
John Routh.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Alice Routh to Samuel Fothergill.

[.signed-section-context-open]
Hawes, Fourth month 8th, 1737.

I would not have you discouraged by thinking that you are out of your place;
for if the enemy could not lead you into other things which
would have drawn down the displeasure of your God upon you,
he was not unlikely to put fears in your mind that you did not worship aright;
it is what others have been tossed with;
but praised be the powerful name of the great Being that has
not allowed the devouring enemy to destroy his plants;
his regard is unto the workmanship of his hands,
although we be tempted and tried with deep poverty; it was the lot of our dear Redeemer,
but he overcame the enemy, and as we follow him we shall be made to overcome,
in his due and appointed time.

[.signed-section-signature]
Alice Routh.

--

[.embedded-content-document.letter]
--

[.letter-heading]
William Longmire to Samuel Fothergill.

[.signed-section-context-open]
Kendal, Fifth month 25th, 1737.

[.salutation]
Dear Samuel,

I hope that good hand and power that visited you,
and made you sensible of his will, and of the unfitness of your own,
and gave you power in degree to deny the one and obey the other,
to your great and unspeakable joy,
has not forgotten to be gracious and merciful in the time of need,
but yet vouchsafes to administer of the comforts of his grace and love,
to maintain and prosper you in the heavenly truth.
Let no poverty or barrenness of soul dismay you; no new or unexpected surprise,
as giants in the land,
ever give you reason to call the truth of the visitation and mission in question.
Many are the fears and false reasonings which at times will rush upon the soul,
especially in times of weakness and need.
The imagination is scarcely ever more at work, and more apt to create false images,
than when the Divine object is partly withdrawn.
And if there is not a steady bearing and holding fast our faith,
and a resignation of the whole soul unto God, we shall certainly, in such seasons,
be very apt to suffer loss, and abundantly weaken our own hands,
and give ourselves up into the power of the enemy.
But, dear Samuel, be strong in the Lord, and in the power of his might,
and he will strengthen you yet more, and increase your joy,
and confirm and establish you in his truth.

[.signed-section-signature]
William Longmire.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Joseph Brown to Samuel Fothergill.

[.signed-section-context-open]
Broxbourne, Sixth month 17th, 1737.

I am sensible that there is nothing that unites and brings so
near one to another as the love of the most holy truth;
and, as we abide in it, though we may be far separated in body,
we shall be near in spirit,
and witness that fellowship and holy communion that the worldly-minded are ignorant of.
So I sincerely desire that we may abide here; for, sure I am,
there is no other place of refuge for us poor worms to flee to.
There is a remnant who can experimentally say,
that it has often been an inexpressible satisfaction to them,
that in the Lord there is strength were it not so, they had fainted long ago.

So, dear friend, although many are the trials,
and exercises that those may meet with here,
as they are sincerely engaged to look over all to their unconquered captain,
Christ Jesus,
he will keep them from fear and from falling into the snares of the wicked one.
Oh, that I may keep my eye steadily to him;
that so I may be enabled to follow him in the ways of his leadings and requirings;
for sure I am, there is no other way to obtain true peace with him.

You have been often brought into my mind, with desires for your welfare every way;
but in an especial manner in the most holy truth, which you have,
through the love of our heavenly Father, chosen for your portion;
and I have to believe as you come to be more obedient and freely given up thereto,
the Lord will enlarge your heart, and pour down his heavenly blessings upon your soul,
like the former and the latter rain; and though you may meet with deep trials,
and provings, and reasonings, and, as it were, the valley of the shadow of death,
to pass through at times; yet, as you are engaged, in sincerity of heart,
to look over all and through all to holy Jesus,
he will preserve you from the fear of evil,
and from falling into the snares of the wicked one.
Oh, I think the Lord`'s love is extended towards a young and rising generation,
and if they embrace it, he will be good to them:
and as they are truly resigned and freely given up to his Divine will,
I do believe that he will raise many up from the sheep-fold,
and send them to see how their brethren fare: and not only so,
but will strengthen and encourage them to go against the great Goliath,
that is so much boasting over and defying the armies of the living God;
and though there may be those that despise,
yet the justness of their cause shall answer for them,
like poor David in innocency saying,--"`Is there not a cause?`"

[.signed-section-signature]
Joseph Brown.^
footnote:[Joseph Brown died near Hertford, eighth month 20th, 1748, aged forty-two.]

[.postscript]
====

P+++.+++ S.--I often see your brother John, and his company is very acceptable to me;
his sweet,
innocent carriage and deportment are exemplary to the
youth of that great city where his lot is now cast;
I desire that many may follow his example.

====

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to his Sister.

[.signed-section-context-open]
Warrington, Sixth month 8th, 1737.

The day after I received yours I was visited with the rheumatism,
so that I have not quite, as yet, regained the use of my arms.
I have had a very hard turn as I ever had in my life, for violent pain outwardly,
yet I never was so easy under it,
having often sensibly to enjoy the Divine presence of the Physician of value, who,
blessed be his name, was near to my support,
in encouraging love to draw me nearer and nearer to himself,
where the true and humble followers of Christ find a secure
rest in all their trials and exigencies of every kind.
O, dear sister,
may we be of the number of those who have chosen the Lord for our portion,
and his truth for the lot of our inheritance; then,
whenever we have to engage with sickness, or any other trial,
our peace will spring up and flow like a river;
our hearts will be united in a bond of peace which nothing can disturb,
and which will last beyond the grave, and this makes everything easy,
so that we shall be ready to cry out--Lead me in your ways, O Lord! be near me,
and ready for my help, and I shall not fear the number of my enemies;
if I may be favored with your presence, I shall not be afraid.
The remembrance of the many mercies of the Almighty, extended to my soul,
enlarges my heart,
and raises strong cries that I may be helped to
walk in the way that is well pleasing to him,
in true thankfulness of heart.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Doctor Fothergill to Samuel Fothergill.

[.signed-section-context-open]
London, Seventh month 7th, 1737.

The few lines which you sent me were very acceptable,
as they proceeded from a mind tinctured with good,
and the openings of true fraternal love.
May those dawnings yet shine brighter, may they dispel all darkness,
and kindle that endearing flame, which neither length of time,
nor all the enemy`'s efforts, will ever be able to extinguish.
In a sense of your sufferings and trials, I salute you; stand fast and immoveable;
bear with constancy the enemy`'s assaults;
Heaven will inspire you at length with secret fortitude; your hands will be strengthened;
triumph and conquest will be known; but may we know sufficiently the command--Steady,
steady, to be adhered to.

Through mercy, I am at present well; and though often in darkness and obscurity,
the fruit of repeated acts of disobedience,
yet secret hopes are sometimes revived that I shall see better days; I stagger and reel,
but am yet in some degree upheld.

Dear Joseph Brown is often inquiring after you.
He comes here sometimes, and it is a pleasure to cultivate a friendship with sincerity,
wherever it appears: he is at too great a distance for me to see him often; otherwise,
his ingenuous freedom, his undesigning simplicity and love,
would induce me to pay him frequent visits.
An acquaintance with such as these, when they stand faithful,
are powerful monitors to call us to our duty, and a closer attention to that within.

Of late I am favored with the acquaintance of a friend, who, next to dear T. A.,
has made the most considerable progress heavenward of any that I know,
no, seems to have surpassed him;
the most unheard of oppression,
by those of his own society, has buried him hitherto;
but the Omnipotent now bids him arise, and has arisen with him.
To give you his whole history would require a book.
He has been among Friends, about twelve or thirteen years, in the ministry about ten.
Refined by the severest trials and hardships, his ministry is living, powerful,
and efficacious;
to the most solid piety is joined an extensive
knowledge of the languages and the mathematics,
the product of uncommon industry and application; his appearance is rustic,
but weighty and solid.

[.signed-section-signature]
John Fothergill

--

[.embedded-content-document.letter]
--

[.letter-heading]
Sarah Routh^
footnote:[Sarah Routh, afterwards Sarah Taylor,
was an eminent and deeply exercised minister.
She died at Manchester, eighth month 19th, 1791, aged seventy-four,
a minister fifty-four years.]
to Samuel Fothergill.

[.signed-section-context-open]
Manchester, Eleventh month 15th, 1737.

Your very acceptable letter was a joy and a help to me,
because I am satisfied it flowed as a fresh spring, in degree,
from the one fountain of all fulness and goodness,
to which I beg we may ever be favored with having free access;
and I am encouraged to hope, as we are diligently concerned to keep near,
and follow on after that which has visited, and cleansed,
and in degree made us sensible of drinking, as at the living spring,
we shall know it to flow in a more abundant manner in our hearts,
to the washing away every hurtful thing,
and yet comfort and encourage everything that is good; for, satisfied I am,
the Lord will strip us of nothing,
the keeping whereof would be of any real advantage to us,
except it be for the trial of our faith; and then, if we freely resign all,
the will will be accepted for the deed.

Let us, therefore, dear cousin,
be encouraged to follow steadily on though through the deeps,
and in the greatest denial of self, and most cross to our own wills;
yet so our wills may become subject, and his will may be done in and by us;
but this is a great attainment, and hard for us to get to,
and yet I believe it is attainable.
May we, therefore, press after it more and more; and I can say,
my heart is at times made glad in the remembrance of you,
and I find my spirit united unto you, in true love, at this time;
and in that I dearly salute you, and wish for you, as for myself,
that no storm or cross wind may ever be able to drive us back,
but when we cannot get forward, we may be helped to stand still,
that so we may indeed see the salvation of the Lord,
and may have cause to acknowledge him to be our Saviour and our Redeemer indeed,
and that because he lives we live also; that we may know him in us and we in him,
our life being bound up and bid with Christ in God;
this is the very travail of your real friend and relation,

[.signed-section-signature]
Sarah Routh.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to his Sister.

[.signed-section-context-open]
Warrington, Twelfth month, 16th, 1737-8.

We lately were favored with a letter from dear father, dated Philadelphia,
which was beyond expression acceptable,
(however to me,) as being filled with the most endearing and
tender expressions of an affectionate parent,
whose soul was filled and warmed with Divine love, and in that, longs,
I may even say wrestles, with the God of Heaven for a blessing upon his children,
and in the most moving and pathetic manner labors with us, his offspring,
to follow holiness, and tread the ways of God`'s commandments.
And in the remembrance of this his tender regard,
and likewise some sense of the love of the Almighty Father,
my soul is often drawn into deep reverence before him, craving earnestly for us,
the descendants of one so worthy and truly honorable,
that our desires may be above all things to follow him, even as he follows Christ;
and that, as we behold an eminently supporting hand near and with him, so we,
by a humble, careful walking, may know, according to our measures,
the same power to preserve and uphold us in well doing,
and a steady perseverance to the end, which my soul longs may be our chief care,
since it must be the end which crowns all, and the Lord alone is able to preserve it.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Alice Routh to Samuel Fothergill.

[.signed-section-context-open]
Hawes, Second month 24th, 1738.

Do not think that you are either forgotten of God or of your friends,
for you are near to my life.
O! that we may so steer through this vale of tears, that when time here shall be over,
we may meet in that mansion of glory that is prepared for the righteous;
for many are their exercises and besetments;
they are at times even like the lone sparrow upon the house top,
or the quail in the stubble field.
How are we pursued by the enemy of our souls, so that I have been ready to say--
How can I go any further?
and have said with David--My way is enclosed with hewn stones, that I cannot get out.
O, let us trust in Him who multiplied the widow`'s oil and the little meal in the barrel.
This has done me good,
when I have rightly considered it for it was a
time of favor when the prophet came to her,
and bade her first make him a cake, and then one for herself,
for she thought of eating it and dying.
I would not have you be discouraged, though it may be a low time with you;
that little will keep alive, until the pure rain be distilled again.

[.signed-section-closing]
So in that pure love that I feel to flow to you, I bid you farewell.

[.signed-section-signature]
Alice Routh.

--
