== Chapter IV.

John Fothergill, after landing in Philadelphia, in the sixth month, 1736,
continued diligently engaged in religious service amongst Friends and others in America.

When the intelligence reached him of some reformation in his son Samuel,
and that the change he so earnestly desired, and for which he had often prayed,
was really begun in him, and some progress made towards a religious life,
it filled his heart with gratitude and thankfulness for this his erring son;
yet hope was mingled with fear, and he rejoiced with trembling,
as some of the following letters indicate.

[.embedded-content-document.letter]
--

[.letter-heading]
John Fothergill to +++______+++.

[.signed-section-context-open]
(No date.)

As to son Samuel, I have been almost unexpectedly quiet in my spirit about him, knowing,
however, I had honestly discharged myself to the utmost of my understanding;
yet I have heard from several of an appearance of a religious mind and application,
being hopeful to prevail with him to a reformation,
to the comfort of those that rightly love him; which, to be sure,
is as much desired by me as is necessary, I believe, and affords some comfort to me.
But he has manifested so much instability in good intents, and I do believe resolutions,
and an aptness to show, at some times, which has not either been in reality,
or he has not brought forth fruit agreeable to expectation,
which still induces me to a cautiousness in rejoicing;
though I believe the fan and the axe of truth are well able to
cut down and purge away both sin and hurtful propensities,
and make sound; for which sure experience,
I with the earnestness of a nearly affectionate father to my own flesh,
and entreaty of a sincere friend,
do tenderly long and advise him to a humble and steady waiting for;
that true judgment may be repeated and attended to, and so feel from time to time,
which will bring forth fruits of steady humility and love to inwardness;
and yet I hope Divine good may make him a living monument of mercy,
and of a right returning.
O that this may be his experience and gracious issue, to Heaven`'s glory and his salvation.
Amen, Amen.

I am, in love and care, beyond what I can express, poor son Samuel,
your nearly well-wishing father,

[.signed-section-signature]
John Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Fothergill to his Son Joseph.

[.signed-section-context-open]
Philadelphia, Ninth month 12th, 1737.

[.salutation]
My beloved son Joseph,

I am desirous to manifest my regardful remembrance of
you and your dear wife by a few lines once more,
wherewith reaches near and true love, and strong well-wishing in every respect,
which is very much in my heart for you, and chiefly that in and through,
and above all pursuits,
true godliness and favor with the all-seeing and Almighty pure God may be your chiefest;
and with the most watchful diligence, and which, as you honestly and patiently seek,
you will often be comforted and engaged in heart, in finding Divine regard to your souls,
renewing reverent trust in, and fear before Him, who knows and can do all things,
from whose hand every good gift comes.
And I am often much satisfied that the gracious eye of
this mighty Being has been and is towards you for good,
and to make you of some worth and service in that place; wherefore,
neglect not to seek the love and sense of Divine favor in your own hearts,
and heavenly mercy and sanctifying life will brighten, feed,
and teach you in righteousness.
My love and care is pure and strong towards you, not forgetting poor Samuel,
who should walk as a brand plucked, in unutterable mercy, out of the fire of destruction,
which, if he retain the sense of in heart duly,
every part of his conduct will be adorned with fruit
which will be beautiful in the eyes of God and man,
and be a living monument of the effects of Divine power as it is turned unto.
Oh that thus, immortal help and gracious goodness may prevail with, sanctify,
and bless you, my truly-beloved and nearly cared for children!

Ninth month 14th.--Dear Joseph--This morning yours with others is come to hand,
the contents whereof enliven my hope in the God of all mercies, on your account,
with reviving comfort to my careful soul for your best good; for in my longing for you,
and you and yours in particular,
I have had a sure evidence of Almighty regard and desire to bless,
and help you to serve him;
but am also assured that he requires that you should stand in awe before him,
and seek his face and the feeling of his power, to season, govern, and redeem the mind,
and beautify the conduct;
that he may delight to work for and let forth his love and fatherly goodness to you.
And to be sure, what I hear, of and from Samuel,
is as comfortable as can be expected to an affectionate
and heretofore deeply afflicted father.
Yet, I rejoice not without awe and fear, though with lively hope,
as he keeps duly mindful of his unworthiness,
and under watchful fear lest any thing that is for judgment should escape;
and to be duly assured of God`'s own putting forth from time to time;
which brings to a careful desire after pure stillness in waiting,
and so to heavenly salvation, and clear understanding of the Divine goings forth;
and I hope all-sufficient help will be with you all; so be it, Amen.

[.signed-section-signature]
John Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Fothergill to +++______+++.

[.signed-section-context-open]
Philadelphia, 1737.

Let my heretofore strongly pressed caution,
which I do not yet get clear from at all times,
doubting the danger of its being not enough minded,
which is to be aware of that devilish, bewitching, darkening, ruinous,
enticing snare of often sipping and dabbling with strong drink,
add the company that loves and uses it, and seldom without unprofitable conversation,
though craftily, from that twisting, serpentine, adulterating spirit of this world,
frequently excused and pleaded for, under artful disguises, to deceive the unwary.
Therefore look at it in time, as an enemy to body and mind,
to present and future interest; or else heaven will assuredly turn its back upon you,
and the earth will become as iron,
and the bowels of your true friends will be shut up--and what can follow then?

I lay weight upon it, as I am sure it is an infernal, and as much as Satan can make it,
a hidden snare; yet, I would strongly hope necessity for this may not be much;
but my love and true care is a just excuse for me herein.
May the love of righteousness and best riches win and guide your heart and views,
and the God of all goodness will be your God and sure helper to blessedness indeed.

[.signed-section-signature]
John Fothergill.

--

This visit to America occupied John Fothergill nearly two years.
In the course of it he attended several of the yearly meetings,
and says--"`On the 9th of fourth month, 1737, the yearly meeting began at Portsmouth,
+++[+++Rhode Island,]
and a large precious meeting it was; I returned to Newport,
where the yearly meeting continued, and held four days,
the assembly being large and peaceable,
and at times comfortable in the arisings of the mighty power and love of God,
who had the glory and the praise.`"
"`On the 24th the yearly meeting began at Nantucket, it was large,
and continued four days, to true satisfaction, and the name of the Lord was glorified.`"

[.embedded-content-document.letter]
--

[.letter-heading]
John Fothergill to his Son John.

[.signed-section-context-open]
Philadelphia, Seventh month, 1737.

"`As to myself, I am somewhat miraculously supported, as a creature,
and am in good health pretty generally.
The yearly meeting at this place ended last night;
it was exceedingly large and upon the whole,
generally acknowledged to have been very edifying,
strongly good and helpful various ways,
and very much to my ease and humbling gladness in the Lord our God,
and never-failing helper; and Friends, in general, are in a good degree of harmony.

"`My heart is nearly affected with the best of love towards you and for you,
that nothing short of rain from the Divine presence may satisfy you,
for this is what only prepares the most acceptable sacrifice,
a broken and contrite spirit, wherein is true light and durable joy.
Thus farewell, farewell, says your nearly affectionate father,
to the best of my capacity, in every respect,
which I hope you are and often will be sensible of.`"

[.signed-section-signature]
John Fothergill.

--

Of the conclusion of his labor in America he has left the
following account:--"`I had a blessed meeting with Friends,
at Pilesgrove, and the next day was at a general meeting at Haddonfield,
wherein the Lord our God graciously owned us and blessed our meeting;
giving us to part one from another in a living sense of his love and power;
and his glorious name was worshipped and praised.
I came the day following to Philadelphia,
where I stayed until the 8th of the tenth month,
and had several great and heavenly meetings;
and after a very open and solidly edifying meeting, I took leave of friends there,
in much true love and nearness of spirit, and heavenly unity in the Lord.`"

Soon after this he took passage to Barbadoes,
and from that island he wrote to one of his sons, as follows: --

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Barbadoes, Eleventh month 27th, 1738.

"`I was brought here well, in thirty-two days from Philadelphia,
yet do not find myself free to leave the place, yet write to inform you,
that I am thus far on my way,
and easy in the hope and sense of the Father`'s favor. Probably no other +++[+++vessel]
will sail for England in less than two months, which is somewhat hard for me to think of,
both in respect to the unpleasantness of the place, from the extreme heats,
the small number of Friends, and the general remoteness of the inhabitants from religion.

Though I am easy in resignation to all-wise disposal, and full of thankfulness,
under the bending sense of gracious and strong
extendings of divine good-will to many of the remote;
and of fatherly succouring encouragement to the few spiritually minded here.
May rain from heaven bedew your soul and understanding,
and cherish and revive the Lord`'s heritage everywhere.

[.signed-section-signature]
John Fothergill.

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Barbadoes, Second month 12th, 1738.

"`In the long absence which wisdom has seen good to order, I am, for that reason,
humbly cheerful in reverent hope;
and for the present we must submit to be yet longer separated than I expected I
hope never to forget the merciful nearness and goodness of Truth to me here;
both in affording the renewed sense of heavenly life,
and in preserving my health.--I cannot well add much,
nor is much more in my thoughts at present; but I may say,
that though this is a poor irreligious place, yet both many of the people,
and the few Friends here, are very loving and respectful;
and I hope I shall leave the place with inward ease to myself and reputation to truth.
From your truly loving father,

[.signed-section-signature]
John Fothergill.

--

Having been engaged in the island of Barbadoes for about three months,
he embarked in a vessel bound for Lancaster,
and arrived there on the 1st of the fourth month, 1738.
He thus writes respecting the voyage:
"`We had a passage of six weeks between land and land, through very rough hard weather;
but I was preserved quiet, inwardly easy, and steady in hope.
I am pretty well in health, as well as easy and sweet in spirit;
worship and praise be to the holy author of all good.`"

From Lancaster he proceeded direct to his own habitation in Netherdale, Yorkshire,
where he was joyfully received by his family and friends,
with humble gratitude and reverence to that Divine power which had, through all,
preserved and restored him to his native land.
