== Chapter V.

Having largely witnessed in himself the redeeming power and efficacy of Divine grace,
and known the remission of past sins, and justification by faith,
through our Lord and Saviour Jesus Christ, Samuel Fothergill,
very early after his own remarkable conversion,
felt powerfully called upon to communicate to others
the gracious dealings of the Lord with his soul;
to tell them of his feelings--of what he had so
eminently known of the power and goodness of God,
and to incite them also, to strive after a participation in the same blessed experience.

Under this Divine and powerful impulse,
and having passed through a preparation for the work,
he carne forth in the ministry of the gospel,
exercising the gift he had therein received, in humility and much fear;
but abiding steadfast and faithful, this gift was enlarged;
his growth in the ministry was rapid, and he became an eminent and favored servant.

The precise period at which he first appeared as a minister cannot now be ascertained;
it is said to have been on the same day that his letter
to the monthly meeting was read in that assembly.
There are some circumstances which render it probable that it took
place about the time that he attained the age of twenty-one years,
being near the close of the year 1736.

The present practice of the Society,
of taking into distinct consideration the ministry of those Friends
who feel engaged so to appear in our religious meetings,
was not introduced until several years after this period,
and there is not any minute of Hardshaw monthly
meeting distinctly recording him as a minister.
The first time that his name occurs in the records of that meeting,
is in the fourth month of 1737,
where he appears as a representative from Penketh preparative meeting,
of which Warrington is a branch,
and he was at the same time appointed to attend the quarterly meeting for sufferings,
at Lancaster.

The first occasion upon which a certificate was granted him to travel as a minister,
was in the first month of 1739.
He had, however, some time previously to this, visited a few meetings in Cheshire,
along with his relation, Lawrence Callan, of Sankey.
And about the same time Susanna Croudson had also been engaged, with certificate,
on a religious visit to Friends of Bristol and that neighborhood.
The following letters relate to these engagements.

Susanna Croudson to Samuel Fothergill.

Worcester, Sixth month 16th, 1737.

I have felt the weight of the burden to be very heavy upon me, and none to help,
but the Great Master in his own time.
I have been left to see my own poverty and weakness,
and have often looked back at my coming out; yes,
I have often desired in secret to know whether I should go forward or turn back,
being willing to do any thing, so that I might but be in my place,
however foolish I might appear in the sight of men.

Remember me when it is well with you, for I have need of the help of my friends.

Susanna Croudson.

[.asterism]
'''

Susanna Croudson to Samuel Fothergill.

Bristol, Sixth month 27th, 1737.

Yours was very acceptable, and came in a needful time, when I was very low;
yet I have got a little faith and strength since I last wrote to you,
and something of inward peace of mind, and a sight of my duty,
and a sweet belief that I am in my place, which is enough,
and makes my journey as a home to me.
I believe you had faith for me, when I had none for myself;
but I believe I am not alone in this,
for many in this day bear weights and burdens because of the careless and lukewarm;
and I believe it is good for us all to see our weakness sometimes,
that we may know that we have no might of our own, and may be willing to seek for help,
that we do not grow lukewarm.

Susanna Croudson.

[.asterism]
'''

Susanna Croudson to Samuel Fothergill.

Warrington, 1738.

You are often in my thoughts, yet not with any heaviness,
though I was much so when I parted with you; yet as soon as you were gone,
a secret satisfaction was raised in my mind that you were in your place,
and better than if you were at home; and the same still remains with me,
which pretty much makes up the loss of your company.

Now, my dear friend, however weak you may seem to yourself, or whatever troublesome,
discouraging thoughts may present themselves before you,
do your endeavor to look over them all to your present business,
for I believe you are in your place, and am in hopes you will get to the same faith;
though I know many are the discouragements that fall in the way of poor travellers,
yet I believe you will be helped through, and have the return of peace.
I speak in a feeling sense of the renewed goodness near to the relief
of the poor and helpless that have no might of their own;
my heart is filled with sympathizing encouragement towards you,
more than I can write at this time.

Susanna Croudson.

[.asterism]
'''

Samuel Fothergill to Susanna Croudson.

Middlewich, 1738.

Your letter was not only pleasing, but very encouraging and helpful,
and came in a needful time,
for the burden of the work seems to be still more and more weighty,
and myself poor and weak;
yet as I am carefully concerned to wait for the renewings of help and strength,
I sometimes experience a gladness and satisfaction of mind that I am come out,
and have made this small visit thus far, and I cannot say,
(notwithstanding I am often very low and heavy,) that I have
occasion to reflect on my leaving home in the least degree.

You are a frequent companion of my thoughts,
yet the nearest enjoyment of each other is to be known in the life,
in the drawings of our souls towards God, and in a secret access to his Divine presence.
Oh, I have found great occasion for frequent inwardness and retired
breathing earnestly after the Filler of the hearts of his people:
my heart is open towards you in the nearest and tenderest of affections,
and therefore lets my pen run thus.
Cousin Lawrence Callan came yesterday, and we think to be at Nantwich tomorrow.

Samuel Fothergill.

[.asterism]
'''

Samuel Fothergill to Susanna Croudson.

Chester, Third month 2nd, 1738.

Through mercy I am well as to my health,
and my mind quiet and easy in a confirmed sense that I am in the discharge of my duty,
which greatly helps and encourages,
in hopes that he who has made me willing to leave home, in obedience to his call,
will support me to answer his requirings.
I am not doubting his helping hand,
knowing that he never requires anything from his
children but he enables them to its performance.
Peter Leadbeater went with me to Wrexham on first-day,
when we had a satisfactory meeting: there are a very few Friends,
but pretty many that are not of our name--a religious, quiet people,

Samuel Fothergill.

From this correspondence it will be seen that the friendship
between Samuel Fothergill and Susanna Croudson still continued.
It had its origin in the sympathy she manifested for him,
and the care with which she watched over and encouraged in him the
early symptoms of his repentance and desires after a religious life;
their mutual friendship grew with the growth of these feelings in his mind;
it was matured into a near and tender regard for each other,
and on the 1st of the sixth month, 1738, they were united in marriage.

She was the daughter of William and Mary Croudson, of Warrington, Friends of good repute,
and well esteemed.

The union thus formed, based upon the surest foundation, proved a happy one.
They lived together in true harmony and religious fellowship,
being helpers to each other in their various religious exercises and engagements;
she cheerfully setting him at liberty,
and encouraging him in the many services to which he was so frequently called.

The following letters may be suitably introduced in this place.

John Fothergill to his Son Samuel.

"`Netherdale, Eighth month 1st, J738.

I am glad to hear of your health, and also of +++[+++your]
hope to live: the latter I doubt not, either with respect to here or hereafter,
if honest, steady regard, in due attention for best succour and light,
be but kept to with patience and content to be little;
if but renewed in life and in merciful access,
and in due remembrance of the child's state, and your station is but such comparatively;
always keeping a care distinctly to discern between what would seek something to self,
and that which only seeks to know and to do the
Heavenly Father's will for his glory only.
Oh, that we all may purely mind this!

I have little to add further,
but am earnest and tender in true longing for your right thriving and
preservation in the way of wisdom in every respect,
and salute you both in a sense of best love: your truly loving and careful Father,

John Fothergill.

[.asterism]
'''

Doctor Fothergill to his Sister.

London, Eighth month 20th, 1738.

A few days ago I was plunged very low; a view of my present situation,
and the disagreeable prospect of my future circumstances,
were so heavy that I knew not how to bear them; however, they have, by degrees, abated,
and now I am not sorry it was so.
O, may my dependence be increased, may every scheme be destroyed,
if its consequence should be to take off my
regard from the Sovereign dispenser of all good.
May the assistance afforded be deeply impressed on our minds,
in such a manner as to produce thankful reverence and gratitude,
only to be ended with our existence.

I was last night at a large meeting which is held here quarterly,
under the name of the Young Folks' Evening Meeting.
I was pleased to see a very numerous appearance
of very promising young Friends of both sexes;
several testimonies were delivered by some that have lately appeared in public:
they seemed to be influenced with love and zeal;
and it afforded satisfaction to me when I considered that it was
possible some of these young heroes might one day stand as bulwarks
against the general corruption and degeneracy among us,
in the places of their deceased worthy elders and fathers.
They had to tell us that better days were coming, that mercy was afresh extended,
that Zion yet should shine more brightly.
O, thrice happy those who live so near the centre of peace, as to be ready,
when the alarm is given, to follow wherever the standard is fixed.
I have sent you a copy or two of Anthony Purver's verses,
and a little book lately published by John Fry;^
footnote:[Of Sutton Benffer, Wilts.]
the poetry is low, but the maxims deserve regard.

I can only now desire this for you and myself,
that our dear father's example and precepts may insinuate
themselves into our minds so far as to influence us to act,
to speak, and even to think,
as it becomes persons favored in such an extraordinary manner.
Dear sister, cease not to strive, though discouragements may too much prevail:
may happiness attend you.
Farewell.

John Fothergill.

[.asterism]
'''

Peter Leadbeater^
footnote:[ Peter Leadbeater was a minister, and well esteemed in his day.
He is spoken of as being "`serviceable in his tender and seasonable advice;
and also being of a good capacity, and clear understanding,
helpful in the management of the discipline of the Church, an encourager of the youth,
to draw them into service in the Society.`"
He died at Chester, on the 13th of seventh month, 1751, aged fifty eight;
a minister about forty three years.]
to Samuel Fothergill.

Chester, Eleventh month 18th, 1738.

I may say you are daily and almost hourly in my remembrance since we parted,
with ardent desires that we may be preserved faithful in
answering the end of our vocation whereunto we are called,
that the hope thereof may not be in vain; therefore,
let us daily eye Him who has called us unto holiness,
and will perfect the same to his praise and our everlasting comfort,
if we keep under the guidance.
of his Holy Spirit; which as we co-operate with it,
will complete our sanctification throughout, in body and soul, and spirit.
My soul is often deeply bowed under a sense of my own weakness and inability,
and am ready to fear lest one day or other I should fall by the hand of my soul's enemy,
who is not lacking to use his utmost endeavors, if possible, to lay waste and destroy,
by his subtle devices, that work which God in his infinite mercy has begun;
may he be frustrated in every attempt, is what I earnestly pray for.
Oh! dear heart, when you are divinely favored,
let me not be wholly out of your remembrance; as we keep near the Lord,
we shall be near and dear one to another in him,
and be as epistles written in one another's hearts,
sympathizing in one another's adversity,
as well as partaking of each other's joy in prosperity.
I was often truly thankful, since the last meeting we had,
that my head was borne up above the waters of
affliction which were ready to pass over the same;
may the same arm of power still be underneath,
to support unto the end through whatever I may yet have to pass,
in which I will put my confidence.
O, Lord, let me never be confounded.
Your truly sorrowful and afflicted brother and companion, Peter Leadbeater.

Doctor Fothergill to Samuel Fothergill.

London, Twelfth month 21st, 1738.

I had an entire satisfaction in reading yours,
though I do not overlook a passage in this, as well as some others of yours,
which insinuates that I expect rhetorical flourishes, and brilliant expressions,
but it is not so.
I love sincerity in the plainest dress; I dislike affectation of any kind, when I see it,
whether in myself or others; and when, in writing to one another or speaking,
we join words together with an intention of concealing our real sentiments,
or to give an idea of ourselves which we are not, we forsake the plain language indeed;
if this happens to have been the case in those which I have written,
I acknowledge myself guilty of using a manner of speech
which the Spirit of truth has declared against,
and for the future will attempt to forsake and amend.

Your affectionate concern for my welfare was doubly grateful;
I wish I could give you the like satisfaction,
by returning such an answer as I know would be acceptable, but alas, I cannot;
none but myself knows what I feel.
I sometimes resolve with myself to abandon all my designs,
and endeavor to live to none but my Creator; and presently,
my condition in this life appears in my view,
and that part which regards only the present, too often prevails,
and here I waste and decline.
I see it, I feel it, yet I almost despair of ever being able to resolve on amendment.
You know these bitter scenes, but have had courage enough to give up,
and become nothing for his sake.
I every day see the happy consequences of such a conduct,
but video meliora proboque deteriora sequor +++[+++That is:
I see the better way and approve it, but I follow the worse way]. Here is my condition,
without disguise; it is easy to say more, but you know by this the rest;
but what can be said to a person, who is conscious how much it would be his interest,
his eternal interest, how much it would rejoice the heart of the tenderest of fathers,
to see a progress made in the internal life,
how much it would also rejoice his relations, his friends,
and all the good of his acquaintance, yet is cowardly enough to give up to the tempter.
I often reproach myself,
I can suffer it in some measure and at some
times from others knowing how much I deserve it.
I am not solicitous of hiding my case from those, who,
knowing the weakness of human nature,
can pity the failures and lament the unhappy condition of the person.

The anxious pressure I feel, perhaps, makes my expressions not guarded;
I write to a brother whose assistance I am far from rejecting;
let me hear from you as soon as you have freedom.

John Fothergill.

Soon after the return of John Fothergill from his last visit to America,
he went to the Quarterly Meeting at York, which was large,
and attended by many Friends from different parts of the nation.
His company was very acceptable; and the occasion was, in a peculiar degree,
solemn and instructive.

Here he met his son Samuel.
Tradition has handed down (and there is no other record
of it) a remarkable circumstance connected with this,
their first interview, since the return of the father to England.
It is said that, from some accidental circumstance,
John Fothergill did not arrive in York until the morning of the day of the meeting,
and that it was late when he entered the meeting-house:
after a short period of silence he stood up, and appeared in testimony;
but after he had proceeded a short time, he stopped,
and informed the meeting that his way was closed;
that what he had before him was taken away, and was, he believed, given to another.
He resumed his seat, and another Friend immediately rose, and taking up the subject,
enlarged upon it in a weighty and impressive testimony, delivered with great power.
It is added,
that at the close of the meeting John Fothergill inquired who the
Friend was that had been so remarkably engaged amongst them,
and was informed that it was his own son Samuel.

Their thus meeting together,
under circumstances so different to those in which
their last memorable interview had taken place,
previous to John Fothergill's departure from England,
was peculiarly moving and affecting to them both.
The son then in a state of rebellion and alienation
from good -- now become "`changed`" indeed,
and a fellow-laborer with his father in the ministry of the gospel,
powerfully advocating and enforcing those great and solemn
truths he had formerly neglected and trodden down,
and engaged earnestly to beseech others to become as he was, reconciled unto God.

The good old man received his son as one restored from the spiritually dead,
and wept and rejoiced over him with no common joy.^
footnote:[Several different versions of this meeting
between John Fothergill and his son are extant,
and I have thought it best not to omit it.
The account here given, I believe to be the most correct.-- G. C.]
Some time after this interview, John Fothergill was again at York,
and proceeded on a religious visit to Friends in Norfolk, Suffolk, Essex,
and the city of London.
Here he remained several weeks, visiting the various meetings in and about the city,
much to the help and encouragement of many, and faithfully discharging his own duty.
On his return home he had several large meetings, which, though attended with deep labor,
were to some advantage, and accompanied with holy help, as he humbly acknowledged.

Early in the year 1739,
his son Samuel communicated to the Monthly Meeting--"`his
intention of visiting Friends in Wales,
Bristol, and some other parts, and requesting our certificate,
to signify our unity therewith; the same is now granted him, signed by several Friends.`"
In returning from this service, he paid a visit to his brother in London.

Soon afterwards, Susanna Fothergill and Sarah Routh,
(afterwards Sarah Taylor,) of Manchester, paid a visit to "`Friends in Westmoreland,
Cumberland, and some parts of Yorkshire.`"

Several of the following letters relate to these engagements.

Peter Leadbeater to Samuel Fothergill.

Chester, 1739.

I am truly glad, in humble thankfulness to the God and Father of all our mercies,
to hear of your health and welfare every way, which I pray may be continued,
not only through this journey,
but during the whole of your pilgrimage through this world:
strong are my desires that the Lord Almighty may go along with you,
and make your journey prosperous and satisfactory to yourself,
and serviceable to his church and people where your lot may be cast.

Oh, dear heart! eye the great and good Guide, and neither run too hastily,
nor yet stay behind, but mind the putting forth of the Divine hand;
and as you follows its direction, you will yet feel the sweet incomes of Divine peace,
and the love of God, to fill your soul more and more,
to the making of your cup to overflow,
in which praises and thanksgiving will be returned to God, the Father,
the author and fountain of all goodness, for ever.

I am, and always was, fully satisfied that the Great Master,
who calls and sends forth his servants into his work and service,
will never leave those who truly depend on him, and have no dependence upon themselves;
though they may have often to go down into the deeps on account of the true seed,
which lies very low in many places, and is oppressed, as a cart with sheaves, yet God,
in his own time, will raise it into dominion,
and they who suffer with it shall reign with it in glory.
Be not discouraged, though you may meet with a variety of spirits to encounter;
He that was with his stripling David, will be with you, and direct the stone to the mark;
be valiant for his name and truth, in a faithful testimony,
bearing it against all false liberty,
which has crept in amongst the professors of truth up and down in this nation.

As you discharges your duty faithfully in God's sight, as made known unto you,
I doubt not but you will return in great peace,
and we shall again have to drink of the pure water of life, clear as crystal,
which proceeds from under the throne of God and the Lamb.
Oh, may our souls often thirst after it,
and never be satisfied with any thing short of it!
If it were not for God's mercy in opening the fresh springs thereof at times,
surely we had fainted long ago;
but it is matter of encouragement to find that God has
not forgotten to be gracious and merciful,
at times beyond what we are capable of expressing in words,
or are in the least worthy of;
but in inexpressible mercy and goodness He takes
delight in nursing up his babes and children,
as a tender father;
may we always learn in true obedience to his Divine will in all things,
in doing which we shall be his disciples indeed.

Love, boundless love, from Him who is love altogether: in this I salute you,
and am your sincere friend and brother,

Peter Leadbeater.

[.asterism]
'''

Samuel Fothergill to his Wife.

Carmarthen, First month 26th, 1739.

I am, through continued mercy, very well in health,
and in a good degree helped inwardly by the renewings of Divine help and regard,
which encourage to renewed waiting upon the divine Opener.
Here are but few Friends, but these are generally a living, tender people,
and such as are waiting for Divine consolation.
I have had several heavenly opportunities amongst them;
that have given me great reason to believe I am in my place,
notwithstanding deep and plunging seasons fall to our lot.
We have a perfect harmony between us, and that is one great help.

Believing myself in the way of my duty makes me more easy that
the Everlasting Preserver will remember us in merciful regard,
and will give us again to be sensible of his Divine favor together.

Samuel Fothergill.

[.asterism]
'''

Samuel Fothergill to his Wife.

Bristol, Second month 20th, 1739.

I have now been nearly two weeks by myself,
in respect of the company of Gharrett Van Hassen;
but have at times been favored with the Divine
company of our Great High Priest and Minister.
Meetings in this county--Gloucestershire--are small, and mostly hard in the general,
though there be a few really living in the particular.

I many times have to go very low in them, and discouragement is ready to creep in,
and sometimes ready to send me home again; but now and then goodness breaks forth,
as the sun in its brightness, and dispels all these dark fogs.
Remember me; but we never shall nor can forget one another,
as we keep in mind where it was we contracted a
near oneness and acquaintance one with another;
your remembrance is near and dear to my soul--next to the spouse, the lamb's wife,
nothing stands in competition with you.

Samuel Fothergill.

[.asterism]
'''

Dr. Fothergill to Susanna Fothergill.

London, Third month 24th, 1739.

Perhaps this may come to your hands sooner than brother gets home; if so,
it may not be unpleasant to hear that we parted at Oxford on third-day last.

I have been much pleased with his conduct, as well as his company, since he came to town;
you may be sure that my affection for him led me to observe him carefully,
and I can only say, upon the whole, that I, as well as we all,
have fresh occasion to be thankful that Providence has placed you together.

I take notice, with pleasure, of an increase in solidity and prudent behavior,
since I last saw him at Warrington;
and I doubt not but his affection will engage him to
regard whatever you shall think he ought to do;
for I cannot but believe that his quick and steady progress has been, and yet will be,
greatly promoted by your watchful, affectionate concern for him.
Gratitude, dear sister, calls for affection in return, for restoring us a brother,
and in part making him what he is.
The sensible part of Friends here have unity with him; the rest, who applaud or condemn,
as mere fancy leads them, are not to be hearkened to.

John Fothergill.

[.asterism]
'''

Samuel Fothergill to his Wife.

Warrington, Fifth month 18th, 1739.

Your very acceptable letter is come to hand.
I can sympathize nearly with you and your companion in this engagement and labor,
having been bowed in spirit for you, in a sense of the exercise you are attended with;
but oh! let it not sink you too low, that many are upon the beds of ease in a profession,
and the work goes on heavily: strong is he who is on your side,
and abundantly gracious to his poor travailing seed and children,
whose hearts are made sad, and not upon their own account,
but because the love of others is declined, and few spirits unite and join,
as shoulder to shoulder, to carry on the work; but it is heavier upon a little remnant.

But the Levites must enter Jordan, in this gospel day, before the rest of the people,
and must abide there until the rest be got over;
therefore think it not a light thing to be bearing the ark of the covenant
before the people but be humbly concerned to go forward in faithfulness,
and the Lord, who said in the beginning, "`Let there be light,
and there was light,`" will separate and disperse the clouds, and cause light to shine,
and in the fulness thereof,
you will know a walking with great peace and joy before you return.

Nothing, my dearest, would be more satisfactory to me than to enjoy your company;
nevertheless, I would not stint you in respect of time--take your own time,
and fully make yourself easy before you return, that the answer of peace may attend you.

Samuel Fothergill.

[.asterism]
'''

John Fothergill to his Son Samuel.

Leeds, Seventh month 8th, 1739.

Dear Samuel, Be assured,
I think both carefully and affectionately often of you and yours;
yet I more praise that gracious power,
which has shown such mercy to us in raising you as from death,
and is mercifully pleased to regard you amongst his children, for your own salvation,
and, I hope, others' good, than too much rejoice in creaturely esteem;
though I am reverently glad of you,
and have some comfortable hope that the Everlasting
Father will help you to remember his mercy to you,
so wisely, and with steady fear and care,
that he may be pleased to continue his regard to, and help you,
in his fatherly goodness and living law, to live, every way, to his praise;
and then it will be in a renewed sense of self-nothingness,
and that He must do all that is truly well done, both in, by, and for us,
and must have all the glory; so be it, says my spirit, for ever and ever.

My salutation is truly affectionate and loving to you all,
my dear and loving sons and daughters,
hoping as well as desiring all your health and comfort.

John Fothergill.

[.asterism]
'''

Doctor Fothergill to his Brother Samuel.

London, Seventh month 15th, 1739.

I received your acceptable letter along with dear father's,
both which came very seasonably-- I was wanting to hear from you both.
I wonder not at the tenderness you expresses in yours; while he was here,
my heart was filled with thankfulness, not only for such a parent,
but also that I could see some marks of that treasure of goodness,
which it has pleased Divine love to place and treasure up in his soul.
The wisdom of his conduct, his uprightness and humility, often affect me,
and make me wish, "`Oh, si ut alter ab illo?
Well, let us incite each other to a more close regard to that
power which can make us in some degree like him;
we shall then perform the duty we owe to each other;
and may Divine goodness make us instrumental to each
other's advancement in the way to perfection,
by often inclining our hearts to stir up the pure mind in each other.
You are nearer the bright day than I am--you can act more regularly, as having more light.
I wish to possess my soul in patience, and follow after the footsteps of the holy flock.

John Fothergill.

Early in the year 1740,
Samuel Fothergill was engaged with a certificate in a religious visit,
in the north of Yorkshire and Durham.
While on this journey, he met, at Lancaster, with James Gough, of Ireland,
in whose journal the circumstance is thus
mentioned -- "`Here I met with Samuel Fothergill,
then young in the ministry, but even then appearing with that solemnity, brightness,
and gospel authority, as gave Friends lively hopes of his proving, as he did,
through the successive stages of his life, a bright and shining light;
a vessel of honor indeed; of eminent service in the church of Christ.
The public service of the quarterly meeting fell to the share of us who were young,
though many weighty, experienced ministers were present; and,
our good Master being with us, it proved a refreshing, satisfactory,
and edifying meeting.`"

Samuel Fothergill to his Wife.

James Wilson's, near Sedbergh, Third month 21st, 1740.

Well, dearest, let us be easy in separation,
and truly given up to the disposal of the great Master;
and I hope he will bring me home in peace, when this parting must give way to, I hope,
a joyful meeting.

Things here afford a melancholy prospect,
in respect to that life and greenness I expected to have found,
though I am favored with a very agreeable companion this week,
but I fear I cannot have his company forward.
It is Amos Robinson, father's late companion to London.
We have had meetings appointed for every day, except seventh-day.
I hope, after first-day, to pass away pretty quickly towards Durham,
but cannot as yet see when I may set my face towards home.
Oh! that I may be enabled, though in much weakness, to get onwards,
so as to discharge my duty;
that low times of much great need may not be renewed oftener than times of strength.
But these meetings are suffering, bowing times.
A strange deadness prevails.
On first-day last, had a pretty good helpful opportunity at a general meeting;
but it is soon lost by the succession of hard, dry seasons.
Thus have I abruptly hinted at my case one way.
Yet I trust in the great Helper and Deliverer of his people from under oppressions.
As to my body it is through mercy very well.

Samuel Fothergill.

[.asterism]
'''

Samuel Fothergill to his Wife.

Carr-End, Third month 25th, 1740.

I am through mercy very well in health, and pretty easy and quiet in mind,
in a good degree of a sense of being in my place in this journey thus far.
I heartily wish I may so watch as to experience renewedly the
manifestations of the Divine will in respect to my duty,
and suitable help to the performance thereof in an agreeable manner,
to the honor of the Great Master, the edification of the church,
and the peace of my own soul.

Well, my dearest, remember me when it is well with you, for I find a prospect of hard,
dull, heavy work; the seed is oppressed in many,
and the well of life is oppressed with rubbish;
though here and there are fellow-laborers,
joined in heart and soul for the advancement of the glorious name;
a remnant of such I met with yesterday,
which helped me out of a very low place--a place of
great need--and in some good degree renewed my strength.

My love flows strongly towards you--that love that absence does not diminish,
nor separation lessen Samuel Fothergill.

[.asterism]
'''

Samuel Fothergill to his Wife.

Malton, Fourth month 20th, 1740.

After a fatiguing week, I now find a little opportunity to write to you.
I have had meetings at Newcastle, Shields, Sunderland, Shotton, Stockton, Yarum, Yatton,
(Ayton,) from which over the moors to Whitby, where, on first-day,
had two large and powerful meetings among that high exalted people;
but renowned be the name of the ever excellent Being, his eternal power was over all,
to the breaking some rocky, adamantine hearts,
and to the comforting of the true travellers.
Next day I was at Castleton, which is Luke Cock's meeting.
I spent an hour with that emblem of innocence, and in the afternoon rode ten miles,
to the house where the ark rests, i. e., John Richardson's,
who went with me next day to Pickering, and I went back with him to his home.

On the following day was at Kirby meeting,
which is the meeting to which that man of God belongs.
It was a very heavenly season.

Oh! let it be for ever remembered by all that partook of the benefit of it.
The good man said they had always good meetings, but this was a very extraordinary one.
The life of truth arose wonderfully, and that Father in Israel, John Richardson,
took me home, where we sat up until almost daylight.
We then repaired to our respective lodgings;
but soon after five in the morning he came and sat by my bedside, and,
though weak and very poorly, would accompany me ten miles to this place,
and have here parted in mutual tenderness.

My soul admires the goodness of God.
His words are faithful, just, and true,
helping through depressing and trying times in many places; but the best are reserved,
to recover my drooping, wounded soul;
blessing and honor be to him who lives and reigns for ever and ever.

Samuel Fothergill.

In this year, (1740,) John Fothergill, though under much bodily weakness,
attended the yearly meeting in London, wherein, at the desire of his brethren,
he gave a concise but instructive account of his late visit to America,
the state of Friends, the increase of the Society in some places,
and its declining state in others,
with the causes which had most obviously contributed to produce this.
He observed, that as the elders of the people were preserved in freshness and zeal,
under a diligent care for the growth of spiritual religion, truth increased,
good order was preserved, the discipline kept up, and the youth, in many places,
tender and hopeful.
On the contrary, where tho.se who were of the first rank,
both in respect to age and situation in life, declined in their religious care;
where the spirit of this world suppressed the
tender desires after riches of a durable nature;
there, weakness, disorder, and unfaithfulness were too obvious,
and a daily decay of real piety, as well as of numbers, prevailed,
to the grief of the honest-hearted,
and the loss of those who unhappily allowed this corrupting spirit to take place.
He pointed out, in a clear manner, some parts where these effects appeared,
and the deep sorrow which attended him when amongst
those whose conduct occasioned these consequences.

In the latter part of the year 1741,
he visited Friends in several of the northern counties.
The following letters were written about the time of these engagements.

John Fothergill to his Son John.

Ninth month 27th, 1740.

I have been, and am, through merciful favor, preserved in usual health,
and attended with best peace and comfort in our heavenly Father's goodness,
though in the manifest appearance, as I have often looked at it many months, of a severe,
threatening time of distress, in various cases, to this nation;
and if we be not quickened and excited hereby to diligence,
in seeking to lay hold of eternal treasure, the love and favor of the blessed,
infinite Rock and Fountain of all good,
we shall be more inexcusable than others of mankind,
who know not so well and clearly where and how to seek happiness and refuge indeed;
which I often inwardly long and breathe in spirit we may lay suitably to heart.
But after this little hint of what is much with me,
I shall take notice of some of your remarks on
your late journey into Holland and Germany,
and first tell you, your account of those people called Mennonists, and Moravians,
as I suppose they call themselves,
exactly agrees with my secret and settled idea of them; for I believe both,
and the latter especially, have had, in some measure, their eyes opened,
but they set man to work, to form and imitate religion, and to build,
without digging properly to find the Rock; yet many, from their pious intentions,
make a show for a time, and some good may turn out of it:
but it is a matter to be lamented, as I have very often thought, that there should be,
as it were, a universal and continued propensity prevailing,
amongst the Germans especially, to run away with speculation,
and thereby so many valuable springings and glimpses of the heavenly
day should have yet brought forth or produced no more durable fruits,
in experiencing salvation in reality.
But it ever will be true, no following Christ acceptably,
without submitting to the cross,
which has always seemed to me to be the place at which that country-people in particular,
as almost all nations in general, have miscarried.
May the plough of God take more effectual hold amongst them, is my heart's desire.
And may this consideration strengthen you in fearing, and even loathing,
a sort of living and delighting, or being at ease, in barren speculation,
even upon best things or principles;
but be still more and more animated to seek daily bread
from the everlasting Father's own hand,
who will hear and answer in due time the sincere and patient, though hidden cries for it;
and thereby such will grow in the living Root, and bear fruit in due season,
to the Father's praise and honor.

But above all,
my longing is for your spiritual access and enlargement in the heavenly pastures,
under the leading and putting forth of the one heavenly Shepherd, which I still hope,
as well as often humbly breathe for, on your account,
being well satisfied of your sincere desires, which,
if properly retained and carefully cherished on your part, I cannot but comfortably hope,
heavenly Help will mercifully regard: so be it.
Amen.

John Fothergill.

[.asterism]
'''

John Fothergill to +++_____+++.

Ninth month 6th, 1741.

I cannot lose hope, nor almost full expectation, but that the Divine power,
which can do all things, will one time or other mercifully help you,
if you labor in watchfulness and patience, to look to him for salvation,
in true diligence, sincere resignation, and holy, humble trust: and that he will refine,
through various manners of dealing, and distressing dispensations, his beloved sons,
whom he would make chosen vessels in his house;
and with such an eye I believe he has looked upon you, somewhat like as upon Jacob,
when a stone was his pillow; yet the Lord of all power and majesty was in that place,
though Jacob knew it not.
And so have some others been made witnesses,
that he in mercy and gracious goodness was even working in and near us,
when sometimes the heavens seemed like brass, and the earth like iron,
and fear and sorrow surrounded.
Thus he has and will winnow and refine, and will show that none else can save,
and yet that he forsakes not those who would have no other God but him,
the ever-living and all-powerful One, everlastingly worthy to have all our hearts,
and to be trusted in, waited for, and praised for ever.

A measure of his glorious love and mercy covers my heart at this time,
and bows my spirit in humble worship to his most worthy name; but I cannot express,
like many others, according to my views, and must, therefore, leave what I have hinted,
for you to gather the substance as you are capable.
I am as well in health, through merciful support, as I have been many years,
and was favored with help from the best hand,
in the little journey through the northern counties,
to as much humbling gladness in the Lord as I have almost ever known;
though we met with several afflicting cases, besides the common heaviness,
or lack of proper hunger, which is, more or less,
almost a general hurt.--I had the good company of Michael Lightfoot most of the time.

John Fothergill.

[.asterism]
'''

John Fothergill to his Son Samuel.

Darley.
Tenth month 10th, 1741.

As you, my truly beloved sons, with your dear wives, whom I sincerely value,
are much in my remembrance in love,
which begets near care and living breathing for
your growth in the saving knowledge of truth,
that the Father of all mercies and true good may be your shepherd,
and help you to live to his praise; as this is almost all I can do for you,
and is often comfortably renewed with me,
so I now and then want to let you know I have you thus and often in mind I
am rather cheerful in my mind about your having drawings towards London,
and hope it may be made serviceable, as you walks watchfully,
and acts in humble care to be an instrument and servant directed by Christ,
and rather be within than exceed.
Remember your temper is active; keep fear, therefore out of meetings and in meetings,
for the Lord will help, and honors those who truly seek his honor, and, therefore,
carefully attend upon him for food, and fresh help to do his will from day to day:
thus may you be so directed and enabled,
that ancient and everlasting life may more and more be known among the people;
then will the Lord God be worshipped, and have the praise, who is worthy, worthy,
worthy for evermore.

I think, if you be under no obligation otherwise,
that John Hayward would cheerfully entertain you, and I know not of a more worthy place;
but they are not great showers of kindness, but real,
where they meet with worthy objects.

My last little journey was made by truth very satisfactory,
though very unpleasant circumstances are to be met with, particularly in Cumberland;
yet there is a people in that county waiting for best help, and worth laboring amongst.
I expect to be much about home this winter,
but I grow to expect I shall see Ireland once more, but it seems not very near.

I must stop my pen, though love would still run on,
and I hope will often live and move towards you.
I will only add now, that I hope Joseph is yet alive,
and I breathe with earnestness in the allowance
of our Father's love for him and his dear wife,
that they may be helped to sanctify the Lord of all power and goodness in their hearts,
and carefully wait that the pure seed may not be hindered by visible things,
but bear fruit to the glory of the mighty Husbandman, who surely waits to enable thereto.

So fare you all well, dear children,
in devoted pursuit of heart to be obedient children of the Lord God,
says your nearly loving father,

John Fothergill.

In 1742, after visiting Friends in Oxfordshire,
he again attended the yearly meeting in London, wherein the same lively zeal, which,
under the guidance of heavenly wisdom,
he had often before manifested on these solemn occasions,
for the prosperity and growth of truth and righteousness, was again conspicuous.

The concern of mind which he had for some time felt to visit Friends in Ireland,
was now matured, and was communicated to his son in the following letter.

John Fothergill to his Son Samuel.

London, Fourth month 5th, 1742.

I have had a desire to impart some thoughts to
you relating to a visit to Friends in Ireland.
I remember you once queried of me if I had any thing of that nature before me;
and though I could not say I had not, it seemed not then to be fully clear to me;
and though I had not much inclination then to inquire the reason of your question,
I was led to think you might have found something on your mind of that nature,
which induces me now to acquaint you that I believe such a visit is now become my duty,
and also that the time draws near; so that if it continue before me as it has done,
I think to be forward about the latter part of next month,
and I see not but your company would be truly easy to me,
if you apprehend such a concern to be with you, and also ripening as to time,
which I would have you to consider; and if so you find it to operate,
there may be the more strong ground of hope our going
together may be sanctified to us and our friends.
Meet me at York, with a few lines in answer hereto.

John Fothergill.

Samuel Fothergill having some prospect on his own mind of a visit to Ireland,
received this proposal with much satisfaction;
the offer of the company of his venerable father,
and the prospect of travelling with him in such an engagement, were truly agreeable.
But, in the exercise of that care which is so indispensable, to wait for the right time,
as well as for the right authority, to proceed in such engagements,
he believed that the proper time for him had not arrived, and, therefore,
notwithstanding the strong inducements which the proposal included, he declined it;
and his visit to Ireland did not take place until the year 1744.

Some account of his father's visit will be found in the following letters.

John Fothergill to +++______+++.

Chester, Sixth month, 1742.

My hands and thoughts have been busy in hastening to
discharge myself of this debt to Ireland,
and I now hope for a passage there the first suitable wind.
I am but in a low and heavy state of mind,
and should be very doubtful of being helped to live and act properly,
but that grain of faith is preserved,
which has heretofore often staid my mind in patient waiting,
till merciful supply of food, and ability to labor again,
has been experienced from the all-sufficient and only right relieving Hand;
and here is my centre, in reverent trust, where, as we endeavor steadily to keep,
duly attending for fresh help, that we may be what we are,
through the grace from on high,
I believe we shall not be neglected or forgotten
of the all-knowing Fountain of every good thing.

John Fothergill.

[.asterism]
'''

Dr. Fothergill to his Sister.

London, Sixth month 28th, 1742.

I have received a letter from dear father, from Dublin;
in it he acquainted me that he had a short and easy passage over,
and was then pretty cheerful.
A friend who saw him at Dublin, and is since come to London,
gave me a pleasing account that his Great Master had eminently
favored him with his presence in several meetings,
at which the friend was along with him.
The need there is of such laborers everywhere,
makes me cheerfully resign him to so hard a service as he must undergo in that country;
but that wisdom and strength which attends him from above,
I hope will support through it all, as well as direct.
Oh, may we, dear sister, more and more seek our father's God!
His favor to us will be all we need, and having him for our portion,
nothing necessary can be withheld.
I every day more affectionately esteem the best of parents, if I grow better myself,
and I cannot without tears call to mind his more than paternal concern for our welfare.

I have nothing so much in view as to contribute all in
my power to the relief of those that need it,
in the way of my profession,
and to the happiness of those whom I am so nearly interested in,
as my father and his beloveds.
It gives me sometimes pain to think that, according to the common period,
one-half of life is nearly spent, exclusive of any accidental blow,
and I not better provided, either for this life or another.
But I hope to cherish the thought, and make it my chief endeavor, to secure the last,
and be content with whatever may be my lot as to the first.

John Fothergill.

[.asterism]
'''

John Fothergill to +++_____+++.

Mountrath, 1742.

I have kept closely stirring along, and much employed,
to answer the end of my coming as diligently and honestly as I know how; which,
through continued merciful help and renewed supply, has been hitherto as well,
or rather better borne, as to the body, as well as in the chief respect,
than I dared to hope for, and I am thus far thankfully easy on my own part, though,
through deep labor, and at times much sorrow; yet I am glad I am here,
because of the blessed favor of help to pay this visit,
and also in that I am sensible of the strong
extendings of gracious regard to this nation,
and even that the dead may hear, and be made to live.

Yours was very acceptable, being accompanied with a relish of religious,
as well as natural love and nearness, which both comforts at present,
and increases reverent trust in, and regard to,
the Almighty Source of all our good and true help, who has hiddenly, yet mercifully,
cared for us many ways, and requires our consideration as such,
in order to encourage and instruct, in humble confidence,
yet with watchfulness towards him, that he may be our Shepherd through time,
and his glorious name may be renowned here and for ever.
Bear with me, dear son, in thus reaching towards you in the living sense of mercy,
the staying comfort whereof is highly worthy of our secret notice,
and solid commemoration I have been round the southern parts, and am now near the middle,
going northward, and hope to be at Dublin at the half-year's meeting.

John Fothergill.

After his return from Ireland, John Fothergill continued much about home,
visiting the neighboring meetings as his health permitted; this grew more precarious,
and the winter proving a severe one, he was prevented from going much abroad.
His care nevertheless, for the prosperity of truth, was as fresh as it had ever been,
his own inward strength being graciously renewed, as he often,
with reverent thankfulness, expressed; and for the preservation of his absent family,
and their increase in Divine experience and steady
progress in the paths of humility and dependence,
his soul was often deeply engaged.

John Fothergill to Frances Henshaw^
footnote:[Frances Henshaw, afterwards Frances Dodshon, was born near Leek,
in the year 1714.
Her parents possessed a considerable estate;
she received an education according to her station in society,
and was of good understanding.
About the twentieth year of her age,
she was convinced of the principles of Truth as held by the Society of Friends,
with whom she was received into religious membership.
So full and powerful was the conviction,
that even in the many deeply trying seasons through
which she had to pass during the course of her life,
the foundation of these principles in her mind, as she often expressed,
could never be shaken.
Soon after her convincement, she was called to the work of the ministry;
she labored much in the exercise of this gift, and travelled extensively.
She had to pass through many afflictions, both spiritually and temporally.
She lived to an advanced age, and died in the eighth month, 1793.]

Darley, First month 12th, 1743.

I had you so much in remembrance in a loving care and sympathy,
that I had thought of writing to you again before I received yours,
which may truly be called a lamentation, and would render your case very lamentable,
but that I am fully persuaded Almighty and merciful care and succouring regard,
from the infinite Being of goodness and mercy, is nearer and more regardful of you,
to stay and protect you, than you at present seems to apprehend; which revives my hope,
if you can but labor with some diligence to be quiet and reverently resigned,
and endeavor to overlook the too much teasing yourself about false accusations,
by which the enemy would deject and destroy you, I still hope, with much quietness,
that the day of salvation will by little and little dawn,
and light and life spring up to you again;
for I cannot think there is so much wrath and judgment
upon you from the God of mercy as you would,
as it were, pull upon yourself in your tender fear,
and the evil disturber would work your sinking temper in this time of trial,
to fear and conclude; this is my real and steady hope and thought about you,
though I know it is hard to be quiet and to
retain any lively hope in the truly loving soul,
when the Beloved hides himself indeed;
but clouds of witnesses bear testimony to the abundant mercy to humble seekers,
and even to the loathness of Goodness to forsake poor man,
but still more contrary to his gracious goodness,
to cast off one that has been and is desirous to follow him with full purpose of heart,
as I believe is truly your case; and if you be but kept reasonably still,
and somewhat cheerful, as very much otherwise would not be of service,
but might rather offend; for in the most stillness we can get to,
is help and strength from the mighty Helper experienced-- I say,
if you so labor to be kept, no reproach will attend it, but what will, in due time,
by best wisdom, be removed.

With respect to going to Grace Chambers' I am pleased with the invitation,
and think your being there awhile may be of advantage both to your health and otherwise,
for she is good and wise company: all that I hesitate about is,
lest your being there should be a means of exposing the case, to your future detriment,
further than one could wish, because all people are not wise;
but I seem not to fear but you may live to see clear weather,
and the light of Divine life upon you again; but reverent stillness in mind,
as at the footstool of the great knower of all our thoughts,
as well as words and actions,
I cannot but beg for you as much as ever you can for yourself;
and although I should be pleased to see you,
I see little probability of its being useful,
nor can I ride much without great difficulty; but whether I see you or not,
my very soul steadily longs for and bears with you,
and almost believes I may live to see you cheerful in the Lord, or, at least,
that you will live to be so, by the help of that eternal,
most gracious Power which ever brings into a right mind:
thus may you be regarded and helped, and so farewell my friend,
beloved for the Father's sake.

Your sincerely affectionate friend,

John Fothergill.

In the spring of 1743 his health and strength were much reduced, yet,
though with some difficulty, he attended in the sixth month,
the general meeting at Pickering, which was to him a favored season,
and he was well satisfied in having undertaken the journey.
These meetings, which were held once a year, were commonly very large,
and held in an open place,
to which some thousands of the neighboring people used to resort:
on this occasion they behaved attentively:
but they did not always comport themselves so well.

He continued very weak during the winter of 1743, getting but little out,
and scarcely able to converse with those friends who came to see him at home;
but his fervor of mind, and love towards the best things, abated not,
but remained undiminished.
And, in addressing at this time one of his friends, he says,
"`Though I am more than a little afflicted in body,
yet I am not forsaken of the everlasting Helper In a renewed consideration,
and in a degree of the sense of his manifold mercies,
and fatherly regard and succour hitherto, my heart worships his name,
and greets you in love and true well-wishing.`"

