== Chapter VI.

After the return of Samuel Fothergill from his visit to the north of Yorkshire, in 1740,
until he went into Ireland, in the year 1744,
there is but little left on record of his services, and only few of his letters.

In 1741 he attended the yearly meeting for the northern counties, held at Kendal,
and also the yearly meeting in London,
and in the autumn he visited some parts of Lancashire and Cumberland;
soon afterwards he had a certificate to pay a visit to some of the southern counties,
and to the city of London, and spent the winter in this engagement.

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to his Wife.

[.signed-section-context-open]
Carlisle, Sixth month 5th, 1741.

I am preserved in a good state of health, through hard labor,
having had as many meetings as days, hitherto, since I came into this county, and,
through the support of Providence, I am so far sustained;
and this I can with reverence and trust say, I never hitherto experienced in my travels,
the opening, sustaining goodness of the Great Master to such a degree:
have this day had a large, open and precious meeting at this place,
with Friends and others from several parts of the county,
it being the time of the assizes, for which, and manifold other mercies,
my soul ascribes glory, honor, and high praise to the Rock of our strength;
and in this holy love and life my soul salutes you,
and longs for our preservation in all lowliness and humility.

I would eagerly return, with the sheaves of peace in my bosom,
and fully clear myself before I return, which will be longer than I expected.

--

In 1742 he was engaged with some other Friends, by appointment of the monthly meeting,
in a religious visit to the families of Friends within that meeting.

The prospect of religious duty in a visit to Ireland,
which had for some time been upon his mind, had continued,
and believing that the right time for the performance of it was arrived,
he proposed it to the monthly meeting,
and with the certificate and unity of that meeting,
he embarked for Dublin in the second month, 1744, and had a good passage.

The following are some of the letters written during this visit:
one of them appears to be an answer to some individual
who had applied to him for spiritual counsel;
the applications of this nature which he received were frequent.

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to his Wife.

[.signed-section-context-open]
Dublin, Second month 27th, 1744.

On my arrival I came up to this city about eight, and went to meeting at ten;
it was very satisfactory; the goodness of the Great Master was evidently manifested,
to the abundant encouragement of my mind; it was as a seal of my commission here,
and very much encouraged me.

I would have you be entirely easy on my account; I hope that I am right in this concern,
and that He that has called me will preserve from every danger;
sufficient is His power to keep us both in our respective situations.

The Papists here are quiet, and profess an attachment to the government,
by their observing the late fast in a solemn manner.
There are fourteen French ships in this harbour, all seized upon by the government;
and two at the Isle of Man.

Through the mercy and kindness of the Almighty, I have my health pretty well;
the closeness of the city is inconvenient, but I soon leave it.
The opening, enlarging power of the gospel has not been lacking,
but has flowed with renewed evidences of my being so far right.

On the 18th, there was in this city the funeral of a Friend, a banker,
which was attended by the greatest concourse of people I have ever seen upon
the like occasion-- a strange mixture of folks--lords and Jesuits,
merchants and parsons, etc.: but the mighty power of God was revealed over all:
to His worthy name be the attribute of praise for ever!

On first-day last, we had a large meeting in the forenoon,
and near the close of that meeting, arrived our dear friend Elizabeth Shipley,
and her companion, after a tedious passage of nearly five days, from Liverpool.
We were five strangers, but none appeared:
J+++.+++ G. took up two and a-half hours in one sermon, the longest, but not the best,
I ever heard, to the great uneasiness of Friends.
Very great is the danger of that highly-called youth.

The meetings, during the course of this national meeting,
have been attended with the evidence of Divine favor.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to +++_______+++.

[.signed-section-context-open]
Dublin, Second month, 1744.

If this letter should come to the hand of the person from whom I received one last night,
know, oh, distressed soul!
I am sensibly touched with your state,
and should be thankful to be instrumental in delivering you from the
gall of bitterness you seems at present closely beset with.
I wish reflections upon the nature and necessity of
solid religion had more place in the minds of our youth;
sure I am it would tend to their great and lasting good,
for in it is the happiness of the reasonable soul, and in its due regard to its dictates.
Oh! that in this the day of your visitation you might be wise in heart,
and give up to the sword that which is for the sword.
If there was a willingness to be divested of every beloved,
inconsistent with the will of Him that has called you, you would experience more help,
and a gradual removing of those things that interfere
between you and the joys of God`'s people.
The sins of all mankind, must come to judgment, either here or hereafter;
and they are happy who have their sins go beforehand to judgment, and submit thereto;
in their humiliation their judgments are taken away.
I never knew right peace but in submitting to the exercise of
the righteous judgment upon the offending part in my own soul.
Now, as the mind is brought to this submission, hard things are made easy,
seeming impossibilities are made possible by the power of God,
and the poor soul triumphs in the power of God revealed for its health and strength;
and one thing after another is put off that has separated from good,
and the soul arises gradually in the image of Him who has called it.
I not only pity you, but, in the love of our heavenly Father,
my soul is baptized into a sense and feeling of your state: I sympathize with you,
and come down as into Jordan with you,
oh poor soul! and a living faith arises in my heart for you,
that if you be truly submissive, and attend to the Word in yourself,
the day will shine forth more and more to you.

Oh! be not afraid of looking inward; there is a merciful God there.
Spread your cause before him, and he will hear you;
for he has arisen for the piercing cries of the poor and distressed, and ever will arise;
and, my friend, let Divine approbation be the standard and measure of your conduct.
Alas! what is man, whose breath is in his nostrils, here today and gone tomorrow,
a poor short-sighted creature,
that apprehension of censures from such a creature should deter any from a
religious pursuit of those things that make for his eternal happiness;
therefore, look above these considerations, consult not with flesh and blood,
but freely give up to the holy visitation.
Remember the footsteps of the holy Jesus and his companions,
and the tribulated flock of God in all ages:
the difficulties in the way are for the trial of our faith, and tend to our advantage.
What can the world do for you, in that solemn period of death?
Can it give you peace of mind?
Can it deliver you from the judgment of God?
No, far from it.
Oh! therefore, that you may be induced to submit to that work you have known to be begun!

Great is the mercy of God to penitent returning sinners,
of whose abundant mercy I am a witness.
Prefer his favor, therefore,
as your chiefest joy--run you the celestial race
that is set before you--despise the shame,
endure the cross--glorious is the recompense,
and weighty is the crown--it is a prize worth contending for, and oh I says my soul,
that you may obtain it; and, inasmuch as this is the day of God`'s renewed mercy to you,
join in with it, lest you become a cast-off for ever,
and lose that sense you now have on your understanding; I much fear your safety,
if you submit not in this renewed reach of love; oh that I could take you by the hand,
and lead you forward a little! my soul is bowed on your behalf,
that you may be blessed with a turn in your soul to God;
I recommend you to the guidance of the Holy Spirit in yourself;
may you attend to its direction, and with the perfection of love and resignation,
wait for the manifestation and production of a holy birth in your soul.
Thus having offered, in an abrupt manner, what seemed on my mind for you, I remain,
in the sincerest manner, your affectionate, sympathizing, and concerned friend,

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to his Wife.

[.signed-section-context-open]
Lisburn, Third month 9th, 1744.

The day on which I wrote my last to you, was held the concluding meeting at Dublin,
to good satisfaction; next day I went to Drogheda, twenty-two miles,
and had a meeting there on first-day; ten or eleven Friends came with me from Dublin,
and many sober people of other persuasions came in, and Truth was exalted over all.
I went from there to Dundalk, and next morning to Rathfriland,
and had a small meeting there, and then fourteen miles to Lurgan that night,
which was a hard day`'s work.
I rested at Lurgan on the 1st, had a meeting there on the 2nd,
and at Moyallen on the 3rd, where the neighboring gentry came in, and several clergymen,
two of whom dined with me at a Friend`'s house; the Lord`'s power was that day magnified,
glory be to his worthy name.

On the 4th instant went to Ballyhagan, where was a large meeting; returned to Lurgan,
and rested there one day; on the next, being the first of the week,
went to Ballinderry in the morning,
where was a mighty large meeting of Friends and others: I went back to Lurgan,
where was a still larger meeting in the evening.
It was a day very shaking to the body, but my soul renewed its strength,
in faith and experience of continued regard.
The next day had a meeting at Hillsborough-- few Friends, but many others,
and some of the greatest rank in the neighborhood.
Yesterday I had no meeting, but there is one appointed for today.

Thus far truth has favored beyond my expectation,
and as there seems a very great openness hereaway, I dare not suddenly leave the north;
and on the other hand, I am cautious of appointing meetings too fast.

Friends here are very loving,
and unfeignedly willing to do any thing that lies in their power for me,
and apprehending me to be tender, +++[+++in health,]
are careful to an extreme lest any thing should ail me.
My landlord, where I now am, a worthy, innocent elder,
has been with me in most meetings I have had,
and proposes to accompany me through the greatest part of the nation,
which will be acceptable to me; he was over with Michael Lightfoot; his name,
Robert Richardson.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to his Wife.

[.signed-section-context-open]
Charlemont, Third month 18th, 1744.

My present business is to look to my concern here,
and the faithful discharge of it to God, the people, and myself;
and living praises to Him that is mindful of his servants,
I may say he has not hitherto failed me in this journey.

We had a pretty large meeting at Lisburn, and though things were heavy amongst them,
yet Truth rose, and we were favored: the next day I rode twelve miles to Antrim,
where we had a poor little meeting; rode twenty-two miles to Ballinacree,
where we had a hard, though pretty satisfactory meeting next morning,
being the first-day; in the afternoon went to Coleraine, where was a large meeting;
many people of rank within several miles came to it,
and the Lord owned us by his mighty power: may that day`'s favor remain always in my mind.
Next day went twenty miles to Grange, where we had a poor, heavy meeting;
on the 16th to Toberhead, where we had a good meeting;
yesterday rode nineteen miles to this place,
where this day the Lord singularly owned us by his power and presence,
to my great admiration and thankfulness.
I know not how I may fare in the rest of my journey--I leave that;
but I may say of a truth,
the evident favor and power of God`'s Truth has hitherto wonderfully helped me,
and my health has been, and yet is, mercifully preserved.

My love to all inquiring friends in Penketh meeting,
in earnest wishes for their prosperity in the glorious truth of our God.
May they gather to the eternal refuge of the people of God,
and therein be preserved to the end.
My mind calls many of them to remembrance with gladness,
and humble yet fervent breathing that they may be gathered to the glorious Shepherd,
whose pastures are sufficiently capacious to hold thousands more than
yet inhabit them;--the fountain is inexpressibly open and free,
and oh that there were a steady thirst alter it!

My heart is renewedly touched with the love of God; in that I am bound up with you,
and near you, in an indissoluble covenant; may our dwelling be evermore in it,
so shall we be helps one to another.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to his Wife.

[.signed-section-context-open]
Limerick, Fourth month 5th, 1744.

On seventh-day, the 19th ult., the Province meeting began at Ballyhagen;
on the next day was a very large meeting there, and what was still better,
a good meeting; the ancient testimony of light and grace opened.
John Turner opened the meeting, and it concluded well;
the hearts of Friends were comforted one in another.

On the 21st, rode sixteen miles to Castleshane, and had a meeting there that day,
very poor and small.
The following day I rode to Cootehill, twelve miles; had another small meeting there:
rode the same evening: to Ballyhays, six miles,
where I had a`' small meeting on the 23rd. On the 24th I rode to Castlebarr,
eighteen miles; had a small meeting there: from there to Moate, thirty-nine miles,
and was at the meeting on first-day, which was pretty large,
and the same evening I went six long miles to Athlone.
On second-day I went ten miles to a meeting in the province of Connaught,
and returned the same evening to Athlone,
where I had a large meeting in the Assembly Room, to good satisfaction.

Very great has been the Lord`'s goodness, and eminent his power,
that has often attended me in this visit.
I sometimes think something is to be met with that will try me thoroughly,
and oh that I may keep to the Rock of the righteous generation, who is able to preserve,
and likewise sufficient, where the mind honestly rests upon him.

I am glad you are easy in mind in my absence;
the Lord of heaven and earth keep us both in the way of our duly to him,
resigned and submissive.
The state of the Church is very low in many parts of this kingdom,
and meetings so dull and heavy that nothing but the weight of the powerful Word itself,
and that manifested in an extraordinary degree, can reach them,
and this has been near from day to day.

Think not that I am puffed up with the abundance of the Divine favor; I am,
through mercy, awfully humbled and bended in mind,
to acknowledge gratefully the favor of Heaven,
and to consecrate the gain of all to the Lord.
May reverence and fear possess my soul for ever!

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Doctor Fothergill to his Sister.

[.signed-section-context-open]
London, Eighth month 11th, 1744.

A considerable number of engagements have so taken up my time,
as even to break in upon those hours which I could always wish to command for retirement,
or to devote to proper thoughtfulness about things of the greatest consequence.
But, alas!
I have been too much robbed of this for some time past,
not indeed by any particular event, but by the general avocations of business, study,
and the interruption of company.
As I have been favored with a sight of the dangers that attend such a life,
I am in hopes sometimes of being strengthened to avoid them.
At other times I see no way to shun the precipice,
but fear that one day or other I shall fall,
and be lost to a sense of those blessed reproofs of instruction which yet, through mercy,
at times attend me.

As I can keep more in this place, dear sister, our correspondence will be more frequent,
more truly affectionate and instructive; for I know your lonesome,
solitary hours are not spent unprofitably;
you are breathing after an inward acquaintance with your father`'s God;
and as you abides in patience, he will come in, and then the night will seem short,
and it will be an additional gladness that you did not repine when left desolate.
Thus let it be our chiefest pleasure to incite and encourage in each other a steady,
patient attention to that sacred power which condescends to enlighten, to teach,
and to enliven those who thus daily seek for the bread of life.
It is seldom, alas! too seldom,
that the hurry and cares of this life permit me to practice what I here recommend,
with the ardor I could wish.

[.signed-section-signature]
John Fothergill.

--

The period was now approaching when John Fothergill,
having labored faithfully and diligently in the service of his Lord and Master,
was to be removed from his labors, to enjoy the reward, and to receive,
as we may reverently believe, the welcome sentence of "`Well done,
good and faithful servant, enter you into the joy of your Lord!`"

In the year 1744, though very weak in body,
he assembled once more with his friends at the yearly meeting in London.
He attended the various sittings of that meeting, evidently under an exemplary reverent,
weighty frame of mind, and his company was truly acceptable and useful.

During the summer of this year he removed his residence from Darley, in Netherdale,
to Knaresborough.

Feeling a desire to visit Friends of Bristol,
and to attend the Circular yearly meeting at Worcester,
he went by way of Cheshire and Shrewsbury, into Herefordshire,
where he visited Friends generally.

In the yearly meeting at Worcester,
he bore a noble Christian testimony to the
all-sufficiency of that Power which had preserved,
supported, and guided him in the way that was right and well-pleasing in degree,
and is able and willing to do the same for all the children of men.

Benjamin Holme was at this meeting, and in his journal thus makes mention of it,
and also of the yearly meeting for Wales:

"`I went to the yearly meeting in Wales,
which was held this year at Glanneedless +++[+++Llanidloes];
the said yearly meeting was large and very peaceable,
there being a great resort of other people who were not of our Society:
our friend Samuel Fothergill was there, and had good service for the Truth.
I was at the yearly meeting for the seven Western Counties, held this year at Worcester;
our friends John Fothergill and his son Samuel were there;
also Joshua Toft and Benjamin Kidd; the meeting was large and peaceable,
and Friends were favored therein with the enjoyment of Divine goodness.`"

From Worcester John Fothergill went to Bristol and Bath,
visiting the various meetings of Friends, and was helped to labor faithfully,
and in much plainness among them.

He left Bath in the beginning of the eighth month, and travelled home by easy journeys,
holding meetings as opportunities occurred.

After his return from this journey he seldom got out, even to his own meeting,
but continued visibly to decline.
In a letter to his son John he mentions,
that though in this journey his natural state was but feeble,
and attended with various difficulties,
yet he was not doubtful but he should be assisted, in mercy and favor,
to discharge himself of the debt, which had seemed to grow and remain upon him,
the way he was going, to such a degree as to return in holy quiet; and adds,
"`I ask no questions farther, but to be helped to live to the ever living Being,
the little time he may permit me to continue on this side the grave.`"

[.embedded-content-document.letter]
--

[.letter-heading]
John Fothergill to his Son John.

As I have no dependance on human assistance but from you,
nor any correspondence which affords me like comfort and satisfaction,
I must beg your frequent remembrance,
and to hear from you as often and freely as leisure will permit; and be assured,
my hearty, careful desires for you, in every true good,
not only are enlivened by the strong ties of nature and affection,
but are more riveted and strengthened by many a gracious spring of
living goodness from the almighty Helper of his people,
who have trusted in him, and feared him.
Thus, dear son, farewell, farewell, says your affectionate father,

[.signed-section-signature]
John Fothergill.

--

"`With these affecting expressions,`" says Doctor Fothergill,
"`ended a correspondence which afforded the strongest
satisfaction that any thing in this life could yield.`"
The letter was dated the 15th of the tenth month, 1744,
from which time he gradually declined till the 13th of the following month,
when he peaceably expired,
leaving to his family and friends the comfortable assurance of his being gone before,
to enjoy that unmixed happiness which is the portion of those
who prefer a conscientious discharge of duty to God,
their families, and the world, though attended with labor, anxious care, and solicitude,
to all the false, though gilded pursuits,
which the spirit of deception throws in the way of mortals.

His remains were honorably interred in Friends`' burial ground at Scotton,
near Knaresborough, the 15th of the eleventh month, 1744;
many friends attending on the solemn occasion.
He was aged sixty-nine years, and was a minister nearly fifty years.

His testimonies were awakening, sound, and edifying,
delivered in the demonstration of Divine authority,
for he handled not the Word of God deceitfully, nor endeavored to please men;
and as he waited to be endued with wisdom and power from on high,
so was he enabled to speak to the conditions of the people.

He was a man zealously concerned for good order and the discipline of the Church,
and was remarkably qualified for the management of its affairs,
being of a quick apprehension, an extensive capacity, and deep judgment,
and could express himself aptly, copiously, and strongly;
and as he diligently attended the various meetings for discipline,
so he was of peculiar service in them, approving himself a wise and able counsellor,
faithful and just to God and man.

His conduct was exemplary, being humble and sincere, doing the work of an evangelist,
and giving proof of his ministry, in patience, temperance, vigilance, and fortitude;
enduring afflictions, and using the things of this life with moderation.

Several of the following letters have reference to the event of John Fothergill`'s decease.

[.embedded-content-document.letter]
--

[.letter-heading]
Alexander Fothergill to T+++_______+++ L+++_______+++.

[.signed-section-context-open]
Carr-End, Eleventh month, 1744.

I have for some time had a desire to give you an account of the decease of your friend,
and my near and worthy father, John Fothergill,
who departed this life on the morning of the 13th of this month,
being the first-day of the week.

His natural body has been visibly going to decay these several years,
though he has been willing to show more care and attention to it of late than formerly;
the reason he gave for this was,
that he might be better able to discharge some services
that he seemed to have before him on Truth`'s account;
in the discharge whereof he frequently forgot the declining state of his body:
thus of late he has returned home, inwardly cheerful and easy in his spirit,
yet the poor outward frame reduced to the lowest ebb:
then care and proper medicines were used to recruit it,
which was no sooner done than it was again exposed to fresh hardships;
his love and zeal for the cause of truth and the welfare of the Church,
working upon a generous mind,
fully devoted to serve his God and his friends without reserve,
carried him faster on than the body was well able to bear.

In this last journey to the west of England,
he wrote from Bath that he had been supported to his admiration,
and had been enabled fully to discharge himself,
and he thought his health had not suffered much,
and that he felt as though he had nothing to do but to
return home with the reward of peace in his bosom:
but the season being very rainy, and he riding every day,
brought oft an aguish complaint, with a total loss of appetite,
so that he was very often sick, and altogether unable to take food.

I saw him twice; he was cheerful and easy in his spirit,
and not without hopes to see his friends again; but said, if it happened otherwise,
he was content, having so labored in the day that he was prepared for the evening;
and if he should recover again,
it would be no further pleasant to him than that he could be serviceable to truth.

[.signed-section-signature]
Alexander Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
May Drummond^
footnote:[May Drummond was of a considerable family in North Britain;
she was convinced of the truth of Friends`' principles at Edinburgh,
by the ministry of Thomas Story, about the year 1731,
at the time that her brother was the Provost of that city.
He was one of the principal founders of the Royal Infirmary,
and his sister was active in procuring funds from
Friends in England in aid of the Institution;
the various sums contributed by several quarterly meetings
remain recorded on a board in one of the apartments.
May Drummond had much to endure from her relations and friends, who,
being what was considered of genteel rank,
were much grieved at her uniting herself to the despised people called Quakers,
and were all against her, except a younger brother.
She, nevertheless, continued firm in her attachment to the principles she had embraced,
and maintaining her ground, was, in a few years, called into the ministry.
In this she was much engaged for many years.
She was a fluent speaker and very popular, particularly amongst those of other societies,
who were much drawn to the meetings she attended:
her character and the circumstances of her convincement often exciting curiosity.
One well qualified to judge, says of her ministry in 1739, "`She has some masculine,
nervous expressions; her periods are mostly regular and just: did she not affect it,
one might say she was eloquent.`"
She died at Edinburgh about the year 1772; but, during the latter years of her life,
was not held in the same estimation that she had formerly been.]
to Samuel and Susanna Fothergill, on the death of their Father.

[.signed-section-context-open]
Bristol, Eleventh month, 1744.

Two days ago the unacceptable tidings of your worthy father`'s death reached me.
Dead! did I say?
No! he is not dead; he lived in the eternal existence,
and in that has lain down a tender fabric.
On his account no friend need to lament; yet nature must have an allowance,
and Divine favor has indulged us so far as to give us the example,
when our great Master shed tears for dead Lazarus.
In your grief on this account I truly share; and of the joy that you feel,
from the certain knowledge which truth has communicated to you,
of your deceased parent`'s felicity, I taste.

So many have fallen who have been raised up to be shining instruments,
that it cannot fail of being an inexpressible consolation to you to
reflect that your worthy deceased parent retained his integrity.
No children had ever better example in a father, nor more seasonable admonitions; and he,
before his departure, lived to see the desire of his soul,
and the prayer he had put up for the salvation of his children answered to his wish,
and all his offspring in so hopeful a way,
that I make no doubt of his saying with good old Simeon, "`Lord,
now let your servant depart in peace; for mine eyes have seen your salvation.`"

[.signed-section-signature]
May Drummond.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Doctor Fothergill to his Sister.

[.signed-section-context-open]
London, Twelfth month 2nd, 1744-5.

I can say nothing to you upon the present distressing
occasion but what your own prudence will suggest to you;
we both feel that our loss is great, yet we do not know it to the full; our best friend,
protector, and counsellor is no more; it would be unnatural not to grieve.
But still we must remember that he is only gone before
to that possession where we shall at last arrive,
if we tread in his steps; to excite and encourage one another in this race, oh,
may it be our constant employ.

Through his care,
and the blessing of kind Providence upon his earnest wishes and prayers,
I am at present in a way of life, that both affords me what I have occasion for,
and seems not unlikely to continue so; and while it is,
neither be afraid of lacking yourself, nor think you are obliged to me.
In this part, while I am able, I will be a father, your friend and brother;
I should not say I will be these things; it is that good hand that blesses my endeavors,
for that dear good man`'s sake and yours.
Brother Samuel has written to me, but very short hints of everything.
Do, dear sister,
take the first opportunity of acquainting me as fully as you
can with all that has passed since he began to decline,
and if any memorable expressions dropped from him in his illness, please to let me know.

I find brother has collected most of his papers; the rest I shall be glad to have,
in order that, from those I have in my hands, and the rest,
I may be able to finish that account which dear father had begun, partly at my request.

[.signed-section-signature]
John Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to his Sister.

[.signed-section-context-open]
Warrington, Twelfth month 2nd, 1744-5.

As the common centre of our love is now, alas! removed,
I feel the sensible transferring of it to you.
May it mutually increase between us!
I am sensible of your lonely situation--I view
it sometimes with secret and strong sympathy.
I strongly hope encouraging goodness may attend you to dissipate the
gloominess and pain that at times must and will be about you.
Great is our loss, and great is the loss of the Church; may we,
the offspring of so worthy a parent,
with redoubled care look to that which made him useful and honorable in his station.
My heart is full when I consider things as they are.

Dear sister, I advise you to endeavor much after quietness in heart and mind.
I know your prudence, and that your cheerful countenance often covers a pained mind;
you have yet some left that love you--some relations that are
not a dishonor to the cause of truth our father promoted,
and that are pleased to have such a relation,
and would give all the evidence they could of it.

[.signed-section-signature]
Samuel Fothergill.

--
