== Chapter VII.

During several of the years succeeding the decease of his father,
there is but little left on record of the labors or correspondence of Samuel Fothergill.
Yet, neither during this period, nor in any other after he had embarked in the work,
could he be numbered amongst the slothful or the indifferent.

He had early attained to a high and settled standing as a minister,
and his faithfulness and diligence were manifested,
not only in those more extended services which he
performed with the certificate of the monthly meeting,
and in the regular attendance of, and services in,
the meetings for worship and for discipline, of which he was strictly a member;
but he also very frequently visited those of the adjacent or more distant counties;
as the Circular or local yearly meetings which were then held
in several parts of the nation--those called General meetings,
and the yearly meeting in London.
His company was much solicited, and very often given, at funerals,
and on other public occasions.
The practice of attending at such times, even at a considerable distance,
being much more common in his day than it has become of later years.

He considered it a part of his Christian duty, as a minister of the gospel,
to make use of every occasion in his power to advocate
and promote the cause of truth and righteousness;
to this he was devoted--to this he gave up much of his time and his substance--and
to this he was ever ready to sacrifice his ease and his strength;
great was his zeal, and it frequently led him into much exertion and fatigue,
whereby his bodily powers were greatly exhausted.

The natural energy of his character was exhibited herein,
and was also developed in his ministry;
in which he was frequently led on in a strain of deep and fervid eloquence,
accompanied by the demonstration of power,
which made strong impressions on the minds of his hearers;
thoroughly convinced himself of the great truths he had to declare,
he desired that similar conviction should be wrought in the hearts of his auditors.

In 1745 he attended the Northern yearly meeting, held at Kendal;
also the yearly meeting in London.
His wife had a certificate to visit Scotland, and some parts of the north of England,
but on account of the political troubles which prevailed,
owing to the irruption of the Scots into England,
her visit was delayed until the following year.

[.embedded-content-document.letter]
--

[.letter-heading]
Doctor Fothergill to Joshual Toft.^
footnote:[Joshual Toft was the intimate friend of Samuel Fothergill,
and his "`fellow-laborer in the gospel of Christ.`"
He had yielded in very early life to the power and influence of Truth,
and was united in religious membership with the Society of Friends.
When in the strength of his days, and extensively engaged in a lucrative business,
which promised to yield him abundance of wealth,
being content with the moderate competency already acquired, he, with noble resolution,
declined trade,
that he might more fully devote himself to his
Lord and Master`'s service in the gospel ministry,
into which he had been called about the thirty-second year of his age.
In this he diligently and faithfully labored many years,
and travelled much in various parts of the nation.
For more than fourteen years of the latter part of his life, he was deprived of his sight.
This, with other bodily afflictions, he bore with much patience and resignation.
A short time before his death,
he said he had received much consolation from a most gracious promise extended to him,
"`I have been with you, I am with you, and I will be with you.`"
He died at his house at Hargate, near Leek, the 15th of the eighth month, 1769,
aged upwards of eighty, a minister forty-eight years.]

[.signed-section-context-open]
London, Fourth month 2nd, 1746.

Those that are at heart concerned for the welfare of the Society,
cannot but be desirous of knowing a little of what has passed
amongst us upon the late solemn occasion +++[+++the yearly meeting.]
We should many of us have been glad to have seen you with us,
but as I hope that you were quite easy in staying away,
we ought to think it was your place,
and therefore acquiesce You will probably have heard that an
address to the king was very early proposed to the meeting,
and,
as most of those Friends who were looked upon as
capable of advising were previously consulted,
it was soon agreed to.
I thought the proper time was elapsed;
had I been present I believe I should have said so much;
but an address was ordered to be drawn, and after a great deal of time spent upon it,
the draft was brought in, and almost unanimously agreed to.^
footnote:[This was an address to George II., on the suppression of the rebellion of 1745.]
It was presented yesterday, by several Friends,
and received in a manner that left them no room to doubt of its being highly acceptable.
The Duke of Grafton was ordered by the king to go out and tell the Friends,
that he had not received one address that had given him more satisfaction,
and that they might assure their friends of it.
There was not much business out of the ordinary course that presented itself,
nor any occasion given for long debates.

I know not whether I am in any condition to give you an account of the other meetings:
in some, things went well; in others, not entirely to satisfaction.
Sometimes too great a loose is given to words.
Plain, simple truth needs little decoration;
it strikes the mind disposed to receive it to advantage
more forcibly than the greatest eloquence.
A parade of words, indeed, bewitches the hearers, and makes them admire and praise,
and at length puff up the poor instrument if possible.
We are all susceptible, in some degree, of these impressions,
unless we are upon the strictest guard.

[.signed-section-signature]
John Fothergill.

--

In the year 1746, Samuel Fothergill paid a religious visit to Cumberland and Scotland;
in the following year he was engaged in a visit to Friends in Warwickshire, Oxfordshire,
and London:
during this journey he attended the Circular yearly meeting held at Leominster,
which he mentions in one of the following letters.
His wife also visited Worcestershire and Gloucestershire.

In 1748 he paid a visit to Friends in Cumberland, and also to the city of Bristol.

[.embedded-content-document.letter]
--

[.letter-heading]
Doctor Fothergill to his Sister.

[.signed-section-context-open]
Eighth month 23rd, 1746.

There are times when we are drawn to retirement, and it is made beneficial to us;
we leave it with cheerfulness, and the mind is relieved and comforted.
These should ever be embraced,
and the disposition to improve them should be carefully cultivated.
But as nothing is so painful to ourselves, or makes us so uneasy to others,
as indulging eating cares, so we should be for ever on our guard against them.

I often reflect, that I know not what is best for me;
the most flattering prospects may be attended with dangers that I cannot see, and it is,
therefore, in kindness that Heaven withholds them from me.
I am already too much retarded in my pursuits
after what alone can make mankind truly happy;
if I have more difficulties, my progress must be still less.
Thus I argue, and thus I think, when the best mind is uppermost; but this true bias,
how often is it perverted by unworthy objects!
Brother Samuel wrote to me from Durham.
His letter gave me great satisfaction;
it spoke his father`'s language in his father`'s spirit;
and may he ever be clothed with it!

I sate the little meeting at Knaresborough.
In the evening I went to the place where the remains of our dear father were laid,
and though I could not join you in performing the office of a child,^
footnote:[In attending at the interment.]
yet I felt then, what you had felt before.

I could not have been fully satisfied with my journey without some such opportunity.

[.signed-section-signature]
John Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Lawford Godfrey.^
footnote:[Lawford Godfrey resided at Exeter, and died in that city,
on the 10th of the eleventh month, 1747, aged sixty-six, a minister nearly forty years.]

[.signed-section-context-open]
Tenth month 11th, 1747.

My mind was reverently humbled before the Almighty,
during the course of that solemnity at Leominster,
and under a lively sense of the extensions of a regard, ancient and new,
that He who is the author of our being, the author of our happiness,
is not only ours who have been so eminently visited,
but is the safety of an alienated world, in the reconciling and restoring it to himself.
For this end we know he immediately reaches to the minds of mankind, and,
having led a remnant into a living experience, through faith in his name,
that he is Jehovah, great in council, and mighty in power,
he has enabled them to be co-workers together with himself,
for the cultivation of their own vineyards, and through a diversity of instruments,
and variety of gifts,
to be as the voice of one crying in the wilderness of this apostatized generation,
"`Prepare you the way of the Lord, make his paths straight.`"
The unity of these laborers, in the promotion of this glorious work, is great,
and unto strangers incomprehensible; but, being baptized by one Lord,
into a most holy faith, some are builders, some hewers of stones, some diggers of them,
as out of the earth,
and some others more immediately bearers of burdens--each led
into their respective services by the great Architect,
and directed to proceed therein through the continuance of the same wisdom,
as fellow servants in the cause of God.
A concern for its promotion, and the mutual preservation one of another,
strongly and frequently prevailed,
and I am persuaded a sincere regard for the honor of the great Name,
and travail for Zion`'s prosperity, attended your mind, and led you,
in openings of Divine council,
to impart your experience in the work of the ministry to me,
that have great need of every help.
I am thankful to the great Master that we have fathers, as well as instructors,
in mercy continued amongst us;
such as by a long course of experience have explored
the great mystery of godliness and ungodliness;
watchmen that are placed upon Zion`'s walls, whose trumpets give a certain sound.
For my own part,
I thank God he has not left me destitute of a humble sense of my own weakness,
and the jeopardies that attend me, engaging according to his wisdom,
by his rod and his staff, to a labor of soul to be what I ought to be,
to fill my station, and stand in my lot to the end of days.

There is none knows, but the Lord and my own soul,
the baptisms wherewith I am at times exercised, nor the steps I have to tread.
Oh, that I may be helped to take heed to the ministry of the Word,
that in all dispensations, to myself and others, I may fulfill it.
I have had a renewed sense, often comfortably impressed on my mind,
in my late visit and travail, that the Lord would preserve through all,
and keep me to the end.
Though my way may be through the shadow of death,
I feel my safety is in a humble walking, and steady feeling after God,
for renewing of bread, day after day.
Sometimes his countenance is clouded, and, blessed be his name,
it is at other times fairer than the children of men.

I sat down with my spirit bowed in gospel fellowship with the true followers of the Lamb;
I knew not what I might offer with respect to words.
May our dwelling be in that, which no language can fully express, and our correspondence,
though not with the ornamental arrangement of words or expressions,
tend to stir up reciprocally the pure mind.

I am, with the salutation of strongest affection, that is everlasting in duration,
and unchangeable in its nature,
your brother and fellow sufferer in the patience and tribulation of Christ`'s kingdom.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Joshua Toft.

[.signed-section-context-open]
Warrington, Sixth month 19th, 1748.

This summer I have made an excursion to Scarborough,
and amongst the meetings of Friends on the eastern shore of Yorkshire.
The consciousness of an honest intention,
and of room for the testimony amongst those without,
together with evident tokens of the Great Master`'s regard, afforded, and still does,
a lively degree of satisfaction and comfort;
but to view the state of the Church in sundry places, particularly in +++_______+++,
gives a good deal of pain: some few keep their places,
but the generality are the most insensible,
unfeeling people I ever was concerned amongst.

The meetings there were large and peaceable,
and to my satisfaction in respect to those not of our Society.
I returned, by the yearly meeting at Pickering, which was very large,
and Friends told me, the greatest they had had for some years;
but as it has overgrown its service,
and many come to it for no better purpose than drunkenness and revelling,
I believe this was the last that will be held there.
Marsden Height^
footnote:[This was one of those called General meetings, then annually held,
and of which Samuel Fothergill was a very frequent attender.]
meeting, I hear, was remarkably large, but I fear not altogether satisfactory.
I had great hopes you would have been there.

[.signed-section-signature]
Samuel Fothergill.

--

In the year 1749, Samuel Fothergill again visited some of the midland counties,
and the city of London;
he afterwards extended his services into some parts of the south and west of England;
and was also at the yearly meeting for Wales, held at Haverfordwest;
from there he went to Swansea, to attend the burial of his friend Benjamin Holme,
who being on his way to the yearly meeting for Wales,
was taken ill at the house of Paul Bevan, in Swansea, and there he departed this life,
on the 14th of second month, 1749, aged sixty-seven years.
So early in life had he entered on the ministry,
that he had been engaged in it for fifty-three years,
and had travelled in that service when only seventeen years of age,
with Joseph Kirkbride and Leonard Fell.
He was much devoted to the service of truth, and labored therein almost incessantly;
and as he lived, so he died-- a pattern of meekness and innocency.
(See an Account of his Life and Travels.
London, 1753.) In 1750, Samuel Fothergill attended the National meeting for Ireland,
held in Dublin, and in 1752 he paid another visit to the city of Bristol.
In most of these years he attended the yearly meeting in London.

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to his Brother John.

[.signed-section-context-open]
Warrington, Tenth month, 1750.

I am sorry to find your fears respecting the improvement of Friends, where I have been,
so justly founded; too little proper thoughtfulness is amongst them; large fortunes,
and religious profession, the fruits of their father`'s industry and real experience,
have had an unhappy effect upon many of them,
and introduced a mixture of pride and indolence that is
no-ways consistent with inward religious growth,
to which the far greater part of them are no-way attentive.

Notwithstanding the deplorable state of the Church there,
yet the strong reaches of inward help are extended towards them;
the God of their fathers remembers his covenant made with them,
and waits to bless their offspring;
by the same means the righteous in every age have been made happy;
the undoubted sense I had given me of the merciful regard and
gracious long-suffering of the God of mercy strongly comforted me;
yet a proportionate fear often attended,
lest disregarded visitations and touches of inward virtue overlooked,
might issue in almost total subversion of a people,
with whom heavenly favor had manifestly dwelt.
My soul was often strongly moved to pay them a visit for some time past,
and I did not fully give up to it until the sixth-day evening before I went;
my mind was quiet and easy, as I was resigned.
I had a quick passage, though not unattended with danger.
That the hairs of my head were numbered, was given me to believe,
and that beyond a doubt; I said with reverence, Good is the word of the Lord,
and was as calm and quiet as at any time of my religious experience.
We came safe to Dublin.
The meeting for ministers and elders was held on fourth-day, and was very small and poor;
the meetings for worship were held in the forenoons of the two following days,
and the meetings for discipline in the afternoons of the same,
in which time their business was finished.

Their discipline is just; nothing inferior to ours in the north,
and there are a few hands that are strong and active in it,
and studious to render it effectual to answer the end of its institution.
The appearance of Friends from Leinsler province was considerable;
from the province of Ulster only four Friends; from the province of Munster not one,
which occasioned a hesitation in the opening of the meeting of business,
whether they could proceed to act,
as they lacked representatives from one-third of their body;
but as the Munster Friends had written an account of
the state of their province to the National Meeting,
it was accepted, and Friends were easy to proceed.

The state of the Church gave great concern to many there, and a warm,
affectionate epistle was sent to the Particular Meetings,
into which I threw a few things that had some weight with me.
The concluding meeting for ministers and elders was held on seventh-day,
which was solemn and bowing; the enlivening,
encouraging Presence was richly manifested to a small handful,
that seemed like the mournful prophet under the juniper-tree, and like the small,
very small gleaning of the vintage.
An eminent degree of the same heavenly truth attended us the next morning,
at our public concluding meeting, which was extremely large,
and I do not remember ever more undoubted proof of merciful condescension.
Many that were not of our name were there, and greatly reached -- remember it,
oh my soul, with due reverence and gratitude!
The afternoon was favored with the same truth, and was a very great meeting.
The funeral of Francis Russell, our father`'s and my former landlord,
occasioned it to be an excessive crowd, though awful, and very quiet.
Meetings every day, and the close, heavy air of the city,
had destroyed my natural abilities; my rest and appetite almost gone,
I was obliged that evening to take coach and go to a Friend`'s country house.
I returned much better next morning,
attended the quarterly meeting for young people the same day,
which was large and satisfactory.
Next morning I set out with Samuel Watson and Robert Lecky to go into the country,
to Kilconner, to see Abigail Watson, who is poorly in health,
but lively in the best respects, and full of the heavenly dew of her youth.
She mentioned you often, and with great esteem, and desired her dear love to you,
and that I would let you know a few lines from you would revive her much.

On my return to Dublin, I went to see some other sick Friends,
with a mind filled with awful reverence for mercies daily renewed,
and a continued sense of daily support.
Spent a space of time with some Friends at John Barclay`'s, on third-day,
in which the humbling presence united us,
and strong cries ascended for mutual preservation in his fear and favor;
his canopy was over us, and he led us to his banqueting-house.
Afterwards I went on board, and after forty-six hours at sea,
came safe to Liverpool on the 30th ultimo.

Thus, my dear brother,
I have given you a recital--probably tedious--of a few weeks`' occurrences,
which I hope not to forget; I have reaped benefit myself, and I hope others likewise:
faithfulness is the way to profit, and to renew life and strength;
though we are weak and poor, infinite strength and riches humbles Himself to our needs,
and will ever regard us with mercy, while we regard him with sincerity.

I salute you and dear sister most affectionately;
may we live to Him who has inwardly quickened us,
that the blessing of preservation may rest upon
us through all the mazes of our probation,
to an inheritance in everlasting quiet.

[.signed-section-closing]
I am yours, in union more near than the ties of nature,

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Greer to Samuel Fothergill.

[.signed-section-context-open]
Dungannon, Ninth month 18th, 1750.

Glad would I have been to have had a little conversation with you when in Dublin,
at the late National Meeting; but that not being the case, I now write,
in the freedom of that love that in your former visit
to this nation nearly united my spirit to you,
for which I have been many times thankful to the Author of my life,
in that he was graciously pleased, through your ministry,
to make such an impression on my spirit as I hope will never be effaced.
Oh! may I never forget his paternal care over me, when,
equipped with the wings of vanity, I was flying into folly;
even then he was pleased to speak, in a language too powerful to be gainsayed--Young man,
where are you going?
May it indeed be engraven as on the palms of my hands;--this unparalleled condescension,
may it ever renew in me a humble breathing in my soul that he may be pleased so to
strengthen and support me through the various vicissitudes that attend this life,
that I may be enabled to live to his honor,
for which great purpose I am satisfied mankind first had and have their existence;
but alas! how liable is depraved man to mistake the matter of greatest importance,
and choose rather to live to himself, and to the gratification of a carnal,
degenerate mind, than to the glory of that Being that formed him,
and seeks his eternal happiness.

Much has been the labor of love that has been bestowed upon this poor unthankful island,
and many have been the faithful laborers who have been sent amongst us,
both from England and other parts,
for which favors all who have any degree of life cannot but be thankful;
also for its being put into your heart to visit us at the late half-year`'s meeting,
at this time of inward poverty and affliction of mind to some whose faces are, I trust,
turned Zionwards, on account of the undue liberty taken by many of the youth;
and the love of the world and earthly-mindedness, it is to be feared,
have overtaken many, who, if they had kept their places,
might have been by this time as stakes in Zion`'s walls.

May the design of an all-wise Providence, in sending you amongst us at this time,
be fully answered, by every one who has been favored with having his condition opened,
in the demonstration of the Spirit and with power--for certainly the Gospel trumpet
has given a certain sound--becoming so wise as to repair to the battle.

[.signed-section-signature]
Thomas Greer.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Thomas Greer.

[.signed-section-context-open]
Warrington, Eleventh month 20th, 1750.

I received in Dublin a letter from you, which gave me satisfaction;
and I rejoice in this,
that the Lord of heaven and earth is visiting by his truth and
working by his power to beget into his heavenly family,
and bless people with that which conveys all the happiness mankind ever did, must now,
or hereafter ever can taste.
Too many are insensible of it, and others too lazy to be religious as they ought;
but it is our interest to pursue our own peace, and transmit to others examples,
how great and excellent a thing it is to be true subjects of Christ`'s kingdom,
and baptized into his nature, and therein to abide.
Great has been his mercy in visiting our souls with his blessed truth;
and it highly behoves us to watch with all diligence lest we render it frustrate.
This is our duty--to look to him daily.
This comprehends all.
Here is our strength and safety; other stays, or temporary helps, will fail,
and leave us destitute and inwardly lean.
Oh! therefore, remember often the dew of your youth,
the tenderness of your heart when first met with.
Cherish in your soul the fresh instances of regard;
and be it your care inwardly to look and live to the Lord;
so shall your hands be made strong and your head kept above the waters.
There is a spirit that is gone forth into the camp, and is splendidly delusive.
It delights in good words, and feeds upon them; it cries out, "`Help,
help,`" but principally to the servant, not to the Master.
This spirit leads into notions; it snuffs up the wind,
and lives in commotions itself raises;
all that are led by it are superficial and know nothing, and must lie down in sorrow.
That Holy Spirit, which was and is the ground of truth for ever, which, I trust,
has reached your heart, is a substantial, operative principle;
its directions are not imaginary, nor its doctrines loose and indeterminate;
but it is light and life to its possessors, and causes them to inherit substance;
it teaches access in heart to that God whose attributes cannot be defined fully;
but experience teaches them it is kind to men, supplying their needs,
supporting their steps,
opening their understanding to those Divine truths that
are higher than human wisdom can trace,
and deeper than all its penetration can explore.
Dear friend, let us wait for this wisdom; let this Spirit be leaned upon above all;
this will help us to stand upright,
and walk steadily in the faith delivered to the saints; retirement will be pleasant;
in meetings and out of meetings, the inward feeling after Divine power,
to live and act to God`'s honor and our own preservation, will be dear and precious to us;
and He that delights to hear the language of his children will
not be slack in the performance of his gracious promises.
I found the free salutation of pure love in my heart towards you;
and earnestly entreat you to abide steadfast in the truth; feel after it; live in it;
hope for its salvation, and it will never fail.
I salute you in the love and affection of Christ, our holy and blessed helper,
and remain your faithful friend.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Mary Peisley^
footnote:[Mary Peisley was a well-esteemed minister.
She visited America in company with Catharine Payton.
She was subsequently married to Samuel Neale, and three days afterwards, viz.,
on the 20th of Third month, 1757, she departed this life.]
to Samuel Fothergill.

[.signed-section-context-open]
Paddock, Eleventh month 28th, 1750.

Your lines carry with them the reaching, convincing evidence of that soft,
sympathetic union, to which the world are strangers:
they neither know nor intermeddle with these joys, the feeling sense of which,
when I received your letter, melted my heart into tenderness,
and bowed my spirit in reverence before the God and Father of all mercies,
to reflect that he, the high and holy One, who inhabits eternity,
should condescend to the low estate of his poor unworthy handmaid,
to bring her into the glorious fellowship which is with him and his dear Son,
a secret union and communion with the saints in light; that I, the least of them all,
should be made a sensible partaker of these blessed privileges,
and be made present in spirit with his dear servants, though absent in body.
Oh! may I, during the residue of my weary pilgrimage here,
walk more worthy of the vocation appointed me, so that, with the Lord`'s chosen servants,
I may finish my course with joy.

It gave me concern to hear of your indisposition, which I do not wonder at,
considering your labors amongst us; but humbly hope you will be spared,
and raised up for future service,
to which may you be made truly willing in the day of God`'s power,
though it must be confessed it is a dangerous and difficult time to go a warfare in;
but it is not at our own expense,
for greater is He that is in and with us than he that is in the world.

Do, dear friend, write freely;
and if you have observed any thing in my conduct that you think reprovable,
do not spare me, for I know that I need help.

[.signed-section-signature]
Mary Peisley.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Catharine Payton.^
footnote:[For many years an intimate friendship and frequent correspondence
was maintained between Samuel Fothergill and Catharine Payton.
She was the daughter of Henry and Ann Payton, of Dudley.
When about twenty-two years of age, she came forth in the ministry,
and in the exercise of this gift travelled much, in most parts of England and Scotland;
also in Ireland, America, and Holland.
In 1772 she was married to William Phillips, of Cornwall, and died in that county,
in the Eighth month, 1794, aged sixty-eight years;
a minister forty-six years.-- See Memoirs of her Life.
London, 1797.]

[.signed-section-context-open]
Warrington, Third month, 1751.

I received your brother`'s letter,
intimating your thoughts of going over to the Half Year`'s meeting, at Dublin,
and I sincerely wish you a good journey,
and pray that the preserving hand may ever sustain you,
and keep you dependent upon himself: by no other means are we likely to be kept properly.
Various humbling times attend the true faithful laborers in the Lord`'s vineyard,
that keep company with the true seed in suffering, and only reign by it;
the applause of the injudicious has hurt some and greatly embarrassed many,
in that kingdom; and therefore keep your eye single.

As the Lord has given you a good gift, and entrusted you with several talents,
you are loudly called upon to diligent improvement;
and that can only be by virtue of the renewing of strength from his hand,
and holy feeding at his table;
thus you will be preserved in dominion over all that which would lift up,
and over that which would cast down, and the name of our jealous God will be honored,
and the gain consecrated to him.
And, dear Kitty, bear your testimony against haughtiness and luxury, by a humble,
watchful conduct.

Be not led by them out of the leadings of truth,
in the appointment of large meetings in court-houses, etc.,
for in this respect I am sensible there is some danger, unless, really,
the very burden of the Word be upon you,
and I would by no means have the faithful laborer in that ability discouraged.
I would have you to be tender in the choice of a companion; if one fall to your share,
let her be one to help spiritually, and not to hinder you by any disagreeable demeanour.
My affection strongly attends,
and craves that the presence of Almighty God may be your guard and companion; live in it,
seek after the enlargement of it, by waiting for daily sustenance from it;
and the God of my life keep us both chaste in our minds to him whose we are,
and ought to serve with the spirit of our minds.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to his Brother John.

[.signed-section-context-open]
Warrington, Seventh month 14th, 1751.

Yesterday I attended the funeral of Peter Leadbeater, of Chester, who,
by a fall on third-day, fractured his skull,
and died next day--a man in many respects worthy and useful,
and let his imperfections be buried with him.

There was the greatest crowd I remember to have seen on such an occasion,
and it was with difficulty we got to the burying-place.
I received a crush in my breast in the throng, I am afraid won`'t soon be forgotten.

I join you in thankful acknowledgments to the Author of good,
for his signal favor in owning those large assemblies with his powerful truth,
to the comfort of the faithful and the exaltation of his name amongst the people.
Oh! that the sense of general and particular favors may be often revived in our minds,
that our souls may be quickened in care to walk worthy.
Nothing ought to be allowed in us that leads to
forget that hand that is filled with blessings,
ready to dispense them, but expects grateful returns.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Sarah Brown.^
footnote:[Daughter of William Brown, from America.]

[.signed-section-context-open]
Warrington, First month 20th, 1752.

I doubt not but the same conveyance that brings this,
will bring some account of your dear and worthy father, whom I saw at Liverpool,
on his way to Ireland, a few weeks ago, in pretty good health,
and alive and cheerful in his labor, in which he has been closely concerned,
and I hope to good service in several respects; doubtless to his own great peace,
and uniting him in heart to the faithful.

In the freedom we had to each other,
he imparted to me one or two of your affectionate letters to him,
which seemed to breathe strongly of the language of tender affection to him,
and an awful regard to the Heavenly Father,
and has been the means of your being often in my very near remembrance,
and some desire attended to send you the salutation of true love in Christ Jesus,
our holy head, in whom stands the fellowship of the family, the world over.
Great has been your advantage, dear friend, in being descended from worthy parents, who,
by example and precept, have sought your nurture and growth in the things of God;
the visitation of heavenly light and life has also been extended,
and I hope in a great and good degree embraced, and has pointed out the means of help,
or the terms of happiness, and inclined your heart to seek it.

Many are the besetments and probations of a mind
awakened to seek an inheritance among the blessed,
and of various kinds they are; but the mighty arm is revealed and made bare,
for all those that refuse to be comforted without it.
Many are the low places the righteous tread,
and in the line of their experience deep answers deep;
some are brought upon us through our inadvertency and negligence;
let us then inquire the cause, and remove it;
sometimes the heavens are made like brass to us, to teach us how to be in need, and,
like winter seasons, to strengthen our roots, that we grow not top heavy;
but in all things our Heavenly Father deals with us tenderly, and for our good.

Let, therefore, your attention be steady to him for counsel and guidance,
and he will not forsake you in the time of your secret bewailings,
but spread a table for you in the desert.
Oh! that our youth might thus awfully bow under the operation of the Lord`'s hand,
that their minds might be subject to him, whose we are,
and whom we ought to serve in the spirit of our minds.
I feel in my mind the sympathy of the blessed covenant,
and the spreading of the Father`'s wing towards you,
and crave of the Almighty One to have you in his keeping,
and of you never to forfeit it by any means.
He is all-sufficient to abide with you continually.

He is often with his people when they perceive it not: he dwells in thick darkness often,
and was as certainly the mighty helper of Israel,
when they groaned in anguish in the land of Egypt,
as when the glory of the Lord filled the temple, at the feast of dedication.
I commend you to him--seek him diligently, serve him honestly,
and follow on to know his requirings, with full purpose of heart to be faithful thereto;
and no weapon formed against you will prosper,
nor any place be allotted so low in which the omnipotent arm will not sustain.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to his Sister.

[.signed-section-context-open]
Warrington, Fourth month 20th, 1752.

I often make myself a party in idea in your converse,
and with pleasure I anticipate the satisfaction arising from a personal interview.
Friendship, founded on its proper stable foundation,
doubtless affords the most sublime sensible joy we are capable of tasting here,
and is an agreeable earnest of that union that
inseparably connects the blessed spirits above.
Oh! beloved sister, how glorious is the prospect, but how difficult the means!
But no cross, no crown: and in our Father`'s arm is everlasting strength.

I have had much to sympathize with you in your present religious circumstances,
and it has revived in my mind, in joyous suffering, to endeavor after a peaceable,
childlike submission to the heavenly Father`'s will; to lie down at his feet, in deep,
resigned silence, even from complaint, has made more for true ease,
and helped to a profitable search into ourselves and Heaven`'s mind.

I believe much deep travail attends you, and an apprehension of being almost alone.
Discourage not yourself at this, nor pain yourself unnecessarily about others;
let your eye be in your head and to your Helper, and his will your standard;
neither be discouraged, beloved sister, at the low times you meets with;
for I am fully satisfied that even the strong men are often bowed down deeply;
and shall the tender plant repine at being shaken by the wind?
The faithfulness of unchangeable help is such, as to render us safe in his protection,
while we seek to abide in it.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to John Churchman.

[.signed-section-context-open]
Warrington, 1752.

I have by no means forgotten you;
you are too deeply fixed in my mind to be easily displaced.
Your affectionate, instructive epistle from Cumberland,
has been often a means of bringing you near to my soul,
and it into a reverent search and jealous care to move rightly when I can move,
and endeavor to stand safe at all times by standing out
of my own abilities and in that which comes from God.

And now, my dear friend, I must inform you of the principal reason of my long silence,
and the discontinuance of my correspondence.
I have had, since my return from Norwich,
a very baptizing time of inward distress and need, and been brought very low in mind,
even sometimes almost to question whether I had ever been right, or should ever be happy.
I ever kept my complaint secret, and my mouth in the dust,
under the correction of my heavenly Father`'s rod; and he sometimes revives a little hope.
In this time of solitary distress, I have observed some causes of chastisement,
and hope of more stability and faithfulness has attended.

To sing I could not; to complain I dared not;
to write of religious things was passing beyond the line of present experience,
and that is a sacrilege.
I know you so well as to be assured you could not relish such a correspondent; however,
I have often remembered you nearly,
and my spirit being so closely touched with secret sympathy with you,
has been some evidence that my life is not altogether gone.
I salute you and Mary Peisley, when you sees her, most affectionately,
and am your friend and companion in the tribulations, and may God grant it,
the patience of the gospel.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Churchman^
footnote:[John Churchman, of East Nottingham, in Pennsylvania,
a Friend well known by the published account of his life and gospel labors.
In the year 1750, accompanied by William Brown, he arrived in England,
on a religious visit to this nation, also visiting Ireland and Holland.
This occupied him nearly four years; and in 1754 he returned to his native land.
He died on the 24th of seventh month, 1775, aged near seventy,
a minister about forty-two years.]
to Samuel Fothergill.

[.signed-section-context-open]
Moate, Eighth month 13th, 1752.

When, by the secret touches of truth, we are made to feel and know each other,
though to the outward entire strangers,
there is a foundation of friendship laid which is not easily erased.
It is hereby we know ourselves to be members one of another,
and cannot help at times remembering each other,
in the participation of the true communion; and the humble address of our souls is,
that ourselves and our brethren may be preserved pure, and as worthy communicants,
presented before the holy table, cleansed from the spots of the world,
and all the crooked wrinkles of self.
We then have no thoughts of asking dignities for ourselves, or for one another,
as to sit on the right hand or on the left, but to be preserved in innocency,
and to have our names written, yes, recorded, in the Lamb`'s book of life;
an inheritance to such is sure in life eternal, if they continue faithful unto death.

When we are humbled before our great Master,
in a sense that his love is lengthened out to his Church and people,
we are made willing to follow him in the way of our own duty whithersoever he leads us;
and good it is to mind our own business properly,
without thinking ourselves too much alone in the work of the Lord,
and others too negligent; or inquiring too busily into the gifts of one,
or be too much concerned what another shall do.
These dispositions seemed to be gently both reprehended and instructed by our Lord,
in his answers to well meaning Martha, when she said, Bid her that she help me,
and to Peter, on his query, What shall this man do?

But when the baptizing virtue and power of Truth overshadows our souls,
we cannot help desiring that the people may keep their ranks, and,
in sanctification of both body and spirit,
stand prepared that the Lord may choose and instruct, gift and qualify, judges,
counsellors, rulers, and chiefs, both in the ministry of the Word,
and in the discipline of his Church.

I have been confined to my`' room for more than ten days, by reason of a great cold,
taken, I suppose, in the north, in damp houses and cold beds,
but through the lender mercy of kind Providence, am in a fair way of recovery.
The respite from travelling and immediate exercise has been as a rest to my spirit,
which has been preserved, resigned, and mostly quiet.
I have often sought to know mine own imperfections,
and have been favored with a sight of several things concerning
myself and my brethren engaged in the work of the ministry.
Methought I had a renewed glimpse of the holy attire with which the
attendants at the holy altar should perpetually stand arrayed;
the vestments are holy, the garments clothe the spirit, and the adorning is beautiful,
and never waxes old; it is girt about the loins of the new man,
and loosely laid aside when immediate service seems over;
it is bound in the heart and coupled in the soul.
Oh! let this Urim and Thummim be for ever with the holy One,
and by him renewed to his children.

Dear Samuel, the near sympathy which arose at first sight,
and silent salutation that made the inward birth move,
has often been brought to my remembrance;
and pursuant to the solemn covenant between us soon after our
first acquaintance in your brother John`'s little parlour,
I have found a great freedom to act towards you as an unreserved, openhearted friend,
and shall, therefore, add a little further.
In a feeling sense of Divine goodness, my soul has been humbled on your account,
that the Lord, in the riches of his sure mercies,
did vouchsafe to pluck you from the fire,
and quench the darts that were shot at your soul, and by lifting your eyes to himself,
healed your wounds, and chose you as a vessel for his use,
and for an instrument to publish his name and
proclaim his light and salvation to the Gentiles.
And it sprang in my heart, in much brotherly affection, to say, Prize your privilege,
mind your calling, for it is high and holy; watch against the world,
that it do not clog you, with the spirit thereof be not too familiar.
There are that pretend to be children of the light,
who are lying in wait to gain the friendship of those whom the Lord,
by the indwelling of his Word,
has made as a flame against those who reside in the Mount of Esau;
and coals from their mouths have kindled in the hidden
treasure of these worldlings and libertines,
and begun to burn in their hearts, and they have sought the friendship of such,
and sometimes, when gained, they have valued themselves, and have smothered the fire,
and continued in their corruptions.

Oh! the awful authority, the becoming sweetness, the instructive mien,
the beseeming gesture, with which Truth arrays her votaries,
far surpassing all our modern polite and worldly genteel airs.
With the salutation of love, your real friend.

[.signed-section-signature]
John Churchman.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Kendall^
footnote:[The Friends who were accompanied by John Kendall, during this visit to Holland,
were William Brown and Samuel Neale.
John Kendall was a Friend well known,
both as a useful member of the Society and as a writer, having published several works.
Besides the occasion here mentioned,
he also paid four other visits to Holland on religious service.
He died at Colchester in 1815, at the advanced age of eighty-nine years,
a minister about sixty-seven years.]
to Samuel Fothergill.

[.signed-section-context-open]
Colchester, Eighth month 17th, 1752.

I am but just returned from my journey in Holland and Germany, and may acquaint you,
that we had various comfortable opportunities
with the few Friends in those parts of the world,
and had great satisfaction in our visit to them,
finding a people unto whom the visitations of our
heavenly Father seemed particularly extended,
and such likewise as have answered the call,
and are become as testimony-bearers for the name and truth of God.
These we hope the Lord will yet further strengthen,
and qualify as instruments in his hand, to promote his glorious cause; yes,
we expect the primitive luster of our Zion shall
yet in some degree be revived in that land,
though certainly there is a mixture, through the unwearied adversary,
who has come as in the night, and sown tares among the good seed.
Our hearts were enlarged in great love at times,
and a concern begotten for the growth of the true seed, and for the right birth,
wherein we labored according to the ability received, and have found the answer of peace,
which abundantly repays.

[.signed-section-signature]
John Kendall.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to John Churchman.

[.signed-section-context-open]
Warrington, 1753.

Yours of the 14th, I this morning received, and hasten to tell you,
I wanted much to know where you were,
that I might send you a short salutation of love unfeigned, which has often,
of late more daily, lived in and flowed forth of my heart towards you.
I received your acceptable, profitable letter, from Moate,
which I acknowledged soon after, which probably came not to your hand; if it did not,
the loss is trivial to you, though important to me,
as it has probably deprived me of some further
indication of your regard and good desires for me.
I am humbly and reverently thankful, in that I feel the unity of the brotherhood;
it is very dear to me.
I am, and have been, in a low, humbling dispensation,
in which that union has been almost my sole evidence
and mark that I was not far out of my way.

I desire to accept, at the heavenly Father`'s hand, my portion; I know it is,
and will be right and in due season; though I may sometimes almost murmur and repine,
yet that adds to my anxiety.
I have had some weighty hints for years, about a piece of labor, which makes me tremble;
and, in short, my way to true settlement seems to lie through your country.
I now stand resigned, and only beg--Put forth, and go before me, O Israel`'s Shepherd,
and I will follow in your strength,
believing in the all-sufficiency of a never-failing arm.

I am sensibly touched with your observation of making poor wages in Ireland,
Alas! my friend, can we expect to flow with wealth when the church is in poverty,
and the priests of Zion in heaviness?
Our sympathy will lead us to mourn,
and our heads will be covered with ashes instead of crowns.
The ministers of our Lord cannot expect to be above their Lord;
he was crowned with thorns for us, and so must we be for his visited seed.
But this you know better than I, though I am not destitute of some experience, which,
I bless the God of my life, I find to increase and flow from patience in tribulation.

Assure yourself, my dear friend,
your correspondence is to me very grateful and profitable,
and when the cords of Divine love draw your mind towards me, be open in counsel,
admonition, or reproof; I need such friends, and value them very greatly.
Accept the salutation of dear love, in the fresh renewings of quickening virtue,
which reaches freely forth to all the servants of Christ, as a divine odour,
for which the true virgins love him:
from your friend and brother in the labor and suffering of and for the gospel,

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Churchman to Samuel Fothergill.

[.signed-section-context-open]
Woodhouse, Third month 17th, 1753.

It was very reviving to me to receive those few lines from you,
for I think the remembrance and love of the brethren seems more and more precious to me,
though I think that I grow but slowly in my passage from death to life.
Those few hints that you give,
that your road to a true settlement leads through our country,
are no way unpleasant to me, and are safe in the bosom of your friend;
yet I can hardly help saying.
Hide it as a precious seed or root in your garden, as much as may be.
I have seen the growth of choice things retarded,
by opening the earth to show others what seed or root has been there planted;
but if they are let alone, and not trod too much upon by man or beast,
in due time they sprout and break forth with beauty and strength.

I do not expect to return before 1754: If I should live to see that happy day,
with the smiles of my Master, or have one, like flesh and bone of one`'s flesh and bone,
for an intimate, in a moving jail,
to which I must be committed before I can be proclaimed free in my native air,
affords a contemplative delight not easy to express.

[.signed-section-signature]
John Churchman.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Samuel Watson, on the death of his wife.^
footnote:[Samuel Watson, of Kilconner, in the county of Carlow,
"`succeeded his ancient and honorable father, John Watson, of the same place,
not only in his outward possessions there,
but in a zealous concern for the testimony of truth, and support of its cause.`"
He was a friend of great use and service many ways,
particularly in meetings for discipline, which he attended with exemplary diligence.
"`Often, under the fresh influence of the divine anointing,
he was enabled to drop living counsel to the affecting and tendering many hearts,
and to raise that life in meetings for discipline which
alone is the crown of all our religious assemblies.`"
"`In religious visits to the families of friends, he was often eminently favored,
and opened in suitable counsel, in an extraordinary manner;
strong and fervent were his desires,
that the youth amongst us might dedicate their hearts fully to the service of God,
that there might be a succession of faithful members in the church,
whereof Christ is the head,
following the ancients in that self-denying path in which they had walked.`"
"`He departed this life in peace, at his own house, at Kilconner,
the 14th of fifth month, 1762, aged seventy-six years.`"
His wife, Abigail Watson, formerly Abigail Bowles,
was an eminent and experienced minister: she travelled much in the service of truth,
having visited England five times, and the provinces of North America once.
Site died eleventh month 11th, 1752, aged sixty-eight, a minister forty years.]

[.signed-section-context-open]
Warrington, Seventh month 7th, 1753.

I affectionately salute you in the fresh renewings of
that near union in which our acquaintance commenced,
and in which you have often been brought of late into my remembrance,
and particularly since the loss of your late worthy companion and my dear friend.

To consider an ancient person, who had long enjoyed the happiness of a help-mate,
in a temporal, and eminently so in a religious sense,
divested of that principal sublunary aid in advanced age--his
satisfaction taken away by the loss of a dear companion,
and a comfortable auxiliary in a joint spiritual labor--
must immediately furnish painful reflections.
Nevertheless,
as the everlasting spring of all true peace and holy ease abides unchangeably the same,
and, through all the mutations attending us, He varies not--in him,
in him let our fresh springs be fixed,
and he will reveal his glorious sufficiency to supply all our needs;
he will reward his faithful afflicted servants with a stay in their various conflicts,
and with a staff in old age.
He whom Jacob worshipped leaning on the top of his staff, whom Moses served,
and whom afflicted Job remembered in his troubles, will, I question not,
be near for your present help to live and labor,
and for strength to preserve to the end of your days.
Oh, let not the decline of life be obscured with a diminution of holy zeal,
that so the heavenly crown may be sure.
I mention my humble petition, not from doubt,
but anxious desire for your glorious issue and present profitable
labor for the help of a people withering and declining in some places.

I request your acceptance of a narrative of some part of dear father`'s labors:
you will remember him with affection and profit.

Accept, my dear friend, the salutation of endeared love,
from your sincere friend and brother in the labor and service of the blessed household,

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Peter Buck, of Netherdale.

[.signed-section-context-open]
Skipton, Eighth month 9th, 1753.

The alliance between our families, our former acquaintance, and to renew it afresh,
with some other considerations, made me very desirous of seeing you,
and I found in my mind a salutation of good will to spread towards you for your help.
It has pleased Divine Providence to afford you several favors of great importance; as,
being sprung from virtuous, religious parents,
who were good examples in their generation, amongst men and before their children;
they loved Friends, and were beloved of them; and, through the blessing of Providence,
they have left you in affluent, easy circumstances,
and possessed of a large share--in comparison
with many--of the good things of this world;
also, what in finitely exceeds all the riches of this transitory world,
the secret visitation of Divine light and love,
to redeem and preserve you from corruption, and to give you a name amongst the living,
a blessed memorial in the Jerusalem of God.

Now, dear kinsman, what lives upon my heart is,
to put you upon a serious and awful inquiry,
how far these mercies have operated on your mind to produce their desired effect.
Remember your parents, and their God and blesser; their plainness, their love to Friends,
their attendance of meetings, their concern in them for their profit,
their care for their children`'s good, their good example.
Has this been your care to imitate, to come up in their footsteps,
and show yourself a worthy descendant from a worthy stock;
has truth opened your heart and house for the reception of Friends,
and drawn your love towards your father`'s friends, whom we ought not to forsake?
If so, I hesitate not to say, the God of your parents will bless you in all things,
and build you up a sure house, and render you useful in that place,
as a strength to that meeting, a useful member of the Society; and above all,
the evidence of heavenly acceptance will cover your soul as a royal garment,
to your own inexpressible peace and joy.

If, on the contrary hand, you forsake your father`'s footsteps,
and turn aside from the law of his God, he will cast you off;
you will become a burden to your friends, and cause of pain to your sincere well-wishers,
and be a hurt to others instead of a help.
I beseech you in time to consider the weight of their guilt
who turn their own feet from the holy paths of truth,
and by their example cause the way of truth to be evilly spoken of,
and hurt the seeking souls of others.

Your possessions in the world will become blessings,
as they are truly sanctified to you by that God who is great on earth,
as well as in heaven; the fatness of the earth is his,
and he condescends to visit in externals.
All things below are in his hand,
and he has often visibly disappointed the pursuits of those who have
forgotten that it is his blessing which makes truly rich.
And, though close application and avarice may be sometimes successful to accumulate wealth,
yet remember, with trembling,
the epithet of "`fool`" was fixed by him who was and is eternal Truth,
upon all those who were laying up treasure for themselves, and were not rich towards God;
and in that solemn hour of decision, when all worldly enjoyments shall issue in vanity,
and the largest possessions be light as a feather,
nothing short of true inward peace will avail,
and that is solely found in the way of well-doing.
The visitation of Divine Providence has been at times near you,
to help over hurtful things,
and to lead you in the path the ancients trod to blessedness.

O let it be dear and precious in your sight; trample not upon it,
nor live above it in yourself; fail down upon it, in true submission of soul; or,
I testify, on God`'s behalf, it will fall upon you and grind you to powder,
in a day which you cannot escape.
Beware, for the sake of your poor soul, of evil company, who would first seduce,
and then deride you; like their master and employer, who tempts, and, if successful,
torments those he has betrayed.
Beware of an unequal marriage, if the peace of your soul, of your family,
your present and future welfare, be at all desirable.
My tender regard for you leads me to use this freedom with you,
as certainly knowing the way of truth, as delivered down to us by our fathers,
is the way to true peace.
I therefore entreat you, by the mercies of God, while yet it is day,
remember Heaven`'s favors, carefully inquire how they have been answered by you;
hasten diligently into the proper labor of a true Christian, who,
conscious he has no continuing city here, seeks with diligence one which has foundations.

My soul craves that a blessing may rest upon you; and in order thereto,
seek you that in which it stands, that so He who blessed the house of Obed-edom,
where the ark rested, may perpetuate his blessings to you and yours.
This is the petition and request of my soul for you,
who am your affectionate kinsman and sincere well-wisher,

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Churchman to Samuel Fothergill.

[.signed-section-context-open]
Norwich, Ninth month 7th, 1753.

I wish to inform you that I have performed my journey in Holland,
and am returned to this city in health and safety,
through the never-failing mercy of kind Providence,
who never sends his servants on an embassy at their own expense,
but supplies with what is needful.
But if we do not lack any thing on our pilgrimage,
or even have to experience that through his power the very devils are made subject,
we have still a deeper and more solemn root of rejoicing, namely,
the evidence of a gentle inflowing peace,
from a conscious sense of having preserved our innocency;
this it is to have our names written in the Lamb`'s book of life.
It has often been the deep travail of my soul that I might more and more experience this;
but when I look at my own frailties,
I am ready to conclude it is yet but in dim characters,
and therefore have need of the prayers of my brethren and sisters,
of which number I am sensible yourself and dear wife are.

After the Yearly Meeting at Norwich, my old companion,
John Pemberton and I embarked at Yarmouth,
and landed at Rotterdam on the 29th of seventh month; from there we went to Amsterdam,
and tarried with Friends in that city about nine days, and were at three meetings,
and then proceeded into North Holland, to Twisk and Abbey-Kirk,
and visited all the families of Friends in those parts,
and had three meetings with Friends, as much by themselves as well could be.
There are but few of the professors sound in the principles of our religion;
they seem to be a kind of half Quakers.

We went next to Hoorne, a very fine city.
I thought I felt something in my mind towards that place, but was low and weak,
and under discouragement, for lack of a suitable interpreter,
so thought I might venture to pass on;
but as I walked very slowly through the city to the boat, with my mind turned inward,
I felt that my Master was not far from me, that his hand was upon me;
and I was strongly desirous to know what he would please to have me to do.
I felt life to spring in me, and a gentle draft of love, which drew me back.
In the interim, I saw a young man in the street, whom something in me seemed to salute,
and I desired the interpreter to ask him if we could have a meeting there, to which,
with a smile, he readily answered he believed we might;
so he took my bags and invited me to his home,
and said he would go and consult some of his acquaintances, and seek for a place.
He soon returned, and said he had found a willingness in several,
and they had got a large room in a private house.
So we attended, and had a good open meeting; familiar Gospel truths opened clearly,
and the love and authority of Truth came over the meeting much more than I expected;
which made me confess the word of the Lord is pure and tried,
it is a shield and a buckler to them that trust therein.

Next day we returned to Amsterdam,
and finished the visit to all the families of Friends in that city,
which we had begun before we went into North Holland,
attending their first-day and week-day meetings.
We spoke by an interpreter:
but the Friend who interpreted is very old and nearly
superannuated to every thing save an innocent,
well-meaning, yet self-confident strong will, which he still inherits.

He preaches a good deal, and has not strength to do much for any other;
if he appear first, he seems so much spent; and if one appear before him,
he has so many of his own old favorite words and sentences,
that he is apt to intersperse them whether proper or improper,
which makes it tedious and wearisome; and while he lives,
it seems impossible to persuade Jean Vander Werf to undertake that service;
he is a tender-spirited young man, and understands English very perfectly.
I had often occasion to try him at translation, for I was forced sometimes to write,
when I could not obtain relief by my tongue, and he did it to good satisfaction.
It is a dull, tedious way of obtaining relief,
and though sometimes Truth much favored in testimony,
and the power thereof was felt over the meeting,
our interpreter would sometimes appear after us when the meeting should have broken up,
whereby, many times the beauty was lost, which is very mortifying and discouraging;
and many were present who never saw a Friends`' meeting before.

We took shipping at Rotterdam on the 29th of last month,
and landed safely in England on the 3rd instant,
having been long detained in the harbour.

[.signed-section-signature]
John Churchman.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to John Churchman.

[.signed-section-context-open]
Warrington, Tenth month, 1753.

I have received a hint which has done me some service,
and I may probably often reflect upon it to advantage.
I had flattered myself with spending several days with you in Cheshire,
even to such a degree as to wait with some
impatience for an account when you came into it.
I saw you, enjoyed the company of your spirit for a short time,
and was deprived of the satisfaction I had hoped so very strongly for,
by a call another way, which, I can assure you,
if I had not heard my Master`'s voice in it, I had not complied with.
The hint I received is this:--It is very good
and profitable to keep near the Fountain Head,
that, if the streams be diverted out of the expected channel, we may not be at a loss,
having that to approach to, which remains everlastingly fixed.

The longer I live, the more I am convinced of the necessity of having one Lord over all,
and the motions of his hand and eye deeply and humbly regarded.
These things are written in very legible characters in your book,
and need not my repetition;
but you have allowed me to converse with you with that
freedom whose grounds and results the world knows not.

I was easy with my journey on the account of the funeral, and made some little earnings,
and more especially at Manchester, on first-day forenoon,
a place I have almost ceased to expect relief of spirit in.
But the virtue of the heavenly name spread, and, I believe,
led several of us into a place, alas! little frequented by many,
but known to some by the name of the valley of decision.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to his Sister.

[.signed-section-context-open]
Warrington, Eleventh month 5th, 1753.

I have some reason to apprehend I must get away to America some part of next summer.
I am quiet, easy, and resigned, and that which has been for years at times a heavy,
painful burden, that I could not clearly see, appears clear;
and I strongly hope gracious Providence, in this quiet calm,
will make the trial easier to bear than I have hitherto apprehended.
I cannot but anticipate the most painful part, being rent the flesh as from the bone;
the dangers of the sea, the various external jeopardies attending,
are of less affecting weight.
But what shall we say?
We are safe in our obedience to heavenly counsel, to Him whose wisdom, mercy,
and goodness, we have great and proved occasion reverently to adore.

Your very acceptable lines affected me with the
strongest emotions of tenderness and near union:
I could not peruse them without a strong sensibility of
the situation of that mind from which they proceed,
and found a sympathy therewith.
Expressions are deficient, and language too short,
to set forth the sentiments and mutual converse of spirits
gathered in measure into that which is unspeakable.
Oh, may every impediment be removed,
that we may more and more drink into that fulness which fills and comprehends all things,
but is comprehended of nothing.

Our various probations, our concealed conflicts, our hidden distresses,
are often alleviated by this secret sympathy and fellowship in suffering,
and eminently so when the great Father of all consolation is
pleased to overshadow with his healing wing.
This was not far from me in my late little journey,
though in much pain for the testimony`'s sake, yet supported to labor,
so as to have peace of mind, and that is indeed enough.

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to John Bragg.^
footnote:[John Bragg lived at Whitehaven, and died there very generally beloved,
in Fifth month, 1795, aged 72.]

[.signed-section-context-open]
Warrington, First month 21st, 1754.

I received, about twelve days ago, an anonymous letter, requesting my return thereto,
agreeable to the superscription I intended to fix upon this.

The author is personally a stranger to me;
but I am not altogether a stranger to the situation described,
and have deeply waited for instruction and ability to direct,
agreeable to the mind of Truth, and the sympathy I feel on my mind with the distressed.
Expect not from me an elaborate disquisition into speculative points;
for this I know from experience,
that part must die which longs to comprehend more truths,
while the former discoveries are yet disobeyed.
The first principles of religion, as I have found, are the knowledge of our own weakness,
and Almighty sufficiency to supply all defects.
Whoever builds on another foundation will be finally disappointed.
Your letter manifests a sense of lack; and, as you attend to that sense,
that which gives it, will, in due time, supply it; for the Lord our God hears his own.
The state of leprous Naaman has been strongly before me on your account.
He was disquieted under his malady, and sought relief; but he had like to have missed it,
by contemning the means;
his pride was piqued that the prophet came not out to work an
immediate cure with some visible demonstration of power;
so that stooping to the simple means of bathing in Jordan was very mortifying to him;
he remembered Abana and Pharpar, rivers of Damascus,
and was willing to believe they were of equal virtue.
But know this assuredly,
there is no river capable of cleansing the soul but that which proceeds from
under the throne of God--no stream flowing from speculation,
or any natural powers can wash out the stain and bring peace to the soul.
Deeply and submissively abide with the sacred Minister of the new covenant;
if you are weak, he is strong; and sure I am,
the God of all strength and truth would not leave you destitute.
Be content to be a child, or you will be a monster;
let his day come upon that which is lofty, and the cross be taken up to hurtful things,
and in his light you will see more light; and,
until you have been fed from on high with milk fit for a babe,
stronger meat or higher discoveries would not be good nourishment,
but create disorders for lack of digestion.

My soul fervently desires your help; but remember, with holy trembling,
the way to heaven lies through the gates of death.
The Lord of all mercy and strength renew effectually his visitation to your soul,
and build you upon the sure foundation that can never be shaken.
I am your true friend and well-wisher,

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
William Brown^
footnote:[William Brown came over from America with John Churchman on a religious visit,
and returned soon after this letter was written:
the visit to Wiltshire therein mentioned, was very seasonable,
he being made helpful to Friends of that county,
who were at that time in some difficulty.]
to Samuel Fothergill.

[.signed-section-context-open]
Third month 16th, 1754.

Having visited meetings in and about London, my way opened to visit Sussex,
Surrey and Kent, which I did with great diligence,
thinking that after then I might sail for Virginia, and so home by land: but then,
when I would eagerly go to sea, it looked fearful and dark,
and I had no heavenly bread for sea-store;
but if I would walk in the light or the way that opened in my view,
I must go through Wiltshire, as I had not visited that county, and so into Wales.
And I discovered a hidden warfare between nature and grace,
although I had often said to myself, and to some Friends,
that I hoped I was truly resigned to His will,
who is so highly worthy to be honored and obeyed.
I felt something in me which seemed to divide soul and spirit,
which made me carry about an aching heart,
and especially when one piece of service after another was performed,
and I let my mind look home till a fear seized me that I should be like Balaam,
if I was so constantly asking for liberty to go, and spake of doing only the Lord`'s will,
who was pleased so to accompany my spirit that I had often to say.
Well, I am glad that I came to visit this place,
as I have been favored with such healing balsam that has bravely healed my sore inside;
and since I came out of Wales,
I have had as close and heavy work as in any part of my religious labors.

[.signed-section-signature]
William Brown.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Fothergill to Ann Appleby.^
footnote:[Ann Appleby, previously Ann Ford, of Leek,
was at this time the widow of Joshua Appleby, who died in the county of Durham,
Third month 16th, 1754, aged 26.]

[.signed-section-context-open]
Warrington, Fourth month, 1754.

In my journey into Yorkshire, from which I returned a few days ago,
I heard the sorrowful account of the death of your husband,
and had it confirmed by your favor of the 21st ult.
The sympathy I strongly felt with you in your present situation, had determined me,
before the receipt of yours, to send you a few lines; and I can assure you,
I am a sharer in your distress, and can mingle my sorrows with yours.
The relation he bore you, my dear friend, and some acquaintance I had with him,
were inducements to esteem and affectionately to regard him; but there seemed,
and really was,
a closer union and connexion at and since our last interview than heretofore.
I thought him near the kingdom,
but was not apprehensive of his being so near his
discharge from the cares and disquietudes of this life.

We must acknowledge the laws of friendship are sacred and strong: we cannot,
we ought not to divest ourselves of their obligations,
nor with insensibility of mind admit their dissolution.
The unspotted Pattern of infinite righteousness, when his friend Lazarus died,
felt as a man, and wept: but various considerations will be suggested,
to that mind which looks the right way,
to alleviate the pain which attends these dispensations--the
mercy and wisdom of an Almighty Being,
glorious and full of majesty as Jehovah,
yet gracious and compassionate as the Father and Fountain of relief,
which has revived many a drooping soul when afflictions have attended.
He knows what is best for us all, and most conducive to his own honor.
We may acknowledge, when our understandings are opened,
though his works may seem marvelous, and his ways past finding out,
yet in wisdom has he made them all.
The tender connexions of husband and father are now for ever broken--but by whom?
One whose wisdom and mercy are over all his works,
and who can abundantly supply all deficiencies,
and has been known to be a father to the fatherless, and a judge for the widow,
from his holy habitation.

He is removed from us in youth, and the prospect of long continuance amongst his friends.
Alas, how know we what remains I for us in the residue of our days,
that we are so anxious to have prolonged?
Many exercises and troubles attend the smoothest passage in this life;
what better time than when under that preparing hand which fits for eternal peace?
It is admirable wisdom and mercy thus to deal with us, to relieve from all dangers,
and translate into that quiet rest, where all sorrows, fears,
and temptations are unknown terms.
Afflictions, dear Nancy, spring not out of the ground;
they are often conducive to our help in the best things.
Let this awful, solemn trial enough close on your mind,
and engage you to look to the everlasting, holy,
unchangeable husband and helper of all who reverently seek to be fit for his acceptance;
who, by the secret working of his unsearchable power,
clothes excellent mercy in the form of disappointment,
and causes all things to work together for good to his servants.

Let the impressions made on your mind, by the moving object so lately before you,
and the true, certain testimony delivered, of the great advantage of true Christianity,
be imprinted in deep humble characters; that so,
merciful protection may be ever with you and yours, and lead, at last,
to a reunion in the kingdom of peace, where you may inherit an unfading crown.

My wife joins me in tender sympathy with you,
and our prayers are for your preservation and Divine help.
Your real friend,

[.signed-section-signature]
Samuel Fothergill.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Ann Fothergill to her Brother Samuel.

[.signed-section-context-open]
London, Seventh month 23rd, 1754.

William Brown, accompanied by Joshua Dixon, has sailed for America.
I, with several other Friends, accompanied them to Gravesend,
and had much solid satisfaction in his good company.
I think I may say a Divine sweetness and joy filled his mind with gratitude, peace,
and thankfulness, that he had been preserved in the way of his duty,
to a full discharge of it in these parts; he repeatedly said, with awful thankfulness,
that he was clear, and had never found the like solid joy and consolation of soul,
without any intermission, as he now enjoyed.
He dropped several weighty admonitions, in much love and tenderness,
which nearly affected and united those present to him; the parting,
with a rising prospect, brought by it very near to my view,
was more than I could sustain unobserved by those present.

The following is part of a letter from Israel Pemberton to William Brown,
which the latter desires me to send you:-- "`I have been, for a long time past,
desirous of writing to Samuel Fothergill;
the reverence I have for his worthy father`'s memory first inclined me to think of it.
I have still deferred it, and now perceive he is preparing to pay us a visit,
of which we have long been very desirous;
the wish I have of engaging his company to my house,
determined me to salute him with a few lines,
and even to offer to attend him through the adjacent provinces;
but though to will is present with me, how to perform I find not, and some doubt arises,
whether such a proposal would or may be agreeable;
therefore I adopt this method of hinting my thoughts and wishes to you,
and if by that means I should succeed in obtaining his
good company to lodge with us when here,
it will afford me a great deal of pleasure, and I hope be to his satisfaction.`"

A letter is received from John Churchman,
who desires us to give you the speediest notice
that he thinks of going with Captain Mesnard,
who is to sail on the first of next month.

[.signed-section-signature]
Ann Fothergill.

--
