== Preface

More than seventy years have now elapsed since the decease of Samuel Fothergill.
It has often, during that period,
been wished that some account of his life and gospel labors should be written,
and that his letters should be published; that thus the example, the sentiments,
and the experience of one, who, in his youth, was so remarkably visited by Divine Grace,
and in more mature life was so eminently gifted for religious service, might not be lost,
but serve for the benefit and instruction of others.
It is this feeling which has led to the present publication,
with a desire that such may be its fruits.

Doctor Fothergill contemplated the publication of such a work,
and made some progress in collecting materials for it,
soon after the decease of his brother; but, whether from his numerous engagements,
whether from the diminished energy which is generally the attendant upon advancing years,
or from whatever cause it might be, he never carried his intention into execution.

By much the larger portion of the letters contained in the present work,
have been long in the possession of my wife`'s family, her mother,
the daughter of Joseph Fothergill, having carefully preserved them,
from the time of her uncle Samuel`'s decease,
and transmitted them to her children as a valuable record of their honorable relative.
A few original documents, belonging to some other branches of the family,
also several letters and papers, long in the possession of my friend Croudson Tunstall,
of Nantwich, have been kindly supplied to me.

In the present volume, the address and conclusion of the letters are,
except in a few instances, left out,
and in many of them the introductory sentence is also omitted,
which may give them an appearance of abruptness.
In order to make the account of some of the events
during the life of John Fothergill more clear,
the order of time is a little departed from in the narration of them,
and in the arrangement of a few of the earlier letters.

It will evidently appear that the letters were written in the
full freedom of affectionate and familiar interaction;
but as those who wrote, and those to whom they were addressed,
have all long since passed away from this life,
most of them without any surviving descendants, I feel a liberty to insert names,
and to retain the expression of sentiments and the mention of circumstances,
which otherwise it would have been proper to withhold.

[.signed-section-signature]
George Crosfield.

[.signed-section-context-close]
Liverpool, Fifth month 20th, 1843.
